### ISSUE TITLE
Not Consuming: Consumer when receives message > 32696 using partitionConsumer Messages()

### ISSUE THREAD

**Issue by anudeepakumar** [Shopify/sarama#1000]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.13.0
Kafka Version: 0.8.2.1
Go Version: 1.7.3

##### Configuration

What configuration values are you using for Sarama and Kafka?
`consumer, err := sarama.NewConsumer([]string{endpoint}, config);`
`partitionConsumer, err := consumer.ConsumePartition(topic, 0, sarama.OffsetNewest);`
`msg := <-partitionConsumer.Messages();`
`error := <-partitionConsumer.Errors();`

##### Problem Description

No msg or error when produced message is greater than 32696 bytes

**Comment by eapache** [comment]
What values are you setting on the config? Are you setting `Consumer.Fetch.Max` or the global `sarama.MaxResponseSize`?

**Comment by anudeepakumar** [comment]
Am not setting `Consumer.Fetch.Max`.. setting the default config

**Comment by eapache** [comment]
Do you have logs enabled? Are there any logs from the consumer when this happens?

**Comment by anudeepakumar** [comment]
I dont have logs but this happen always.
When message size is greater than 32696 bytes.
Able to consume 32696 byte message but not 32697

**Comment by anudeepakumar** [comment]
@eapache Are you able to reproduce?

**Comment by eapache** [comment]
I have not been able to reproduce. I was able to successfully produce and consume substantially larger messages (over 200KB). Mind you, I was not using Kafka 0.8.2 - I no longer have a cluster set up for that version.

```go
msg := <-partitionConsumer.Messages();
error := <-partitionConsumer.Errors();
```

Is this your actual code? It may not work as you expect, since if there is an error, the `Messages` line will block first and you many never see it. Please try using a `select` statement instead.

**Comment by anudeepakumar** [comment]
Yes I do use `select`
```
ConsumerLoop:
for {
	select {
		case msg := <-partitionConsumer.Messages():
			fmt.Println("msg", msg)
		case err := <-partitionConsumer.Errors():
			fmt.Println("err", err)

		case <-signals:
			break ConsumerLoop
	}
}

```
this is my actual code

**Comment by eapache** [comment]
Then I'm not sure what could be going wrong. If you enable Sarama logging that could provide a clue.

**Comment by eapache** [comment]
Please reopen if you can provide additional logs that might let me reproduce.
