### ISSUE TITLE
Details of using with a secured Kafka cluster

### ISSUE THREAD

**Issue by michaelandrepearce** [Shopify/sarama#1001]
##### Versions

Kafka Version: 0.10+

##### Configuration

Kafka secured by Kerberos or Plain Auth

##### Problem Description

It is not clear how to configure Sarama client where the broker has been secured with either kerberos or plain auth. 

There should be some documents how to do this.

If this feature is missing, could we request for it to be added to keep inline with kafka features.

**Comment by eapache** [comment]
Plain auth is supported by setting values in the `config.Net.SASL` struct. Kerberos is not supported at this time, and I have no immediate plans to work on it.

**Comment by michaelandrepearce** [comment]
@eapache many thanks for this detail, appreciated.

**Comment by alonana** [comment]
I am not sure if this is exactly the type of secure connection that you're looking for, but I've used a secure connection, and it worked fine. You can see the full details of the example I've use in the post [Secure connection to Kafka from a GoLang client](https://runkiss.blogspot.com/2020/06/secure-connection-to-kafak-from-golang.html). If this is not what you're looking for, let me know, and I will try investigating it.
