### ISSUE TITLE
Consumer Errors after replacing a broker

### ISSUE THREAD

**Issue by aravindvs** [Shopify/sarama#1004]
##### Problem Description

We had to replace one of the brokers for maintenance reasons. We did the following to replace the broker:
(1) Gracefully stop the Kafka broker (id: 48)
(2) Make sure producers/consumers were fine (the consumers coordinated by this broker now were managed by another broker and things were fine)
(3) Spin up a new instance with the same IP
(4) Make sure the new instance's config is the same as old with the same broker ID.
(5) Bring the new one back up.

It took ~35 to 40 mins to do this. But once the broker came back up, the consumer groups coordinated by *this* broker were getting constant errors that this CG is not coordinated by this broker for nearly 30 to 40 mins until i stopped the broker again.

Note: we use bsm/sarama-cluster but I am opening this here because I do see we refresh the metadata in Sarama lib every 10 mins by default but looks like the metadata kept returning that the coordinator for this CG is the same old broker (id 48).

(1) Are there any known issues/recent fixes for this?
(2) Why didn't the metadata refresh even after the ticker elapsed? Is it a Kafka issue or a sarama issue? Any ideas on what could be happening?

Note 2: This is different from https://github.com/Shopify/sarama/issues/846 in which the IP address changed underneath and caused weirdness but here we didn't have that.

##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: Version 1.13.0
Kafka Version: 0.10.1
Go Version: 1.9.2

##### Configuration

producerConfig := sarama.NewConfig()
producerConfig.Producer.Return.Successes = true // Report successfully produced record
producerConfig.ClientID = config.ClientID
producerConfig.Version = sarama.V0_10_1_0

Consumer: sarama-cluster with the default config for the underlying sarama library (for metadata refresh, etc).
Consumer.Return.Errors = true
Consumer.Offsets.Initial = sarama.OffsetOldest

##### Logs
<these below logs just repeated for ~40 mins until i stopped the bad broker and the coordinator changed>

sarama-logger : client/coordinator requesting coordinator for consumergroup <CG> from <IP>
sarama-logger : client/coordinator coordinator for consumergroup <CG> is #48 
kafka- Error: kafka server: Request was for a consumer group that is not coordinated by this broker.

Kafka server log on the bad broker (id: 48):
Error for partition [<topic>, <pn>] to broker 2:org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition. (kafka.server.ReplicaFetcherThread)

**Comment by eapache** [comment]
The metadata update that occurs in the background (every ten minutes by default) only updates replica and leadership information; it does not update coordinator information. I suppose it could plausibly update the coordinator information as well, but it shouldn't have to in this case; sarama-cluster should be explicitly triggering a refresh when it determines that the coordinator it has is wrong.

The log line `client/coordinator requesting coordinator for consumergroup from ` is part of that refresh flow, so this indicates that Sarama *is* asking the cluster for an updated coordinator and it's Kafka returning the incorrect data. I'm not sure if I can provide much more insight here; sarama-cluster might have a better idea what's gone wrong in this case.

It might be simpler to just give the new instance a different broker ID; I imagine kafka will be happier in that case and you won't run into this kind of cache confusion.

**Comment by aravindvs** [comment]
Ah.. ok. Good to know the metadata update doesn't update the coordinator info.

It does look like Kafka is returning the stale info. Looks like I am probably running into bullet 2 in the "interesting scenarios" here:
 https://cwiki.apache.org/confluence/display/KAFKA/Kafka+0.9+Consumer+Rewrite+Design#Kafka0.9ConsumerRewriteDesign-Co-ordinatorfailoverorconnectionlosstotheco-ordinator

One thing I am not sure is why the controller doesn't update the metadata for this long. Will raise it with Kafka to see if there is something known.

Also will try different ID and see if it does solve it.

Thanks for the quick response.

**Comment by jerrygb** [comment]
@eapache I know this closed but we seem to have the same issue using sarama-cluster/sarama.


The on client side we continuously receive empty rebalance notifications, basically due to the rebalance error. If you notice below, we finally receive the co-ordinator details from same broker id #146, after sometime. 

```
[sarama]2018/01/18 04:38:29 client/coordinator requesting coordinator for consumergroup test-cg from 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator coordinator for consumergroup test-cg is #146 (10.0.0.1:9092)
[sarama]2018/01/18 04:38:29 rebalance error: kafka server: Request was for a consumer group that is not coordinated by this broker.
[sarama]2018/01/18 04:38:29 client/metadata fetching metadata for all topics from broker 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator requesting coordinator for consumergroup test-cg from 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator coordinator for consumergroup test-cg is #146 (10.0.0.1:9092)
[sarama]2018/01/18 04:38:29 cluster/consumer  rebalance
[sarama]2018/01/18 04:38:29 Connected to broker at 10.0.0.1:9092 (registered as #146)
[sarama]2018/01/18 04:38:29 Closed connection to broker 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator requesting coordinator for consumergroup test-cg from 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator coordinator for consumergroup test-cg is #146 (10.0.0.1:9092)
[sarama]2018/01/18 04:38:29 rebalance error: kafka server: Request was for a consumer group that is not coordinated by this broker.
[sarama]2018/01/18 04:38:29 client/metadata fetching metadata for all topics from broker 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator requesting coordinator for consumergroup test-cg from 10.0.0.1:9092
[sarama]2018/01/18 04:38:29 client/coordinator coordinator for consumergroup test-cg is #146 (10.0.0.1:9092)
[sarama]2018/01/18 04:38:29 cluster/consumer  rebalance
[sarama]2018/01/18 04:38:29 Connected to broker at 10.0.0.1:9092 (registered as #146)
[sarama]2018/01/18 04:38:39 cluster/consumer set-reset-offsets-dcf333c2-f1e7-4334-82c5-1f91271abc45 consume test-topic/35 from 44017414845
[sarama]2018/01/18 04:38:39 cluster/consumer set-reset-offsets-dcf333c2-f1e7-4334-82c5-1f91271abc45 consume test-topic/1 from 43977083671
[sarama]2018/01/18 04:38:39 cluster/consumer set-reset-offsets-dcf333c2-f1e7-4334-82c5-1f91271abc45 consume test-topic/19 from 44191339075
```

We co-related this the group metadata refresh on the server at about the same time.

```
{"@timestamp": "2018-01-18T04:24:46.900", "level":"INFO", "thread":"group-metadata-manager-0", "class":"kafka.coordinator.GroupCoordinator", "message":"[GroupCoordinator 146]: Unloading group metadata for test-cg with generation 7617"}
{"@timestamp": "2018-01-18T04:38:29.461", "level":"INFO", "thread":"group-metadata-manager-0", "class":"kafka.coordinator.GroupCoordinator", "message":"[GroupCoordinator 146]: Loading group metadata for test-cg with generation 7617"}
```

Weird part is the generation id remains the same.

Though it looks more to do with kafka, is there any chance you know any setting related to expiry for load/unload of the group metadata cache?

**Comment by jerrygb** [comment]
@aravindvs Also if you have narrowed down the actual environment issue, could you please let me know.

**Comment by eapache** [comment]
I have no idea, sorry.
