### ISSUE TITLE
always get -1 when get offset from brokers

### ISSUE THREAD

**Issue by simon-xia** [Shopify/sarama#1012]
Sarama Version: 2fd980e23bdcbb8edeb78fc704de0c39a6567ffc
Kafka Version: 0.10.0.0
Go Version: 1.8.1

	cli, err := sarama.NewClient(strings.Split(brokers, ","), nil)
	if err != nil {
		return
	}

	b, err := cli.Coordinator(group)
	if err != nil {
		return
	}

	ps, err := cli.Partitions(topic)
	if err != nil {
		return
	}

	req := &sarama.OffsetFetchRequest{
		Version:       1,
		ConsumerGroup: group,
	}

	for _, pid := range ps {
		req.AddPartition(topic, pid)
	}

	resp, err := b.FetchOffset(req)
	if err != nil {
		return
	}
	for id, msg := range resp.Blocks[topic] {
		fmt.Println(id, *msg)
	}

I get 

```
135 {-1  kafka server: Not an error, why are you printing me?}
150 {-1  kafka server: Not an error, why are you printing me?}
17 {-1  kafka server: Not an error, why are you printing me?}
62 {-1  kafka server: Not an error, why are you printing me?}
82 {-1  kafka server: Not an error, why are you printing me?}
113 {-1  kafka server: Not an error, why are you printing me?}
......


```

**Comment by eapache** [comment]
Presumably that means the brokers aren't storing offsets for those topic/partition/group combinations? Has something actually set the offsets in kafka? Or perhaps the offsets are still being stored in ZooKeeper and you need to use Version 0 of the `OffsetFetchRequest`?

**Comment by eapache** [comment]
Please feel free to reopen if you have more information showing this is a Sarama bug.
