### ISSUE TITLE
Concurrent calls to ConsumePartition are unsafe

### ISSUE THREAD

**Issue by sanjaypsmc** [Shopify/sarama#1018]
##### Versions

Sarama Version: v1.15.0
Kafka Version: 2.11-0.10.1.0
Go Version: 1.9.2

##### Configuration

What configuration values are you using for Sarama and Kafka?

Defaults in both cases.

##### Problem Description

I'm attempting to parallelize PartitionConsumer creation to speed up the initialization of my application. Concurrent calls to sarama.Consumer.ConsumePartition for the same topic appear to result in non-deterministic race conditions (concurrent calls for _different_ topics do not appear to cause any issues).

The documentation isn't clear on whether or not users should expect concurrency-safety. Could you please offer some clarity on this issue? It may also be worth updating the documentation to make this explicit.

**Comment by eapache** [comment]
Off the top of my head `ConsumePartition` should be completely safe for concurrent calls, even for the exact same partition. Let me check.

**Comment by eapache** [comment]
Yes, as far as I can tell by reading the code, it should be fully concurrency-safe; the main locking happens in the `addChild` method.

**Comment by sanjaypsmc** [comment]
Okay thanks for your help! I'll try and send a repro your way the next chance I get.

**Comment by eapache** [comment]
Feel free to reopen if you can reproduce.
