### ISSUE TITLE
How using multiple sync producer using multiple go routine ?

### ISSUE THREAD

**Issue by davidmgkang** [Shopify/sarama#1020]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1
Kafka Version: 0.11.0.2
Go Version: 1.9.2

It's a simple question.

Do I see some example understanding
https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#is-it-safe-to-send-messages-to-the-synchronous-producer-concurrently-from-multiple-goroutines ?

I'd like to know **How using multiple sync producer using multiple go routine for One topic** (with 3 partition, 3 replicas)

I wanna see some example codes.
Could you please?

**Comment by eapache** [comment]
There is a simple example (one goroutine) in the documentation already: https://godoc.org/github.com/Shopify/sarama#example-SyncProducer

Using it concurrently would just requiring calling `SendMessage` from multiple goroutines at once.
