### ISSUE TITLE
Question: why Broker API is not included in Version 1.15.0 (2017-12-08)

### ISSUE THREAD

**Issue by JunliWang** [Shopify/sarama#1025]
When I download source code from :https://github.com/Shopify/sarama/archive/v1.15.0.zip
There is no: Broker.go
But it is in the master branch
Is it not officially supported?
And could you also write interface for it, so that I can generate mocks for UT, thank you!

**Comment by eapache** [comment]
I see a file `broker.go` in that zip. Are you sure it's missing?

Making the broker an interface is something that we want to do but will break compatibility, so we haven't yet (https://github.com/Shopify/sarama/wiki/Ideas-that-will-break-backwards-compatibility)

**Comment by JunliWang** [comment]
I was using `glide get github.com/Shopify/sarama` to get v1.15, I see the `changelog.md` is correct, but no `broker.go`. I'm not sure what went wrong, but I ended up getting from master branch.
