### ISSUE TITLE
CreateTopics, DeleteTopics, but no DescribeTopics

### ISSUE THREAD

**Issue by andrejvanderzee** [Shopify/sarama#1031]
I have noticed that the master branch has a CreateTopics and DeleteTopics method for the broker (thanks for that). Is there any work done on DescribeTopics?

Cheers

**Comment by buyology** [comment]
You can use the [`MetadataRequest`](https://godoc.org/github.com/Shopify/sarama#MetadataRequest) to get basic topics information (set it to a nil slice to retrieve all topics). 

If you also need info on the topics configuration [this PR for the `DescribeConfigs` message](https://github.com/Shopify/sarama/pull/1014) will allow you to retrieve that.

**Comment by andrejvanderzee** [comment]
Nice. With the AlterConfigs, will I be able to change topic configuration too?

**Comment by andrejvanderzee** [comment]
In the patch I see:

```
func (acr *AlterConfigsRequest) requiredVersion() KafkaVersion {
	return V0_11_0_0
}
```

We are on 0.10.2.1. Is that because the Kafka protocol doesn't support it, or is it just not tested?

**Comment by buyology** [comment]
> With the AlterConfigs, will I be able to change topic configuration too?

Yes!

> We are on 0.10.2.1. Is that because the Kafka protocol doesn't support it, or is it just not tested?

Those protocols were added in 0.11.0, as more and more of the configuration now goes through the brokers instead of via ZooKeeper. For earlier versions you can use a library that interacts directly with the data in ZooKeeper, e.g. https://github.com/wvanbergen/kazoo-go

**Comment by andrejvanderzee** [comment]
Thanks alot, very useful! 

Unfortunately the Kazoo library does not allow for changing topics.
