### ISSUE TITLE
Configurable compression level

### ISSUE THREAD

**Issue by bobrik** [Shopify/sarama#1042]
Currently there's no way to configure compression level for Gzip. We also want to add Zstd support to Kafka itself, where there are many compression levels:

* https://github.com/apache/kafka/pull/2267

There should be a setting to set compression level in producer config. I'm not sure whether we want separate config per codec (`CompressionLevelGZIP`, `CompressionLevelZSTD`) or one setting to rule them all (`CompressionLevel`). The former seems more flexible.

**Comment by eapache** [comment]
Separate config does feel more flexible, but given that gzip, zstd, and all other compression codecs I can think of specify levels in simple integers, a single `CompressionLevel` seems sufficient? There's currently no way to specify multiple compression codecs in a single config, so there should never be any ambiguity.
