### ISSUE TITLE
GoRoutines for NewSynProducer keeps on increasing

### ISSUE THREAD

**Issue by Kartikkumar-Shetty** [Shopify/sarama#1043]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.15.0
Kafka Version: 0.10
Go Version: 1.8

##### Configuration

What configuration values are you using for Sarama and Kafka?

```
	config := sarama.NewConfig()
	config.Producer.Partitioner = sarama.NewRandomPartitioner
	config.Producer.Return.Successes = true	
	producer, err := sarama.NewSyncProducer(brokerAddress, config)
```

//Code to push message
```

	p, o, e := pc.syncProducer.SendMessage(&msg)
	if e != nil {
		fmt.Println("Push Error")
		fmt.Println(e)
	}	
	return p, o, e
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

We are using a single instance of NewSyncProducer to push messages to Kafka, throughout our session.(Singleton Producer) 
We are tracking the number of goroutines our application is creating using pprof, 
when we test our code on single(one node) kafka cluster the number of goroutines that sarama producer creates reaches a fixed value and stays more or less stable.
However when we run this on a 10 node kafka cluster the number of goroutines keeps on increasing through out the day, below is the pprof stack trace.

out of 1168 total, 583 goroutines belong to sarama, and this number keeps increasing without ever reducing.

Why is it creating a async Producer and a Partition Producer, when from my code i create a NewSyncProducer? Why does the goroutine never decrease.

Note: none of the goroutines are blocked
---------------------------------------------------------------------------
0 | block
-- | --
1316 | goroutine
540 | heap
0 | mutex
7 | threadcreate

PProf goroutine stack

goroutine profile: total 1168
731 @ 0x42dfaa 0x42e08e 0x4066c1 0x406335 0x71a790 0x757cba 0x753263 0x45a841
	0x71a78f	github.com/OrgName/ProjectName/src/vendor/github.com/Shopify/sarama.(*partitionProducer).dispatch+0xcf												/home/jenkins/workspace/dev_projName/src/github.com/OrgName/ProjectName/src/vendor/github.com/Shopify/sarama/async_producer.go:428
	0x757cb9	github.com/OrgName/ProjectName/src/vendor/github.com/Shopify/sarama.(*partitionProducer).(github.com/OrgName/ProjectName/src/vendor/github.com/Shopify/sarama.dispatch)-fm+0x29	/home/jenkins/workspace/dev_ProjectName/src/github.com/OrgName/ProjectName/src/vendor/github.com/Shopify/sarama/async_producer.go:414
	0x753262	github.com/OrgName/ProjectName/src/vendor/github.com/Shopify/sarama.withRecover+0x42		

--Update----------------------------------
It seems that sarama creates a go routine with partition producer for every partition , but then this needs to reach an upper limit and stop

**Comment by eapache** [comment]
> Why is it creating a async Producer and a Partition Producer, when from my code i create a NewSyncProducer?

The sync producer is just a wrapper around the async producer which has a bit of extra logic to wait for each message. This part is normal.

> It seems that sarama creates a go routine with partition producer for every partition , but then this needs to reach an upper limit and stop

How many partitions do you have in your topics? Sarama will create a goroutine for every partition as you notice, a long with a few others (one per broker, so an extra 10 in your case, plus a few singleton goroutines). It should reach an upper limit and stop however.

The logs requested in the issue template would help a lot here.

**Comment by Kartikkumar-Shetty** [comment]
We have 256 partitions per topic and we have 6 topic, but the goroutine count does not stabilize

**Comment by eapache** [comment]
I wouldn’t expect it to stabilize until ~1600 goroutines are created. Does it increase beyond that point?

**Comment by Kartikkumar-Shetty** [comment]
We have not seen more than 1600 goroutines on our test server yet but number of goroutine keeps increasing the max number I have seen is around 1400 and increasing, is this normal and as the number of requests to kafka increase will the number of goroutines increase as well ? since we are seeing spike in go routines on our Live Systems

**Comment by eapache** [comment]
>  is this normal

Yes, when you have such a large number of total partitions (6*256 = 1536) then an equivalently large number of goroutines is normal.

> as the number of requests to kafka increase will the number of goroutines increase as well

The per-partition goroutines are created lazily as needed, which is why the count gradually increases after startup. However, the count will stabilize once all partitions have been accessed.

This behaviour is normal, correct, and perfectly safe unless you are running under extremely limited memory. There is no leak, and goroutines are very cheap.

I would suggest though, based on this behaviour, that you don't need 256 partitions on your topics. You are clearly not seeing sufficient load to require that kind of parallelism.
