### ISSUE TITLE
Message was too large, server rejected it to avoid allocation error when using Headers

### ISSUE THREAD

**Issue by eapache** [Shopify/sarama#1045]
@pkedy from https://github.com/Shopify/sarama/pull/1040#issuecomment-365025401

That error can occur in two ways:
- The producer will short-circuit a message on its own if it detects it too large: https://github.com/Shopify/sarama/blob/f7be6aa2bc7b2e38edf816b08b582782194a1c02/async_producer.go#L274-L277 That check currently includes the length of headers, but maybe it shouldn't?
- The broker sends it back to us.

If increasing the client-side config makes it go away that *sounds* like the first case? Kafka 0.11 did change how some of these configs were checked broker-side (e.g. https://github.com/Shopify/sarama/issues/959#issuecomment-333950995) but AFAICT that was mostly loosening the restrictions, not tightening them.

**Comment by ccassar** [comment]
In the case where compression is enabled the size test coming into async producer in dispatcher() is performed against the uncompressed payload. Is this intentional?

**Comment by eapache** [comment]
:thinking: it's been a while but I think it is; if I remember correctly the broker-side check is also against the uncompressed size. Or at least, it was for the older compression formats. It's possible that the new 1.0 record set format changed that?

**Comment by ccassar** [comment]
I ran a quick couple of tests and it would seem the broker side uses compressed size for test.

producer messages.max.bytes 20M, compression off, topic created with  max.message.bytes 5M
  msg size of 15M rejected "kafka server: Message was too large, server rejected it to avoid allocation error."

producer messages.max.bytes 20M, compression gzip, topic created with  max.message.bytes 5M
  msg size of 15M accepted and consumer from kafka-console-consumer

(I set producer side to 20M to skip the test in dispatcher).

**Comment by adwinsky** [comment]
I think it is done like this because there is no efficient way to determine the size of the raw data after the compression, which you need to know in advance to spawn a new messages buffer in brokerProducer worker when it exceeds max message limit. 

But this is not a big problem. In case you use compression and this limit, you can just make it 2-3 times larger (as the average compression rate), and this would give similar results.

**Comment by kmulvey** [comment]
kafka verion: 2.2
message bytes: 276
compression: off
sarama: 1.20.1
socket.request.max.bytes=1048576000  & a second try with 104857600

Ive been trying to produce the same message 10M times and its succeeds most times (5/6) but (1/6) fails with "message too large" error. It seems that if the size of each message is the same, the same number of messages should fit in each batch. It should either always success or always fail, no?
