### ISSUE TITLE
question: Long running process with TLS client certificate expiration

### ISSUE THREAD

**Issue by andrewhavck** [Shopify/sarama#1054]
##### Versions

Sarama Version: v1.14.0
Kafka Version: 0.10.0.1
Go Version: 1.8.3

##### Logs

```
client/metadata got error from broker while fetching metadata: local error: tls: no renegotiation
client/metadata got error from broker while fetching metadata: local error: tls: no renegotiation
client/brokers deregistered broker #-1 at <broker>:<port>
client/metadata no available broker to send metadata request to
client/brokers resurrecting 3 dead seed brokers
kafka: Failed to produce message to topic access-logs: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)..
client/metadata got error from broker while fetching metadata: local error: tls: no renegotiation
client/brokers resurrecting 0 dead seed brokers
Client background metadata update: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
client/metadata fetching metadata for all topics from broker <broker>:<port>
client/metadata got error from broker while fetching metadata: local error: tls: no renegotiation
client/brokers deregistered broker #-1 at <broker>:<port>
client/metadata fetching metadata for [access-logs] from broker <broker>:<port>
client/metadata got error from broker while fetching metadata: local error: tls: no renegotiation
client/brokers deregistered broker #-1 at <broker>:<port>
client/metadata fetching metadata for [access-logs] from broker <broker>:<port>
client/metadata got error from broker while fetching metadata: local error: tls: no renegotiation
```

##### Problem Description

Sarama applications that are long running and use a TLS client certificate enter a **tls: no renegotiation** loop when the certificate expires. An **ErrOutOfBrokers** error will eventually come through the AsyncProducer Errors() channel but this doesn't describe the TLS connection issue.

How are others in the Sarama community handling this? Ideally I'd want to stop the AsyncProducer and re-initialize a new one with an updated tls.Config when the **tls: no renegotiation** error is received. Is there a way to capture the renegotiation error and act on it?

**Comment by eapache** [comment]
A couple of ideas here:
- I suppose `ErrOutOfBrokers` can/should wrap the underlying connection issue (if any) so that you can identify it when it comes back.
- It's probably useful to have a blacklist of error types (such as tls: no renegotiation) which are not retriable in order to short-circuit that process and make recovery faster.

**Comment by andyfeller** [comment]
Something similar also happens whenever the kafka brokers renew their certificates without restarting the service using sarama.

**Comment by andrewhavck** [comment]
@eapache Thanks for responding to my issue.

>I suppose ErrOutOfBrokers can/should wrap the underlying connection issue (if any) so that you can identify it when it comes back.

I see value in doing this for broad error handling and debugging when the cluster is no longer reachable, I'm not sure if it's the right solution for this scenario.

>It's probably useful to have a blacklist of error types (such as tls: no renegotiation) which are not retriable in order to short-circuit that process and make recovery faster.

This feels like the right approach for handling unrecoverable connection issues.

I'd be willing to submit a pull request if you believe this is how Sarama should be handling these errors.

**Comment by eapache** [comment]
> I'm not sure if it's the right solution for this scenario.

I think it basically is: it will let you capture the error, stop the producer and initialize a new one with the updated config?

**Comment by andrewhavck** [comment]
>I think it basically is: it will let you capture the error, stop the producer and initialize a new one with the updated config?

Having `ErrOutOfBrokers` wrap the underlying connection issue works but it makes the application responsible for knowing when the producer needs to be re-initialized or not. It would be nice if the producer told the application when it needed to be re-initialized. I'd imagine this would happen whenever the producer matched a blacklisted error. Perhaps an `ErrOutOfBrokersFatal` code could relay the information?

**Comment by eapache** [comment]
I think that makes sense. Although I'm not sure how many errors we can really know that for in advance? Even `tls: no renegotiation` could indicate a broker-side misconfiguration, and the producer will keep running fine if you fix the broker?

**Comment by andrewhavck** [comment]
Good point, to limit scope and make things simple for this use case it makes sense to only wrap the underlying connection issue with `ErrOutOfBrokers` so the client can handle it.

**Comment by andyfeller** [comment]
Oh the memories.  Guess nothing came about this.  Good times.
