### ISSUE TITLE
Plans to support SASL/SCRAM authentication?

### ISSUE THREAD

**Issue by tarikdemirci** [Shopify/sarama#1057]
##### Problem Description
Is there anyone working on SASL/SCRAM support?

##### Related links
http://kafka.apache.org/documentation.html#security_sasl_scram
https://www.cloudkarafka.com/docs-go.html  (This doc implies Sarama has no support for SCRAM and suggests confluent-kafka-go instead)

**Comment by eapache** [comment]
I am not currently working on this. Per https://github.com/Shopify/sarama/blob/bfaa60f9e0d0b6781a78ed5f01e0426615a5ea13/config.go#L43-L44 the only supported method right now is `SASL/PLAIN`.

**Comment by chasse-code** [comment]
I would like to have SCRAM authentication too. It's been a part of Kafka for a while now and there are valid reasons to want to have the secret not be plain. Not sure why that comment indicates that SASL/PLAIN is the only one.

**Comment by tarikdemirci** [comment]
> Not sure why that comment indicates that SASL/PLAIN is the only one.

It's the only supported SASL option by Sarama right now. There is also SASL/GSSAPI which is again not supported by Sarama.

**Comment by chasse-code** [comment]
I would love to have the authentication methods match that which is currently supported by Kafka. I have to rework our security to be able to allow Burrow to be able to communicate with Kafka over PLAINTEXT so it can access the __consumer_offsets but no other topics.

**Comment by neqel** [comment]
Are there any plans on implementing support for this yet?

**Comment by eapache** [comment]
I'm not working on this in the foreseeable future. I'm happy to take PRs though.

**Comment by freddiesunarso** [comment]
@eapache would you give some pointer/guidance on how to add this support?

**Comment by enrmarc** [comment]
Hi. What's the status of the SASL/SCRAM support?

**Comment by praseodym** [comment]
https://github.com/Shopify/sarama/pull/1295

**Comment by jbresciani** [comment]
with scram support now in Sarama will we be seeing support for it in burrow? or is it there already?
