### ISSUE TITLE
Which import case is authoritative: Shopify/shopify?

### ISSUE THREAD

**Issue by therealplato** [Shopify/sarama#1058]
While trying to vendor a repo with `dep` I encountered this:
```
master: Could not introduce github.com/bsm/sarama-cluster@master due to a case-only variation: it depends on "github.com/Shopify/sarama", but "github.com/shopify/sarama" was already established as the case variant for that project root by depender (root)
```
This makes sense, dependency `github.com/bsm/sarama-cluster` wants upper case `Shopify` and my code is importing lower case `shopify`. 

I encountered similar issues with [`Sirupsen/sirupsen`](https://github.com/sirupsen/logrus/issues/451) and it was a pain to resolve.

I suspect my code's lowercase import is wrong but I'd like official confirmation. Can you bless either `github.com/Shopify/sarama` or `github.com/shopify/sarama` as an authoritative import path?

**Comment by eapache** [comment]
I tend to prefer `github.com/Shopify/sarama` but I don't know if there's any technical way to bless that?

**Comment by therealplato** [comment]
Places I looked were readme and issue search for "case", "import"

**Comment by eapache** [comment]
Well, this ticket should do then :)
