### ISSUE TITLE
Samara 1.16.0 / go 1.9.4 x86_64 → FAIL: TestProduceRequest 

### ISSUE THREAD

**Issue by nim-nim** [Shopify/sarama#1061]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.16.0
Kafka Version: N/A
Go Version: 1.9.4 x86_64

Installed:
  golang-github-davecgh-spew-devel.noarch 1.1.1-0.4.0.20180301git8991bc2.el7.llt
  golang-github-eapache-go-resiliency-devel.noarch 0-0.2.gitb86b1ec.el7         
  golang-github-eapache-queue-devel.noarch 1.1.0-1.0.el7.llt                    
  golang-github-eapache-xerial-snappy-devel.noarch 0-0.1.0.20180228gitbb955e0.el7.llt
  golang-github-pierrec-lz4-devel.noarch 0-0.1.0.20180228gited8d4cc.el7.llt     
  golang-github-rcrowley-metrics-devel.noarch 0-0.23.0.20180228gite181e09.el7.llt
  golang-github-shopify-toxiproxy-devel.noarch 2.1.2-2.0.20180228gita321431.el7.llt
  golang-github-BurntSushi-toml-devel.noarch 0-0.10.git2ceedfe.el7              
  golang-github-gorilla-mux-devel.noarch 1.6.1-1.0.el7.llt                      
  golang-github-pierrec-xxhash-devel.noarch 0-0.1.0.20180228gita0006b1.el7.llt  
  golang-github-rcrowley-metrics.x86_64 0-0.23.0.20180228gite181e09.el7.llt     
  golang-github-sirupsen-logrus-devel.noarch 1.0.4-2.0.el7.llt                  
  golang-github-snappy-devel.noarch 0-0.22.0.20180228git553a641.el7.llt         
  golang-github-stathat-devel.noarch 0-0.19.0.20180228git74669b9.el7.llt        
  golang-github-urfave-cli-devel.noarch 1.18.0-0.1.git61f519f.el7               
  golang-gopkg-tomb-1-devel.noarch 0-0.21.0.20180228gitdd63297.el7.llt          
  golang-gopkg-yaml-devel-v2.noarch 1-15.el7                                    
  golang-x-crypto-devel.noarch 0-0.28.0.20180228git91a49db.el7.llt              
  golang-x-sys-unix-devel.noarch 0-0.27.0.20180228gitf6cff07.el7.llt  

##### Configuration

Just running default unit tests

##### Logs

```(shell)
go test -buildmode pie -compiler gc -ldflags ' -X github.com/Shopify/sarama/version=1.16.0 -extldflags '\''-Wl,-z,relro  '\'''
--- FAIL: TestProduceRequest (0.00s)
        request_test.go:76: Decoded request "one record" does not match the encoded one
                encoded: <*>(0xc4202e71c0){TransactionalID:<nil> RequiredAcks:291 Timeout:1092 Version:3 records:map[topic:map[173:{recordsType:2 msgSet:<nil> recordBatch:<*>(0xc4203ca0a0){FirstOffset:0 PartitionLeaderEpoch:0 Version:2 Codec:0 Control:false LastOffsetDelta:1 FirstT
imestamp:2016-11-22 21:49:55 +0100 CET MaxTimestamp:1970-01-01 01:00:00 +0100 CET ProducerID:0 ProducerEpoch:0 FirstSequence:0 Records:[<*>(0xc4200a6b60){Attributes:0 TimestampDelta:5ms OffsetDelta:0 Key:[1 2 3 4] Value:[5 6 7] Headers:[<*>(0xc4207eaae0){Key:[8 9 10] Value:[11 12]}
] length:{startOffset:0 length:20}}] PartialTrailingRecord:false compressedRecords:[40 0 10 0 8 1 2 3 4 6 5 6 7 2 6 8 9 10 4 11 12] recordsLen:21}}]]}
                decoded: <*>(0xc4202e74a0){TransactionalID:<nil> RequiredAcks:291 Timeout:1092 Version:3 records:map[topic:map[173:{recordsType:2 msgSet:<nil> recordBatch:<*>(0xc4203ca140){FirstOffset:0 PartitionLeaderEpoch:0 Version:2 Codec:0 Control:false LastOffsetDelta:1 FirstTimestamp:2016-11-22 21:49:55 +0100 CET MaxTimestamp:1970-01-01 01:00:00 +0100 CET ProducerID:0 ProducerEpoch:0 FirstSequence:0 Records:[<*>(0xc4200a6bd0){Attributes:0 TimestampDelta:5ms OffsetDelta:0 Key:[1 2 3 4] Value:[5 6 7] Headers:[<*>(0xc4207eac00){Key:[8 9 10] Value:[11 12]}] length:{startOffset:0 length:20}}] PartialTrailingRecord:false compressedRecords:<nil> recordsLen:21}}]]}
FAIL
```

**Comment by eapache** [comment]
`-buildmode pie` is not supported on my computer, but otherwise the unit tests pass for me with an identical command (and of course they're regularly passing on CI). It looks like the failure you posted is due to a difference in compression; perhaps one of the compression libraries is not working properly on your system?

**Comment by nim-nim** [comment]
Well, I rebuilt all the stack it depends on switched to Go 1.10, and yet:

```
+ GOPATH=/builddir/build/BUILD/sarama-1.16.0/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro  '\'''
--- FAIL: TestMessageEncoding (0.00s)
	request_test.go:34: Encoding empty gzip failed
		got  [132 99 80 148 0 1 255 255 255 255 0 0 0 23 31 139 8 0 0 0 0 0 0 255 1 0 0 255 255 0 0 0 0 0 0 0 0] 
		want [97 79 149 90 0 1 255 255 255 255 0 0 0 23 31 139 8 0 0 9 110 136 0 255 1 0 0 255 255 0 0 0 0 0 0 0 0]
--- FAIL: TestProduceRequest (0.00s)
	request_test.go:76: Decoded request "one record" does not match the encoded one
		encoded: <*>(0xc420426ba0){TransactionalID:<nil> RequiredAcks:291 Timeout:1092 Version:3 records:map[topic:map[173:{recordsType:2 msgSet:<nil> recordBatch:<*>(0xc4201963c0){FirstOffset:0 PartitionLeaderEpoch:0 Version:2 Codec:0 Control:false LastOffsetDelta:1 FirstTimestamp:2016-11-22 21:49:55 +0100 CET MaxTimestamp:1970-01-01 01:00:00 +0100 CET ProducerID:0 ProducerEpoch:0 FirstSequence:0 Records:[<*>(0xc420494070){Attributes:0 TimestampDelta:5ms OffsetDelta:0 Key:[1 2 3 4] Value:[5 6 7] Headers:[<*>(0xc420200420){Key:[8 9 10] Value:[11 12]}] length:{startOffset:0 length:20}}] PartialTrailingRecord:false compressedRecords:[40 0 10 0 8 1 2 3 4 6 5 6 7 2 6 8 9 10 4 11 12] recordsLen:21}}]]}
		decoded: <*>(0xc420426ea0){TransactionalID:<nil> RequiredAcks:291 Timeout:1092 Version:3 records:map[topic:map[173:{recordsType:2 msgSet:<nil> recordBatch:<*>(0xc420196460){FirstOffset:0 PartitionLeaderEpoch:0 Version:2 Codec:0 Control:false LastOffsetDelta:1 FirstTimestamp:2016-11-22 21:49:55 +0100 CET MaxTimestamp:1970-01-01 01:00:00 +0100 CET ProducerID:0 ProducerEpoch:0 FirstSequence:0 Records:[<*>(0xc4204942a0){Attributes:0 TimestampDelta:5ms OffsetDelta:0 Key:[1 2 3 4] Value:[5 6 7] Headers:[<*>(0xc420200540){Key:[8 9 10] Value:[11 12]}] length:{startOffset:0 length:20}}] PartialTrailingRecord:false compressedRecords:<nil> recordsLen:21}}]]}
FAIL
```

**Comment by eapache** [comment]
That's really weird, I still can't reproduce and I don't know what could be causing this.

**Comment by eapache** [comment]
@abjsaha just reported this too, so it's something real even if I still can't reproduce it.
