### ISSUE TITLE
Produce message with sarama cost too much time(sometimes 1s,2s)

### ISSUE THREAD

**Issue by pirlck** [Shopify/sarama#1062]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.0
Kafka Version:1.0
Go Version:1.8

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs
435 func (b *Broker) send(rb protocolBody, promiseResponse bool) (*responsePromise, error) {
436     in := time.Now()
437     Logger.Printf("in func[%s]", in)
438     defer func() {
439         out := time.Since(in)
440         Logger.Printf("call send func cost[%s]", out)
441     }()
442 
443     b.lock.Lock()
444     defer b.lock.Unlock()
445 
446     sendTime := time.Now()

INFO 2018-03-02 14:49:44 broker.go:
in func[2018-03-02 14:49:41.997159421 +0800 CST],      --> 436
send time[2018-03-02 14:49:44.003321624 +0800 CST]  --> 446
INFO 2018-03-02 14:49:44 broker.go:440 call send func cost[2.006262616s]

##### Problem Description
I try to print cost time in functions and determine the send() functions in broker.go cost much of time.
Further， I print the 436 and 446 line timestamp and the time difference sometimes can reach to 1->2s.

may the lock in golang cause the problem?

**Comment by eapache** [comment]
That is where the broker will block if you already have `config.Net.MaxOpenRequests` in flight. Try increasing that value?

**Comment by tcrayford** [comment]
as a note, GC pauses on kafka could also cause this kind of issue. Anything like that in your broker's GC logs?

**Comment by pirlck** [comment]
@eapache   Ok, I will try it. 
Sarama version is  Version 1.15.0
 13     config.Producer.Return.Successes = true
 14     config.Producer.MaxMessageBytes = topic.MaxMessage
 15     config.Producer.Timeout = topic.RepTimeout(500ms)
 16     config.Producer.Partitioner = sarama.NewHashPartitioner
 17     config.Producer.RequiredAcks = sarama.WaitForAll
  Other configuration items by default.
  Thank you ~~

**Comment by pirlck** [comment]
@tcrayford   I do not find broker's GC logs.
Thank you ~

**Comment by pirlck** [comment]
@eapache . This problem occured since I updated the sarama from version 1.10.1 to 1.15.0, because i want to use kafka1.0

**Comment by pirlck** [comment]
@eapache  I tried  increasing config.Net.MaxOpenRequests to 10(default), but it does not work.

**Comment by eapache** [comment]
Please try with v1.16. If that doesn’t work, it would be helpful to know which version introduced this problem.

**Comment by pirlck** [comment]
@eapache  Hi, it seems that  the number of clients has  influence. I change it smaller (300 -> 10) and that case happen less. But still the following case happen and  make  the production have long time(about 1s)

 async_producer.go:834 producer/broker/1 state change to [closing] because EOF
 broker.go:189 Closed connection to broker gzns-kafka-es01.gzns.iwm.name:9094
 async_producer.go:486 producer/leader/wmsg/38 state change to [retrying-1]
 async_producer.go:496 producer/leader/wmsg/38 abandoning broker 1
 
What is the reason for EOF? And which paraments can i adjust to avoid this case?

Thank you ~

**Comment by eapache** [comment]
`EOF` means the broker closed the connection. The reason will be in the broker's logs.

**Comment by pirlck** [comment]
OK, I will read the broker logs. Thank you~
