### ISSUE TITLE
client has run out of available brokers to talk to (Is your cluster reachable?)

### ISSUE THREAD

**Issue by cosastro** [Shopify/sarama#1067]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.0
Kafka Version:0.8
Go Version:1.8

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

I use sarama(version 1.0) to send lots of messages to kafka of version 0.8, some of the messages can be sent successfully, but some of them failed, and I got "client has run out of available brokers to talk to (Is your cluster reachable?)", please help me, thanks a lot.

**Comment by eapache** [comment]
Please provide the Sarama logs, they will have more details about what the error is.

**Comment by homer6** [comment]
I ran into this issue, too, but was able to resolve it.

I added 

    //verbose debugging (comment this line to disabled verbose sarama logging)
    sarama.Logger = log.New(os.Stdout, "[sarama] ", log.LstdFlags)

to enable the verbose logging. After which, it said that I was not including my port number in the connection string. I would have thought it would use the default kafka port, if unspecified, as rdkafka does, but samara requires it to be explicitly set.

I actually left verbose logging on and was able to gain valuable information on another hard to diagnose issue. So, I've chosen to leave verbose logging on for production because it doesn't appear to be too verbose.

**Comment by eapache** [comment]
The logging is intended to be fairly quiet - we run with it in production. The only reason it doesn't default to enabled is because it's not good practice for a library to start randomly generating output to stdout, and there's no other good default location to log to.

**Comment by homer6** [comment]
The log level makes sense as a default as you have it.

What I meant by default was the port number. If I left the port number off of the connection string, I'd expect Sarama to default to kafka's default port 9092. Right now, if I leave the port off of the connection string, it generates the "client has run out of available brokers to talk to" error.

Thanks for Sarama, btw. It works really well!

**Comment by eapache** [comment]
Ah, ya, that's a bit awkward. We just pass the string you provide to https://golang.org/pkg/net/#Dial so Sarama never treats it as structured at all. I suppose we could use https://golang.org/pkg/net/#SplitHostPort or something to parse it, default the port number, and then join it together again?

I wouldn't be opposed to a Pull Request implementing that, but it seems like a lot of work for minor benefit.

**Comment by eapache** [comment]
With recent kafka versions now using a separate port for secure/TLS connections, defaulting the port becomes even more error-prone, so I don't think there's enough value in us trying to do that.
