### ISSUE TITLE
SSL: Unexpected EOF while fetching metadata from broker

### ISSUE THREAD

**Issue by andrewmunro** [Shopify/sarama#1071]
##### Versions
Sarama Version: v1.16.0 (f7be6aa2bc7b2e38edf816b08b582782194a1c02)
Kafka Version: Kafka 2.12-0.11.0.1
Go Version: golang:1.10-alpine (https://github.com/docker-library/golang/blob/9bf6daddb324a4d8e82b0613cf348a6eff363f95/1.10/alpine3.7/Dockerfile)

##### Configuration
Kafka: 
listeners=plaintext://:10092,ssl://:9093
ssl.client.auth=requested
ssl.enabled.protocols=TLSv1.2
security.inter.broker.protocol=SSL
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
allow.everyone.if.no.acl.found=true
inter.broker.protocol.version=0.11.0.0

Sarama:

Im using the https://github.com/lovoo/goka library with the following setup:

```
	caCertPool := x509.NewCertPool()
	caCertPool.AppendCertsFromPEM([]byte(caCert))

	cert, err := tls.X509KeyPair([]byte(clientCrt), []byte(clientKey))
	if err != nil {
		panic(err)
	}

	tlsConfig := &tls.Config{
		Certificates:       []tls.Certificate{cert},
		RootCAs:            caCertPool,
		InsecureSkipVerify: true,
		CipherSuites:       []uint16{tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384},
	}

	tlsConfig.BuildNameToCertificate()

	config := kafka.NewConfig()
	config.Net.TLS.Enable = true
	config.Net.TLS.Config = tlsConfig

	view, err := goka.NewView(
		brokers,
		goka.GroupTable(group),
		new(codec),
		goka.WithViewConsumerBuilder(
			kafka.ConsumerBuilderWithConfig(config),
		),
	)

	if err != nil {
		panic(err)
	}
	go view.Start()
	defer view.Stop()
```

##### Logs
```
[Sarama] 2018/03/22 11:49:10 Initializing new client
[Sarama] 2018/03/22 11:49:10 client/metadata fetching metadata for all topics from broker redacted:9093
[Sarama] 2018/03/22 11:49:10 Connected to broker at redacted:9093 (unregistered)
[Sarama] 2018/03/22 11:49:11 client/brokers registered new broker #2 at redacted:9093
[Sarama] 2018/03/22 11:49:11 client/brokers registered new broker #4 at redacted:9093
[Sarama] 2018/03/22 11:49:11 client/brokers registered new broker #1 at redacted:9093
[Sarama] 2018/03/22 11:49:11 client/brokers registered new broker #3 at redacted:9093
[Sarama] 2018/03/22 11:49:11 client/brokers registered new broker #0 at redacted:9093
[Sarama] 2018/03/22 11:49:11 Successfully initialized new client
[Sarama] 2018/03/22 11:49:11 Initializing new client
[Sarama] 2018/03/22 11:49:11 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[Sarama] 2018/03/22 11:49:11 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[Sarama] 2018/03/22 11:49:11 client/metadata fetching metadata for all topics from broker redacted:9093
[Sarama] 2018/03/22 11:49:11 Connected to broker at redacted:9093 (unregistered)
[Sarama] 2018/03/22 11:49:11 bytes read:  7
[Sarama] 2018/03/22 11:49:11 header err:  unexpected EOF
[Sarama] 2018/03/22 11:49:11 client/metadata got error from broker while fetching metadata: unexpected EOF
[Sarama] 2018/03/22 11:49:11 Closed connection to broker redacted:9093
```

##### Problem Description

I'm trying to connect to our kafka cluster on the SSL port. It seems to fail reading the metadata and fetching the topics. I can connect using other clients and on the plaintext port.

I can even connect using openssl:

```
:: openssl s_client -connect redacted:9093
...
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
```

I've traced the issue down to the following code:
https://github.com/Shopify/sarama/blob/v1.16.0/broker.go#L645

It seems to be reading 7 bytes when it expects 8 for the header. Every other SSL issue I've seen issues with the TLS handshake, but from the logs it seems to be connecting fine, discovering the other available brokers but then choking fetching metadata. I'm pretty sure this is a problem with my setup somewhere, but I have no idea how to diagnose further.

**Comment by eapache** [comment]
🤔 Are there broker-side logs when this happens? "Unexpected EOF" usually means the broker hit an exception and killed the connection.

> from the logs it seems to be connecting fine, discovering the other available brokers but then choking fetching metadata

I'm not sure this is true. From the looks of your Sarama logs there are *two* clients being created (note "Initializing new client" twice). One is connecting *and* fetching metadata correctly, the other is failing on the initial connect. But it's hard to tell because it's not clear which logs belong to which client unfortunately.

**Comment by andrewmunro** [comment]
@eapache thanks for pointing me in the right direction. The key was that there was two clients connecting, one to fetch the topics and the other to pull the data. I had only configured one to use TLS, so it was failing to connect! I had to make a few modifications to the goka library, but this is my setup now:
```
	c := connection.NewConfig(certPath)

	view, err := goka.NewView(
		brokers,
		goka.GroupTable(group),
		new(customer.Codec),
		**goka.WithViewTopicManagerBuilder(
			kafka.TopicManagerBuilderWithConfig(c),
		),**
		goka.WithViewConsumerBuilder(
			kafka.ConsumerBuilderWithConfig(c),
		),
	)```

I'll open an issue with them to get this working!
