### ISSUE TITLE
DescribeAcls returns empty Acl's list

### ISSUE THREAD

**Issue by sarunask** [Shopify/sarama#1075]
##### Versions
Sarama Version: 5e8fd95863bd4a894fcd29225547d56967f189ad
Kafka Version: kafka_2.11-1.0.0
Go Version: 0.10.1

##### Configuration

Kafka configured with ACLs (kafka.security.auth.SimpleAclAuthorizer) based on X.509 cert subject names.
Sarama config:
>	config := sarama.NewConfig()
>	config.Producer.RequiredAcks = sarama.WaitForAll // Wait for all in-sync replicas to ack the message
>	config.Producer.Retry.Max = 10                   // Retry up to 10 times to produce the message
>	config.Producer.Return.Successes = true
>	config.Version = sarama.V1_0_0_0
>	config.ClientID = "acl_reader"
>	tlsConfig := createTlsConfiguration()
>	config.Net.TLS.Config = tlsConfig
>	config.Net.TLS.Enable = true
>
>	describeAclsReq := &sarama.DescribeAclsRequest{
>		AclFilter: sarama.AclFilter{
>			ResourceType: sarama.AclResourceTopic,
>			PermissionType: sarama.AclPermissionAny,
>		},
>	}
>
>	broker := newBroker(brokerList)
>	defer func() {
>		if err := broker.Close(); err != nil {
>			log.Panic(err)
>		}
>	}()
>
>	describeAclsResp, err := broker.DescribeAcls(describeAclsReq)
>	if err != nil {
>		log.Fatal(err)
>	}
>	acls := describeAclsResp.ResourceAcls
>	log.Print(acls)

##### Logs

Sarama log output:
>[sarama] 2018/04/06 03:39:41 Successfully initialized new client
>[sarama] 2018/04/06 03:39:41 Connected to broker at 127.0.0.1:9093 (unregistered)
>2018/04/06 03:39:41 []
>[sarama] 2018/04/06 03:39:41 Closed connection to broker 127.0.0.1:9093

Kafka Authorizer DEBUG log output:
>[2018-04-06 03:21:37,653] DEBUG operation = Describe on resource = Cluster:kafka-cluster from host = 127.0.0.1 is Allow based on acl = User:CN=sk-test.servers-managers.io has Allow permission for operations: Describe from hosts: * (kafka.authorizer.logger)
>[2018-04-06 03:21:37,653] DEBUG Principal = User:CN=sk-test.servers-managers.io is Allowed Operation = Describe from host = 127.0.0.1 on resource = Cluster:kafka-cluster (kafka.authorizer.logger)

##### Problem Description

Sarama doesn't return any ACL's which are on Kafka cluster, even permissions for that are granted and Java adminClient, with same certs, returns all ACL's.

**Comment by buyology** [comment]
You have to specify an `Operation` to filter on — the zero value for `Operation` is `AclOperationUnknown`. 

This should work:

```go
describeAclsReq := &sarama.DescribeAclsRequest{
	AclFilter: sarama.AclFilter{
		ResourceType:   sarama.AclResourceTopic,
		PermissionType: sarama.AclPermissionAny,
		Operation:      sarama.AclOperationAny,
	},
}
```

**Comment by sarunask** [comment]
Thank you, this code works :)
