### ISSUE TITLE
i can‘t get library

### ISSUE THREAD

**Issue by 15029836736** [Shopify/sarama#1076]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:  
Kafka Version:  
Go Version: 1.6.3

##### Problem Description
when I get library：
go get -u github.com/Shopify/sarama
# github.com/Shopify/sarama
/home/XX/goproc/src/github.com/Shopify/sarama/delete_records_request.go:96: undefined: sort.Slice
/home/xx/goproc/src/github.com/Shopify/sarama/delete_records_response.go:99: undefined: sort.Slice

**Comment by eapache** [comment]
Per the README, we currently only support back to Go 1.8, where (I believe) `sort.Slice` was added. You might want to try a different tagged version rather than master.
