### ISSUE TITLE
SyncProducer should respect context deadlines

### ISSUE THREAD

**Issue by MatthewDolan** [Shopify/sarama#1078]
##### Versions

Sarama Version: 8da9fa72b86689a02355dca1182444cca607e054 (latest master)
Kafka Version: 1.0.0
Go Version: 1.10

##### Configuration

Standard Configuration for Synchronous Production.

##### Logs

No specific logs.

##### Problem Description

The problem I saw with this is that if Kafka takes a long time to respond to requests or hangs entirely, the SendMessage and SendMessages in the SyncProducer calls will block for a long time (holding resources like memory and creating an unbounded queue of messages that will try to be enqueued when the kafka becomes available again).

One nice way to get around this is to use context deadline and cancelation. This is similar to how the sql client used context to cancel requests if something ends up hanging.

I have a working version of the code changes submitted as a pull request (https://github.com/Shopify/sarama/pull/1077) but wanted provide the motivation for the change with with this issue.

**Comment by eapache** [comment]
The PR you filed originally *looks* roughly correct to me.

Really though, by using the `SyncProducer` I assume that blocking is the behaviour you want. If you want non-blocking or timeouts or anything like that, you can just use the `AsyncProducer` instead? That's what it's for.

**Comment by eapache** [comment]
Feel free to reopen if you come up with anything.
