### ISSUE TITLE
can sarama support alter a topic?

### ISSUE THREAD

**Issue by jilieryuyi** [Shopify/sarama#1081]
hi, all
I can find a way to create a topic use sarama, but i can not find a way to alter a topic, like add Partitions or change ReplicationFactor, can sarama support it ?

can somebody tell me?

**Comment by eapache** [comment]
CreatePartitions: https://github.com/Shopify/sarama/blob/8da9fa72b86689a02355dca1182444cca607e054/broker.go#L389

DeletePartitions: https://github.com/Shopify/sarama/blob/8da9fa72b86689a02355dca1182444cca607e054/broker.go#L411

AlterConfigs: https://github.com/Shopify/sarama/blob/8da9fa72b86689a02355dca1182444cca607e054/broker.go#L532
