### ISSUE TITLE
Question - Does sync producer SendMessages() method guarantees ordering in a batch?

### ISSUE THREAD

**Issue by varun06** [Shopify/sarama#1085]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: e8552c0
Kafka Version: Latest
Go Version: 1.10

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

After reading code for SendMessages, it seems that there is no order guarantee in batch ->
https://github.com/Shopify/sarama/blob/431b10fa60888b165be2892b8f4a6bb82af5475b/sync_producer.go#L109-L142

Am I right , is it possible to keep the order?

**Comment by eapache** [comment]
The ordering is guaranteed, because the loop on line 122 iterates over the messages in order and puts them into `sp.producer.Input()` in order.

**Comment by varun06** [comment]
My bad, I was asking about failure case, what happens when a publish fails in middle of the batch? does it stop or it retries that particular message?

**Comment by eapache** [comment]
I think https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#does-saramas-producer-guarantee-message-ordering and https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#does-saramas-producer-guarantee-that-successful-messages-are-contiguous cover your main points?

**Comment by varun06** [comment]
That clears it, thanks a lot.
