### ISSUE TITLE
broker.ApiVersions does not reflect real supported API version

### ISSUE THREAD

**Issue by schinivision** [Shopify/sarama#1088]
##### Versions

Sarama Version: e8552c0dbf502cd7ec9186b57897e6cf9f15fb34
Kafka Version: 1.0.0
Go Version: go1.9.4 windows/amd64

Attached to a 3 node kafka cluster

##### Problem Description

I found an issue when I wanted to refresh MetaData from a broker (broker.GetMetadata)

First I ask the Broker about the supported API versions.

```go
apiVersion, errorApiVersion := broker.ApiVersions(&sarama.ApiVersionsRequest{})
```

The Result is this:

>ApiVersions of Broker Key 0 : &{ApiKey:0 MinVersion:0 MaxVersion:5}
>ApiVersions of Broker Key 1 : &{ApiKey:1 MinVersion:0 MaxVersion:6}
>ApiVersions of Broker Key 2 : &{ApiKey:2 MinVersion:0 MaxVersion:2}
>ApiVersions of Broker Key 3 : &{ApiKey:3 MinVersion:0 MaxVersion:5}
>ApiVersions of Broker Key 4 : &{ApiKey:4 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 5 : &{ApiKey:5 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 6 : &{ApiKey:6 MinVersion:0 MaxVersion:4}
>ApiVersions of Broker Key 7 : &{ApiKey:7 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 8 : &{ApiKey:8 MinVersion:0 MaxVersion:3}
>ApiVersions of Broker Key 9 : &{ApiKey:9 MinVersion:0 MaxVersion:3}
>ApiVersions of Broker Key 10 : &{ApiKey:10 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 11 : &{ApiKey:11 MinVersion:0 MaxVersion:2}
>ApiVersions of Broker Key 12 : &{ApiKey:12 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 13 : &{ApiKey:13 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 14 : &{ApiKey:14 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 15 : &{ApiKey:15 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 16 : &{ApiKey:16 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 17 : &{ApiKey:17 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 18 : &{ApiKey:18 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 19 : &{ApiKey:19 MinVersion:0 MaxVersion:2}
>ApiVersions of Broker Key 20 : &{ApiKey:20 MinVersion:0 MaxVersion:1}
>ApiVersions of Broker Key 21 : &{ApiKey:21 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 22 : &{ApiKey:22 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 23 : &{ApiKey:23 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 24 : &{ApiKey:24 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 25 : &{ApiKey:25 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 26 : &{ApiKey:26 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 27 : &{ApiKey:27 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 28 : &{ApiKey:28 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 29 : &{ApiKey:29 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 30 : &{ApiKey:30 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 31 : &{ApiKey:31 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 32 : &{ApiKey:32 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 33 : &{ApiKey:33 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 34 : &{ApiKey:34 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 35 : &{ApiKey:35 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 36 : &{ApiKey:36 MinVersion:0 MaxVersion:0}
>ApiVersions of Broker Key 37 : &{ApiKey:37 MinVersion:0 MaxVersion:0}

In particular for Metadata Update the key is 3. Taking the information from apiVersion for key 3 the highest supporting version is 5. If I would try to get a MetadataRequest

```go
metadataRequest := sarama.MetadataRequest{Version: apiVersion.ApiVersions[3].MaxVersion, Topics:[]string{}}
metadataResponse, errorMetaDataFetch := broker.GetMetadata(&metadataRequest)
```

The code will fail and errorMetaDataFetch will state that the API is not supported.
I have to decrease the version for the MetadataRequest down to 2 until the "API Version not supported" disappears and I get an actual response.

Does the support that the Kafka API publishes and the samara library have not correlate or am I getting something wrong here.

Would be nice if this would reflect the sarama API-level that is supported (correlated with Kafka of course) than only stating what Kafka is reporting.

For completion this is what kafka-broker-api-versions.sh reports for the same kafka node.
>Produce(0): 0 to 5 [usable: 5],
>Fetch(1): 0 to 6 [usable: 6],
>ListOffsets(2): 0 to 2 [usable: 2],
>Metadata(3): 0 to 5 [usable: 5],
>LeaderAndIsr(4): 0 to 1 [usable: 1],
>StopReplica(5): 0 [usable: 0],
>UpdateMetadata(6): 0 to 4 [usable: 4],
>ControlledShutdown(7): 0 to 1 [usable: 1],
>OffsetCommit(8): 0 to 3 [usable: 3],
>OffsetFetch(9): 0 to 3 [usable: 3],
>FindCoordinator(10): 0 to 1 [usable: 1],
>JoinGroup(11): 0 to 2 [usable: 2],
>Heartbeat(12): 0 to 1 [usable: 1],
>LeaveGroup(13): 0 to 1 [usable: 1],
>SyncGroup(14): 0 to 1 [usable: 1],
>DescribeGroups(15): 0 to 1 [usable: 1],
>ListGroups(16): 0 to 1 [usable: 1],
>SaslHandshake(17): 0 to 1 [usable: 1],
>ApiVersions(18): 0 to 1 [usable: 1],
>CreateTopics(19): 0 to 2 [usable: 2],
>DeleteTopics(20): 0 to 1 [usable: 1],
>DeleteRecords(21): 0 [usable: 0],
>InitProducerId(22): 0 [usable: 0],
>OffsetForLeaderEpoch(23): 0 [usable: 0],
>AddPartitionsToTxn(24): 0 [usable: 0],
>AddOffsetsToTxn(25): 0 [usable: 0],
>EndTxn(26): 0 [usable: 0],
>WriteTxnMarkers(27): 0 [usable: 0],
>TxnOffsetCommit(28): 0 [usable: 0],
>DescribeAcls(29): 0 [usable: 0],
>CreateAcls(30): 0 [usable: 0],
>DeleteAcls(31): 0 [usable: 0],
>DescribeConfigs(32): 0 [usable: 0],
>AlterConfigs(33): 0 [usable: 0],
>AlterReplicaLogDirs(34): 0 [usable: 0],
>DescribeLogDirs(35): 0 [usable: 0],
>SaslAuthenticate(36): 0 [usable: 0],
>CreatePartitions(37): 0 [usable: 0]

Thanks for your efforts
BR
Stefan

**Comment by eapache** [comment]
Not sure what's going on here, sarama does support metadata requests up to and include v5. What's the exact error? Are there any messages in the broker logs?

**Comment by schinivision** [comment]
Hi. No there are no broker logs, neither does the sarama library state any errors (debug turned on)... But I think I found a way to reproduce it. It has something to do with the combination of the saram.version and the actual kafka version that you use...

I am using a Kafka Version: 1.0.0

When I want to fetch Metadata from a broker with the max version that is received by broker.ApiVersions, it actually depends on what sarama.version is selected.

If I connect and make the call using -> sarama.V1_0_0_0 this code will return a valid result
```go
metadataRequest := sarama.MetadataRequest{Version: apiVersion.ApiVersions[3].MaxVersion, Topics:[]string{}}
```
If I connect and make the call using -> sarama.V0_10_2_0 the same call
```go
metadataResponse, errorMetaDataFetch := sarama.MetadataRequest{Version: apiVersion.ApiVersions[3].MaxVersion, Topics:[]string{}}
```
will fail reporting the error message (errorMetaDataFetch):
kafka server: The version of API is not supported

This could lead to some problems:
1) the error message is misleading, indicating that Kafka can not support this version where actually sarama is not able to serve this version
2) if someone would upgrade Kafka and would leave the sarama.version as is, the application might fail because Kafka reports a higher version than the actual sarama client can support (rendering your application inoperable).

Solution (proposal):
Would it be possible to return a "mix" when calling

```go
broker.ApiVersions(&sarama.ApiVersionsRequest{})
```
that really reflects what kafka is reporting and sarama.VX_X_X_X can really support?

**Comment by eapache** [comment]
I'm not sure what the difference is supposed to be between the two snippets, they are identical?
```
metadataResponse, errorMetaDataFetch := sarama.MetadataRequest{Version: apiVersion.ApiVersions[3].MaxVersion, Topics:[]string{}}
```

If you're referring to the value set in the config (`Config.Version`) then this behaviour is already documented. Specifically: "setting it to a version older than you have will not break anything, although it may prevent you from using the latest features". It sounds like that's what's happening here?
