### ISSUE TITLE
GetOffset by timestamp always return -1

### ISSUE THREAD

**Issue by bowen-unglue** [Shopify/sarama#1089]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1.16.0
Kafka Version: 1.1.0
Go Version: 1.8

##### Configuration

```
ts := utcNow.Add(-1 * time.Hour).UnixNano() / 1000000

clientConfig := sarama.NewConfig()
clientConfig.Version = sarama.V1_1_0_0
client, err := sarama.NewClient(brokers, clientConfig)

if err != nil {
	log.Error(err.Error())
	return
}

defer client.Close()

partitions, err := client.Partitions(topic)

if err != nil {
	log.Error(err.Error())
	return
}

for _, val := range partitions {
	offset, err := client.GetOffset(topic, val, ts)

	if err != nil {
		fmt.Printf("error getting offset for partition %d. %v", val, err.Error())
	} else {
		fmt.Printf("offset for partition %d is %d.", val, offset)
	}
}
```

##### Logs

offset for partition 0 is -1.offset for partition 1 is -1.

##### Problem Description
Trying to start processing data at offset based on time stamp.   But it only returns -1 with no error.
This #857[](url) seems to have similar problem to that I have, yet the solution does not work for me.  I've tried   Unix(), UnixNano() / 1000000, UnixNano() / int64(time.Millisecond), none of them work.  
Am I missing something? Does that have anything to do with broker config?   Pleas advice.

(It works fine if it processes from the newest offset.)

**Comment by eapache** [comment]
What is the error being returned alongside the `-1`?

**Comment by bowen-unglue** [comment]
Thanks so much for replying on this!
As I mentioned on the previous thread, there was no error.  only -1 was return as the offset.

**Comment by bowen-unglue** [comment]
Thanks for the suggestion, I will check the broker log and tried local time. I may come back with more questions later.  Hope you don't mind.

**Comment by bowen-unglue** [comment]
Just come up an strange thought.  Would this due to the consumer have not consumed any of the data and hence can not move the offset backward?

Here is one of the scenario:   Let's say my broker's data retention is 24 hours.  There are producer writing to broker constantly.  Let's say I only start consumer once a week and stop it within one hour.
By the time I start consumer,  all the data in broker are new data, which mean it has no previous offset stored, and hence can not move the offset backward?

**Comment by eapache** [comment]
Yes, that's possible. If the broker no longer has any messages around the given timestamp (due to the broker expiring those messages after passing the data retention time) then you will see -1 like this.
