### ISSUE TITLE
createTopics error "kafka server: The version of API is not supported."

### ISSUE THREAD

**Issue by quanhengzhuang** [Shopify/sarama#1103]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:kafka_2.12-1.1.0
Go Version:go1.10.1

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

```
func CreateTopic(topicName string, partitions int, replicationFactors int) error {
    config := sarama.NewConfig()
    config.Version = sarama.V1_0_0_0

    brokers := storage.GetBrokerHosts()
    c, err := sarama.NewClient(brokers, config)
    if err != nil {
        log.Printf("create topic failed. new client not created. err:%v", err)
        return err
    }
    defer c.Close()

    connected, err := c.Brokers()[0].Connected()
    if err != nil {
        log.Printf("create topic failed. broker connected error. err:%v", err)
        return err
    }

    if !connected {
        err = c.Brokers()[0].Open(nil)
        if err != nil {
            log.Printf("create topic failed. error opening connection to broker. err:%v", err)
            return err
        }
        defer c.Brokers()[0].Close()
    }

    request := &sarama.CreateTopicsRequest{}
    request.TopicDetails = make(map[string]*sarama.TopicDetail)
    request.TopicDetails[topicName] = &sarama.TopicDetail {
        NumPartitions: int32(partitions),
        ReplicationFactor: int16(replicationFactors),
    }

    rsp, err := c.Brokers()[0].CreateTopics(request)
    if err != nil {
        log.Printf("create topic failed. err:%v", err)
        return err
    }

    log.Printf("create topic success. resp:%v", rsp.TopicErrors)
    return nil
}
```

**Comment by eapache** [comment]
Which request specifically is failing?

**Comment by quanhengzhuang** [comment]
c.Brokers()[0].CreateTopics(request) return error "kafka server: The version of API is not supported"

**Comment by eapache** [comment]
For more recent versions of kafka you may need to set `request.Version` to 1 or 2, as I'm not sure if version 0 is still supported.

**Comment by eapache** [comment]
On master Sarama you should just be able to use https://github.com/Shopify/sarama/blob/master/admin.go

**Comment by andy2046** [comment]
@eapache I tried to use the new admin.go NewClusterAdmin but got `kafka server: Request exceeded the user-specified time limit in the request.`
