### ISSUE TITLE
brokerConsumer getting set to nil

### ISSUE THREAD

**Issue by Ronin11** [Shopify/sarama#1104]
##### Versions 

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 3c763ff04e6daa57d4a4614e5bcd908f2527c989
Kafka Version: 2.11-1.0.0
Go Version: go version go1.9.2 darwin/amd64

##### Logs

[sarama]2018/05/22 20:24:47 consumer/test/0 finding new broker
kafka: error while consuming test/0: kafka: tried to use a client that was closed
&sarama.partitionConsumer{highWaterMarkOffset:7, consumer:(*sarama.consumer)(0xc42006b600), conf:(*sarama.Config)(0xc42007a600), topic:"test", partition:0, broker:(*sarama.brokerConsumer)(nil), messages:(chan *sarama.ConsumerMessage)(0xc42006ef00), errors:(chan *sarama.ConsumerError)(0xc42006ef60), feeder:(chan *sarama.FetchResponse)(0xc42006efc0), trigger:(chan sarama.none)(0xc4200287e0), dying:(chan sarama.none)(0xc420028840), responseResult:error(nil), closeOnce:sync.Once{m:sync.Mutex{state:0, sema:0x0}, done:0x0}, fetchSize:1048576, offset:7}

##### Problem Description
The KafkaConsumer gets created, reads the available messages, and then closes itself I guess? Im just trying to create some consumer, and then have it call a number of functions when the consumer receives a new message.

Heres the code:
```
type onEvent func(data string)

type polarisKafkaConsumer struct {
	consumer sarama.PartitionConsumer
	callbacks []onEvent
}

var consumerList []*polarisKafkaConsumer

func startConsumer(kafkaConsumer *polarisKafkaConsumer){
	for {
		select {
		case err := <-kafkaConsumer.consumer.Errors():
			fmt.Println(err)
		case msg := <-kafkaConsumer.consumer.Messages():
			for _, callback := range kafkaConsumer.callbacks {
				callback(string(msg.Value))
			}
		}
	}
}

func CreateKafkaConsumer(broker string, topic string) *polarisKafkaConsumer{
	config := sarama.NewConfig()
	config.Consumer.Return.Errors = true

	// Specify brokers address
	brokers := []string{broker}
	sarama.Logger = log.New(os.Stderr, "[sarama]", log.LstdFlags)

	// Create new consumer

	master, err := sarama.NewConsumer(brokers, config)
	if err != nil {
		panic(err)
	}

	defer func() {
		if err := master.Close(); err != nil {
			panic(err)
		}
	}()
	// How to decide partition, is it fixed value...?
	consumer, err := master.ConsumePartition(topic, 0, sarama.OffsetOldest)
	if err != nil {
		panic(err)
	}
	
	kafkaConsumer := polarisKafkaConsumer{consumer, []onEvent{}}
	consumerList = append(consumerList, &kafkaConsumer)
	go startConsumer(&kafkaConsumer)

	return &kafkaConsumer
}


func OnMsgEvent(consumer *polarisKafkaConsumer, callback onEvent){
	consumer.callbacks = append(consumer.callbacks, callback)
}

func main() {
	log.Info("Starting the go service template")
	consumer := server.CreateKafkaConsumer("192.168.100.216:9092", "test")
	server.OnMsgEvent(consumer, test)
}
```

**Comment by eapache** [comment]
There's nothing in your program to prevent the main thread from exiting, at which point the entire program gets shut down. You'll want to put some code at the bottom of `main()` to wait for some condition before exiting.
