### ISSUE TITLE
MaxOpenRequests=1 semantics

### ISSUE THREAD

**Issue by kiro** [Shopify/sarama#1105]
Hi, if we have async producer with MaxOpenRequests=1, does it guarantee that the batches will be delivered in order? E.g. if there is a failure sending a batch it won't try to send the next one?

**Comment by eapache** [comment]
I'm not sure what you mean? Even with the default MaxOpenRequests, sarama guarantees message ordering within a partition: https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#does-saramas-producer-guarantee-message-ordering

Message *batches* are entirely dynamic and not reflected to the consumer, so I'm not sure what it would mean for them to also have an order.
