### ISSUE TITLE
It's possible to subscribe to list of topics?

### ISSUE THREAD

**Issue by Karmadon** [Shopify/sarama#1107]
##### Versions
Sarama Version:1.16.0
Kafka Version:1.1.0
Go Version:10.1

##### Configuration

Standard Configs

##### Problem Description

Apache Kafka docs tells me:
```
 KafkaConsumer<String, String> consumer = new KafkaConsumer<>(props);
     consumer.subscribe(Arrays.asList("foo", "bar"));
```

but how to use it in sarama?

	topic := "Payments" // wanna to use array of topics
	consumer, err := master.ConsumePartition(topic, 0, sarama.OffsetNewest)

**Comment by eapache** [comment]
You probably want https://github.com/bsm/sarama-cluster.

**Comment by Karmadon** [comment]
THX!
