### ISSUE TITLE
Is really documentation enough to use Sarama?

### ISSUE THREAD

**Issue by adililhan** [Shopify/sarama#1113]
I've just tried to use Sarama. Even, hello world is unclear in godoc.

2900+ people liked Sarama. is everyone able to use Sarama via its godoc? really?

**Comment by bai** [comment]
Documentation is never perfect, you should also look for other projects that use Sarama, e.g. [this](https://github.com/linkedin/Burrow), [this](https://github.com/tcnksm-sample/sarama), [this](https://gist.github.com/nilsmagnus/4b582f9a36279bff5f8f9d453f8fb9c4). Happy to see PRs improving the docs though.
