### ISSUE TITLE
async producer crashes with compression enabled

### ISSUE THREAD

**Issue by vrischmann** [Shopify/sarama#1119]
##### Versions

Sarama Version: 1.17.0
Kafka Version: 0.11.0.2
Go Version: 1.10.3

##### Configuration

Kafka is using the default configuration file in the 0.11.0.2 archive with this added: `message.max.bytes=20971520`

You can find the sarama config in the code: https://github.com/vrischmann/saramabug/blob/simplified/main.go#L20-L30

##### Logs

Using the code above I get variants of this:

    2018/06/25 00:19:41 Initializing new client
    2018/06/25 00:19:41 client/metadata fetching metadata for all topics from broker localhost:9092
    2018/06/25 00:19:41 Connected to broker at localhost:9092 (unregistered)
    2018/06/25 00:19:41 client/brokers registered new broker #0 at thor:9092
    2018/06/25 00:19:41 Successfully initialized new client
    2018/06/25 00:19:41 producer/broker/0 starting up
    2018/06/25 00:19:41 producer/broker/0 state change to [open] on foobar/3
    2018/06/25 00:19:41 producer/broker/0 state change to [open] on foobar/0
    2018/06/25 00:19:41 producer/broker/0 state change to [open] on foobar/1
    2018/06/25 00:19:41 producer/broker/0 state change to [open] on foobar/2
    2018/06/25 00:19:42 producer/broker/0 maximum request accumulated, waiting for space
    2018/06/25 00:19:42 Connected to broker at thor:9092 (registered as #0)
    2018/06/25 00:19:42 producer/broker/0 maximum request accumulated, waiting for space
    2018/06/25 00:19:42 producer/broker/0 maximum request accumulated, waiting for space
    2018/06/25 00:19:42 producer/broker/0 maximum request accumulated, waiting for space
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x65610b]
    goroutine 46 [running]:
    github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama.(*produceSet).wouldOverflow(0xc420118000, 0xc420150090, 0x3)
            /home/vincent/dev/go/src/github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama/produce_set.go:221 +0x25b
    github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama.(*brokerProducer).run(0xc42010ea20)
            /home/vincent/dev/go/src/github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama/async_producer.go:635 +0x625
    github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama.(*brokerProducer).(github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama.run)-fm()
            /home/vincent/dev/go/src/github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama/async_producer.go:554 +0x2a
    github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama.withRecover(0xc4201102c0)
            /home/vincent/dev/go/src/github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama/utils.go:45 +0x43
    created by github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama.(*asyncProducer).newBrokerProducer
            /home/vincent/dev/go/src/github.com/vrischmann/saramabug/vendor/github.com/Shopify/sarama/async_producer.go:554 +0x1ba

##### Problem Description

With compression enabled the producer crashes with a nil pointer dereference, with no compression it works. I can reproduce the panic every time.

**Comment by vrischmann** [comment]
well nevermid that, just when I hit send I find my mistake.
Reusing the message like that is the problem.

I was trying to avoid allocating a message every time since in my test it was the same (I'm trying to measure performance) but I guess I can't do that.

**Comment by eapache** [comment]
You should be able to re-use a message object once it is returned out of `Successes` or `Errors` but not before, as it tracks some state during the actual produce flow.

**Comment by vrischmann** [comment]
Good to know, I'll test that. Thanks.
