### ISSUE TITLE
All the requests in admin.go don't specify a timeout and none is allowed to be set causing them to ErrRequestTimedOut

### ISSUE THREAD

**Issue by gadkrumholz** [Shopify/sarama#1120]
##### Versions
Sarama Version: master@46cf3e2cf1acef7876068f66cf69ec31aad2d0b2
Kafka Version: 1.10
Go Version: 1.10

##### Configuration
N/A

What configuration values are you using for Sarama and Kafka?
N/A

##### Logs
N/A

##### Problem Description
When a long-running operation like creating a topic with a lot of partitions and replicasets or when changing a topic's # of partitions (the 2 examples we've run into this with) you may sometimes get ErrRequestTimedOut even though the operation completes successfully.

Could you please expose the Timeout parameter for the requests to be passed in with each method call or have it use the same Timeout parameter from the config passed into NewClusterAdmin(...)?

**Comment by eapache** [comment]
I don't think there's an existing config value which makes sense for those timeouts, but I'm happy to take a PR adding one.

**Comment by andy2046** [comment]
@eapache do you think adding Cluster Timeout into existing Config is the right way to solve this? or you have better idea, I'd like to raise a PR for this 

```go
type Config struct {
	Cluster struct {
		Timeout Time.Duration
	}
}
```

**Comment by eapache** [comment]
Something like that. I could see an argument for putting this value under `Metadata`, or for creating a new `Admin` struct in config. The name `Cluster` on its own isn't specific enough for me.

**Comment by andy2046** [comment]
@eapache Thanks for the advise, I raised a PR [1142](https://github.com/Shopify/sarama/pull/1142) with new `Admin` struct. please help to review and comment, thanks.

**Comment by andy2046** [comment]
@eapache should we close this issue?

**Comment by d1egoaz** [comment]
fixed by https://github.com/Shopify/sarama/pull/1142
thanks
