### ISSUE TITLE
sarama retries unusable?

### ISSUE THREAD

**Issue by JeffreyDing11223** [Shopify/sarama#1126]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: newest master
Kafka Version: 1.1
Go Version: 1.10

##### Configuration

What configuration values are you using for Sarama and Kafka?

        config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.Partitioner = sarama.NewRandomPartitioner
	
	config.Producer.Return.Successes = true
	config.Producer.Return.Errors = true
	
	config.Producer.Retry.Max=10
	config.Producer.Retry.Backoff=6*time.Second
	
	config.Version=sarama.V1_1_0_0

##### Logs

offset:  641 partitions:  0 metaData: this is a message 0706 19:31:42 value: this is a message 0706 19:31:42

err:  kafka: client has run out of available brokers to talk to (Is your cluster reachable?) errMsg: this is a message 0706 19:32:07 errMetaData this is a message 0706 19:32:07 errOffset: 0 errPartition: 0 errTopic: 0706_test

offset:  642 partitions:  0 metaData: this is a message 0706 19:32:32 value: this is a message 0706 19:32:32
offset:  643 partitions:  0 metaData: this is a message 0706 19:32:57 value: this is a message 0706 19:32:57

##### Problem Description
config.Producer.Retry.Max=10
config.Producer.Retry.Backoff=6*time.Second

## description:
producer produces msg per 25 seconds,

After '19:31:42' msg succeed, I shut down the Kafka. 

And then the '19:32:07' msg failed , then it started to retry, max 10 times, per 6 seconds.

After 10 seconds, I start the Kafka.

The msg '19:32:32' and msg '19:32:57' delivered to the Kafka successfully, but '19:32:07' msg  was lost. 
'19:32:07' msg should be retried 10 times in 60 seconds .

But now , 
'19:31:42' msg-----offset 641
'19:32:32' msg------offset 642
'19:32:57' msg------offset 643

where is '19:32:07' msg ? 
I am confused. Plesase help.

thanks a lot .

**Comment by eapache** [comment]
Please set `sarama.Logger` and provide that output. Without it I cannot debug.

**Comment by JeffreyDing11223** [comment]
#### Thank for replying.
I used `sarama.Logger.PrintLn()` , but it did not display any output in the console. So I still used fmt.PrintLn() to replcae it.

#### My codes are very simple:
```
func SaramaProducer()  {

	config := sarama.NewConfig()
	
	config.Producer.RequiredAcks = sarama.WaitForAll
	
	config.Producer.Partitioner = sarama.NewRandomPartitioner
	
	config.Producer.Return.Successes = true
	config.Producer.Return.Errors = true
	
	config.Producer.Retry.Max= 10
	config.Producer.Retry.Backoff= 6*time.Second
	
	config.Version= sarama.V1_1_0_0

	fmt.Println("start make producer")
	
	producer, e := sarama.NewAsyncProducer([]string{"127.0.0.1:9092"}, config)
	if e != nil {
		fmt.Println(e)
		return
	}
	defer producer.AsyncClose()
	fmt.Println("make producer done")

	time.Sleep(1*time.Second)

	go func(p sarama.AsyncProducer) {
		for{
			select {
			case suc:= <-p.Successes():
				bytes,_:=suc.Value.Encode()
				value:=string(bytes)
				fmt.Println("success response, "," offset: ", suc.Offset, " partitions: ", suc.Partition," metaData:",suc.Metadata," value:",value)
			case fail := <-p.Errors():
				bytes,_:=fail.Msg.Value.Encode()
				value:=string(bytes)
				fmt.Println("err response, ","err: ", fail.Err," errMsg:",value," errMetaData",fail.Msg.Metadata," errOffset:",fail.Msg.Offset,
					" errPartition:",fail.Msg.Partition," errTopic:",fail.Msg.Topic)
			}
		}
	}(producer)


	var value string
	for i:=0;;i++ {

		time11:=time.Now()
		value = "this is a message 0706 "+time11.Format("15:04:05")

		//make message
		msg := &sarama.ProducerMessage{
			Topic: "0706_test",
			Metadata: value,
		}

		producer.Input() <- msg

		time.Sleep(25*time.Second)
	}

}
```
start kafka -----> start the program-----> the first msg succeed-----> shut down kafka----->after about 25 seconds , the second msg failed----->about 10 seconds later (let second msg retry at least once) , start kafka -----> a few seconds later, third msg succeed , fourth msg succeed. But , the second msg was lost, retries may did not work ?

**Comment by JeffreyDing11223** [comment]
#### this is my log output which is  corresponding to the above process.
```
start make producer
make producer done

success response,   offset:  663  partitions:  0  metaData: this is a message 0706 13:39:35  value: this is a message 0706 13:39:35

err response,  err:  kafka: client has run out of available brokers to talk to (Is your cluster reachable?)  errMsg: this is a message 0706 13:40:00  errMetaData this is a message 0706 13:40:00  errOffset: 0  errPartition: 0  errTopic: 0706_test

success response,   offset:  664  partitions:  0  metaData: this is a message 0706 13:40:25  value: this is a message 0706 13:40:25

success response,   offset:  665  partitions:  0  metaData: this is a message 0706 13:40:50  value: this is a message 0706 13:40:50
```

the `this is a message 0706 13:40:00` is the second msg

**Comment by eapache** [comment]
Sorry, I wasn't clear. You need to *set* `sarama.Logger`, not *call* it. Something like
```
sarama.Logger = log.New(os.Stdout, "[sarama]      ", log.LstdFlags)
```
Then it will give you logs from Sarama internal state which will help me debug.

**Comment by JeffreyDing11223** [comment]
#### Thanks.
Here are the sarama logs:
[sarama]      2018/07/10 10:06:22 Initializing new client
[sarama]      2018/07/10 10:06:22 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:06:22 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:06:22 client/metadata fetching metadata for all topics from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:06:22 Connected to broker at 127.0.0.1:9092 (unregistered)
[sarama]      2018/07/10 10:06:22 client/brokers registered new broker #0 at 172.16.71.115:9092
[sarama]      2018/07/10 10:06:22 Successfully initialized new client
[sarama]      2018/07/10 10:06:22 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:06:22 producer/broker/0 starting up
[sarama]      2018/07/10 10:06:22 producer/broker/0 state change to [open] on 0709_test/0
[sarama]      2018/07/10 10:06:22 Connected to broker at 172.16.71.115:9092 (registered as #0)
offset: 20  partitions: 0  metadata: this is a message 0709 10:06:22  value: this is a message 0709 10:06:22
[sarama]      2018/07/10 10:06:47 producer/broker/0 state change to [closing] because EOF
[sarama]      2018/07/10 10:06:47 Closed connection to broker 172.16.71.115:9092
[sarama]      2018/07/10 10:06:47 producer/leader/0709_test/0 state change to [retrying-1]
[sarama]      2018/07/10 10:06:47 producer/leader/0709_test/0 abandoning broker 0
[sarama]      2018/07/10 10:06:47 producer/broker/0 shut down
[sarama]      2018/07/10 10:06:53 client/metadata fetching metadata for [0709_test] from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:06:53 client/metadata got error from broker while fetching metadata: EOF
[sarama]      2018/07/10 10:06:53 Closed connection to broker 127.0.0.1:9092
[sarama]      2018/07/10 10:06:53 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:06:53 client/metadata fetching metadata for [0709_test] from broker 172.16.71.115:9092
[sarama]      2018/07/10 10:06:53 Failed to connect to broker 172.16.71.115:9092: dial tcp 172.16.71.115:9092: connect: connection refused
[sarama]      2018/07/10 10:06:53 client/metadata got error from broker while fetching metadata: dial tcp 172.16.71.115:9092: connect: connection refused
[sarama]      2018/07/10 10:06:53 client/brokers deregistered broker #0 at 172.16.71.115:9092
[sarama]      2018/07/10 10:06:53 client/metadata no available broker to send metadata request to
[sarama]      2018/07/10 10:06:53 client/brokers resurrecting 1 dead seed brokers
[sarama]      2018/07/10 10:06:53 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama]      2018/07/10 10:06:53 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:06:53 client/metadata fetching metadata for [0709_test] from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:06:53 Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:06:53 client/metadata got error from broker while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:06:53 client/metadata no available broker to send metadata request to
[sarama]      2018/07/10 10:06:53 client/brokers resurrecting 1 dead seed brokers
[sarama]      2018/07/10 10:06:53 client/metadata retrying after 250ms... (2 attempts remaining)
[sarama]      2018/07/10 10:06:54 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:06:54 client/metadata fetching metadata for [0709_test] from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:06:54 Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:06:54 client/metadata got error from broker while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:06:54 client/metadata no available broker to send metadata request to
[sarama]      2018/07/10 10:06:54 client/brokers resurrecting 1 dead seed brokers
[sarama]      2018/07/10 10:06:54 client/metadata retrying after 250ms... (1 attempts remaining)
[sarama]      2018/07/10 10:06:54 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:06:54 client/metadata fetching metadata for [0709_test] from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:06:54 Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:06:54 client/metadata got error from broker while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:06:54 client/metadata no available broker to send metadata request to
[sarama]      2018/07/10 10:06:54 client/brokers resurrecting 1 dead seed brokers
err:  kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
[sarama]      2018/07/10 10:07:00 producer/leader/0709_test/0 state change to [flushing-1]
[sarama]      2018/07/10 10:07:00 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:07:00 client/metadata fetching metadata for [0709_test] from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:07:00 Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:07:00 client/metadata got error from broker while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:07:00 client/metadata no available broker to send metadata request to
[sarama]      2018/07/10 10:07:00 client/brokers resurrecting 1 dead seed brokers
[sarama]      2018/07/10 10:07:00 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama]      2018/07/10 10:07:00 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:07:00 client/metadata fetching metadata for [0709_test] from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:07:00 Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:07:00 client/metadata got error from broker while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:07:00 client/metadata no available broker to send metadata request to
[sarama]      2018/07/10 10:07:00 client/brokers resurrecting 1 dead seed brokers
[sarama]      2018/07/10 10:07:00 client/metadata retrying after 250ms... (2 attempts remaining)
[sarama]      2018/07/10 10:07:00 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:07:00 client/metadata fetching metadata for [0709_test] from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:07:00 Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:07:00 client/metadata got error from broker while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:07:00 client/metadata no available broker to send metadata request to
[sarama]      2018/07/10 10:07:00 client/brokers resurrecting 1 dead seed brokers
[sarama]      2018/07/10 10:07:00 client/metadata retrying after 250ms... (1 attempts remaining)
[sarama]      2018/07/10 10:07:01 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:07:01 client/metadata fetching metadata for [0709_test] from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:07:01 Failed to connect to broker 127.0.0.1:9092: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:07:01 client/metadata got error from broker while fetching metadata: dial tcp 127.0.0.1:9092: connect: connection refused
[sarama]      2018/07/10 10:07:01 client/metadata no available broker to send metadata request to
[sarama]      2018/07/10 10:07:01 client/brokers resurrecting 1 dead seed brokers
[sarama]      2018/07/10 10:07:01 producer/leader/0709_test/0 state change to [normal]
[sarama]      2018/07/10 10:07:12 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:07:12 client/metadata fetching metadata for [0709_test] from broker 127.0.0.1:9092
[sarama]      2018/07/10 10:07:12 Connected to broker at 127.0.0.1:9092 (unregistered)
[sarama]      2018/07/10 10:07:12 client/brokers registered new broker #0 at 172.16.71.115:9092
[sarama]      2018/07/10 10:07:12 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama]      2018/07/10 10:07:12 producer/broker/0 starting up
[sarama]      2018/07/10 10:07:12 producer/broker/0 state change to [open] on 0709_test/0
[sarama]      2018/07/10 10:07:12 producer/leader/0709_test/0 selected broker 0
[sarama]      2018/07/10 10:07:12 Connected to broker at 172.16.71.115:9092 (registered as #0)
offset: 21  partitions: 0  metadata: this is a message 0709 10:07:12  value: this is a message 0709 10:07:12
offset: 22  partitions: 0  metadata: this is a message 0709 10:07:37  value: this is a message 0709 10:07:37

#### as above log, the msg `this is a message 0709 10:06:47` is lost.

**Comment by eapache** [comment]
Per these logs, the issue is because it isn't the producing that fails; you have only one broker and when you shut down the broker Sarama is unable to retrieve metadata. This uses a separate retry loop (`config.Metadata.Retry`) which you will need to change as well to account for this case.

Usually with Kafka clusters this isn't an issue because even when nodes go away Sarama can get metadata from a different broker.

**Comment by JeffreyDing11223** [comment]
Thanks.
Consequently, if there is only one broker and this broker is down, the Sarama can't resend message, can it ?

**Comment by eapache** [comment]
If there is only one broker and that broker is down, nobody can do anything because the "entire cluster" has become unreachable.

**Comment by githubgaohang** [comment]
the version of kafka is not matched
