### ISSUE TITLE
I can not   find "github.com/eapache/go-resiliency/breaker"   can you give me a link

### ISSUE THREAD

**Issue by zs1503** [Shopify/sarama#1135]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

**Comment by eapache** [comment]
The repo is at https://github.com/eapache/go-resiliency/

The specific subfolder is at https://github.com/eapache/go-resiliency/tree/master/breaker
