### ISSUE TITLE
Producer doesn't respect MaxMessageBytes limit for uncompressed requests

### ISSUE THREAD

**Issue by adwinsky** [Shopify/sarama#1140]
##### Versions

Sarama Version: 5cd4d8675b3b11c08e71529e7280c45f9fc3dafe
Kafka Version: 1.1.0
Go Version:  1.10.2

##### Configuration

Version = "1.1.0"
Producer.MaxMessageBytes = 100000
Producer.Flush.Frequency = 5 * time.Second

##### Problem Description

After I set Producer.Flush.Frequency config variable, my consumer started to throw following error:

> Failed to produce message to topic test: kafka server: Message was too large, server rejected it to avoid allocation error.

I also noticed that this issue doesn't happen for compressed messages (Producer.Compression = sarama.CompressionLZ4). 

I dig a bit and figured this is because of the following line of the code:

https://github.com/Shopify/sarama/blob/97f65c78943cbc4956eca1277befd8df655e6f28/produce_set.go#L219

Seems that for some reasons, MaxMessageBytes limit is not applied for uncompressed messages. For me it is hard to understand why, especially because it is not the case for Flush.MaxMessages a line below.

I produced a PR that resolves this issue https://github.com/Shopify/sarama/pull/1141

**Comment by eapache** [comment]
I'm a bit confused; `MaxMessageBytes` is the per-*message* limit, already enforced at the beginning of the flow at https://github.com/Shopify/sarama/blob/c5b44e38e1ca1b27bcaa35d908f161b690ea72e0/async_producer.go#L278-L281

The code you're referencing is checking against message *batches*; the only reason that applies at all for compressed messages is that old versions of Kafka do this dumb thing where compressed messages get wrapped inside another message object. I thought that none of that code would even apply to kafka versions >= 1.0...

**Comment by bhand-mm** [comment]
@eapache That code seems very strange to me.  Why is `version` (a number that can be expected to be either 1 or 2 in that scope) being compared to `p.conf.Producer.MaxMessageBytes`?

**Comment by adwinsky** [comment]
@eapache I thought that MaxMessageBytes is an equivalent of max.message.bytes Kafka config variable which is clearly referencing to the batch size. At least in the Kafka docs, it is mentioned that since 0.11.0.0 this is the case.  

How else I would be able to control the size of the batch in Sarama? In my example the problem is when I set Flush.MaxMessages config setting, which is leading to sending less often, bigger message batches. For uncompressed messages this produces "Failed to produce message to topic test: kafka server: Message was too large, server rejected it to avoid allocation error." For compressed messages this is not an issue because of the following code:

https://github.com/Shopify/sarama/blob/97f65c78943cbc4956eca1277befd8df655e6f28/produce_set.go#L219

Which is spawning a new messages buffer when the total size of the buffer is going to exceed this limit.

@bhand-mm you probably need to look at this code once again msg.byteSize(version) returns the size of the msg, which is different depending on Kafka version that is in use.

**Comment by dalegaard** [comment]
@eapache the 0.11.0.0 changelog has this entry which may be relevant:
```The broker configuration max.message.bytes now applies to the total size of a batch of messages. Previously the setting applied to batches of compressed messages, or to non-compressed messages individually. <snip>```

**Comment by KamranMaharov** [comment]
I ran into the same issue. This is especially relevant when messages we push to Kafka topic have a huge variance in size. As an example, let's say one message is 0.5 MB and another message is 100 bytes.

Kafka server says that 
> each Produce API call should not have payload with size more than `max.messages.bytes`.

With `Producer.Flush.MaxMessages` we can have upper bound on number of messages in a single batch, (asserted this using sarama metrics, thanks for this functionality), but it will exceed `max.messages.bytes` limit if one of the messages are big enough to make the batch size more than that.
I also vote for this PR because it really solves this particular problem.

Thanks.

**Comment by KamranMaharov** [comment]
Does sarama currently have guaranteed way to enforce maximum `total byte size of the payload` for the batch messages (without using global config `sarama.MaxRequstSize`, because it is going to enforce maximum size not only for Produce API)?
I don't know the answer, and highly appreciate your help in this.

Thanks.

**Comment by varun06** [comment]
PR is merged. Closing this issue.
