### ISSUE TITLE
sarama.PacketDecodingError=kafka : error decoding packet: message of length 1213486160 too large or too small

### ISSUE THREAD

**Issue by programmer4m** [Shopify/sarama#1147]
Kafka Version:2.12
Go Version: 1.10.3

##### Problem Description

I find this in the log , no other issues found .
WARN kafka message: client/metadata got error from broker while fetching metadata:%!(EXTRA sarama.PacketDecodingError=kafka: error decoding packet: message of length 1213486160 too large or too small)

In detail log : 

WARN kafka message: Initializing new client
WARN client/metadata fetching metadata for all topics from broker
WARN Connected to broker at ...... (unregistered)
WARN kafka message: client/metadata got error from broker while fetching metadata:%!(EXTRA sarama.PacketDecodingError=kafka: error decoding packet: message of length 1213486160 too large or too small)
WARN Closed connection to broker
WARN kafka message: client/metadata no available broker to send metadata request to
WARN client/brokers resurrecting 1 dead seed brokers

**Comment by wladh** [comment]
Might be a dup of #1144 
There's no Kafka: 2.12, do you mean Kafka 2.0 compiled with Scala 2.12?

**Comment by sathibault** [comment]
We are experiencing this same error in production with:
Kafka 2.0.0
Sarama: 1.19.0

Brokers are configured with KAFKA_COMPRESSION_TYPE: "lz4"

**Comment by d1egoaz** [comment]
https://github.com/Shopify/sarama/issues/1199 seems a dup of this 

would this workaround work for you @programmer4m ?https://github.com/Shopify/sarama/issues/1199#issuecomment-434428494

**Comment by lovasoa** [comment]
- 1213486160 is the decimal representation of 0x48 0x54 0x54 0x50 which is `HTTP` in ascii
 - What happened is probably this: A client expecting a binary payload (such as kafka) received an HTTP response instead. It may either be talking to the wrong host and port, or there is an HTTP proxy (such as kubernetes ingress) where there shouldn't be one.
