### ISSUE TITLE
memory usage extremely high

### ISSUE THREAD

**Issue by wangxiangyu** [Shopify/sarama#1151]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:

574d3147eee384229bf96a5d12c207fe7b5234f3

Kafka Version:
0.10.0
Go Version:
go1.10.3
##### Configuration

What configuration values are you using for Sarama and Kafka?
I am using "github.com/bsm/sarama-cluster" to consume kafka and very simple configuration.
```
	config := cluster.NewConfig()
	config.Consumer.Return.Errors = true
	config.Group.Return.Notifications = true
	config.Group.Topics.Whitelist = regexp.MustCompile(ij.c.Kafka.TopicRegex)
	// init consumer
	consumer, err = cluster.NewConsumer(ij.c.Kafka.Brokers, ij.c.Kafka.GroupId, nil, config)
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
memory usage is very high , I profile and found this:
```
ROUTINE ======================== billions-index-json/vendor/github.com/Shopify/sarama.(*Broker).responseReceiver in /root/golib/src/billions-index-json/vendor/github.com/Shopify/sarama/broker.go
    2.40GB     2.40GB (flat, cum) 85.47% of Total
         .          .    507:			dead = PacketDecodingError{fmt.Sprintf("correlation ID didn't match, wanted %d, got %d", response.correlationID, decodedHeader.correlationID)}
         .          .    508:			response.errors <- dead
         .          .    509:			continue
         .          .    510:		}
         .          .    511:
    2.40GB     2.40GB    512:		buf := make([]byte, decodedHeader.length-4)
         .          .    513:		bytesReadBody, err := io.ReadFull(b.conn, buf)
         .          .    514:		b.updateIncomingCommunicationMetrics(bytesReadHeader+bytesReadBody, requestLatency)
         .          .    515:		if err != nil {
         .          .    516:			dead = err
         .          .    517:			response.errors <- err
```

**Comment by varun06** [comment]
Is this still an issue. If not, please close.

**Comment by d1egoaz** [comment]
closing, feel free to re-open if this is still an issue

**Comment by rengongzhizang** [comment]
pls make sure that all references of the `consumerMessage` have been released, a huge amount of memory would be occupied otherwise.  More details: https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#why-is-the-consumer-leaking-memory-andor-goroutines
