### ISSUE TITLE
Allow the Consumer to disable auto-commit offsets

### ISSUE THREAD

**Issue by kjelle** [Shopify/sarama#1158]
##### Versions

Sarama Version: v1.17.0
Kafka Version: 2.2.0
Go Version: go1.10

##### Configuration

Not applicable

##### Logs

Not applicable

##### Problem Description

I have a scenario where I want to use the PartitionManager in Sarama, but disable the auto commit of offsets. I use the MarkOffset to calculate `lag` in my consumer.  I also see from a google search there are others with similar issues.

Since the `Consumer.Offsets.CommitInterval` is used in a time.NewTicker it cannot be disabled:
`The duration d must be greater than zero; if not, NewTicker will panic.`

##### Workarounds
A workaround would be to set this to a high number so the `bom.timer.C` never triggers. We run Go in docker containers which runs for months or years, I would prefer a disable.

Another workaround would be not to call `MarkOffset`. I then would need to keep my own store of current partition offsets in the consumer.

##### My own branch
I have run a branched Sarama version for some time, it has two additions:
- It adds a configuration `Consumer.Offsets.Enable` bool
- In https://github.com/Shopify/sarama/blob/v1.17.0/offset_manager.go#L417 we check if `Consumer.Offsets.Enable` is false, and then calls `bom.timer.Stop()`.

This might not be the ideal solution, or right place to put the check, but it works for me.

Since I need to reapply my patch for every release of Sarama, perhaps this could be addressed and fixed in the library?

**Comment by kjelle** [comment]
A possibly better approach would be to check for `Consumer.Offsets.Enable` in https://github.com/Shopify/sarama/blob/v1.17.0/offset_manager.go#L445 so we do not tamper with the `bom.timer` but only block the `OffsetCommitRequest` as long as `Consumer.Offsets.Enable` is set.

I could prepare a PR

**Comment by varun06** [comment]
@kjelle PR is definitely welcome.

**Comment by kjelle** [comment]
@varun06 Any way of getting #1164  merged? CLA is signed

**Comment by varun06** [comment]
Will do today. Thanks.

**Comment by p3lim** [comment]
@varun06 What's the status on this?

**Comment by varun06** [comment]
Hey Friend, there is one comment on PR, please have a look, once that is resolved, will merge it.

**Comment by kjelle** [comment]
I am closing this issue since the PR #1164 was merged.
