### ISSUE TITLE
Release for #1144

### ISSUE THREAD

**Issue by thomaslee** [Shopify/sarama#1159]
Howdy -- not sure what the typical release cycle looks like, but just wanted to put my vote in to ship a new release for https://github.com/Shopify/sarama/issues/1144 now that Kafka 2.0.0 has shipped. We're currently working around this by pinning ourselves to master, but would prefer to target a "real" release.

**Comment by bai** [comment]
Hey -- I'll cut the release early next week.

**Comment by thomaslee** [comment]
Great news, thanks very much!

**Comment by jessicaxiejw** [comment]
up this^

**Comment by guiburi** [comment]
up this^

**Comment by stackeric** [comment]
up this^

**Comment by bai** [comment]
Here we go: https://github.com/Shopify/sarama/releases/tag/v1.18.0. Apologies for the delay, got overwhelmed and haven't had time to compile changelog.

**Comment by thomaslee** [comment]
Not at all, appreciate it. Thank you!
