### ISSUE TITLE
Cannot find package "github.com/pierrec/lz4/v2/internal/xxh32"

### ISSUE THREAD

**Issue by kjelle** [Shopify/sarama#1163]
##### Versions

Sarama Version: v1.17.0
Kafka Version: 2.2.0
Go Version: go1.10

##### Configuration

N/A

##### Logs

`
go get -v github.com/Shopify/sarama
github.com/pierrec/lz4 (download)
package github.com/pierrec/lz4/v2/internal/xxh32: cannot find package "github.com/pierrec/lz4/v2/internal/xxh32" in any of:
        /usr/local/go/src/github.com/pierrec/lz4/v2/internal/xxh32 (from $GOROOT)
        /go/src/github.com/pierrec/lz4/v2/internal/xxh32 (from $GOPATH)
`

##### Problem Description

Sarama depends on a library which doesn't work with go1.10

Issue in that library;
https://github.com/pierrec/lz4/issues/33

I added a Godeps with v2.0.4 of pierrec/lz4 and it works again..

**Comment by vaijira** [comment]
Another workaround: https://github.com/pierrec/lz4/issues/33#issuecomment-418701621 until fix

**Comment by kjelle** [comment]
The breaking change was reverted: https://github.com/pierrec/lz4/commit/bb6bfd13c6a262f1943c0446eb25b7f54c1fb9a2

Closing this issue
