### ISSUE TITLE
should kafka 0.10 work with sarama v1.18 ?

### ISSUE THREAD

**Issue by Dieterbe** [Shopify/sarama#1171]
Hi sarama friends,
we're currently running kafka 0.10 and sarama v1.16 but we have to upgrade to kafka 2.0 because we were struck by some clustering bugs that are fixed in 2.0

since each sarama release only supports a range of kafka versions which is narrower than the 0.10->2.0 range, i have the choice between turning this into 2 separate kafka upgrades, or first running kafka 0.10 with sarama v1.18, and then upgrading kafka (once) to 2.0

i know it's not officially supported, but can anyone give some color on how well it should work? after all it looks like 1.18 supports kafka 0.11 .. thanks!

**Comment by eapache** [comment]
I can't think of a reason why it wouldn't work, but I haven't tried it, so "should" is the right word.

**Comment by Dieterbe** [comment]
thanks @eapache 
can you confirm what's the oldest version supported by v1.18? the readme says 0.11 but that doesn't seem to match with what's in the travis config,which says 1.0.0

**Comment by eapache** [comment]
I think the README is just stale. 1.0.0 is the oldest CI-tested version. I would expect 0.8.2+ to still work though since Kafka itself is pretty backwards-compatible and Sarama hasn't removed support for any of the old message types.

**Comment by d1egoaz** [comment]
@Dieterbe did you end using a newer sarama version?

**Comment by Dieterbe** [comment]
Yes we occasionally update sarama in our project and I don't recall running into issues.
For more details see https://github.com/grafana/metrictank/pulls?utf8=%E2%9C%93&q=is%3Apr+sarama
