### ISSUE TITLE
Producer deadlock

### ISSUE THREAD

**Issue by muirrn** [Shopify/sarama#1187]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: f21e149e5948e9c9b9034f1a19f430d62e00c4d3
Kafka Version: 1.0
Go Version: 1.11

##### Problem Description

We ran into a producer deadlock which lead to OOM. Looking at a goroutine pprof:

```
1 @ 0x42e38b 0x42e433 0x404ead 0x404c85 0x8186c0 0x85b019 0x850694 0x8180b9 0x817ecb 0x816fc6 0x85f04a 0x859683 0x45c0d1
#       0x8186bf        vendor/github.com/Shopify/sarama.(*asyncProducer).retryBatch+0x5cf              .../go/src/vendor/github.com/Shopify/sarama/async_producer.go:894
#       0x85b018        vendor/github.com/Shopify/sarama.(*brokerProducer).handleSuccess.func2+0x428    .../go/src/vendor/github.com/Shopify/sarama/async_producer.go:863
#       0x850693        vendor/github.com/Shopify/sarama.(*produceSet).eachPartition+0xb3               .../go/src/vendor/github.com/Shopify/sarama/produce_set.go:196
#       0x8180b8        vendor/github.com/Shopify/sarama.(*brokerProducer).handleSuccess+0x1d8          .../go/src/vendor/github.com/Shopify/sarama/async_producer.go:845
#       0x817eca        vendor/github.com/Shopify/sarama.(*brokerProducer).handleResponse+0x13a         .../go/src/vendor/github.com/Shopify/sarama/async_producer.go:789
#       0x816fc5        vendor/github.com/Shopify/sarama.(*brokerProducer).run+0x335                    .../go/src/vendor/github.com/Shopify/sarama/async_producer.go:723
#       0x85f049        vendor/github.com/Shopify/sarama.(*brokerProducer).run-fm+0x29                  .../go/src/vendor/github.com/Shopify/sarama/async_producer.go:622
#       0x859682        vendor/github.com/Shopify/sarama.withRecover+0x42                               .../go/src/vendor/github.com/Shopify/sarama/utils.go:45

1 @ 0x42e38b 0x42e433 0x404ead 0x404c85 0x85a5d4 0x859683 0x45c0d1
#       0x85a5d3        vendor/github.com/Shopify/sarama.(*asyncProducer).newBrokerProducer.func1+0x63  .../go/src/vendor/github.com/Shopify/sarama/async_producer.go:631
#       0x859682        vendor/github.com/Shopify/sarama.withRecover+0x42
```

You can see brokerProducer.run calls handleResponse calls handleSuccess calls retryBatch which blocks sending to the brokerProducer.output "bridge". The bridge reader however is blocked sending to brokerProducer.responses, which run() isn't reading because it is off its event loop in handleResponse.

It looks like this was added in 4e5d4779800333bf45ddb38369994f9baee75bc1 by @edoardocomar .

**Comment by apetruhin** [comment]
We faced the same issue. Producing stuck forever on retries.
Rollback to v1.19.0 fixed it.

**Comment by muirrn** [comment]
@edoardocomar do you have an idea of how to fix this? If no one wants to fix it we should consider reverting the changes on master as this is a showstopper bug.

**Comment by edoardocomar** [comment]
I was away for some days - I will look into this, thanks for reporting

CC @mimaison

**Comment by mimaison** [comment]
@muirrn @apetruhin where you running with `Config.Producer.Idempotent` enabled?

**Comment by muirrn** [comment]
> where you running with Config.Producer.Idempotent enabled?

Nope.

**Comment by apetruhin** [comment]
> where you running with Config.Producer.Idempotent enabled?

No.
Our config if it helps. Nothing changed except new sarama from master.
```
kafkaConfig.Producer.Retry.Backoff = time.Second
kafkaConfig.Producer.Retry.Max = 1
kafkaConfig.Producer.Timeout = time.Second
kafkaConfig.Producer.Partitioner = sarama.NewManualPartitioner
kafkaConfig.Producer.Return.Successes = true
kafkaConfig.Producer.Return.Errors = true
kafkaConfig.Producer.MaxMessageBytes = 100000000
kafkaConfig.Producer.RequiredAcks = sarama.WaitForAll
```

**Comment by edoardocomar** [comment]
@muirrn @apetruhin - thanks so much for the report. We have been able to reproduce.
We agree that now the master branch is broken with the changes for the idempotent producer:

1. there is the deadlock that you experienced
1. we tried a couple of fixes to that - which fail the true idempotent case as there is a race condition between new batches being produced and batches being retried which may lead to out of sequence errors
1. same as case 2 (out of sequence) are possible when handling errors in sending produce messages, rather than handling the produce responses

 We would like to fix the non-idempotent producer ASAP. Possibly by retrying single messages rather than batches.
Then we'll open a separate issue for fixing the idempotent producer (which will take longer)

what do you think ?

cc @bai

**Comment by mimaison** [comment]
@muirrn @apetruhin We've opened a PR which should fix this issue. It would be great if you could give it a try and confirm this is the case.
