### ISSUE TITLE
Consumer group partitions always wait for slowest partition

### ISSUE THREAD

**Issue by muirdm** [Shopify/sarama#1188]
We ran into an issue where our consumer group started falling behind on some topics. We had one consumer group servicing multiple topics. We found that sarama suffers from "naughty neighbor" between all partitions the consumer is subscribed to. If there is one slower partition (either because it is slower, or because it just has more work), all partitions must wait for the slow partition to finish. This is because `subscriptionConsumer()` waits for all partition consumers to finish before asking for more data from the server.

This is especially problematic if you are using consistently hashed partitions. Data is not spread randomly, so it is easier to get temporary hot spots where one partition has a lot more work, or perhaps has a type of work that takes a lot longer to process. While that issue persists, all your partitions start to back up instead of just one.

Do you have any thoughts on how to address this? Maybe a min/max/maxwaittime approach for waiting for the partitions to be done?

We have already switched to separate consumers for each topic, which helped for now. Another workaround would be to just spin up multiple consumers for each topic in the same process.

**Comment by eapache** [comment]
Are you looking for the `Consumer.MaxProcessingTime` config? I believe lowering that does what you want.

**Comment by muirrn** [comment]
Thank you for responding. We already have MaxProcessingTime configured appropriately. The issue in sarama stems from the fact there is a single event loop per consumer per broker (pasted below).

It fetches data for all partitions/topics, kicks off processing in separate goroutines, waits for all to finish, then handles errors and fetches the next batch of data. Consider what happens if you have 8 partitions and each piece of work takes 1 second to process. If one of the partitions gets a huge influx of 1000 items and each of the other 7 partitions has only 1 item to process, _all_ the partitions will wait 1000 seconds for the slow partition before consumer more data. This will cause all partitions to back up instead of just the single partition.

```
func (bc *brokerConsumer) subscriptionConsumer() {
	<-bc.wait // wait for our first piece of work

	// the subscriptionConsumer ensures we will get nil right away if no new subscriptions is available
	for newSubscriptions := range bc.newSubscriptions {
		bc.updateSubscriptions(newSubscriptions)

		if len(bc.subscriptions) == 0 {
			// We're about to be shut down or we're about to receive more subscriptions.
			// Either way, the signal just hasn't propagated to our goroutine yet.
			<-bc.wait
			continue
		}

		response, err := bc.fetchNewMessages()

		if err != nil {
			Logger.Printf("consumer/broker/%d disconnecting due to error processing FetchRequest: %s\n", bc.broker.ID(), err)
			bc.abort(err)
			return
		}

		bc.acks.Add(len(bc.subscriptions))
		for child := range bc.subscriptions {
			child.feeder <- response
		}
		bc.acks.Wait()
		bc.handleResponses()
	}
}
```

**Comment by daniel-almeida-cmd** [comment]
I think I'm observing something similar to this issue. In a setup with multiple brokers and 10 partitions, adding more consumers to a consumer group (CG) doesn't result in any improvement in overall throughput (i.e., the total number of messages processed by all consumers in a CG). Instead, the load seems to be spread among the consumers almost equally.

![image](https://user-images.githubusercontent.com/76969120/122849374-3e8e5080-d2c0-11eb-9ae3-cae034357fe2.png)

Now, that effect seems to change based on the processing time. When the processing time is short (50ms), adding consumers actually leads to higher overall throughput. When the processing time is higher (e.g., 250 or 500ms), however, not only the throughput of each individual consumer is slower (as expected), but adding more consumers to the CG doesn't result in any increases in overall throughput. **It's as if slow consumers were holding back the other consumers in the same CG.** 

We've tested up to 10 consumers (1 per partition) and the overall throughput is capped at basically the same as what we see with 2 consumers. Other info about our setup:

- We have plenty of messages to be processed (millions);
- The consumers run the exact same code and consume from the same topics;
- The consumers are running in independent processes (VMs) and are not in any way close to their limit;
- The brokers are also fine; adding more consumers to different consumer groups results in much higher throughput.
