### ISSUE TITLE
error decoding packet: message of length 104857903 too large or too small

### ISSUE THREAD

**Issue by sathibault** [Shopify/sarama#1199]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.19.0
Kafka Version: 2.0.0
Go Version: 1.10.1

##### Configuration

Consumer config:
config.Version = sarama.V1_1_0_0
config.Metadata.Full = true
config.Consumer.Return.Errors = true
config.Consumer.Fetch.Default = 20000000
config.ChannelBufferSize = 1024

Brokers config:
KAFKA_COMPRESSION_TYPE: "lz4"

##### Logs

We are getting this error regularly (more than once an hour):
consumer/broker/1 disconnecting due to error processing FetchRequest: kafka: error decoding packet: message of length 104857903 too large or too small
Closed connection to broker prod-cohort-kafka-1:9092

##### Problem Description

The console consumer is able to read the topic without any errors, but we are getting the errors above using the sarama consumer.

**Comment by huangyiminghappy** [comment]
i have found the same error

**Comment by sathibault** [comment]
We've worked around this issue by setting:
```
config.Consumer.Fetch.Max = 40000000
```

**Comment by ZhangShurong** [comment]
the type config.Consumer.Fetch.Max is int32.
But 40000000 is much bigger than the maximum of int32.
@sathibault

**Comment by focusj** [comment]
Any feedback or progress on this ISSUE?
