### ISSUE TITLE
sarama can not support consumer message In some cases

### ISSUE THREAD

**Issue by huangyiminghappy** [Shopify/sarama#1205]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.19.0 
Kafka Version:0.10.2.0
Go Version: 1.11.1

##### Configuration

What configuration values are you using for Sarama and Kafka?
in kafka broker i use this configuration in server.properties(my kafka version is 0.10.2.0):
inter.broker.protocol.version=0.10.2.0
log.message.format.version=0.9.0.1

and in Sarama  my producer use
config.Producer.Compression = sarama.CompressionLZ4 
##### Logs

2018/10/30 17:03:05 consumer/broker/3 disconnecting due to error processing FetchRequest: lz4: invalid header checksum: got 1a; expected 82

2018/10/30 17:03:05 Closed connection to broker 10.179.162.20:9092
2018/10/30 17:03:05 kafka: error while consuming test/0: lz4: invalid header checksum: got 1a; expected 82

##### Problem Description
i use java client  or go client produce lz4 message,java client can consumer,but go client can not .
 ,the log is 
"2018/10/30 17:03:05 consumer/broker/3 disconnecting due to error processing FetchRequest: lz4: invalid header checksum: got 1a; expected 82

2018/10/30 17:03:05 Closed connection to broker 10.179.162.20:9092
2018/10/30 17:03:05 kafka: error while consuming test/0: lz4: invalid header checksum: got 1a; expected 82"

**Comment by rafaelzimmermann** [comment]
This is caused by a bug on Kafka that incorrectly calculates the header checksum.
https://issues.apache.org/jira/browse/KAFKA-3160

**Comment by rafaelzimmermann** [comment]
We can see here https://patch-diff.githubusercontent.com/raw/apache/kafka/pull/1212.patch that, on Kafka client implementation, they added a flag to ignore the HC checksum.

More details on lz4 frame format here:
https://github.com/lz4/lz4/blob/master/doc/lz4_Frame_format.md

**Comment by huangyiminghappy** [comment]
thank you

**Comment by jonathansantilli** [comment]
Hello, I have raised the issue in Burrow https://github.com/linkedin/Burrow/issues/494 where the error is still showing up: **lz4: invalid header checksum: got 1a; expected 82**
At the moment am writing this, the **sarama** client used by Burrow is **1.22.1**.
Is there a plan to tackle this issue?

Cheers!
