### ISSUE TITLE
10KiB is not enough for async produce overflow protection when MessageSet contains many messages

### ISSUE THREAD

**Issue by PChou** [Shopify/sarama#1206]
##### Versions

Sarama Version:e7238b119b7daab993720f0153eafb88e2b0ac1f
Kafka Version: 0.10.2.1
Go Version:1.10.3 linux/amd64

##### Problem Description

I am trying to test the benchmark of async producer, but i found many encoding errors as follows:

```
error encoding packet: invalid request size (106300834)
```

This is triggered by `prep_encode` which is used to calculate the size of the final packet before real memory allocation, but found overflow, and then drop all.
After checking and analyzing the code, I figure out that, when `input` is much faster than `output`( for instance, the network switch is 1000mb/s), `produceSet` grows very fast during `brokerProducer.bridge` is "busy"
Although `bp.buffer.wouldOverflow` is trying to protect messageBatch from overflow than `MaxRequestSize(100*1024*1024)`，but when the growing batch contains to 15w+ messages(and each message size is between about 400~600B), the final encoded packet size may grow by 2%. The following additional log is added by myself:

```
[Sarama] 2018/11/01 16:47:52 In buildRequest: ps.bufferBytes:99614493
[Sarama] 2018/11/01 16:47:52 In ProduceRequest.encode: pe.offset():101001448
```

This means the produceSet's accumulation size is lower than the final encoded size.
Following is the code which is try to protect size overflow:

produce_set.go
```go
// Would we overflow our maximum possible size-on-the-wire? 10KiB is arbitrary overhead for safety.
case ps.bufferBytes+msg.byteSize(version) >= int(MaxRequestSize-(10*1024)):
```
I think the 10KiB is not enough for some cases. Increasing the `protect-area-size` to 2MB(2% x 100MB) can fix my situation.
Or let the size configurable other than hardcode?

**Comment by Stephan14** [comment]
I meet the same question

**Comment by Stephan14** [comment]
Can I reduce `Config.Producer.Flush.Bytes ` value to solve this problems?
