### ISSUE TITLE
What is the best way to distinguish type of log messages (error, debug, etc.) in sarama logs

### ISSUE THREAD

**Issue by abrosimov** [Shopify/sarama#1207]
Unfortunately I didn't found any place where I can ask about impl details

##### Problem Description
Current version of sarama.StdLogger supports only Print* methods for error logging, but automated error log collecting systems can not distinguish what type have messages in log (error, debug, info, etc). For example:
"consumer/broker/%d disconnecting due to error processing FetchRequest: %s" is error (consumer.go:695), but "consumer/broker/%d added subscription to %s/%d" isn't (consumer.go:712).

I see two ways:
1) Pass logger with changed print behaviour: analyze log message and add prefix. But it look like a crutch. 
2) Extend current logger with errors level add few methods (Error, Errorf, Errorln) to StdLogger interface. 

Or probably I do something wrong?

**Comment by d1egoaz** [comment]
I think this is related to https://github.com/Shopify/sarama/pull/1275

> As originally designed the only log output during normal golden-path operation should be the metadata update heartbeat (one line every ten minutes). If the lines in question are what you're seeing regularly, I would not expect normal operation to require initializing clients after the app itself has finished starting up.

**Comment by d1egoaz** [comment]
There is also an idea to add support to logrus, but that'll break the API.

See https://github.com/Shopify/sarama/wiki/Ideas-that-will-break-backwards-compatibility

**Comment by daniel-cohen** [comment]
I'm not sure why this has to break the API ? 
you can have the default behaviour stay the same where everything is logged to one output, But if someone setup a different logger that supports levels, it will work.
