### ISSUE TITLE
Question - context aware api for ConsumerGroupHandler api

### ISSUE THREAD

**Issue by varun06** [Shopify/sarama#1208]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:v1.19
Kafka Version:1.2
Go Version: v1.11

##### Problem Description
to get context to consumer group claim, I have to do something like 
```
type c struct {
    ctx context.Context

    //Other stuff
}
```
embedding context to a struct is frowned upon, can we have a context aware api ->  https://github.com/Shopify/sarama/blob/master/consumer_group.go#L701

**Comment by burdiyan** [comment]
@varun06 `ConsumerGroupHandler` provides context in `ConsumerGroupSession` argument: https://godoc.org/github.com/Shopify/sarama#ConsumerGroupSession
