### ISSUE TITLE
High rate of producer errors with async producer

### ISSUE THREAD

**Issue by varun06** [Shopify/sarama#1212]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.19
Kafka Version:0.11
Go Version:1.11

##### Problem Description

I have been getting a lots of producer errors with aysnc producer. The message size if 2KB but kafka is erring out with "kafka server: Message was too large, server rejected it to avoid allocation error." Is there a way to bring the rate of publish errors down?

**Comment by egor2d** [comment]
I have had the same issue one day. My understanding is that it is not related to an individual message but rather to a batch of messages. Kafka default is 1Mb as far as I remember, so I have increased  it to 20Mb in Kafka but I found out that you also need to increase in the producer code with config.Producer.MaxMessageBytes = 20000000.
`    config := sarama.NewConfig()
	config.Net.SASL.Enable = true
	config.Net.SASL.User = cfg.user
	config.Net.SASL.Password = cfg.password
	config.Net.TLS.Enable = true
	config.Net.TLS.Config = &tls.Config{InsecureSkipVerify: true}
	config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.Retry.Max = 5
	config.Producer.MaxMessageBytes = 20000000
	config.Producer.Return.Successes = true
`

**Comment by varun06** [comment]
Did that help you, coz only thing that works for me is https://github.com/Shopify/sarama/blob/master/sarama.go#L92

**Comment by varun06** [comment]
Fixed.
