### ISSUE TITLE
Link to DataDog/zstd breaks Cygwin

### ISSUE THREAD

**Issue by ncastagnoli** [Shopify/sarama#1215]
##### Versions 

Sarama Version: Checkin e42dc76c4e0af and later
Kafka Version: N/A
Go Version: go version go1.9 windows/amd64
--

##### Logs

$ go build                                                                                                                                                                          # github.com/mistsys/location/dtest                                                                                                                                                 c:\home\nealc\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1                                                                                                 /usr/lib/gcc/x86_64-pc-cygwin/7.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex                                                                                      /usr/lib/gcc/x86_64-pc-cygwin/7.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32                                                                                      collect2: error: ld returned 1 exit status
--

##### Problem Description

Data Dog and it's use of embedded "C" is causing some weird issue with "Go" linking the sarama package.

DataDog was added to the Sarama package in e42dc76c4e0af.

The only resolution I've found is to install mingw, and remove "gcc", which would cause a bunch of issues.

**Comment by ncastagnoli** [comment]
Sorry, I wrote the version wrong zstd was added in:

49c4c9a35917a18e15b9f0706f9dc91f6f07a89b
--

**Comment by prune998** [comment]
Same issue here... Sarama should not include dependencies that embed C code !

**Comment by antsbean** [comment]
disable CGO, can install on the windows env, please see #1182

**Comment by d1egoaz** [comment]
nothing we can do right now as this was merged, hopefully we can get rid of cgo in the future.
Also, the zstd support is not working right now :(
