### ISSUE TITLE
Is there a need to close Client when NewConsumerFromClient failed？

### ISSUE THREAD

**Issue by firnsan** [Shopify/sarama#1220]
https://github.com/Shopify/sarama/blob/cebb5847efade319a00e1888acfd8bcdb393e478/consumer.go#L88-L100

Hi.
Above is the code of func NewConsumer. I have a question, if NewClient succeed but NewConsumerFromClient failed later, is there a need to close Client just created？

**Comment by varun06** [comment]
Don't think you should be worried about that, if call to that function fail, you don't get access to client anyway(not exported in this case). your application stops and everything is cleared out.

**Comment by firnsan** [comment]
What if the application is long time running service, if that function fail,  the application chooses to retry (automatically or manually)?  I think in this case  there is no way to release to socket, goroutine or other resources under the Client.

**Comment by d1egoaz** [comment]
If you're worried about unnecessary open TCP connection, then, yes, you can call `Close()` if you are not interested anymore on that client instance
