### ISSUE TITLE
commit offset manually when using consumer group

### ISSUE THREAD

**Issue by danpmx** [Shopify/sarama#1221]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.19.0
Kafka Version: 0.10.2.1
Go Version:1.10

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

Hi, 
I need to ability to commit offsets immediately when using sarama consumer group . Is there any way to do that?
Any plans to support it?

Thanks

**Comment by anantheshadiga** [comment]
Are you expecting `MarkOffset` functionality on consumer messages? This is supported:
https://github.com/Shopify/sarama/blob/v1.21.0/consumer_group_test.go#L15

**Comment by burdiyan** [comment]
I'm pretty sure author was referring to explicit commit, rather than just marking the offset internally. We would also like to have this feature!

**Comment by wolking** [comment]
I also want to submit an offset for each message I consume. When the program is suddenly interrupted, those who have consumed will not be consumed again, instead of submitting an offset at intervals of 'Config.Consumer.Offsets.CommitInterval'

**Comment by ankitm123** [comment]
Can I poke at it, if no one else is looking at it atm? @d1egoaz

**Comment by d1egoaz** [comment]
sure @ankitm123 ! thanks!

**Comment by ankitm123** [comment]
Thanks @d1egoaz. I have time this month to work on this, I will come out with a PR in the next 2 weeks :)
