### ISSUE TITLE
How to consume after recovery 

### ISSUE THREAD

**Issue by saswatp** [Shopify/sarama#1235]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:

Kafka Version:
10.0
Go Version:
1.11 

##### Configuration

What configuration values are you using for Sarama and Kafka?

(struct { Group struct { Session struct { Timeout time.Duration }; Heartbeat struct { Interval time.Duration }; Rebalance struct { Strategy sarama.BalanceStrategy; Timeout time.Duration; Retry struct { Max int; Backoff time.Duration } }; Member struct { UserData []uint8 } }; Retry struct { Backoff time.Duration }; Fetch struct { Min int32; Default int32; Max int32 }; MaxWaitTime time.Duration; MaxProcessingTime time.Duration; Return struct { Errors bool }; Offsets struct { CommitInterval time.Duration; Initial int64; Retention time.Duration; Retry struct { Max int } } }) {
 Group: (struct { Session struct { Timeout time.Duration }; Heartbeat struct { Interval time.Duration }; Rebalance struct { Strategy sarama.BalanceStrategy; Timeout time.Duration; Retry struct { Max int; Backoff time.Duration } }; Member struct { UserData []uint8 } }) {
  Session: (struct { Timeout time.Duration }) {
   Timeout: (time.Duration) 10s
  },
  Heartbeat: (struct { Interval time.Duration }) {
   Interval: (time.Duration) 3s
  },
  Rebalance: (struct { Strategy sarama.BalanceStrategy; Timeout time.Duration; Retry struct { Max int; Backoff time.Duration } }) {
   Strategy: (*sarama.balanceStrategy)(0x4f23240)({
    name: (string) (len=5) "range",
    coreFn: (func(sarama.BalanceStrategyPlan, []string, string, []int32)) 0x4331e70
   }),
   Timeout: (time.Duration) 1m0s,
   Retry: (struct { Max int; Backoff time.Duration }) {
    Max: (int) 4,
    Backoff: (time.Duration) 2s
   }
  },
  Member: (struct { UserData []uint8 }) {
   UserData: ([]uint8) <nil>
  }
 },
 Retry: (struct { Backoff time.Duration }) {
  Backoff: (time.Duration) 2s
 },
 Fetch: (struct { Min int32; Default int32; Max int32 }) {
  Min: (int32) 1,
  Default: (int32) 1048576,
  Max: (int32) 0
 },
 MaxWaitTime: (time.Duration) 250ms,
 MaxProcessingTime: (time.Duration) 100ms,
 Return: (struct { Errors bool }) {
  Errors: (bool) false
 },
 Offsets: (struct { CommitInterval time.Duration; Initial int64; Retention time.Duration; Retry struct { Max int } }) {
  CommitInterval: (time.Duration) 1s,
  Initial: (int64) -1,
  Retention: (time.Duration) 0s,
  Retry: (struct { Max int }) {
   Max: (int) 3
  }
 }
}

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

My need is to make the _consumer_ to start from the last message it processed before it stopped/crashed. Fortunately I am in the case of having only one topic, with one partition and one consumer.

I cannot retrieve the last committed offset. I cannot figure out how to make a sarama consumer to start from said offset. _The only configurable parameter I've found so far is to set read offset to OffsetNewest or OffsetOldest._

So,  
  How to retrieve the last committed offset?
  How to make the consumer start from the last message whose offset has been committed? 

_Setting offset to OffsetNewest or offsetoldest is not helping._ 

Thank in advance

P.S. I am using Kafka 10.0, so the offsets are stores in a kafka and not in zookeeper.

**Comment by varun06** [comment]
hmm, So if you have a producer producing messages to kafka, and then the producer go down for some reason, and then you/automation restart producer, it will start from the next offset in that particular topic, right. You don't have to do anything special (as long as you don't have any other producer producing to the same topic).

It is bit different in case of consumer as if a consumer go down, producer is still producing records, so you have to keep track(consumer group does that for you), but if you have a single producer you don't have to worry about it. Kafka is an immutable data store and offsets always increase..

Let me know if I misread your question?

**Comment by saswatp** [comment]
Hi @varun06 - Thanks for the response and my apologies for the late reply. I did some more searching and looks like I need to move to sarama-cluster to get the functionality I am looking for. consumer group is needed to keep track of the last offset and that's something supported in sarama cluster.

**Comment by varun06** [comment]
Hey, so yeah, but you don't need sarama-cluster for that anymore. sarama-cluster is deprecated and cosnumer group is available in sarama itself. check -> https://github.com/Shopify/sarama/blob/master/consumer.go

**Comment by saswatp** [comment]
Thanks Varun . I will close the issue.
