### ISSUE TITLE
Consumer Group has no response (rebalance notified) for added partition during runtime while producer is ok

### ISSUE THREAD

**Issue by PoacherBro** [Shopify/sarama#1237]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.19.0
Kafka Version: 1.1.0
Go Version: 1.11.2

##### Configuration

What configuration values are you using for Sarama and Kafka?
- Kafka is default setting, no change
- Sarama: use `ConsumerGroup` API, specify oldest kafka version is **0.10.2**, metadata refresh frequency is **1 minute**, offset initial is **OffsetNewest**.

For detail code, you can refer to [consumer_group_test.go](https://github.com/PoacherBro/golab/blob/master/kafka/consumer_group_test.go).

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

```
// Consumer Group log
[sarama] 2018/12/16 21:52:27 client/metadata fetching metadata for all topics from broker localhost:9092
.......  // still consumer the message pre-created partition
```

```
// Producer log
2018/12/16 producer_test.go:52: Pushed value: key[leo]-value[20181216215131]
[sarama] 2018/12/16 21:51:31 producer/broker/1 state change to [open] on test1/2
2018/12/16 producer_test.go:52: Pushed value: key[leo]-value[20181216215134]
[sarama] 2018/12/16 21:51:34 producer/broker/1 state change to [open] on test1/1
```

##### Problem Description
When add new partitions (from 1 to 3), producer can refreshed and send new message to added partitions, but for consumer group, it has no response (rebalance notification) until I start-up a new consumer in a same consumer group.

**Comment by chenhengqi** [comment]
Any updates on this issue ?  I also experienced this problem.

**Comment by clhongooo** [comment]
> Any updates on this issue ? I also experienced this problem.

+1

**Comment by antsbean** [comment]
This bug does exist

**Comment by PoacherBro** [comment]
See the fix, closed this issue.
