### ISSUE TITLE
newConsumerGroupSession initialization slowness with thousands of partitions

### ISSUE THREAD

**Issue by royantman** [Shopify/sarama#1241]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1.20.0
Kafka Version: 2.0.0
Go Version: 1.11

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

Logless parts of the implementation

##### Problem Description
Hello there.
ConsumerGroupSession initialization with many(throngs!) of claims results in a huge slowness due to
fetches of initial offset for each partition serially.
On clients that don't have single digit latencies this is a major issue.

Fetch request V1 can be used to get all the offsets in a single request for all the claims instead of thousands.

I can work on a PR if this isn't something that can be addressed "soon".
 
https://github.com/Shopify/sarama/blob/94536b3e82d393e4b5dfa36475b40fc668e9486f/consumer_group.go#L486-L502

https://github.com/Shopify/sarama/blob/94536b3e82d393e4b5dfa36475b40fc668e9486f/offset_manager.go#L472-L476

**Comment by varun06** [comment]
I kind of predicted that and I guess your best bet is to get a PR up(you already know what needs to be done). I can also help as I might have same issue soonish.
