### ISSUE TITLE
how to limit number of partitions assigned to consumer

### ISSUE THREAD

**Issue by nitin302** [Shopify/sarama#1247]
For Kafka, partitions provide a way for consumption to scale. Hence, it is necessary that consumers needs to scale horizontally as well.

Is there any way to limit number of partitions per consumer, so that we can add more consumers so that all partitions are assigned to one of the consumers (total consumers * partitions per consumer = total partitions of the topic)? How can I do this?

What should the configuration of the node in this case? What logic can be used for size a consumer for a given number of partitions?

**Comment by varun06** [comment]
You can have as many consumers as there are partitions, going over that is not advisable. in terms of limit, if you have 10 partitions, you can spin two costumers in a group and that will give you 5 partitions each per consumer.

Let me know if that answers your questions, or I am off by long stretch?
