### ISSUE TITLE
Website is outdated

### ISSUE THREAD

**Issue by jeffwidman** [Shopify/sarama#1248]
https://shopify.github.io/sarama/ says:
> Sarama provides a “2 releases + 2 months” compatibility guarantee: we support the two latest stable releases of Kafka and Go, and we provide a two month grace period for older releases. This means we currently officially support Go 1.7 and 1.6, and Kafka 0.10.0 and 0.9.0, although older releases are still likely to work.

Those versions are outdated. In fact the current Readme says:
> Sarama provides a "2 releases + 2 months" compatibility guarantee: we support the two latest stable releases of Kafka and Go, and we provide a two month grace period for older releases. This means we currently officially support Go 1.8 through 1.11, and Kafka 1.0 through 2.0, although older releases are still likely to work.

So I think the website just needs to be updated to match the readme... I tried to submit a PR, but couldn't find the source code of that webpage.

**Comment by d1egoaz** [comment]
@bai this seems it's part of some internal Shopify site 🤷‍♂

**Comment by jeffwidman** [comment]
Please review, still appears to be an active issue

**Comment by dnwe** [comment]
@d1egoaz it's a GitHub pages generated website so the code is on the `gh-pages` branch.

**Comment by jeffwidman** [comment]
Thx @dnwe, I put up #1651 to fix.
