### ISSUE TITLE
Refactor code to support more SASL (as Dialer?)

### ISSUE THREAD

**Issue by giautm** [Shopify/sarama#1249]
Hi, I think the `net.Conn` can be inited by custom Dialer to support more SASL without touch into sarama core?

https://github.com/Shopify/sarama/blob/bb6b5baaf18c899a7bab84baf62f3f6a2716b24f/broker.go#L92-L96

https://github.com/Shopify/sarama/blob/bb6b5baaf18c899a7bab84baf62f3f6a2716b24f/broker.go#L127-L140

**Comment by varun06** [comment]
@giautm can you please elaborate more? if it is not much work, PR is also welcome.
