### ISSUE TITLE
How to consume from multiple topics?

### ISSUE THREAD

**Issue by imumesh18** [Shopify/sarama#1253]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
I want to consume from multiple topics on a same partition. I can see ConsumePartition(*topic, 0, sarama.OffsetNewest) only allows one topic per consumer. Is there a way I can make one consumer consume from multiple topics.

**Comment by kishoregv** [comment]
To my knowledge, In Kafka world topics own partitions. 
I guess your scenario is there are two topics *ABC* and *XYZ* from both the topics you want to read a partition with ID *N*.

You can create a [Consumer](https://github.com/Shopify/sarama/blob/master/consumer.go#L51) with multiple topics, and filter the partitions you are interested in.

**Comment by pmalekn** [comment]
> You can create a Consumer with multiple topics, and filter the partitions you are interested in.

I've hit the same problem now and I cannot find the function that would allow me to do that. 
@kishoregv Can you point it where can I find that? 
@imumesh18 How did you manage to solve your problem?

`Topics` method from `Consumer` interface **returns** the available topics that the broker sent.
