### ISSUE TITLE
Return zookeeper.connect value to sarama client?

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#1255]
Assume I have:
1. The address of a Kafka broker
2. A sarama [Client](https://godoc.org/github.com/Shopify/sarama#Client)

Can I use the Client to get the address of the ZooKeeper node that my broker is connected to?

As best as I can tell the answer is no, but I'd like to verify that.

If there is another way I should be going at it, please let me know. Thanks!

**Comment by d1egoaz** [comment]
I don't think that brokers are given that information to clients in the form of a API call.
Have you seen other kafka clients providing something similar?

**Comment by d1egoaz** [comment]
you can maybe try to connect to a broker JMX endpoint to get this information, assuming that exposing securely the JMX endpoint is sorted out.

Or having something running next to kafka cluster that can talk securily to JMX, and then make that **thing** push a message in a specific kafka topic, where clients can subscribe to get the necessary information.

But unsure what's your user case @kchristidis

**Comment by kchristidis** [comment]
> Have you seen other kafka clients providing something similar?

I have not. Simply wondering whether this functionality is available and I'm missing it. Thanks for the response!
