### ISSUE TITLE
LogAppend timestamp support

### ISSUE THREAD

**Issue by zimin2000** [Shopify/sarama#1259]
##### Versions

Sarama Version: eae91468c24263f06ae73dce45eb26252c73b1d6
Kafka Version: 1.0.0
Go Version: go1.11.2

##### Configuration

The only really important configuration is 
```
# Use broker time for message timestamps.
log.message.timestamp.type=LogAppendTime
```

##### Logs

N/A

##### Problem Description

At this stage the problem seems to be identified and fixed. The PR is https://github.com/Shopify/sarama/pull/1258 .  The description of how problem reveals itself is the following:

We have noticed mismatch in timestamps between `Timestamp` field in `ConsumerMessage` and result returned by `GetOffset` for the same offset. The difference is usually about ~1sec. We have compared the implementation for parsing the message in sarama with similar code in https://github.com/dpkp/kafka-python .

It turned out that sarama does not check the timestamp type (e.g. like [here](https://github.com/dpkp/kafka-python/blob/34fcb11c1cf96d69573274104d3b746ce67a97f4/kafka/record/default_records.py#L149) ) and is missing handling the case like [here](https://github.com/dpkp/kafka-python/blob/34fcb11c1cf96d69573274104d3b746ce67a97f4/kafka/record/default_records.py#L204) and [here](https://github.com/dpkp/kafka-python/blob/34fcb11c1cf96d69573274104d3b746ce67a97f4/kafka/record/legacy_records.py#L262) .

We did detect the problem for the new protocol (processed with `parseRecords `) and the problem seems to exist for the old one as well (processed with `parseMessage`).

**Comment by varun06** [comment]
@zimin2000 is it related to https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message?

trying to understand the functionality before reviewing code.

**Comment by zimin2000** [comment]
Yes, KIP-32 introduced 2 types of timestamps (`CreateTime` and `LogAppendTime`) and the later does not seem to be supported. From the [page]( https://cwiki.apache.org/confluence/display/KAFKA/KIP-32+-+Add+timestamps+to+Kafka+message):
```
message.timestamp.type - This topic level configuration defines the type of timestamp in the messages of a topic. The valid values are CreateTime or LogAppendTime.
```
The code is essentially supporting it taking pythons implementation for the reference.
