### ISSUE TITLE
How to get the stats

### ISSUE THREAD

**Issue by pradeepkusingh** [Shopify/sarama#1260]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: latest
Kafka Version: 2.1
Go Version: 1.11

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

I would like to fetch stats for Consumer group, consumer, producer and performance.  Need help.

**Comment by varun06** [comment]
Sarama expose metrics using https://github.com/rcrowley/go-metrics and metrics are defined in 
https://github.com/Shopify/sarama/blob/master/metrics.go

**Comment by pradeepkusingh** [comment]
Do we have any better example or code?

**Comment by varun06** [comment]
Check that out -> https://godoc.org/github.com/Shopify/sarama#example-Config--Metrics

**Comment by varun06** [comment]
Did that resolve your issue? also sarama only exposes producer and broker metrics.
