### ISSUE TITLE
renaming ErrXxx constants is an API changing change

### ISSUE THREAD

**Issue by nsd20463** [Shopify/sarama#1261]
FYI commit 04e4286cc194cd39150d98dcaf7e399601febf5f breaks [my] code because it removes several public ErrXxx names.

Perhaps this is deliberate, though strange in a tagged "1.something" repo. Or it's an accident and you meant to keep the old names around too.

**Comment by bai** [comment]
cc: @nrvnrvn @varun06

**Comment by bai** [comment]
Yep, this is a valid degradation.

**Comment by varun06** [comment]
ouch, can we please create a release and mention the breaking api change part. Will be more careful in future for these changes.

**Comment by bai** [comment]
I'm revering the PR in https://github.com/Shopify/sarama/pull/1262 on 🍏. Sorry for the trouble and thanks for reporting!

**Comment by nsd20463** [comment]
Thanks.
