### ISSUE TITLE
How to do the LAG check and get Consumer group owner client id and hosts?

### ISSUE THREAD

**Issue by pradeepkusingh** [Shopify/sarama#1263]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: Latest
Kafka Version: 1.11
Go Version: 1..11

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
Need some guidance on how to check the lag?

**Comment by abonec** [comment]
Is it possible to check without reading message? Say if there is no messages available (lag = 0) approach with msg offset doesn't work

**Comment by varun06** [comment]
hmm, not aware of anything in sarama that does that, check this out -> https://github.com/google-cloud-tools/kafka-minion

**Comment by d1egoaz** [comment]
@abonec you can also use something like https://github.com/linkedin/Burrow
