### ISSUE TITLE
How to get consumer metrics ? 

### ISSUE THREAD

**Issue by dhbarman** [Shopify/sarama#1269]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:

Top of the tree - master 

Kafka Version:

 ./bin/kafka-topics.sh --version
2.0.0 (Commit:3402a8361b734732)

Go Version:

go version go1.11 darwin/amd64

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

How can I obtain kafka consumer specific metrics ? How the following metrics related to any kafka consumer ? 

incoming-byte-rate  
incoming-byte-rate-for-broker-<broker-id>

**Comment by varun06** [comment]
Sarama only exposes Broker and Producer related metrics. 

Can you please elaborate on your second question.

**Comment by dhbarman** [comment]
Hi,

If you consider the following two metrics - 
   incoming-byte-rate . (Bytes/second read off all brokers)
   incoming-byte-rate-for-broker-<broker-id> . (Bytes/second read off a given broker )

Is there any relationship with any kafka consumer which is consumer data off the cluster or a particular broker ?

**Comment by jeroenrinzema** [comment]
@dhbarman Currently it is not plausible with Sarama to detect the io byte rate on a Kafka cluster. Please take a look at the [documentation provided by confluent](https://docs.confluent.io/current/kafka/monitoring.html#broker-metrics) on monitoring. You have to setup a JMX metrics exporter that collects the io byte rate of Kafka.

>`kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec`
>Aggregate incoming byte rate.
>`kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec`
>Aggregate outgoing byte rate.
