### ISSUE TITLE
GetOffset function not working properly

### ISSUE THREAD

**Issue by josesanchezr** [Shopify/sarama#127]
This function should return the last Offset correct to Topic/Partition, but always return the error:
kafka server: 
The requested offset is outside the range of offsets maintained by the server for the given topic/partition. 
#123

**Comment by ThomasAlxDmy** [comment]
@eapache did something changed? I get undefined: sarama.LatestOffsets

**Comment by wvanbergen** [comment]
OffsetLatest

**Comment by ThomasAlxDmy** [comment]
@wvanbergen it's actually sarama.OffsetLatest but thanks :)
