### ISSUE TITLE
Go module support

### ISSUE THREAD

**Issue by ebati** [Shopify/sarama#1272]
CI tests with the latest available packages as it does `go get`. However, since those versions are not recorded, the versions of dependencies this library is tested against is unknown to users of this library.

Is it OK if I send PR for dependency management with go modules.

**Comment by varun06** [comment]
Please do.

**Comment by magicdvd** [comment]
Please do.

**Comment by varun06** [comment]
@ebati Are you working on it? If not, I can take a crack sometime in coming week.

**Comment by ebati** [comment]
Actually i prepared go.mod and sum files but i am not sure how to handle go 1.10 which will not able to fetch these version. It might be better to wait 1.12 to come?

**Comment by varun06** [comment]
I thought that it works with old go version -> https://github.com/golang/go/wiki/Modules#how-are-v2-modules-treated-in-a-build-if-modules-support-is-not-enabled-how-does-minimal-module-compatibility-work-in-197-1103-and-111

**Comment by ebati** [comment]
The issue i am talking about is not about building the code but downloading the appropriate version of dependencies, that is fixed with go.mod, with go 1.10. Since this project does not vendor dependencies and run `go get -t` on each build running get with 1.10 will get the latest version not the version in go.mod. Please correct me if i am wrong about the matter.
