### ISSUE TITLE
Working with consumer group claims in parallel using goroutines

### ISSUE THREAD

**Issue by varun06** [Shopify/sarama#1276]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

Hey @dim, have a quick question. I have a use case where I want to consume using consumer group and then publish those messages to another topic in a a different kafka cluster.  I was wondering if something like this is possible on publish part.

```
func (h *handler) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	go func(claim sarama.ConsumerGroupClaim) {
		for msg := range claim.Messages() {
                     publisher.Publish(msg)
                     sess.MarkMessage(msg, "")
                }
        }(claim)
}
```

Can that work or I am missing something?

**Comment by dim** [comment]
@varun06 sorry, that's not right as `ConsumeClaim` is run in separate goroutines, hence all you need is:

```
func (h *handler) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	for msg := range claim.Messages() {
		publisher.Publish(msg)
		sess.MarkMessage(msg, "")
	}
	return nil
}
```

The only thing to be careful of is that `publisher.Publish` is thread-safe. The `ClusterConsumer` will create a goroutine for each of the claims and messages will be processed in multiple goroutines by default. If you need to scale and increase parallelism, just increase the number of partitions. I have tried to explain this in the documentation as well as I could but I feel it's still not clear to users. I am sure the sarama team is happy to accept PRs to address this uncertainty.

**Comment by varun06** [comment]
thanks for clarification. I also reached at same conclusion. I will also look at documentation and see if I can add something based on this convo.
