### ISSUE TITLE
OffsetRequest / OffsetResponse should contain offset type

### ISSUE THREAD

**Issue by weeco** [Shopify/sarama#1278]
I ommited the required issue fields (sarama, kafka version etc) as they are most likely not relevant for this issue.

**Use case**

I am writing a kafka prometheus exporter where I need to get all partition offsets. Therefore I am sending `OffsetRequest` with lots of requests to each broker. Specifically I am interested in the oldestOffset **and** newestOffset and here comes the problem. I put them alltogether using the `AddBlock()` method.

However when I iterate all the `OffsetResponseBlocks` I don't know whether the responseBlock with the Offset field is the "newest" or "oldest" offset or am I missing something here?

**Code:**

```go
offsetRequests := &sarama.OffsetRequest{}
offsetRequests.AddBlock(topic, partitionID, sarama.OffsetNewest, 1)
offsetRequests.AddBlock(topic, partitionID, sarama.OffsetOldest, 1)

offsetResponse, err := broker.GetAvailableOffsets(offsetRequests)
for topic, partitions := range offsetsResponse.Blocks {
  for partitionID, offsetResponse := range partitions {
    // How am I supposed to know if this offset is the oldest or newest offset (because I am asking for both in my requests)
    offset := offsetResponse.Offsets[0]
  }
}
```

PS: Since I got that little snippet from another exporter, I wonder what the last parameter (maxOffsets) indicates? Unfortunately I couldn't find any documentation about the AddBlock() method and it's parameters.

**Comment by varun06** [comment]
Hmm, can you use highwatermark to figure that out? I am trying to figure out the use case also interested in you reproter, is it going to be open sourced?

**Comment by weeco** [comment]
> Hmm, can you use highwatermark to figure that out?

Not really because I want to get the oldest and newest offset requests in parallel. The exporter is supposed to fetch the latest metrics on every scrape, therefore I want to run as many requests as possible concurrently.

Yes indeed the exporter is open source, but it's still under development: https://github.com/google-cloud-tools/kafka-minion . I am currently working on TLS support so that it can be ran on production clusters too.

**Comment by varun06** [comment]
Interesting, I will have a look at code today to make sense of it. On a cursory look, any particular reason you are using consumer and not consumergroup from sarama?

**Comment by weeco** [comment]
I intend to create a proper documentation / readme describing how the exporter works (this exporter does not consume the consumer group offsets topic). Since the exporter does not consume the consumer group offsets (like burrow for instance) I don't need a consumer group. The consumer is only used to get the Topics list
