### ISSUE TITLE
After publishing to AsyncProducer, Successes returned have null timestamps

### ISSUE THREAD

**Issue by deusnefum** [Shopify/sarama#1280]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.17.0
Kafka Version: 1.0.0.0
Go Version: 1.10.3

##### Configuration

Kafka is all default except for automatic topic creation which has been disabled

Saram config:
   config.Producer.RequiredAcks = sarama.WaitForLocal     // Only wait for the leader to ack
   config.Producer.Compression = sarama.CompressionSnappy // Compress messages
   config.Producer.Flush.Frequency = 1 * time.Millisecond // Flush batches every 500ms
   config.Producer.Return.Successes = true
   config.Version = sarama.V1_0_0_0

##### Problem Description

After adding the version specification, the timestamp started showing up on messages as expected: 

> bash > kafkacat -b localhost -C -t auto-alert-raw -f "%T\n" -o 0
> -1
> -1
> -1
> -1
> -1
> -1
> -1
> -1
> -1
> -1
> -1
> -1
> -1
> -1
> 1549984045355
> 1549984491171
> 1549984976336
> 1549985006789
> 1549985763100
> 1549985836450
> 1549985881538
> % Reached end of topic auto-alert-raw [0] at offset 21
> 

But logging the result of the returned success shows the timestamp as null.

:   producer.Input() <- &sarama.ProducerMessage{
:   :   Topic: "auto-alert-raw",
:   :   Value: sarama.StringEncoder(data),
:   }
:   select {
:   case success := <-producer.Successes():
:   :   logrus.WithFields(logrus.Fields{
:   :   :   "value":   success,
:   :   }).Trace("New alert published to kafka")
:   }

That gives me: 

  "Headers": null,
  "Key": null,
  "Metadata": null,
  "Offset": 20,
  "Partition": 0,
  "Timestamp": "0001-01-01T00:00:00Z",
  "Topic": "auto-alert-raw",
  "Value": "redacted"

Am I doing something wrong? Is this expected? A bug?

**Comment by varun06** [comment]
Are you still seeing this?

**Comment by deusnefum** [comment]
Yes I am.
