### ISSUE TITLE
Adding consumer batch-size matric to sarama

### ISSUE THREAD

**Issue by varun06** [Shopify/sarama#1281]
##### Problem Description

If I have to expose a consumer batch metric from sarama, is this -> https://github.com/Shopify/sarama/blob/master/consumer.go#L519-L545 right place to do it? parseRecords get batch as an argument, can I put len(batch) as consumer-batch-size in metric?

@dim @eapache

**Comment by dim** [comment]
@varun06 sorry this isn't my code, but I assume it depends on the `Consumer.Fetch` settings in https://github.com/Shopify/sarama/blob/master/config.go#L244

**Comment by varun06** [comment]
Thanks. I shall keep looking.
