### ISSUE TITLE
consumerGroup.Consume() with background context should be executed in a go routine

### ISSUE THREAD

**Issue by AlmogBaku** [Shopify/sarama#1285]
I expect that `consumerGroup.Consume()` with `context.Background` will execute the consuming in the background(as specified) and will be run in a different go-routine.

cc @dim

**Comment by dim** [comment]
Consume will acquire a claim on a number of partitions and will process each of the claimed partitions in its own goroutine, as explained in the documentation.

**Comment by varun06** [comment]
Hey @AlmogBaku 
does that answer your question, if yes, can we please close this issue?
