### ISSUE TITLE
[typo] message.go#L160 previousy -> previously

### ISSUE THREAD

**Issue by wrfly** [Shopify/sarama#1288]
https://github.com/Shopify/sarama/blob/2dcf36cdd2017e60a9fcd9d530ab517cc1b6d854/message.go#L160

previousy -> previously

**Comment by bai** [comment]
Thanks!

**Comment by wrfly** [comment]
This "typo" is 5 years ago...

**Comment by bai** [comment]
Happens to the best of us! ¯\_(ツ)_/¯ Thanks for reporting this one!
