### ISSUE TITLE
new sarama use pierrec/lz4  , V 1.18.0 use which pierrec/lz4?

### ISSUE THREAD

**Issue by h00401342** [Shopify/sarama#1292]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

**Comment by varun06** [comment]
Can you please elaborate more?

**Comment by d1egoaz** [comment]
@h00401342 not sure if the thing you're trying to mention is that we are using a non versioned dependency to the lz4 lib?

as currently go.mod is referencing a commit for lz4:
```
github.com/pierrec/lz4 v0.0.0-20190327172049-315a67e90e41
```

I think we could add a reference to a released version, however the lz4 repo doesn't use go mod, but at least, it's tagging the releases.

Something like:
```
github.com/pierrec/lz4 v2.2.6+incompatible
```
