### ISSUE TITLE
How Does "sarama" Support Transaction

### ISSUE THREAD

**Issue by figoxu** [Shopify/sarama#1299]
How Does This SDK Support The Methods Of 'Producer And Consumer' Such As : 'BeginTransaction' 'CommitTransaction' 'Rollback'

**Comment by panamafrancis** [comment]
AFAIK it does not support all kafka transaction features yet.

**Comment by robinryden** [comment]
@panamafrancis what features are not supported atm regarding transactions? thanks

**Comment by yangshengBE** [comment]
I am using consumer group, before committing the offset, I want to publish 1 or more msgs to next topic in the same or different partitions (like streaming). Is sarama support this currently?
