### ISSUE TITLE
Is it safe to reuse value from AsyncProducer.Successes()

### ISSUE THREAD

**Issue by abonec** [Shopify/sarama#1302]
Is it safe to reuse value from AsyncProducer.Successes() to next messages? Due to lack of documentation in the code it is not clear. 
Need to clarify it in the doc.

**Comment by varun06** [comment]
Can you please elaborate more and give a quick use case?

**Comment by abonec** [comment]
My messages in megabytes and I want to check AsyncProducer.Successes and put those slices to sync.Pool to reuse later in order to reduce pressure to GC.

**Comment by varun06** [comment]
More curious - First of all, sync.Pool gets cleared every [GC cycle](https://github.com/golang/go/issues/22950), so you should use it very carefully, but I am more curious about your storing messages from success and doing something with them, can you tell me more about your use case?

**Comment by abonec** [comment]
Ok. My algorithm as following:
Send loop:
1. Take []byte from the sync.Pool
2. Serialize (size of slice counts in megabytes) message to this slice
3. Produce this message via async producer.
Release loop:
1. Get sent message from the AsyncProducer.Successes
2. Put underlying slice back to the pool to serialize next message.

My question is:
Is it safe to reuse []byte to future serialization? I ask because there will be serious issue if there will be concurrent write to this slice between sarama and my code.

**Comment by vincentbernat** [comment]
This question is quite interesting. Does someone has an answer for it?
