### ISSUE TITLE
Consumer Group

### ISSUE THREAD

**Issue by 1995parham** [Shopify/sarama#1305]
I want to know is there any difference with Sarama and [Sarama Cluster](https://github.com/bsm/sarama-cluster)? I Sarama itself has a consumer group interface in its GoDoc so can we use it? I am asking this because in the same GoDoc Sarama refer to Sarama Cluster for group consuming.

**Comment by varun06** [comment]
Sarama cluster is going to be deprecated in favor of Sarama consumer groups -> https://github.com/bsm/sarama-cluster/issues/262#issuecomment-419878258

Please use sarama. I will clean up sarama go-doc soon.
