### ISSUE TITLE
About method : InitProducerID

### ISSUE THREAD

**Issue by Andy320** [Shopify/sarama#1308]
Sarama Version: Latest
Kafka Version: 2.1
Go Version: 1.11

##### Problem Description
``` go
func (client *client) InitProducerID() (*InitProducerIDResponse, error) {
	var err error
	for broker := client.any(); broker != nil; broker = client.any() {

		req := &InitProducerIDRequest{}

		response, err := broker.InitProducerID(req)
		switch err.(type) {
		case nil:
			return response, nil
		default:
			// some error, remove that broker and try again
			Logger.Printf("Client got error from broker %d when issuing InitProducerID : %v\n", broker.ID(), err)
			_ = broker.Close()
			client.deregisterBroker(broker)
		}
	}
	return nil, err
}

type InitProducerIDRequest struct {
	TransactionalID    *string
	TransactionTimeout time.Duration
}
```

Question is:
How to set the TransactionalID ?  thanks

**Comment by varun06** [comment]
one way to do that would be-> 

`req := &InitProducerIDRequest{TransactionalID: 24whatever}`

Now, why/what are you trying to do? more info will help in answering better.

**Comment by Andy320** [comment]
What am I going to do is ,
1. Call producer.(some method) to initialize a kafka producer transaction in the kafka cluster.
2. If 1 is ok, call producer.(some method) to send a message(like order created) to start the transaction.
3. Do local mysql transaction.
4. If 3 is ok, Call producer.(some method) to commit this kafka transaction. 
5. For now, the consumers begin to handle the committed message.
6.......

I saw the interfaces are implemented in kafka api level in sarama.broker, like FindCoordinator/InitProducerIDRequest... etc, but in the app level, we still have to do a lot of complicated things to coordinate these kafka apis to finish a correct transaction, just as the implementation of java kafka client, am I understand right? @varun06
