### ISSUE TITLE
Confusion with Sarama MaxMessageBytes and Kafka message.max.bytes different meaning

### ISSUE THREAD

**Issue by yum-install-brains** [Shopify/sarama#1309]
##### Versions

Sarama Version: v1.20.1
Kafka Version: v2.0.0
Go Version: v1.11.5

##### Configuration
Kafka:
```
message.max.bytes  = 5000000
```

Sarama SyncProducer:
```
cfg.Version = sarama.V2_0_0_0
	cfg.Producer.Partitioner = sarama.NewHashPartitioner
	cfg.Producer.RequiredAcks = sarama.WaitForAll
	cfg.Producer.Retry.Max = maxRetry
	cfg.Producer.Retry.Backoff = maxBackoff
	cfg.Producer.Return.Successes = true
```

##### Problem Description
According to https://github.com/Shopify/sarama/issues/636#issuecomment-203611747 Sarama uses batching by default. However, `MaxMessageBytes` in Sarama is per message parameter and `message.max.bytes` in Kafka is per batch (similar question without answer was in comment https://github.com/Shopify/sarama/issues/1140#issuecomment-411103709). 

So, my question is How Sarama will batch events in case of default Flush configuration parameters? Will it send only one event per request? Or is there some default delay time, when Sarama waits for more messages to come before sending batch to broker (if so, what is the delay time)? 

Please, help me to understand default batching mechanism in Sarama.

Best regards, 
Tolya

**Comment by varun06** [comment]
Here -> https://github.com/Shopify/sarama/blob/master/config.go#L393-L401 are the defaults, please let me know if they are not helpful.

**Comment by yum-install-brains** [comment]
@varun06, thank you for quick answer! 

But I am still not sure about default batching on sync producer. For example, with only default configuration values I am not batching messages at all (sending one message per request always)?
