### ISSUE TITLE
unknown generation error while consuming using consumer group

### ISSUE THREAD

**Issue by varun06** [Shopify/sarama#1310]
##### Versions

Sarama Version:1.21.0
Kafka Version: 1.1.0
Go Version:1.12

##### Configuration
```
		cfg.Consumer.Group.Session.Timeout = 20 * time.Second
		cfg.Consumer.Group.Heartbeat.Interval = 6 * time.Second

```

##### Logs
```
ERRO[0051] kafka: error while consuming <topic-name>: kafka server: The provided member is not known in the current generation.  
```

##### Problem Description

We have a library that provide some abstraction over sarama consumer group. while using the library I see lots of above ^^ errors. I have already looked at session timeout values, but no help. @dim can you please help me understand this error and point towards some steps?

**Comment by varun06** [comment]
@bai have you seen this error ever?

**Comment by bai** [comment]
Possibly related? https://github.com/bsm/sarama-cluster/issues/29

**Comment by varun06** [comment]
Thanks Bai, that's helpful.

**Comment by varun06** [comment]
Hey @dim I think I need your help here. I have tried bunch things but still getting below error in sarama logs.

```
ERRO[0098] kafka: error while consuming ewr.kessel-run.mt-raw.1/8: kafka server: The provided member is not known in the current generation.  offset=-3 partition=-1 topic=unknown type=kafka
ERRO[0098] kafka: error while consuming ewr.kessel-run.mt-raw.1/1: kafka server: The provided member is not known in the current generation.  offset=-3 partition=-1 topic=unknown type=kafka
ERRO[0098] kafka: error while consuming ewr.kessel-run.mt-raw.1/4: kafka server: The provided member is not known in the current generation.  offset=-3 partition=-1 topic=unknown type=kafka
```

Here is my consumer side config -

```
		cfg.Consumer.Group.Session.Timeout = 20 * time.Second
		cfg.Consumer.Group.Heartbeat.Interval = 6 * time.Second
		cfg.Consumer.MaxProcessingTime = 500 * time.Millisecond
```

**Comment by dim** [comment]
@varun06 sorry, I have been slightly distracted recently :) My apologies, but I am not 100% sure how to help. Generation errors only happen when a member tries to commit offsets after the session has been closed server side. I assume you are not stopping your consume loop quickly enough after a rebalance is triggered. The broker is then starting a new session with a new generation and giving up on the previous one. I would try to increase the Session.Timeout and see if that makes a difference.

**Comment by varun06** [comment]
Thanks @dim I have been playing with timeouts and they have helped, so errors are very sporadic now, I am sure it is the way we committing the offsets, we commit them in batch and that code has some oddities as you mentioned.

**Comment by 1995parham** [comment]
@varun06 can you please describe and share your timeout values with us? We have the same problem with Sarama.

**Comment by varun06** [comment]
@1995parham 
```
cfg.Consumer.Group.Session.Timeout = 20 * time.Second
cfg.Consumer.Group.Heartbeat.Interval = 6 * time.Second
cfg.Consumer.MaxProcessingTime = 500 * time.Millisecond
```

**Comment by ibitday** [comment]
cfg.Consumer.Group.Session.Timeout = 20 * time.Second
cfg.Consumer.Group.Heartbeat.Interval = 6 * time.Second
cfg.Consumer.MaxProcessingTime = 500 * time.Millisecond

> [@1995parham](https://github.com/1995parham)
> 
> ```
> cfg.Consumer.Group.Session.Timeout = 20 * time.Second
> cfg.Consumer.Group.Heartbeat.Interval = 6 * time.Second
> cfg.Consumer.MaxProcessingTime = 500 * time.Millisecond
> ```

i set the same config with above value, but the `kafka server: The provided member is not known in the current generation` still happend.
