### ISSUE TITLE
Client does not support operation to return the offline replicas of a given partition

### ISSUE THREAD

**Issue by drsoares** [Shopify/sarama#1311]
##### Versions

Sarama Version: v1.21.0, revision:4602b5a8c6e826f9e0737865818dd43b2339a092
Kafka Version:0.11.0.0
Go Version: 1.11.2 

##### Problem Description
I think it would be helpful to have the Offline Replicas number available on the sarama.Client interface.

Similar to the number of partitions and similar to the number of the out of sync replicas. Something like:

	OfflineReplicas(topic string, partitionID int32) ([]int32, error)

I would be happy to perform the necessary changes to support this feature.

**Comment by varun06** [comment]
that sounds helpful @drsoares plese make a PR and we can take it forward from there.

**Comment by d1egoaz** [comment]
closed by https://github.com/Shopify/sarama/pull/1318/
