### ISSUE TITLE
Consume large batches of message?

### ISSUE THREAD

**Issue by matzew** [Shopify/sarama#1324]
With code like:

```
func (hexampleConsumerGroupHandler) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {

	for msg := range claim.Messages() {
		sess.MarkMessage(msg, "")
	}
	return nil
}
```

I read messages 1-by-1

what's the best way to read (larger/configurable) batches of lot's of messages ?

**Comment by varun06** [comment]
when a consumer reads from broker, it batches those reads. When you are consuming the claim, you are getting message from channel and you are consuming it one by one, but batching is definitely happening in the backend. you can tweak the number of messages to batch with `config.consumer.Fetch.Min` setting. 

Let me know if I answered your question.

**Comment by matzew** [comment]
Thanks, @varun06!

The doc says:

> The minimum number of message bytes to fetch in a request

So, it's bytes, not messages..

I was wondering if I am able to read 1000 messages in once, and than throw them in "n" goroutines to some other infrastructure/server, that will store/process them.

In Java client, the `poll` returns a "collection" (`ConsumerRecords`), which contains a number of `ConsumerRecord` objects

**Comment by varun06** [comment]
hmm, it's a channel based consumer so you will receive 1 message at a time, one thing that you can do is write your own batching procedure and then send those batch to downstream processors. But as far as I know sarama doesn't give you a collection of records to process.

@bai can you help with this?

**Comment by birdayz** [comment]
you can do a hack: when reading from the channel, keep reading from it into a slice, until - in a select - you would get a blocking read (nothing is in the channel).

**Comment by eightnoteight** [comment]
> you can do a hack: when reading from the channel, keep reading from it into a slice, until - in a select - you would get a blocking read (nothing is in the channel).

@birdayz won't this lead to `conf.Consumer.MaxProcessingTime` to trigger rebalancing if batch size being read from kafka is lower than slice batch size?
