### ISSUE TITLE
Best Practice on Client vs new Consumer/Producer

### ISSUE THREAD

**Issue by vishalmodak** [Shopify/sarama#1325]
Hello,

I am trying to figure what is good practice for creating consumers or producers.
Is it better to create a Client once and then re-use it to create multiple consumers/producers thru the life of the application? 
Alternatively, is the cost of creating a consumer/producer for every message expensive? I have noticed that every instance of consumer/producer creates a new connection with the broker, registers the client & sets up other things.
In my application, I have 1 consumer & 3 different producers. 2 of the producers function as ad-hoc emitters (emit when necessary). Creating a new producer for every send message send  doesn't seem like a good pattern. 

Thanks in advance.

**Comment by varun06** [comment]
>Alternatively, is the cost of creating a consumer/producer for every message expensive?

Yes, you don't want to do that in general case, you create a consumer or producer and use it to consume and publish messages to kafka. Once you are done, you close both consumer and producer. 

Same thing with client, you create it once and the use to create consumer and producer. client reuse is highly recommended. 
https://godoc.org/github.com/Shopify/sarama#Client

**Comment by wajidp** [comment]
Sorry to reopen this issue again, what if i have multiple clients say 10000 should i create a producer for all or is there any best approach?
