### ISSUE TITLE
Improve consumer group example [documentation]

### ISSUE THREAD

**Issue by curt-hash** [Shopify/sarama#1336]
Running the existing consumer group example results in a panic. It's pretty clear why, but it might be good to have an example that shows an idiomatic way to cleanly break out of the `Consume()` loop if the client is closed.

```go
for {
    err := client.Consume(ctx, strings.Split(topics, ","), &consumer)
    if err != nil {
        panic(err)
    }
}
```

```
go run main.go -brokers="127.0.0.1:9092" -topics="sarama" -group="example"
2019/04/01 10:47:58 Starting a new Sarama consumer
2019/04/01 10:47:59 Sarama consumer up and running!...
^Cpanic: kafka: tried to use a consumer group that was closed

goroutine 19 [running]:
main.main.func1(0x886cc0, 0xc000116070, 0x887900, 0xc00001e100, 0xc000010060)
	/sarama/examples/consumergroup/main.go:87 +0xeb
```

**Comment by zhaoweiguo** [comment]
And it seems like that this command is not work:
> config.Consumer.Offsets.Initial = sarama.OffsetNewest
Has anyone encountered the same problem?

**Comment by dhbarman** [comment]
Is it possible to enhance the documentation and examples/test cases describing how to handle the following ? 

Suppose there is a go-routine A which is invoked (periodically). This go-routine A represents a consumer of a consumer-group. Therefore, A will initiate consume() and that will lead to processing of messages on various claims. 

All the messages need to be aggregated at A. One way to achieve this is to create channels. Can we do that without creating channels and communicate between A and ConsumeClaim() methods ?
