### ISSUE TITLE
Discussion - Metrics in sarama

### ISSUE THREAD

**Issue by varun06** [Shopify/sarama#1340]
I have been fighting with go-metrics model of doing stats. There is definitely a gap between go-metrics and prometheus etc. Then I came across https://github.com/rcrowley/go-metrics/pull/242#issuecomment-455613410.

That makes me wonder if we should think about doing stats in sarama in a different way. thoughts?

@bai - Please feel free to add more folks here.

**Comment by varun06** [comment]
@bai have you looked at https://opencensus.io. May be we should use that in place of go-metrics?

**Comment by bai** [comment]
I'm just flying from KubeCon right now and the news is that OpenCensus and OpenTracing are merging into OpenTelemetry. I think it makes sense to explore using OpenTelemetry instead of go-metrics, I'll take a look and will follow up here over the next few weeks.

**Comment by varun06** [comment]
Oh man, I hope they keep the api same, otherwise it's gonna be a big headache for us. Yeah, let's look at them as they look great for our use case.

**Comment by giautm** [comment]
OpenCensus look still stable for our, OpenTelemetry has a long milestone to stable - (12/2019)

**Comment by bai** [comment]
To be honest, given this is a breaking change and it kind of paves the way for Sarama 2.0, I don't think it's going to take less than a few months to go over, incorporate, and stabilize [this list](https://github.com/Shopify/sarama/wiki/Ideas-that-will-break-backwards-compatibility).

**Comment by varun06** [comment]
Yeah, let do that. Also should we add metrics change to above list?

**Comment by giautm** [comment]
yep, waiting for `Sarama@v2`.
