### ISSUE TITLE
Health checking Kafka connection

### ISSUE THREAD

**Issue by weeco** [Shopify/sarama#1341]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1.21.0
Kafka Version: v2.2.0
Go Version: v1.12

##### Question

I'd like to implement a health check which tells me whether the client can talk to the Kafka cluster or not. Since it's regularly called by Kubernetes I'd like to avoid any heavier request.

Thus I am wondering if there's something like an internal cached state to figure out if it's healthy, or if you've got something like a ping/pong function for this purpose?

**Comment by varun06** [comment]
How about checking active brokers -> https://github.com/Shopify/sarama/blob/master/client.go#L23-L24??

**Comment by weeco** [comment]
Is somewhere defined what "active brokers" means in this context? Depending on that definition that could perfectly suit my needs.

**Comment by varun06** [comment]
It is fetching that information from metadata about the cluster, so these are the brokers active at that particular moment in time.

**Comment by weeco** [comment]
Alright, seems to work as health check. I'll report back if I figure out it doesn't. Thank you
