### ISSUE TITLE
ConsumeClaim accessing external system

### ISSUE THREAD

**Issue by matzew** [Shopify/sarama#1357]
I recently did add a note to the example, that _inside_ the `ConumeClaim` there should be no `goroutine`, see:

* https://github.com/Shopify/sarama/pull/1334/files

From this community @varun06 and @dim did approve the note.

However I was wondering what's best to access a 3rd party system (e.g. HTTP server) with messages consumed in the `Claim`.

What's best solution to do that? 

Imagine, I have one single consumer that consume 100 partitions of one topic, this translates into 100 go-routines (one per topic partion)

Now, what will happen if the communication to the external system is taking LONG time (E.g. a few seconds), and when there is huge amount of messages on the topic. 

What's the best to submit received messages (or their payload) to a external system ?

**Comment by dim** [comment]
> Now, what will happen if the communication to the external system is taking LONG time (E.g. a few seconds), and when there is huge amount of messages on the topic.

You can init a batch at the start of `ConsumeClaim`, accumulate some messages and send them to the HTTP service as a batch. 

If you need to send your messages 1-by-1 and your HTTP service cannot cope with the flood of messages (i.e. you produce quicker than you can consume), you can add more partitions, but you probably also need to rethink your architecture.
