### ISSUE TITLE
add consumers for consumer group

### ISSUE THREAD

**Issue by bluesky1024** [Shopify/sarama#1362]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:2.2.0
Kafka Version:2.2.0
Go Version:1.11.5

##### Configuration

What configuration values are you using for Sarama and Kafka?
kafka:
broker:1
topic: "my-topic"-3partition-1 replicas

the sarama producer:
```go
	config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.Partitioner = sarama.NewHashPartitioner
	config.Producer.Return.Successes = true
	config.Producer.Return.Errors = true
	config.Version = sarama.V2_2_0_0

	producer, err := sarama.NewSyncProducer([]string{"0.0.0.0:9092"}, config)
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
according to the example given in https://github.com/Shopify/sarama/tree/master/examples/consumergroup
the consumergroup is built, and the consumer is defined as follows
```go
        ...
	ctx := context.Background()
	client, err := sarama.NewConsumerGroup(strings.Split(brokers, ","), group, config)
	if err != nil {
		panic(err)
	}

	consumerA := Consumer{
		ready:     make(chan bool, 0),
	}

	go func() {
		for {
			err := client.Consume(ctx, strings.Split(topics, ","), &consumerA)
			if err != nil {
				panic(err)
			}
		}
	}()

	<-consumerA.ready // Await till the consumer has been set up
	log.Println("Sarama consumerA up and running!...")
```
However, when i want to add more consumer in the same consumerGroup client or just go run one more the same file, panic appears. Is there more example about how to add more consumer in the same consumerGroup?
thanks for your attention.

**Comment by junweiyang** [comment]
i have the same issue。

**Comment by varun06** [comment]
hmm, I will have a look this weekend.

**Comment by varun06** [comment]
Alright, I ran same example locally and I was able to run more than 1 consumer per consumer group. it didn't panic at all and it subscribed to partitions in topic fine.

I have a 10 partition topic btw.

That's the command I ran locally multiple time to have multiple consumers.

`go run main.go -brokers localhost:9092 -group test -topics consumer-group-test -verbose`

@bluesky1024 ^^

**Comment by bluesky1024** [comment]
@varun06 Thanks for your relay. I can not figure out what‘s wrong with my code...
I tried to run the same file. The result is as follows
a.
```shell
2019/04/28 13:15:37 Starting a new Sarama consumer
[sarama] 2019/04/28 13:15:37 Initializing new client
[sarama] 2019/04/28 13:15:37 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2019/04/28 13:15:37 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2019/04/28 13:15:37 client/metadata fetching metadata for all topics from broker 127.0.0.1:9092
[sarama] 2019/04/28 13:15:37 Connected to broker at 127.0.0.1:9092 (unregistered)
[sarama] 2019/04/28 13:15:37 client/brokers registered new broker #1001 at 127.0.0.1:9092
[sarama] 2019/04/28 13:15:37 Successfully initialized new client
[sarama] 2019/04/28 13:15:37 client/metadata fetching metadata for [my-topic] from broker 127.0.0.1:9092
[sarama] 2019/04/28 13:15:37 client/coordinator requesting coordinator for consumergroup example1 from 127.0.0.1:9092
[sarama] 2019/04/28 13:15:37 client/coordinator coordinator for consumergroup example1 is #1001 (127.0.0.1:9092)
[sarama] 2019/04/28 13:15:37 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2019/04/28 13:15:37 Connected to broker at 127.0.0.1:9092 (registered as #1001)
[sarama] 2019/04/28 13:15:37 client/coordinator requesting coordinator for consumergroup example1 from 127.0.0.1:9092
[sarama] 2019/04/28 13:15:37 client/coordinator coordinator for consumergroup example1 is #1001 (127.0.0.1:9092)
2019/04/28 13:15:37 Sarama consumerA up and running!...
[sarama] 2019/04/28 13:15:37 consumer/broker/1001 added subscription to my-topic/2
[sarama] 2019/04/28 13:15:37 consumer/broker/1001 added subscription to my-topic/0
[sarama] 2019/04/28 13:15:37 consumer/broker/1001 added subscription to my-topic/1
[sarama] 2019/04/28 13:15:55 consumer/broker/1001 closed dead subscription to my-topic/2
[sarama] 2019/04/28 13:15:55 consumer/broker/1001 closed dead subscription to my-topic/0
[sarama] 2019/04/28 13:15:55 consumer/broker/1001 closed dead subscription to my-topic/1
[sarama] 2019/04/28 13:15:55 client/metadata fetching metadata for [my-topic] from broker 127.0.0.1:9092
[sarama] 2019/04/28 13:15:55 client/coordinator requesting coordinator for consumergroup example1 from 127.0.0.1:9092
[sarama] 2019/04/28 13:15:55 client/coordinator coordinator for consumergroup example1 is #1001 (127.0.0.1:9092)
panic: close of closed channel
```
b.
```shell
2019/04/28 13:15:53 Starting a new Sarama consumer
[sarama] 2019/04/28 13:15:53 Initializing new client
[sarama] 2019/04/28 13:15:53 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2019/04/28 13:15:53 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2019/04/28 13:15:53 client/metadata fetching metadata for all topics from broker 127.0.0.1:9092
[sarama] 2019/04/28 13:15:53 Connected to broker at 127.0.0.1:9092 (unregistered)
[sarama] 2019/04/28 13:15:53 client/brokers registered new broker #1001 at 127.0.0.1:9092
[sarama] 2019/04/28 13:15:53 Successfully initialized new client
[sarama] 2019/04/28 13:15:53 client/metadata fetching metadata for [my-topic] from broker 127.0.0.1:9092
[sarama] 2019/04/28 13:15:53 client/coordinator requesting coordinator for consumergroup example1 from 127.0.0.1:9092
[sarama] 2019/04/28 13:15:53 client/coordinator coordinator for consumergroup example1 is #1001 (127.0.0.1:9092)
[sarama] 2019/04/28 13:15:53 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2019/04/28 13:15:53 Connected to broker at 127.0.0.1:9092 (registered as #1001)
[sarama] 2019/04/28 13:15:55 client/coordinator requesting coordinator for consumergroup example1 from 127.0.0.1:9092
[sarama] 2019/04/28 13:15:55 client/coordinator coordinator for consumergroup example1 is #1001 (127.0.0.1:9092)
2019/04/28 13:15:55 Sarama consumerA up and running!...
[sarama] 2019/04/28 13:15:55 consumer/broker/1001 added subscription to my-topic/2
[sarama] 2019/04/28 13:16:08 consumer/broker/1001 closed dead subscription to my-topic/2
[sarama] 2019/04/28 13:16:08 client/metadata fetching metadata for [my-topic] from broker 127.0.0.1:9092
[sarama] 2019/04/28 13:16:08 client/coordinator requesting coordinator for consumergroup example1 from 127.0.0.1:9092
[sarama] 2019/04/28 13:16:08 client/coordinator coordinator for consumergroup example1 is #1001 (127.0.0.1:9092)
panic: close of closed channel
```

it seems that the first process has added subscription of my-topic 's 3 partition. When the second process added subscription of the same topic's same partition, panic appear, which causing dead subscription. 

Is it possible that there is something wrong on my configure of kafka?

**Comment by varun06** [comment]
Can you please share kafka configs?

**Comment by bluesky1024** [comment]
@varun06 I'm terribly sorry for forgetting check my email these days...
I use the docker images from https://github.com/wurstmeister/kafka-docker. And the YML configure file is as follow
```bash
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.9
      KAFKA_CREATE_TOPICS: "relation_trans:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by hilalevavi** [comment]
> ally multiple t

can you share please an example for one creating consumerGroup but create couple of consumer instance in this consumer group that consume success consume both? when i use the log
after call the second consumer (from the same consumerGroup of the first consumer i created i got)
[sarama] 2019/05/06 15:01:45 consumer/broker/2 closed dead subscription to cs/31
[sarama] 2019/05/06 15:01:45 consumer/broker/2 closed dead subscription to cs/21
[sarama] 2019/05/06 15:01:45 consumer/broker/2 closed dead subscription to cs/16
etc for all the partition and it (i have no replications and 32 partitions)
and then it 
[sarama] 2019/05/06 *********consumer/broker/4 added subscription to cs/13

so an example of creating couple consumer in the same group can be useful :)
thanks :)

**Comment by bluesky1024** [comment]
@hilalevavi I got the same problem as yours. Here is my program, is there something wrong?
https://github.com/bluesky1024/goMblog/blob/20190425_mblog_to_feed/daemon/kafka/relation/main.go

**Comment by prune998** [comment]
Did you set a different `config.ClientID` in each run ? (not sure if it makes a difference)

**Comment by bluesky1024** [comment]
@prune998 thanks for you advice very much. It proves that i had not set the config.clientId. And my process run normally after set different config.clientId for every run. Thanks again...

**Comment by bluesky1024** [comment]
@prune998  Thanks for your advice very much. In fact, my program run normally now. However, I do not figure out why my process failed before...😂
And it proves that the config.ClientId is defined as string "sarama" commonly if not specific this parameter.  These processes run normally without set different clientId.

**Comment by d1egoaz** [comment]
If I understood correctly, is this issue already solved @bluesky1024  ?

can we close the issue?

**Comment by bluesky1024** [comment]
> If I understood correctly, is this issue already solved @bluesky1024 ?
> 
> can we close the issue?

yes, thanks

**Comment by jeff303** [comment]
We are having a similar problem, from the consumer side (also using the sample code), on Sarama `1.37.2`.  The panic is occurring [here](https://github.com/Shopify/sarama/blob/v1.37.2/examples/consumergroup/main.go#L167).

Is it, in fact, the case that multiple concurrent consumers need to have a distinct consumer group in order to avoid the problem?  That seems to be what my experimentation has revealed, but that doesn't quite make sense, since doing such a thing is legitimate from the Kafka broker POV (multiple concurrent consumers in the same group to parallelize reads).
