### ISSUE TITLE
[Question] Why consumer groups requires kafka version to be greater than 0.10.2.0

### ISSUE THREAD

**Issue by leoneuwald** [Shopify/sarama#1363]
##### Versions

Sarama Version: 1.22.0
Kafka Version: 0.10.1.1
Go Version: 1.12.2

##### Configuration

`config.Version = sarama.V0_10_1_1`

##### Problem Description

Hi, 

I'm trying to understand the reason for the validation bellow:

[consumer_group.go](https://github.com/Shopify/sarama/blob/master/consumer_group.go#L94)
```
if !config.Version.IsAtLeast(V0_10_2_0) {
	return nil, ConfigurationError("consumer groups require Version to be >= V0_10_2_0")
}
```

At the [Kafka Protocol Guide](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-VersioningandCompatibility) I couldn't find any protocol change between versions 0.10.1.x and 0.10.2.x.

I made some tests using `ConsumerGroup` with Kafka version 0.10.1.1 and configuration like `config.Version = sarama.V0_10_2_0`. It seams to be working, but first I'd like to know if there's any restriction.

Thanks for your attention.

**Comment by varun06** [comment]
@dim can you please answer it?

**Comment by dim** [comment]
I don't remember the exact reason, but I do remember that there was one. It may be related to https://github.com/apache/kafka/pull/1336 which was added/fixed in 0.10.2.x

**Comment by varun06** [comment]
does that answer your question @leoneuwald ??

**Comment by leoneuwald** [comment]
Yes. Thanks!
