### ISSUE TITLE
kerberos auth support

### ISSUE THREAD

**Issue by yzpnet** [Shopify/sarama#1375]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: latest
Kafka Version: 0.9.0
Go Version: go1.12 darwin/amd64

##### Problem Description

I need the kerberos authentication.

Need auth by xxxx.keytab file.

**Comment by yzpnet** [comment]
Sarama Version: v1.22.1

**Comment by Lou-Cipher** [comment]
I'm currently working on adding Kerberos support, using gokrb5.  I'm learning go as I work on this, so it might take a bit to get it fully working.  I'm hoping to add support for both password auth and keytabs.  End goal is to add support for Kerberos auth to the Telegraf Kafka output, and Telegraf uses sarama.

**Comment by yzpnet** [comment]
> I'm currently working on adding Kerberos support, using gokrb5. I'm learning go as I work on this, so it might take a bit to get it fully working. I'm hoping to add support for both password auth and keytabs. End goal is to add support for Kerberos auth to the Telegraf Kafka output, and Telegraf uses sarama.

Thanks a lot. 
Hope can be used as soon as possible.

**Comment by d1egoaz** [comment]
some kerberos support was added in https://github.com/Shopify/sarama/pull/1366
If it doesn't work for you, feel free to re-open the issue.
