### ISSUE TITLE
is it a bug with DeleteRecords 

### ISSUE THREAD

**Issue by evazca** [Shopify/sarama#1377]
Versions
Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.
Sarama Version: a4a1b88
Kafka Version: 2.1.1
Go Version: 1.12.1

Configuration
Not relevant

Logs
Not relevant

Problem Description
The method DeleteRecords in admin.go seems to have a bug. The DeleteRecordsRequest should be sent to Leader according to  KafkaAdminClient rather than the controller（https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/admin/KafkaAdminClient.java）.  Also the controller will respond with an error code 6 but the return error of the method is nil.

I'm going to fix it as below
1.  call client.Leader  to get leader info
2.  send the request to the leaders.
3.  an error will be returned if a topic partition failed.   (or return slice of errors)

**Comment by d1egoaz** [comment]
fixed by https://github.com/Shopify/sarama/pull/1425
