### ISSUE TITLE
How to get all consumer groups that subscribe to a topic?

### ISSUE THREAD

**Issue by funkol2007** [Shopify/sarama#1378]
Hi all, I was wondering if there is any method to get the consumer group list that subscribe to some topic.  If there has some metod to get the relationship between topics and consumer groups is much better!

**Comment by cheesedosa** [comment]
Have you looked at [Cluster Admin](https://godoc.org/github.com/Shopify/sarama#ClusterAdmin)? It is possible to list all consumer groups and fetch metadata individually for each consumer for the group and map them if they are consuming from your topic.

**Comment by d1egoaz** [comment]
does the above comment answered your question @funkol2007 ?

**Comment by ys-achinta** [comment]
Hi, we needed this functionality for our use case as well.
In case this hasn't been closed, can we go ahead and raise a PR for this feature? cc @d1egoaz
