### ISSUE TITLE
regex topic subscription 

### ISSUE THREAD

**Issue by taalhach** [Shopify/sarama#1379]
hi all i am trying to do pattern matching to topics names and subscribe to the topics that matches to given regex and if a topic is added after running the consumer then it should also subscribe to that topic. we can do that in confluent but they reads the message by polling and using one routine i want to handle message consumption in separate go routine per topic is there any way we can achieve it here ?

**Comment by DrmagicE** [comment]
@taalhach Hi, can you show me how to use pattern matching topic? 
I tried in this issue: https://github.com/Shopify/sarama/issues/1382, but it is not working..

**Comment by taalhach** [comment]
i used confluent's go library for pattern matching didn't try it with sarama
click the link below and check 1st consumer example
https://github.com/confluentinc/confluent-kafka-go

**Comment by d1egoaz** [comment]
I've updated the issue title, I think the right term here is regex, and not pattern matching

**Comment by chrispassas** [comment]
In case it helps for implementing the feature this library built on samara and offers regex support.

https://github.com/bsm/sarama-cluster

**Comment by ameghdadian** [comment]
Hi!

Any updates on this issue would be appreciated. 

The combination of regex subscription to topics and automatic consumer rebalancing whenever a new matching topic is created on the fly works great in my use case.
