### ISSUE TITLE
How to start consuming from the latest offset after client restart ?

### ISSUE THREAD

**Issue by dhbarman** [Shopify/sarama#1384]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1.22.0 
Kafka Version: 2.0.0 
Go Version: 1.12.5

##### Configuration

Standard config as in the example here.

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

After kafka client restart, I want to consume from the recent most offset. 
I was trying to apply session.MarkOffset() with HighWaterMark() but there is 
no claim object in Setup() function. Is there any other way to MarkOffset() to the recent 
most offset ?

func (consumer *ConsumerHandler) Setup(session sarama.ConsumerGroupSession) error {
	return nil
}

**Comment by cheesedosa** [comment]
If you want to consume only the recent messages produced after you connect to a cluster, you can join with a new consumer group and set `Consumer.Offsets.Initial` to `Offset.Newest`. Does this not work for you?

**Comment by dhbarman** [comment]
Hi,

Thanks for responding. That's exactly what I have done. But I need a
cleaner way of achieving the same. I don't want to change consumer group
name every time a client restarts.

Regards,
Dhiman

**Comment by cheesedosa** [comment]
What you can do is never `session.MarkMessage(msg)` in your `Consume` handler and set `Consumer.Offsets.Initial` to `OffsetNewest`. Since no offsets are committed, `Consumer.Offsets.Initial` would be considered as the offset to start consumption from.

**Comment by dhbarman** [comment]
Hi,

That's an interesting idea. Will there any side-effects ? What if
rebalancing happens on the brokers ?

Thanks,
Dhiman

**Comment by cheesedosa** [comment]
There shouldn't be any side-effects except that you will lose the messages that are produced while a rebalance is in progress. But then again you are consuming only the newest messages after joining, so you are losing messages already (the ones that were produced when your consumers were offline).

**Comment by dhbarman** [comment]
Hi,

When a client comes up for the first time with the configuration -
Consumer.Offsets.Initial set to OffsetNewest (and let's say that value of
the offset the client receives X), will this state not be stored in backend
broker ? If so, when the client restarts the second time, will it not get
the same offset X the second time ?

Thanks,
Dhiman

**Comment by cheesedosa** [comment]
No, only the offsets that are committed are stored on the broker. 
If you commit offsets for say 100 messages after X, then the next time the consumer comes up, it will read from X+101. 
If you don't commit offsets, the consumer (if configured with OffsetNewest) will start consuming messages that will be produced *after* the consumer joins the broker. If you produced messages while the consumer was away, you would lose those messages.

**Comment by dhbarman** [comment]
There are two scenarios as far as a consumer joining a broker is concerned.
Assume no customer in a consumer group is committing any offset.

1) A consumer (C) goes down, comes up and joins a broker. In this case, the
consumer will start consuming messages from the newest offset of a given
partition. This situation is as per requirement.

2) Due to network issues, the connection between the consumer (C) and a
broker breaks or may be the broker does not receive heart beats from C (and
timeouts occur). The broker considers the consumer to be unavailable but
the consumer is up.  This might cause re-balancing of the partitions.
Furthermore, assume the last message that C consumes before the disruption
is at offset 200 on partition P. Whereas at the same, the broker writes
message at offset 700 because customer C is slow. After re-balancing,
another customer D is assigned this partition (P). The customer D starts
receiving messages from 700 resulting in a loss of 500 messages in the
system. If this is not true, what offset will D start receiving after
re-balancing ?

**Comment by cheesedosa** [comment]
That is correct. D will start consuming from the newest offset (which is 700) resulting in a loss of 500 messages.
