### ISSUE TITLE
message Repeat consumption

### ISSUE THREAD

**Issue by cafra** [Shopify/sarama#1388]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:  v1.22.1
Kafka Version:  v1.0.0
Go Version: v1.11

##### Configuration

config := sarama.NewConfig()
	config.Version = sarama.V0_10_2_0
	config.Consumer.Return.Errors = true
	config.Consumer.Offsets.Initial = sarama.OffsetOldest

##### Logs

![image](https://user-images.githubusercontent.com/13758306/58773637-6682bc80-85f0-11e9-8ab6-89e6d6f1193d.png)

Message topic:"kafka_investment_recharge" 	partition:0 	offset:4576	value:{"uid":1411020,"tid":"e0889650935fa82f3df54f72fae3033c","money":4000000,"pay_time":1559269991,"invest_id":37047,"charge_type":2}	err=<nil>

Message topic:"kafka_investment_recharge" 	partition:0 	offset:4576	value:{"uid":1411020,"tid":"e0889650935fa82f3df54f72fae3033c","money":4000000,"pay_time":1559269991,"invest_id":37047,"charge_type":2}	err=<nil>

##### Problem Description

message Repeat consumption;

Previously using this library, "github.com/bsm/sarama-cluster"
often in the system upgrade, repeated consumption, it is a headache;
and later directly use the latest version of the current library, 
the system has two AB test used at the same time. 
Currently sdk, there is still repeated consumption, where is the problem?

**Comment by cafra** [comment]
The following is my packaged code

```
func NewConsumer2(brokers, topics, group_id string, handler CommonHandler) {
	// Init config, specify appropriate version
	config := sarama.NewConfig()
	config.Version = sarama.V0_10_2_0
	config.Consumer.Return.Errors = true
	config.Consumer.Offsets.Initial = sarama.OffsetOldest

	// Start with a client
	brokersList := strings.Split(brokers, ",")
	client, err := sarama.NewClient(brokersList, config)
	if err != nil {
		panic(err)
	}
	// gorputine 退出时，关闭客户端
	defer func() { _ = client.Close() }()

	// Start a new consumer group
	group, err := sarama.NewConsumerGroupFromClient(group_id, client)
	if err != nil {
		panic(err)
	}
	defer func() { _ = group.Close() }()

	// Track errors
	go func() {
		for err := range group.Errors() {
			fmt.Println("KAFKA |group Errors=", err)
		}
	}()

	// Iterate over consumer sessions.
	ctx := context.Background()
	topicsList := strings.Split(topics, ",")

	for {
		err := group.Consume(ctx, topicsList,
			exampleConsumerGroupHandler{
				handler: handler,
			})
		if err != nil {
			fmt.Println("KAFKA |Consume err=", err)
		}
	}

	return
}
```

**Comment by cafra** [comment]
this is  my github address:
https://github.com/cafra/utils/blob/dev/mq/kafka/consumer2.go

**Comment by cheesedosa** [comment]
I am guessing you are exiting/crashing before offsets are getting committed to Kafka. `sess.MarkMessage(msg)` does not commit offsets immediately to the broker. The offsets are committed in a background thread which can be configured using `Config.Consumer.Offsets.CommitInterval` (default is `1s`). I would recommend handling `SIGTERM` and breaking out of the `Consume` loop to exit the app instead of killing ungracefully. This will ensure that offsets are committed to the broker.

**Comment by cafra** [comment]
Ok, I will handle this and see if it will appear again. Thank you

**Comment by d1egoaz** [comment]
@cafra lets us know if that solved the problem.
I'm going to close the issue, feel free to re-open it if still have problems.
