### ISSUE TITLE
The version of API is not supported , and how can I monitor consumer lag 

### ISSUE THREAD

**Issue by sunjiansen** [Shopify/sarama#1390]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.16.0
Kafka Version: 0.11.0.2
Go Version:1.12

##### Configuration

default config

##### Problem Description
Information can be seen through the script provided by kafka。
![image](https://user-images.githubusercontent.com/41364558/58868831-b6947880-86ef-11e9-8b62-fca7bded6f27.png)

I want to use sarama to monitor the consumption delay of the consumer group. The process is as follows:
 Find all topic and consumer groups, view them one by one, the current offset and lag of each consumer group
**instance.Conn is sarama.Client and is connect to localhost:9092**
`// getConsumerGroupLags 
func (exporter *Exporter) getConsumerGroupLags(instance Instance) (err error) {
	topics, err := instance.Conn.Topics()
	if nil != err {
		log.Errorf("[Kafka][Topic] List topics failed. err: %s", err.Error())
	}
	log.Infof("[Kafka][%s] topics: %+v", instance.Name, topics)

	for _, topic := range topics {
		partitions, err := instance.Conn.Partitions(topic)
		if nil != err {
			log.Errorf("[Kafka][%s] Get topic partitions failed. topic: %s, err: %s", instance.Name, topic, err.Error())
			return err
		}
		log.Infof("[Kafka][%s] topic: %s, partitions: %+v", instance.Name, topic, partitions)
		fmt.Println(topic)
		if topic == "__consumer_offsets" {
			continue
		}
		for _, partition := range partitions {
			newestOffset, err := instance.Conn.GetOffset(topic, partition, sarama.OffsetNewest)
			if nil != err {
				log.Errorf("[Kafka][%s] Get newest offset failed. topic: %s, err: %s", instance.Name, topic, err.Error())
				return err
			}
			log.Infof("[Kafka][%s] topic: %s, newest offset: %+v", instance.Name, topic, newestOffset)
			broker, err := instance.Conn.Leader(topic, partition)
			if nil != err {
				log.Errorf("[Kafka][%s] Get leader broker failed. topic: %s, partition: %d, err: %s", instance.Name, topic, partition, err.Error())
				return err
			}
			log.Infof("[Kafka][%s] topic: %s, partition: %d, broker: %+v", instance.Name, topic, partition, broker)
			lgr, err := broker.ListGroups(&sarama.ListGroupsRequest{})
			if nil != err {
				log.Errorf("[Kafka][%s] List consumer groups failed. err: %s", instance.Name, err.Error())
				return err
			}
			log.Infof("[Kafka][%s] consumer groups: %+v", instance.Name, lgr.Groups)
		}
	}
	return nil
}
`
but when the code run listgroups it make a error .
![image](https://user-images.githubusercontent.com/41364558/58868595-3bcb5d80-86ef-11e9-80d6-e21da499bf6f.png)
Besides, how should I get this Lag?

**Comment by varun06** [comment]
To get the consumer lag, you can do something with sarama consumer group api

```
for msg := range claim.Messages() {
		lag := claim.HighWaterMarkOffset() - msg.Offset)
}
```

**Comment by sunjiansen** [comment]
Thank you very much, yes, I know this way of spending, but I want to be an exporter to lag monitor my existing consumption group and topic.

**Comment by weeco** [comment]
@sunjiansen https://github.com/cloudworkz/kafka-minion :-). It's also using sarama.
