### ISSUE TITLE
wrong token id using kerberos authentication

### ISSUE THREAD

**Issue by filedesless** [Shopify/sarama#1400]
##### Versions

Sarama Version: cd910a683f9faa57222e5120d17b60d2e65f7fa9
Kafka Version: unknown
Go Version: go version go1.11.6 linux/amd64

##### Configuration

Trying to authenticate via keytab to our Active Directory

I disabled FAST negotiation as suggested https://github.com/jcmturner/gokrb5

```
// from kerberos_client.go
//client = krb5client.NewClientWithKeytab(config.Username, config.Realm, kt, cfg)
client = krb5client.NewClientWithKeytab(config.Username, config.Realm, kt, cfg, krb5client.DisablePAFXFAST(true))
```

##### Logs

```
2019-06-12T16:23:35.656-0400	INFO	kafka/log.go:53	client/metadata fetching metadata for [<TOPIC>] from broker <BROKER>
...
2019-06-12T16:23:35.692-0400	INFO	kafka/log.go:53	Error while performing GSSAPI Kerberos Authentication: wrong Token ID. Expected 0504, was 6030
...
2019-06-12T16:23:35.727-0400	INFO	kafka/log.go:53	client/metadata got error from broker -1 while fetching metadata: wrong Token ID. Expected 0504, was 6030
```

##### Problem Description

Can't seem to connect to kafka broker using kerberos auth

**Comment by rubenvp8510** [comment]
It could be the encryption type you are using. 

Please see my comments on the original PR: https://github.com/Shopify/sarama/pull/1366

It that works for you we can close this.

Thanks

**Comment by d1egoaz** [comment]
@rubenvp8510 wondering if we could add some documentation regarding the kerberos support in order to tell what is and what's not supported (like rc4-hmac according the the mentioned PR)

**Comment by rubenvp8510** [comment]
@d1egoaz That definitely could help!
