### ISSUE TITLE
require in go.mod github.com/DataDog/zstd v1.3.6-0.20190409195224-796139022798 does not exist 

### ISSUE THREAD

**Issue by zhaoying818** [Shopify/sarama#1401]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.22.1
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
https://github.com/DataDog/zstd/tags
![image](https://user-images.githubusercontent.com/7424997/59399902-3db8af00-8dc8-11e9-8bb3-f3a28e70d503.png)

**Comment by d1egoaz** [comment]
Thanks for reporting @zhaoying818
