### ISSUE TITLE
ConsumerGroup Testing

### ISSUE THREAD

**Issue by damiannolan** [Shopify/sarama#1403]
Hi Guys,

Loving the sarama Library!
Looking for some information on unit testing the sarama ConsumerGroup.
Any help or direction would be greatly appreciated! 

Thanks

**Comment by varun06** [comment]
Hey,

What do you mean by unit testing sarama ConsumerGroup. Sarama already does that. Need more information to answer this question.

**Comment by damiannolan** [comment]
Sorry, I should rather phrase this as - I am looking for information on how to test a ConsumerGroup implementation - For example: what is the best way to go about testing the consumergroup implementation in the sarama examples directory?

**Comment by pgarneau** [comment]
Update on this? Looking to do the same

**Comment by damiannolan** [comment]
I ended up creating a mock struct which implemented the ConsumerGroupClaim interface and pre-populating the messages read chan with test data if that helps. As far as I remember it ended up being a lot of test code for what I was doing.

Maybe using testify/mock pkg could help but I am yet to experiment with it, if anyone could share a best practice for this I'd be grateful :)

**Comment by Krithika3** [comment]
@damiannolan : I would like to do the same, could you post a sample snippet of how you did this so it could help the community. Thanks a bunch

**Comment by rickwang7712** [comment]
Hi, 
I copied the code of `ExampleConsumerGroup`  from consumer_group_test.go , and tried to feed the broker address from `NewMockBroker` to `NewClient`. Unfortunately, it ends up to timeout panic. Looks like the consumer group cannot fetch from the MockBroker?
