### ISSUE TITLE
Panic on close in sarama consumer group error channel

### ISSUE THREAD

**Issue by ganesh-karthick** [Shopify/sarama#1405]
##### Versions

Sarama Version: v1.22.1
Kafka Version: 1.1 
Go Version: 1.11.4

##### Configuration

```Go
	defaultConfig := sarama.NewConfig()
	defaultConfig.Consumer.Return.Errors = true
	defaultConfig.Version = sarama.V1_1_0_0
	defaultConfig.Consumer.Offsets.Initial = sarama.OffsetNewest
	defaultConfig.Producer.Partitioner = sarama.NewRandomPartitioner
	defaultConfig.Producer.RequiredAcks = sarama.WaitForLocal
	defaultConfig.Producer.Return.Successes = true
	defaultConfig.Producer.Retry.Max = 2
```
Kafka configuration is default values with a single broker and single zookeeper instance

##### Logs

```log
panic: send on closed channel

goroutine 1181 [running]:
github3.internal.com/cg/vendor/github.com/Shopify/sarama.(*consumerGroup).handleError(0xc003ae1960, 0x18dcec0, 0xc0044e2b70, 0xc003ae8630, 0x2d, 0x0)
	/home/jenkins/workspace/robot-builds/pipeline/pipeline-develop-build/src/github3.internal.com/cg/vendor/github.com/Shopify/sarama/consumer_group.go:414 +0x13d
github3.internal.com/cg/vendor/github.com/Shopify/sarama.newConsumerGroupClaim.func1(0x1920d20, 0xc003aae280, 0xc003b38400, 0xc003ae8630, 0x2d, 0x0)
	/home/jenkins/workspace/robot-builds/pipeline/pipeline-develop-build/src/github3.internal.com/cg/vendor/github.com/Shopify/sarama/consumer_group.go:774 +0x96
created by github3.internal.com/cg/vendor/github.com/Shopify/sarama.newConsumerGroupClaim
	/home/jenkins/workspace/robot-builds/pipeline/pipeline-develop-build/src/github3.internal.com/cg/vendor/github.com/Shopify/sarama/consumer_group.go:772 +0x10d
```

##### Problem Description

- Start a consumer group using new [high level consumer group api
](https://godoc.org/github.com/Shopify/sarama#NewConsumerGroup)
- Restart kafka broker
- [consume](https://github.com/Shopify/sarama/blob/master/examples/consumergroup/main.go#L84) exits eventually because of restart
- The above crash was observed panic send on closed error channel
- The crash is not consistent. It could be race condition in [handleError](https://github.com/Shopify/sarama/blob/master/consumer_group.go#L397) method .

**Comment by varun06** [comment]
Hmm, interesting, you mention that it is not consistent, how often you are able to reproduce it?

**Comment by ganesh-karthick** [comment]
Once , but its been only a week when we switched to new sarama lib , so odds so far are 1 in 7.

**Comment by varun06** [comment]
How's it doing now @ganesh-karthick ?

**Comment by d1egoaz** [comment]
is this still a problem @ganesh-karthick ?
