### ISSUE TITLE
occur ErrNotCoordinatorForConsumer when consume start

### ISSUE THREAD

**Issue by chacha923** [Shopify/sarama#1413]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.22.1
Kafka Version: 1.1.1
Go Version:1.12

##### Configuration
config := sarama.NewConfig()
config.ClientID = kc.clientId
config.Consumer.Offsets.Initial = sarama.OffsetNewest
config.Consumer.Fetch.Default = 8388608 //8M
config.Consumer.Fetch.Min = 8388608     //8M
config.Consumer.Return.Errors = true
config.Consumer.Group.Heartbeat.Interval = 10 * time.Second
config.Consumer.Group.Session.Timeout = 30 * time.Second
config.Version = sarama.V1_1_1_0

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
hi, when I start run a consumer,  it usually return an error:  kafka server: Request was for a consumer group that is not coordinated by this broker.  retry is also not use. 

it happens when i use sarama.NewConsumerFromClient() to consume specified partition as well as use sarama.NewConsumerGroupFromClient() to creates a new consumer group

**Comment by varun06** [comment]
Can you please post the code snippet where you doing that too?
