### ISSUE TITLE
Empty (nil) message pointers are received from 'Errors' and 'Successes' channels.

### ISSUE THREAD

**Issue by wb-waldemar** [Shopify/sarama#1421]
##### Versions
Sarama Version: latest for now (2019-07-04).
Kafka Version: 2.12-2.1.0.
Go Version: go1.12.5 linux/amd64.

##### Configuration
```
func createTestSaramaConfig() *sarama.Config {

	var config *sarama.Config

	config = sarama.NewConfig()

	config.ClientID = SaramaClientId
	config.ChannelBufferSize = 512
	config.Version = sarama.V2_0_0_0

	config.Producer.RequiredAcks = sarama.WaitForLocal
	config.Producer.Retry.Max = 5
	config.Producer.Return.Successes = true
	config.Producer.Return.Errors = true
	config.Producer.Flush.Messages = 128

	return config
}
```
##### Logs
none

##### Problem Description
After the sarama.AsyncProducer is closed by the 'Close' Method, i read the 'Errors' and 'Successes' Channels and recieve empty (nil, nulled) pointers from both those channels. That is weird.
If I close the AsyncProducer by the 'AsyncClose' Method, this bug does not happen.

In Go language it is common to close the channel or send nothing instead of sending garbage into channel.

The GoDoc and GitHub's documentation says nothing about nil pointers returned.

Is that a normal behaviour or is it a bug-o-feature ?

Thank you.

P. S.

The source code says following about these two channels:
```
// Successes is the success output channel back to the user when Return.Successes is
// enabled. If Return.Successes is true, you MUST read from this channel or the
// Producer will deadlock. It is suggested that you send and read messages
// together in a single select statement.
Successes() <-chan *ProducerMessage

// Errors is the error output channel back to the user. You MUST read from this
// channel or the Producer will deadlock when the channel is full. Alternatively,
// you can set Producer.Return.Errors in your config to false, which prevents
// errors to be returned.
Errors() <-chan *ProducerError
```
Both 'MUST' words  are Upper-Cased, so I am doing as they say.

**Comment by cheesedosa** [comment]
That is the correct behaviour. 
A closed channel will return the default value (zero value) for the type it holds after it has been closed. The zero value for a pointer in Go is `nil`.
You should use the receive/2 syntax which also returns a `false (bool)` after the channel has been closed. 
```go
msg, ok := <-Successes()
``` 
Sending is not allowed on a closed channel but there may be messages still buffered in the channel that may need to be consumed. Once you have received all messages, you will start receiving infinite `false` from the closed channel. You should break out of your receiving loop after receiving `false` from both `Successes` and `Errors`.

**Comment by wb-waldemar** [comment]
cheesedosa, thank you. I have forgotten about that fact.
I will try reading the channels using the 'range' form in the finalization stage.
