### ISSUE TITLE
How to create Partitioner, which is equals to Java Kafka client Partitioner?

### ISSUE THREAD

**Issue by Hixon10** [Shopify/sarama#1424]
Java kafka client uses `murmur2` <a href="https://github.com/apache/kafka/blob/2.3/clients/src/main/java/org/apache/kafka/common/utils/Utils.java#L394">hash algorithm</a>. sarama's hash function is not equals to this one. 

Can we add `murmur2` implementation to sarama? For example, there is this such port of algorithm - https://stackoverflow.com/q/48582589/1756750

**Comment by FrancoisPoinsot** [comment]
Just pointing a reference from the same dude, he actually made a partionner available for everyone:
https://github.com/burdiyan/kafkautil/blob/master/partitioner.go

To use it, just import and add
`Config.Producer.Partitioner = NewJVMCompatiblePartitioner`

But yes, that would be nice if it were part of sarama directly.
