### ISSUE TITLE
Multiple calls to ConsumerGroup.Consume

### ISSUE THREAD

**Issue by jmwri** [Shopify/sarama#1426]
##### Versions

Sarama Version: 1.22.1
Kafka Version:
Go Version: 1.12.1

Is it possible to call `ConsumerGroup.Consume` more than once on the same consumer group?
Ideally I would like to create a single consumer group, and rather than using a single consumer to consume from multiple topics, I would like to call `Consume` for each topic.

I tried this but it seems to only consume for the first call.

After that, I tried creating multiple consumer groups with the same name but then the claims seemed to be split per consumer group, even though I was using them for different topics.

Any more info would be great, thanks!

**Comment by jmwri** [comment]
To give more context on what I am trying to achieve, I have 2 topics: `account.create`, `account.rename`.

I have 1 consumer group: `account.manager`.

There are 2 consumers each with the same consumer group assigned to each topic.

I have gotten around the issue for the time being by using a separate consumer group for each consumer, i.e. `account.manager.create`, `account.manager.rename`.

Is this how the library is intended to be used?

**Comment by varun06** [comment]
If I am understanding your question correctly, you should be able to do it.
If you look at consumer group api here -> https://godoc.org/github.com/Shopify/sarama#ConsumerGroup

You pass a `[]string` as topics to consume method.
`Consume(ctx context.Context, topics []string, handler ConsumerGroupHandler) error`

in your case it will be `err := Consume(ctx, []string{account.create, account.rename}, handler)`

Let me know if that doesn't work

**Comment by jmwri** [comment]
Hi @varun06, your snippet does work but I am doing the following.

```
group := &ConsumerGroup{}
createHandler := &CreateHandler{}
renameHandler := &RenameHandler{}
err := Consume(ctx, []string{account.create}, createHandler)
err := Consume(ctx, []string{account.rename}, renameHandler)
```

In the meantime I have implemented as your suggestion.

**Comment by d1egoaz** [comment]
@jmwri you can also have a single handler, and in the handler, check the message's topic and route the message to the right routine.

I'm going to close this issue as it seems you already have a solution. Feel free to re-open it.
