### ISSUE TITLE
Health check with sarama.AsyncProducer?

### ISSUE THREAD

**Issue by Zaazik** [Shopify/sarama#1436]
##### Versions

Sarama Version: 1.22.1
Kafka Version: 1.1.1
Go Version:1.12

##### Problem Description
Hello, how we can make health check with sarama.AsyncProducer?

**Comment by Zaazik** [comment]
Resolve that using `sarama.NewAsyncProducerFromClient(saramaClient)`:
`
saramaClient, err := sarama.NewClient(config.Brokers, saramaCfg)
if err!=nil{
	return nil, err
}

saramaProducer, err := sarama.NewAsyncProducerFromClient(saramaClient)
if err != nil {
	return nil, errors.WithStack(err)
}
`
Attach client to internal struct:
`
type Producer struct {
	client sarama.Client
}
` 
And create method `IsHealthy1`
`
func (p *Producer) IsHealthy() bool {
	return len(p.client.Brokers()) > 0
}
`

**Comment by d1egoaz** [comment]
Hey @Zaazik  it seems you found an answer for this, can this issue be closed?

**Comment by d1egoaz** [comment]
seems it's already resolved, feel free to re-open the issue if need more help.
