### ISSUE TITLE
How to control consume speed?

### ISSUE THREAD

**Issue by hoobean1996** [Shopify/sarama#1440]
Thx for sarama team. 
##### Versions
Sarama Version:	github.com/Shopify/sarama v1.23.1
Kafka Version: 0.10.0
Go Version: 1.12

##### Problem Description
I'm using the sarama#ConsumerGroup to consume the Kafka under the pattern 
```go
for msg := range claims.Messages() {
   Publish(msg)
}
```
My question is that how can I control the messages polling speed? 
I've tried 
```go
for {
  for range ticker.C {
    msg := <- claim.Messages()
    Publish(msg)
  }
}
```
But in this way, it seems like the rebalance would be working strangely. 
Could you please give me some ideas? thx

**Comment by d1egoaz** [comment]
Could you please expand more about the rebalance problem?

is the initial problem, that you're consuming too fast and want to consume at a lower speed?

**Comment by eaglexiang** [comment]
Yes we have the same question, we need to consume at a low speed, unlimited msgs in would cause performance problems in our system.
