### ISSUE TITLE
consumer just receives first message after that it stops

### ISSUE THREAD

**Issue by belwalkar** [Shopify/sarama#1444]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

I have producer and consumer. I periodically  put message on producer input channel. but consumer receives only first message after that it doesnt get any messages. but producer dosent give any error.
This creates producer
``` go
func (s *Server) kafkaInit() {
        fmt.Println("Starting kafka init to Connect to broker: ")
        config := sarama.NewConfig()
        config.Producer.RequiredAcks = sarama.WaitForAll
        config.Producer.Retry.Max = 10
        config.Producer.Return.Successes = true
        producer, err := sarama.NewAsyncProducer([]string{"cord-kafka.default.svc.cluster.local:9092"}, config)
        if err != nil {
                panic(err)
        }
        s.dataproducer = producer
}
```
periodically pushing messages on producer
``` go
func (s *Server) collect_data(ip_address string) {
        freqchan := s.devicemap[ip_address].freqchan
        ticker := s.devicemap[ip_address].datacollector.getdata
        donechan := s.devicemap[ip_address].datacollector.quit
        for {
                select {
                case freq := <-freqchan:
                        ticker.Stop()
                        ticker = *time.NewTicker(time.Duration(freq) * time.Second)
                case <-ticker.C:
                        for _, service := range redfish_services {
                                rtn, data := get_status(ip_address, service)
                                if rtn {
                                        for _, str := range data {
                                                str = "Device IP: " + ip_address + " " + str
                                                fmt.Println("collected data  %s ...", str)
                                                b := []byte(str)
                                                msg := &sarama.ProducerMessage{Topic: importerTopic, Value: sarama.StringEncoder(b)}
                                                 s.dataproducer.Input() <- msg                                  }
                                }
                        }
                case <-donechan:
                        ticker.Stop()
                        fmt.Println("getdata ticker stopped")
                        return
                }
        }
}
```

**Comment by FrancoisPoinsot** [comment]
You have specified `config.Producer.Return.Successes = true` in the config but created an async producer.
Basically the producer tries to output the result of the operation in a finite channel that no one reads.
When that happen, there is no error. The producer just get "stuck".

So either 
- create a syncProducer, the success channel is read by the producer to be wait on success/failure to ensure being "sync"
- read the success channel your self. You can use that to log what happen
- set `return.Success` to false

**Comment by FrancoisPoinsot** [comment]
Although it could be wrong, it s bit hard to guess the problem from here.
You should checkout if the problem come from the consumer or the producer.
Try to consume the topic with a cli like kafkacat or kafka-console-consumer.sh and check if the messages you are supposed to consume are actually here.

**Comment by d1egoaz** [comment]
@belwalkar please let us know if @FrancoisPoinsot answer helped you with the problem

**Comment by belwalkar** [comment]
yes it did thank you very much

**Comment by belwalkar** [comment]
Thank you very much

Dinesh
