### ISSUE TITLE
In istio Mixer adapter always return "dial tcp 141.8.225.31:9092: connect: connection refused" when " producer, err := sarama.NewSyncProducer([]string{"xxx.xxx.131.133:9092"}, config)"

### ISSUE THREAD

**Issue by fredyu** [Shopify/sarama#1447]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:

Kafka Version:
kafka_2.12-2.3.0
Go Version:
go1.12.7 linux/amd64
##### Configuration

What configuration values are you using for Sarama and Kafka?
default configure 
##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

In istio Mixer adapter always return "dial tcp 141.8.225.31:9092: connect: connection refused" 
when connect with  " producer, err := sarama.NewSyncProducer([]string{"xxx.xxx.131.133:9092"}, config)"

Thanks

**Comment by fredyu** [comment]
My adapter's handler as following:

// HandleMetric records metric entries
func (s *MyGrpcAdapter) HandleMetric(ctx context.Context, r *metric.HandleMetricRequest) (*v1beta1.ReportResult, error) {

	log.Infof("received request %v\n", *r)
	var b bytes.Buffer
	cfg := &config.Params{}

	if r.AdapterConfig != nil {
		if err := cfg.Unmarshal(r.AdapterConfig.Value); err != nil {
			log.Errorf("error unmarshalling adapter config: %v", err)
			return nil, err
		}
	}

	b.WriteString(fmt.Sprintf("HandleMetric invoked with:\n  Adapter config: %s\n  Instances: %s\n",
		cfg.String(), instances(r.Instances)))

	if cfg.FilePath == "" {
		fmt.Println(b.String())
	} else {
		_, err := os.OpenFile("out.txt", os.O_RDONLY|os.O_CREATE, 0666)
		if err != nil {
			log.Errorf("error creating file: %v", err)
		}
		f, err := os.OpenFile(cfg.FilePath, os.O_APPEND|os.O_WRONLY, 0600)
		if err != nil {
			log.Errorf("error opening file for append: %v", err)
		}

		defer f.Close()

		log.Infof("writing instances to file %s", f.Name())
		if _, err = f.Write(b.Bytes()); err != nil {
			log.Errorf("error writing to file: %v", err)
		}
/*added to send received message to IP:PORT
    		conn, err := net.Dial("tcp", "192.168.131.133:1208")
   		if err != nil {
        		fmt.Printf("Fail to connect, %s\n", err)
    		}

    		defer conn.Close()
       		conn.Write([]byte(b.Bytes()))
send it to kafka topic */
        config := sarama.NewConfig()
        config.Producer.Return.Successes = true
        config.Producer.RequiredAcks = sarama.WaitForAll
        config.Producer.Partitioner = sarama.NewRandomPartitioner

        producer, err := sarama.NewSyncProducer([]string{"192.168.131.133:9092"}, config)

        if err != nil {
                panic(err)
        }
        defer producer.Close()

        msg := &sarama.ProducerMessage{
                Topic:     "testGo",
                Partition: int32(-1),
                Key:       sarama.StringEncoder("key"),
        }

**Comment by fredyu** [comment]
Hello Sir,
Any update on this issue?
Thanks.

**Comment by d1egoaz** [comment]
are you sure you can talk to kafka?
try using kafkacat to see if this is not an environment issue.
Example to get cluster metadata:
`kafkacat -L -b 192.168.131.133:9092`

**Comment by fredyu** [comment]
kafka is ok 👍 
Metadata for all topics (from broker -1: 192.168.131.133:9092/bootstrap):
 1 brokers:
  broker 0 at master-node:9092
 1 topics:
  topic "testGo" with 1 partitions:
    partition 0, leader 0, replicas: 0, isrs: 0

**Comment by fredyu** [comment]
The point is why I try to connect kafka with 192.168.131.133:9092, but  it returns connect to 141.8.225.31:9092 failed as following:

Send Message Fail: %s dial tcp 141.8.225.31:9092: connect: connection refused

Thanks.

**Comment by fredyu** [comment]
BTW,  this Go script is running in a Docker.
Thanks

**Comment by fredyu** [comment]
In that Docker vm,  I can ping and access to 192.168.131.133:9092 .
Thansk

**Comment by fredyu** [comment]
Seems In Docker vm, any external host name  point to 141.8.225.31 through nslookup.

**Comment by fredyu** [comment]
Is it possible config  sarama.NewSyncProducer treat "192.168.131.133"  as a real IP not to call the low level's api (somethings like nslookup) ?.  Since I have test that net.Dial("tcp", "192.168.131.133:9092") works well in same Docker.

Thank,
