### ISSUE TITLE
RFC:  Make Client accessible from ClusterAdmin

### ISSUE THREAD

**Issue by chasewalden** [Shopify/sarama#1448]
The `Client` should be accessible from `ClusterAdmin`. 

The `ClusterAdmin` interface should either expose a `Client() *Client` function or the ClusterAdmin should compose the Client interface. A third option would be create a `NewClusterAdminFromClient(client *Client) (*ClusterAdmin, error)` function which would allow the user to reuse the existing Client 

I have written an application that requires me to get all topics from the cluster and differentiate internal from "normal" topics. 95% of all my needs are filled by the `Client`, but getting Topic Metadata is only accomplished by the `ClusterAdmin`. It doesn't make a ton of sense for me to open two clients: one that I can use and the internal one opened by the `ClusterAdmin`.

**Comment by varun06** [comment]
Does this work for you -> https://github.com/Shopify/sarama/pull/1415 ?

**Comment by chasewalden** [comment]
Looks Good!

Thanks, I’ll pull latest now.
