### ISSUE TITLE
The ListAcls method does not return the AclResourcePatternType field

### ISSUE THREAD

**Issue by symaras** [Shopify/sarama#1451]
##### Versions
Sarama Version: 1.23.0
Kafka Version: 2.1.0
Go Version: 1.11.1

##### Problem Description
The ListAcls method of the ClusterAdmin interface does not consider the version of the config. Thus, it creates a DescribeAclsRequest struct with no version defined and this defaults to V0_11_0_0, which in turn causes the method to not return the AclResourcePatternType field.

**Comment by varun06** [comment]
Hey @symaras 

would you please do a PR for the change?

**Comment by symaras** [comment]
Hi @varun06, here it is: https://github.com/Shopify/sarama/pull/1452

**Comment by symaras** [comment]
PR merged, closing issue.
