### ISSUE TITLE
Hi, all. Dose the producer cannot reconnect to the broker after the broker killed and restart?  I config only one broker.

### ISSUE THREAD

**Issue by Drewryz** [Shopify/sarama#1463]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: V0_10_2_0
Kafka Version: 2.11
Go Version: 1.11

##### Configuration

What configuration values are you using for Sarama and Kafka?
{
		"kafka_host":        "10.179.40.145:9092",
		"kafka_topic":       "test",
		"kafka_client_id":   "localhost",
		"kafka_retry_max":   "3",
		"kafka_compression": "lz4",
		"kafka_timeout":     "30s",
		"kafka_keep_alive":  "0",
		"max_message_bytes": "4194304",
}
##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.
[Sarama] 2019/08/19 18:33:00 client/metadata no available broker to send metadata request to
[Sarama] 2019/08/19 18:33:00 client/brokers resurrecting 0 dead seed brokers
[Sarama] 2019/08/19 18:33:00 client/metadata retrying after 750ms... (3 attempts remaining)
[Sarama] 2019/08/19 18:33:01 client/metadata no available broker to send metadata request to
[Sarama] 2019/08/19 18:33:01 client/brokers resurrecting 0 dead seed brokers
[Sarama] 2019/08/19 18:33:01 client/metadata retrying after 750ms... (2 attempts remaining)
[Sarama] 2019/08/19 18:33:02 client/metadata no available broker to send metadata request to
[Sarama] 2019/08/19 18:33:02 client/brokers resurrecting 0 dead seed brokers
[Sarama] 2019/08/19 18:33:02 client/metadata retrying after 750ms... (1 attempts remaining)
[Sarama] 2019/08/19 18:33:02 client/metadata no available broker to send metadata request to
[Sarama] 2019/08/19 18:33:02 client/brokers resurrecting 0 dead seed brokers

##### Problem Description

The producer could connect to kafka broker at first. After I kill the broker and restart the broker, the producer could not reconnect to the broker. The saram log is printed after I kill the broker.

**Comment by d1egoaz** [comment]
are you sure you can talk to kafka?
try using `kafkacat` to see if this is not an environment issue.
Example to get cluster metadata: 
`kafkacat -L -b 10.179.40.145:9092`

**Comment by Drewryz** [comment]
> are you sure you can talk to kafka?
> try using `kafkacat` to see if this is not an environment issue.
> Example to get cluster metadata:
> `kafkacat -L -b 10.179.40.145:9092`

Thanks for your reply. The producer could connect to kafka broker at first. After I kill the broker and restart the broker, the producer could not reconnect to the broker. The saram log is printed after I kill the broker.
