### ISSUE TITLE
Message not consumed from command line when produced from Sarama Client

### ISSUE THREAD

**Issue by bcashier** [Shopify/sarama#1475]
Hi,

When I produce messages from Go code and consume it from Go code aswell, it works fine.

But when I try to consume the message from command line:
`
bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic testTopic --from-beginning
`

Nothing received ! Noting that when I try this, I disable first consuming from Go code.

Message is produced using this code:
```

producer := createProducer()
stringtest := "test"

producer.Input() <- &sarama.ProducerMessage{
	Topic: "testTopic",
	Value: sarama.StringEncoder(stringtest),
}

func createProducer() sarama.AsyncProducer {
	config := sarama.NewConfig()
	config.Producer.Return.Successes = false
	config.Producer.Return.Errors = true
	config.Producer.RequiredAcks = sarama.WaitForAll
	producer, err := sarama.NewAsyncProducer([]string{"127.0.0.1:9092"}, config)
	if err != nil {
		log.Fatal("Unable to connect producer to kafka server")
	}
	return producer
}
```

What is the problem please ? What I did wrong ?

Thank you in advance.

**Comment by FrancoisPoinsot** [comment]
You have created an asynProducer.
The application is closing before the producer has time to produce the message.
Call `producer.Close()` just before the application end will solve this problem.

**Comment by bcashier** [comment]
@FrancoisPoinsot Thank you for your answer.

The application is not closing at all since I am using loop to consume messages and in the same time depend on the command received, I produce the messages.

I can't see where I can put `producer.Close()` since I am using LOOP to listen to a new messages ?
Is there a way to flush messages without closing the producer ? Since it is actively used ?

**Comment by FrancoisPoinsot** [comment]
Ha, I assumed the upper part of the code was the main func.
I don't think there is a way to flush an async producer without closing it. 
But also there should not be a need for that.

The asyncProducer should flush regularly. The default behavior is "flush as-fast-as-possible".

Without more detail on your code or your setup, I cannot help.

Meanwhile here is what I ran locally. It did succesfully produced and read messages, so maybe you will be able to spot a difference.
in console
```
docker run -d -p 2181:2181 -p 3030:3030 -p 8081-8083:8081-8083 \
           -p 9581-9585:9581-9585 -p 9092:9092 -e ADV_HOST=localhost \
           -e RUNNING_SAMPLEDATA=0 landoop/fast-data-dev
```

the code 
```
package main

import (
	"github.com/Shopify/sarama"
	"log"
	"time"
)

func main() {
	for {
		producer := createProducer()
		stringtest := "test"

		producer.Input() <- &sarama.ProducerMessage{
			Topic: "testTopic",
			Value: sarama.StringEncoder(stringtest),
		}
		time.Sleep(1 * time.Second)
	}
}

func createProducer() sarama.AsyncProducer {
	config := sarama.NewConfig()
	config.Producer.Return.Successes = false
	config.Producer.Return.Errors = true
	config.Producer.RequiredAcks = sarama.WaitForAll
	producer, err := sarama.NewAsyncProducer([]string{"127.0.0.1:9092"}, config)
	if err != nil {
		log.Fatal("Unable to connect producer to kafka server")
	}
	return producer
}
```

the consumer
```
kafka-console-consumer --bootstrap-server 127.0.0.1:9092 --topic testTopic --from-beginning
```

**Comment by bcashier** [comment]
This is not working on my case ... I used to switch to rdkafka.

Thanks for your help sir :)
