### ISSUE TITLE
question

### ISSUE THREAD

**Issue by jonyjeffry** [Shopify/sarama#1483]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Problem Description

now, i work on my first golang project, i need to consume kafka message. when i search information for kafka client, i saw sarama may crushed in high concurrency condition. so, i want to konw, this proplem has been resolved or not?

**Comment by varun06** [comment]
What do you mean by high concurrency condition. Can you please elaborate more on your use case?
