### ISSUE TITLE
Question: Messages from consumer group

### ISSUE THREAD

**Issue by el-chen** [Shopify/sarama#1486]
##### Versions
Sarama Version: Latest
Kafka Version: 2.3.0 (Windows)
Go Version: go version go1.12.9 windows/amd64

##### Problem Description

The consumergroup example in the github consumes the messages inside ConsumeClaim function. Is there any way to get claim.Messages()  and write to a channel  so other functions read/enrich the data  from that channel ?  if possible, Can you give a code snippet to show how to do this?

**Comment by d1egoaz** [comment]
You could do something like this:

```go
type SimpleKafkaConsumerGroup struct {
	Messages chan<- *sarama.ConsumerMessage
}

func (SimpleKafkaConsumerGroup) Setup(_ sarama.ConsumerGroupSession) error { return nil }
func (SimpleKafkaConsumerGroup) Cleanup(c sarama.ConsumerGroupSession) error {
	log.Infof("closing kafka consumer %v", c)
	return nil
}
func (c SimpleKafkaConsumerGroup) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	log.Infof("kafka consumer handler created for: %v:%v", claim.Topic(), claim.Partition())
	for m := range claim.Messages() {
		log.Debugf("Received message from %v:%v", claim.Topic(), claim.Partition())
		c.Messages <- m
		sess.MarkMessage(m, "")
	}
	return nil
}

```


then, you can create the `messages` channel that you can use in other functions
like this:

``` go
messages := make(chan *sarama.ConsumerMessage)
handler := kafka.SimpleKafkaConsumerGroup{Messages: messages}
go group.Consume(ctx, topics, handler)


// here, just pass or use directly the `messages` channel
for {
    select {
    case msg := <-messages:
    ...
    }
 }
```

Just need to make sure about when to mark the message as read, in this example
I'm marking the message as read immediately, which could cause some message loss
if the other functions fail to do whatever they are supposed to do

Let us know if this helps
