### ISSUE TITLE
Any way to re-consume the same message on the same consumer when the message is not confirmed?

### ISSUE THREAD

**Issue by 84970000** [Shopify/sarama#1488]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|V0_10_0_0  | 0.10.2.0 | 1.9 |

##### Problem Description
I try to use the sarama.ConsumerGroup to consume message. When I don't confirm a message, the message can't be re-consume from the Message() channel in the same consumer. But after I restart the process, the message can be consumed again. 

My question is that, if there is any way to re-consume the message that not confirmed in the same consumer(without restarting the process)?

**Comment by FrancoisPoinsot** [comment]
You could wrap your process in a loop, exiting only when you confirm the message is processed.
Kafka give you the guarentee that no other consumer will consume this partition so you are free to do whatever you want locally.
