### ISSUE TITLE
Sticky assignor seems not to be working

### ISSUE THREAD

**Issue by grongor** [Shopify/sarama#1493]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| master#2af3badd8c04 | 5.3.1-ccs (Confluent, Kafka version 2.3) | 1.13 |

##### Configuration

Nothing special: newConfig() + clientID + correct KafkaVersion + sticky rebalance strategy

##### Problem Description

When I tried running and killing multiple consumers it seemed like the "sticky" strategy isn't working at all because the partitions were assigned randomly (didn't "stick" to the consumer where they were before).

So I tried to add some debugging code and it seems like the userData isn't persisted in the Kafka cluster - I can see the data encoded correctly after the rebalance, but when the next rebalancing is triggered, there are no userData received in the balance strategy (the byte array is empty).

Do I have wrong Kafka version, missing some config, ... or is something broken? I bet the issue is on my side but after 3 hours of investigating I was not able to find it.

**Comment by skidder** [comment]
Hello @grongor, sorry to hear you're having difficulty using the sticky partition assignor. Have you checked the consumer-group example?
https://github.com/Shopify/sarama/blob/master/examples/consumergroup/main.go

The sticky partition assignor can be enabled by running the consumer group example with the `-assignor sticky` flag. The description for my pull-request to add sticky partition assignor support shows how this works:
https://github.com/Shopify/sarama/pull/1416

**Comment by skidder** [comment]
One more thing, I suggest changing the consumer-group name when altering the partition assignment strategy.
