### ISSUE TITLE
Consumer groups question

### ISSUE THREAD

**Issue by blacktoot** [Shopify/sarama#1505]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Problem Description
Hi guys,
I know how to use single cosumer,but don't know how to use consumer group.I read the consumer group example,but had no answer for me.If a consumer group has more than one consumer,how to control which consumer  to consume the topic partition, is thers any example code? THX

**Comment by FrancoisPoinsot** [comment]
The usual practice is not to control which consumer gets which partition.
By default, they will share partitions nicely between them.

If you want to customize this behavior you can change `Config.Consumer.Rebalance.Strategy`
