### ISSUE TITLE
Let's talk transactions

### ISSUE THREAD

**Issue by FrancoisPoinsot** [Shopify/sarama#1512]
I intend to implement transactions in sarama.

To familiarize myself with the API I just set up a small example in my fork: https://github.com/Shopify/sarama/compare/master...FrancoisPoinsot:transactions
I tried to resolve the dependencies problem using go.mod, so if you want to run it locally I think go v1.13 is a requirement.
There is a makefile to run the broker and consume messages.

This example can already successfully produce committed and uncommitted messages.
You can check using `make read-committed` and `make read-uncommitted` commands.

Of course, the end goal would be to have most of these calls done by the producer internally with a `beginTransaction()`, `commitTransaction()` and `abortTransaction()` method on the producer.

@bai @varun06 , can you confirm I am not in conflict with any current works?
Also, do you have an opinion on how I should proceed?

One problem I see right now: how can AsyncProducer handle a transaction? What would it look like as a library user?

**Comment by varun06** [comment]
I don't think that anyone else is tackling this work yet, glad that you are thinking of doing it. As far as implementation goes, I have been away from kafka from some time, so have to read the spec and figure out what we can do.

**Comment by FrancoisPoinsot** [comment]
I went a bit further: https://github.com/Shopify/sarama/compare/master...FrancoisPoinsot:739694a

For the `AsyncProducer`'s public behavior, I settled for this:
When you ask for the commit, every message sent before should be part of the same transaction.
This makes the AsyncProducer somehow stateful and less concurrent-friendly that the `input` channel would make you expect.
But that is how the Kafka protocol works on low-level either way.


And I definitely have a problem with the asyncProducer.
I tried 2 different ways:
1) send a message on the input channel to end the transaction.
problems:
- the input channel is actually not ordered since it is reused to retry message
- messages processed by the `asyncProducer`'s dispatcher are still being processed by either the `topicProducer` or one of its descendant

2) Make a sync `commit` method that waits on `InFlight` waitGroup
problem:
- there is a delay between "the message is read from `input channel`" and "`inFlight` waitGroup is incremented". So I might commit a txn without all the expected messages

In this compare you see the 2nd method implemented.
With the `SyncProducer` it works fine since it waits on the `expectation` chan of each message.

To make this works, I might have to add a new `AddMessage` method on the AsyncProducer to ensure `InFlight` is incremented before the `input` channel is used.
I would also make this method wait for any ongoing commit/abort to finish
It is a bit less golang-ish but that is basically how the `SyncProducer` works today.


Another obvious solution would be to implement transactions on the `SyncProducer` only.
I just fear that doing so would make it super hard to change after.


The `transaction` example in the linked commit is working.
It is a lot shorter now that most of the transaction logic is internal!
There might be an "coordinator does not exist" error message the first time you run. I am still trying to figure out why this one popped up suddenly.


@varun06 , @bai , Would you prefer I begin a draft PR with this branch?
I am all for quick live feefback.

**Comment by varun06** [comment]
That's great work. At this point, I will definitely like to see the PR, as seeing all this in code will make more sense to me.
