### ISSUE TITLE
Improve implementation of OffsetRequest

### ISSUE THREAD

**Issue by weeco** [Shopify/sarama#1522]
#### Problem Description

`OffsetRequest` and `OffsetResponse` implement the `ListOffsetRequest` from Kafka's Offset API. You can use them to request (in bulk):

- Topic/Partition High + Low Water marks
- Find an index within a partition for a given timestamp

The implementation of this endpoint is suboptimal though:

- File and struct are called `OffsetRequest` instead of `ListOffsetRequest` as opposed to the official client/documentation
- Requests/Response implementation do not really stick to the original which also leads to problems using it. If someone wants to request the high and low watermarks of a single topic/partition, this will not work as the request and response use a map where the `partitionID` is the key. Thus you are forced to make two separate ListOffsetRequests even though you could put them into one

#### My proposal:

For these reasons I'd like to create a new `ListOffsetRequest` as I can not change the current `OffsetRequest` because this would cause breaking changes. Beside the above thing I'll also add:

- Proper documentation for the properties you can set in the request
- Add Version 0, Version 2, Version 3 and Version 4 of this request so that more brokers and more features are supported.

Can I proceed with the idea / would you accept a PR for this?

**Comment by d1egoaz** [comment]
sounds good to me!
Do you have any thoughts on this @bai ?


@weeco might want also to post a more detailed (high level) plan, in order to lets us know what are you planning to modify exactly, to have a picture of what could be changed for the current API (if any current API is changed)

**Comment by weeco** [comment]
I do not plan to modify any of the existing code (except I could add for the current "Offset_request.go" implementation). I intend to only add the "list_offset_request.go". I can not modify the current implementation as this would likely cause breaking changes for people using sarama.

However in sarama v2 one could deprecate the "offset_request.go" and only use the new "list_offset_request.go". The primary difference is that I am going to use an array instead of a map for the request blocks for the explained reasons. This way I also stick to the original java client implementation.

**Comment by weeco** [comment]
@d1egoaz @bai I created a draft PR here: https://github.com/Shopify/sarama/pull/1532

I haven't written the tests yet, nor did I actually test it. I am currently trying to figure out whether this can work at all, because I believe this switch/case is important to figure out what struct is used for decoding incoming responses from Kafka.

Do you have an idea how/whether I can get around this?

**Comment by dnwe** [comment]
> I haven't written the tests yet, nor did I actually test it. I am currently trying to figure out whether this can work at all, because I believe this switch/case is important to figure out what struct is used for decoding incoming responses from Kafka.
> 
> Do you have an idea how/whether I can get around this?

@weeco could you explain what your question is here a little more, I didn't understand

**Comment by weeco** [comment]
@dnwe This issue seeks to improve the implementation of the `OffsetRequest` and it's response. The problem with this is that a proper implementation requires a breaking change (reasons are described in this issue). This could be a problem because users might directly use the OffsetRequest / Response thing since it is exported and not necessarily used internally.

Thus my suggestion was to add a second implementation of the same feature in a proper way. One could choose which request to send. Unfortunately this is a problem when decoding the package, because of this: https://github.com/weeco/sarama/blob/master/request.go#L115-L116

You have to choose which struct is responsible for decoding a package. At this point we can't know whether the response belongs to the "new requestpacket" or to a the "old requestpacket".

Does that make sense? I don't think I can workaround this and this is a breaking change. I can't judge whether this would be accepted without a new major version.

**Comment by dnwe** [comment]
@weeco ah yes thanks, I understand now. I wonder if it's worth doing something like adding a `SaramaApiVersion` field to the configuration struct that defaults to 1 for now (and the current implementation) but if the user sets it to 2 then it uses your improved version. We could use that method elsewhere to stage out breaking api changes before then making the SaramaApiVersion default to 2 when we eventually release Sarama 2.x (and remove or deprecate the old versions)
