### ISSUE TITLE
Method for getting list of all consumer group 

### ISSUE THREAD

**Issue by ut0mt8** [Shopify/sarama#1537]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.24.1 | 2.12-2.2.1 | go1.12.3 linux/amd64  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
```
config.Consumer.Return.Errors = true
config.Version = sarama.V2_1_0_0
```

##### Problem Description

So I'm a bit new with sarama. I try to list all consumer group known by the kafka cluster.
I try something like this : 

```
        kcfg := sarama.NewConfig()
        kcfg.Consumer.Return.Errors = true
        kcfg.Version = sarama.V2_1_0_0

        
        client, err := sarama.NewClient(bks, kcfg)
        if err != nil {
                return nil, fmt.Errorf("cannot connect to broker : %v", err)
        }

        for _, broker := range client.Brokers() {
                if ok, _ := broker.Connected(); !ok {
                        broker.Open(client.Config())
                }
                cresp, err := broker.ListGroups(&sarama.ListGroupsRequest{})
                if err != nil {
                        log.Fatalf("cannot list groups : %v", err)
                }

                for _, group := range cresp.Groups {
                        log.Infof("list group : %s", group)
                }
        }
```

but unfortunately it only print me "consumer", so I guess I'm doing wrong.

**Comment by etc-crontab** [comment]
Hello @ut0mt8,

Is there any reason for you not to use the 'ListConsumerGroups' function of the [ClusterAdmin type](https://godoc.org/github.com/Shopify/sarama#ClusterAdmin)?
Checking the code of this function gives you the answer to your question: "cresp.Groups" returns a map[string]string but you have to read the key to get the consumer group name. The value is the type of the element a "consumer" in this case.
So doing:
```go
                for group, typ := range cresp.Groups {
                        log.Infof("list group : %s of type: %s", group, typ)
                }
````
should work.

**Comment by ut0mt8** [comment]
Hi, I finally found the ClusterAdmin api . Btw my little program want to export lag/offset to prometheus, so if I can avoid the double connexion (one to clusterAdmin, one to normal client) I take.
