### ISSUE TITLE
type *sarama.ProducerError has no field or method Metadata

### ISSUE THREAD

**Issue by bnarang** [Shopify/sarama#1563]
##### Versions

Sarama Version:v1.24.1
Kafka Version:0.9.0.1
Go Version:1.12

##### Configuration

What configuration values are you using for Sarama and Kafka?

```
        config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.Retry.Max = 5
	config.Producer.Return.Successes = true
	config.Producer.Return.Errors = true
```

##### Problem Description

I am calling sarama.AsyncProducer and reading the response over channels. I am passing additional metadata along with value to be sent over topic
```
&sarama.ProducerMessage{
			Topic:    outgoingTopic,
			Value:    sarama.StringEncoder(value),
			Metadata: testMsg}
```
On trying to read metadata from <-producer.Errors(), it says - type *sarama.ProducerError has no field or method MetaData. 

I can access metadata on <-producer.Successes() though

**Comment by genzgd** [comment]
You want to access the ProducerError.Msg property (type *ProducerMessage) that will have your original metadata field.

**Comment by bnarang** [comment]
Thank you

> You want to access the ProducerError.Msg property (type *ProducerMessage) that will have your original metadata field.
