### ISSUE TITLE
Group consumer on 0.9 support question.

### ISSUE THREAD

**Issue by rubenvp8510** [Shopify/sarama#1567]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description
Why the version at least v0.10.2 constrain[1] on consumer group implementation?

IIRC consumer group is implemented since 0.9, I know that is an old version and sarama does not guaranteed compatibility, but my questiobn is, why that hard constrain? Is there any good reason?

1) https://github.com/Shopify/sarama/blob/master/consumer_group.go#L96

**Comment by d1egoaz** [comment]
@rubenvp8510 a similar question was asked here: https://github.com/Shopify/sarama/issues/1363

It might work with previous versions 🤷‍♂
