### ISSUE TITLE
client has run out of available brokers to talk to

### ISSUE THREAD

**Issue by leo-zj** [Shopify/sarama#1568]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

**Comment by elsesiy** [comment]
@leo-zj We're experiencing the same issue, did you find a solution for this?

**Comment by charlielin** [comment]
@leo-zj We're experiencing the same issue, did you find a solution for this?
