### ISSUE TITLE
NewAsyncProducer: Unexpected (unknown?) server error.

### ISSUE THREAD

**Issue by dstruck** [Shopify/sarama#1572]
Using Sarama version 1.25.0 with Kafka version 2.4.0 I get the following error message with the NewAsyncProducer:

"Failed to produce message kafka: Failed to produce message to topic xxx: kafka server: Unexpected (unknown?) server error."

Code used is almost exactly the "AsyncProducer (Select) Broker" example. Previous Sarama version 1.23.0 worked.

Is there a way to get a more explicit error message?

**Comment by dnwe** [comment]
@dstruck as per the GitHub [issue template](https://github.com/Shopify/sarama/blob/master/.github/ISSUE_TEMPLATE.md) if you set the `sarama.Logger` to something you'll capture Sarama's general output with the interactions against the remote broker which may or may not contain more info

e.g.,
```go
	sarama.Logger = log.New(os.Stdout, "[Sarama] ", log.LstdFlags)
```

**Comment by dstruck** [comment]
Unfortunately I cannot replicate the issue in our test setup, it only happens in production.

I turned on logging and got the following message right before the error:

> INFO[0306] kafka: error while consuming xxx/1: kafka: tried to use a client that was closed
> INFO[0306] consumer/xxx/4 finding new broker
> INFO[0306] kafka: error while consuming xxx/4: kafka: tried to use a client that was closed
> INFO[0306] consumer/xxx/2 finding new broker
> INFO[0306] kafka: error while consuming xxx/2: kafka: tried to use a client that was closed
> INFO[0306] consumer/xxx/5 finding new broker
> INFO[0306] kafka: error while consuming xxx/5: kafka: tried to use a client that was closed
> FATA[0306] Failed to produce message kafka: Failed to produce message to topic xxx: kafka server: Unexpected (unknown?) server error.

But I am seeing also the **tried to use a client that was closed** error in the test setup where the producer does not fail.

**Comment by dstruck** [comment]
Found the culprit in the Kafka server log:

> [2020-01-16 10:56:28,164] ERROR [ReplicaManager broker=3] Error processing append operation on partition xxx2-4 (kafka.server.ReplicaManager)
> org.apache.kafka.common.KafkaException: Failed to decompress record stream
>         at org.apache.kafka.common.record.DefaultRecordBatch$StreamRecordIterator.readNext(DefaultRecordBatch.java:619)
>         at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:580)
>         at org.apache.kafka.common.record.DefaultRecordBatch$RecordIterator.next(DefaultRecordBatch.java:549)
>         at org.apache.kafka.common.record.DefaultRecordBatch.iterator(DefaultRecordBatch.java:319)
>         at scala.collection.convert.Wrappers$JIterableWrapper.iterator(Wrappers.scala:55)
>         at scala.collection.IterableLike$$anon$1.iterator(IterableLike.scala:333)
>         at scala.collection.IterableViewLike$Zipped.iterator(IterableViewLike.scala:94)
>         at scala.collection.IterableViewLike$Zipped.iterator$(IterableViewLike.scala:94)
>         at scala.collection.IterableViewLike$$anon$1.iterator(IterableViewLike.scala:112)
>         at scala.collection.IterableViewLike$Transformed.foreach(IterableViewLike.scala:47)
>         at scala.collection.IterableViewLike$Transformed.foreach$(IterableViewLike.scala:47)
>         at scala.collection.IterableViewLike$AbstractTransformed.foreach(IterableViewLike.scala:43)
>         at scala.collection.TraversableViewLike$Filtered.foreach(TraversableViewLike.scala:220)
>         at scala.collection.TraversableViewLike$Filtered.foreach$(TraversableViewLike.scala:219)
>         at scala.collection.IterableViewLike$$anon$8.foreach(IterableViewLike.scala:123)
>         at kafka.log.LogValidator$.$anonfun$validateMessagesAndAssignOffsetsCompressed$1(LogValidator.scala:357)
>         at kafka.log.LogValidator$.$anonfun$validateMessagesAndAssignOffsetsCompressed$1$adapted(LogValidator.scala:345)
>         at scala.collection.Iterator.foreach(Iterator.scala:941)
>         at scala.collection.Iterator.foreach$(Iterator.scala:941)
>         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
>         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
>         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
>         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
>         at kafka.log.LogValidator$.validateMessagesAndAssignOffsetsCompressed(LogValidator.scala:345)
>         at kafka.log.LogValidator$.validateMessagesAndAssignOffsets(LogValidator.scala:79)
>         at kafka.log.Log.liftedTree1$1(Log.scala:1065)
>         at kafka.log.Log.$anonfun$append$2(Log.scala:1050)
>         at kafka.log.Log.maybeHandleIOException(Log.scala:2316)
>         at kafka.log.Log.append(Log.scala:1032)
>         at kafka.log.Log.appendAsLeader(Log.scala:1001)
>         at kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:955)
>         at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
>         at kafka.utils.CoreUtils$.inReadLock(CoreUtils.scala:259)
>         at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:943)
>         at kafka.server.ReplicaManager.$anonfun$appendToLocalLog$4(ReplicaManager.scala:805)
>         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
>         at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
>         at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
>         at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
>         at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
>         at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
>         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
>         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
>         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
>         at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:793)
>         at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:517)
>         at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:577)
>         at kafka.server.KafkaApis.handle(KafkaApis.scala:126)
>         at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:70)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.io.IOException: net.jpountz.lz4.LZ4Exception: Error decoding offset 602471 of input buffer
>         at org.apache.kafka.common.record.KafkaLZ4BlockInputStream.readBlock(KafkaLZ4BlockInputStream.java:195)
>         at org.apache.kafka.common.record.KafkaLZ4BlockInputStream.read(KafkaLZ4BlockInputStream.java:223)
>         at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
>         at org.apache.kafka.common.utils.ByteUtils.readUnsignedVarint(ByteUtils.java:168)
>         at org.apache.kafka.common.utils.ByteUtils.readVarint(ByteUtils.java:203)
>         at org.apache.kafka.common.record.DefaultRecord.readFrom(DefaultRecord.java:296)
>         at org.apache.kafka.common.record.DefaultRecordBatch$2.doReadRecord(DefaultRecordBatch.java:278)
>         at org.apache.kafka.common.record.DefaultRecordBatch$StreamRecordIterator.readNext(DefaultRecordBatch.java:615)
>         ... 49 more
> Caused by: net.jpountz.lz4.LZ4Exception: Error decoding offset 602471 of input buffer
>         at net.jpountz.lz4.LZ4JNISafeDecompressor.decompress(LZ4JNISafeDecompressor.java:38)
>         at org.apache.kafka.common.record.KafkaLZ4BlockInputStream.readBlock(KafkaLZ4BlockInputStream.java:178)
>         ... 56 more

Apparently lz4 is causing problems, switching to snappy compression prevents the error.

Is the "tried to use a client that was closed" error message harmless or should it be investigated further?

**Comment by cafra** [comment]
You can check the Kafka server logs. The problems I encountered, both producers and consumers have this problem: unkown error, and finally found that the version of the consumer is too low.
Because version 0.11+ only supports headers, but consumers are lower than this version.
Note, including the version of producer, broker, consumer

**Comment by cafra** [comment]
> Using Sarama version 1.25.0 with Kafka version 2.4.0 I get the following error message with the NewAsyncProducer:
> 
> "Failed to produce message kafka: Failed to produce message to topic xxx: kafka server: Unexpected (unknown?) server error."
> 
> Code used is almost exactly the "AsyncProducer (Select) Broker" example. Previous Sarama version 1.23.0 worked.
> 
> Is there a way to get a more explicit error message?

You can check the Kafka server logs. The problems I encountered, both producers and consumers have this problem: unkown error, and finally found that the version of the consumer is too low.
Because version 0.11+ only supports headers, but consumers are lower than this version.
Note, including the version of producer, broker, consumer
