### ISSUE TITLE
how to flush data in AsyncProducer

### ISSUE THREAD

**Issue by lonerwolf** [Shopify/sarama#1593]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.26|2.4  |1.13.6  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description
how to flush in async?use close? use asyncclose?or use successes chan and  calculate the count?hava any other way
```go
func main() {
	config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.WaitForLocal
	config.Producer.Partitioner = sarama.NewHashPartitioner
	//config.Producer.Return.Successes = true
	config.Producer.Return.Errors = true
/*	config.Producer.Flush.Messages = 10
	config.Producer.Flush.Frequency = time.Second*/
	config.Producer.Flush.MaxMessages = 10000
	config.Version = sarama.V2_1_0_0

	client,err := sarama.NewAsyncProducer([]string{"192.168.2.201:9092","192.168.2.202:9092","192.168.2.203:9092"},config)
	if err != nil {
		fmt.Println("qqqqqqqqq")
		return
	}
	defer func(){
		fmt.Println("end time:" + time.Now().Format("2006-01-02 15:04:05.111"))
	}()
	defer client.Close()
	go func(p sarama.AsyncProducer) {
		errors := p.Errors()
		//success := p.Successes()
		for {
			select {
			case err := <-errors:
				if err != nil {
					fmt.Println("qz",err,err.Msg.Partition,err.Msg.Topic)
				}
			}
		}
	}(client)

	fmt.Println("start time:" + time.Now().Format("2006-01-02 15:04:05.111"))
	for i := 0; i < 1000; i++{
		msg := &sarama.ProducerMessage{}
		msg.Topic = "test"
		msg.Key = sarama.StringEncoder(strconv.Itoa(i))
		data := make([]byte,256)
		data[0] = 'T'
		data[1] = 'e'
		data[2] = 's'
		data[3] = 't'
		msg.Value = sarama.ByteEncoder(data)
		client.Input() <- msg
	}
	//fmt.Println("end time:" + time.Now().Format("2006-01-02 15:04:05.111"))
	//client.Close()
	fmt.Println("end time:" + time.Now().Format("2006-01-02 15:04:05.111"))
	time.Sleep(time.Second*15)
}
```

**Comment by d1egoaz** [comment]
you can do both,


https://github.com/Shopify/sarama/blob/master/async_producer.go#L21-L31
![image](https://user-images.githubusercontent.com/950087/73465880-0a269700-434f-11ea-9ccc-375c42f83052.png)


`Close` basically calls `AsyncClose` and keeps reading from the successes and errors channel for you, and it return the errors if any

<img src="https://screenshot.click/2020-01-30_10-58-38_tmuqy.png" width="50%" />
