### ISSUE TITLE
How to set offset to a specified value in Initialization 

### ISSUE THREAD

**Issue by blackfox1983** [Shopify/sarama#1610]
value of c.Consumer.Offsets.Initial must be OffsetNewest or OffsetOldest.

But in some cases, I need to comsume message from a specified offset.

i read the code but have not found method to solution my problem.

somebody who knows help me..thanks..

sorry for my poor english :(

**Comment by dnwe** [comment]
@blackfox1983 I think you are looking for this?https://github.com/Shopify/sarama/blob/6fb86a44d5915dcfd42af71a4c99674bb55650ca/consumer.go#L60-L64

**Comment by d1egoaz** [comment]
@blackfox1983 your English is great, don't worry about that.

Regarding the question, one importan thing from @dnwe response, is that this is only supported by the low level consumer and it's not supported by `ConsumerGroups`

**Comment by Jianli-lin** [comment]
Also hope we can support set offset for `ConsumerGroup`

Or we can commit offset manually. (https://github.com/Shopify/sarama/issues/1570)
