### ISSUE TITLE
go get fails: undefined: zstd

### ISSUE THREAD

**Issue by ajbeach2** [Shopify/sarama#1611]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 6fb86a44d5915dcfd42af71a4c99674bb55650ca | N/A  | go version go1.13 darwin/amd64 |

##### Problem Description
Go get command fails:

```bash
go get -v github.com/Shopify/sarama
github.com/Shopify/sarama
# github.com/Shopify/sarama
../../Shopify/sarama/zstd.go:10:11: undefined: zstd.Encoder
../../Shopify/sarama/zstd.go:24:16: undefined: zstd.NewWriter
../../Shopify/sarama/zstd.go:24:36: undefined: zstd.WithZeroFrames
```

**Comment by dnwe** [comment]
@ajbeach2 it looks like you might be running under 1.13 but under a GOPATH directory which is causing go get not to fetch the module dependencies and instead to try and just build as-is under a GOPATH source checkout. 

Suggest trying:

1. mkdir /tmp/test
2. go mod init test
3. go get -v github.com/Shopify/sarama

**Comment by ajbeach2** [comment]
Yeah. Seems to work only if I use modules.

**Comment by dnwe** [comment]
So even pre-modules, I believe you'd have either needed to use your own dependency manager to collect and fetch Sarama's runtime deps or you'd have had to have them cloned in your GOPATH already so they could be found at compile time. 

Did you have a specific use case for not wanting to adopt go modules?

**Comment by ajbeach2** [comment]
No specific use case other than a quick prototype that didn't use modules.

**Comment by dnwe** [comment]
@ajbeach2 are you happy to close the issue? I don't think there's anything more we can do to help here
