### ISSUE TITLE
Sarama-cluster broke since removal of default CommitInterval config

### ISSUE THREAD

**Issue by reenjii** [Shopify/sarama#1616]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 5885bb2d56ee4de66793d303338cd0aae66099ed | n/a | go1.13.5 |

##### Configuration

All default

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```
time.NewTicker(0x0, 0xc0003105c0)
        /usr/local/share/go/src/time/tick.go:23 +0x147
github.com/bsm/sarama-cluster.(*Consumer).cmLoop(0xc000014000, 0xc000650300)
        /home/user/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/consumer.go:452 +0x4d
github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc000328f20, 0xc0003de960)
        /home/user/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:73 +0xa9
created by github.com/bsm/sarama-cluster.(*loopTomb).Go
        /home/user/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:69 +0x66
```

</p>
</details>

##### Problem Description

The following commit removes `c.Consumer.Offsets.CommitInterval` default value and the variable.

https://github.com/Shopify/sarama/commit/72a629d7d1ac130c1f1221e66396e0b54dfeef3f#diff-b4bda758a2aef091432646c354b4dc59L426

The following issue rollbacks the variable, but does not rollback the initial value.

https://github.com/Shopify/sarama/pull/1164

Thus, when sarama-cluster creates a `time.NewTicker` with the variable that is now 0, it panics.

https://golang.org/pkg/time/#NewTicker

**Comment by d1egoaz** [comment]
If you are coming from sarama-cluster please see the closing comment on https://github.com/Shopify/sarama/pull/1618: 

tl/dr:
Please update your configuration to use `Consumer.Offsets.AutoCommit` instead of `Consumer.Offsets.CommitInterval`.
The field was added back to Sarama so sarama-cluster users can use the latest sarama version.

**Comment by rogpeppe** [comment]
@d1egoaz That doesn't change the fact that this old code that's been working for ages crashes when the Sarama version is upgraded. It would be nice if that was fixed.
