### ISSUE TITLE
Unable to set connections.max.reauth.ms to force regular reauthentication

### ISSUE THREAD

**Issue by danchemla** [Shopify/sarama#1620]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.26.1 | * | 1.13.1 |

##### Problem Description

I want to deploy consumer instances in the infrastructure of my client. They will be able to connect to my kafka topics using SASL/PLAIN authentication. Because of the long-lived nature of connections, if I remove the access for a given client which is already authenticated, he will keep reading messages from the topics.

Reading from https://cwiki.apache.org/confluence/display/KAFKA/KIP-368%3A+Allow+SASL+Connections+to+Periodically+Re-Authenticate
I discover that there is a setting that could be used exactly for this purpose `connections.max.reauth.ms`. However I could not find in sarama how to set its value.

Did I miss something ?

**Comment by mkaminski1988** [comment]
I don't believe Sarama supports this feature yet.
