### ISSUE TITLE
client access old broker when reduce capacity of the cluster

### ISSUE THREAD

**Issue by Stephan14** [Shopify/sarama#1629]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| Version 1.18.0 (2018-09-07) | 0.10.1 |  1.13|

##### Configuration

What configuration values are you using for Sarama and Kafka?

``` 
default configuration
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
Request was for a topic or partition that does not exist on this broker
```

</p>
</details>

##### Problem Description

When i try to reduce the capacity of cluster and remove data from broker A to broke B, if broker A does not shut down or replace to another cluster, but client still access broker A and client log show above.

**Comment by dnwe** [comment]
Should be fixed by #1645 (thanks @Stephan14 )
