### ISSUE TITLE
dynamically change topic while calling ConsumerGroup.Consume

### ISSUE THREAD

**Issue by yichengliu58** [Shopify/sarama#1653]
##### Versions
| Sarama | Kafka | Go |
|--------|-------|----|
| latest | 0.10.1 | latest |

##### Problem Description
Hi, I use ConsumerGroup.Consume() function to read some topics data from kafka, and find this situation where current sarama can't satisfy: I need to change topics being read dynamically.

For now ConsumerGroup.Consume() function only supports fixed topic list:
```go
err := consumerGroup.Consume(context, input.config.Topics, handler)
```
but there are some newly created topic coming into kafka, and I need to read them while old topics are being read at the same time. Because ConsumerGroup.Consume() blocks while reading data from kafka, I failed to find a way to stop it and run it again with new topic list.

So if someone have an idea about this plz tell me. Thx so much!

**Comment by cheesedosa** [comment]
Hi,
You can cancel the context and the consumption will return `err==nil`.

Do note that on rebalance `consumerGroup.Consume` returns `err==nil` and stops consuming. So, you need a loop around `consumerGroup.Consume`.

You can put a guard to check the top-level context if it was cancelled and decide to break consumption and handle it in your app code.

Something like so:
```go
        // ...
	for {
		if ctx.Err() == context.Canceled {
			break
		}

		err := consumerGroup.Consume(ctx, input.config.Topics, handler)
		if err != nil {
			return err
		}
	}
        // ...
```

The `ctx` here is: `ctx, cancelFunc := context.WithCancel(context.Background())`. 
You can cancel `ctx` by calling `cancelFunc()` in your app logic when you detect new topics.

**Comment by yichengliu58** [comment]
@cheesedosa thanks mate, this is a good approach
