### ISSUE TITLE
something wrong whith GSSAPIKerberosAuth.Authorize

### ISSUE THREAD

**Issue by fatsheng** [Shopify/sarama#1654]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.26 | 2.1 |  1.13.1|

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
Error while performing GSSAPI Kerberos Authentication: EOF
```

</p>
</details>

##### Problem Description
```go
packBytes, err := krbAuth.initSecContext(receivedBytes, kerberosClient)
requestTime := time.Now()
bytesWritten, err := krbAuth.writePackage(broker, packBytes)
```
hi , compare to java implement ,i'm confuse with 2 place:
1、i found no handshake action during Authentication , but java do
2、i found the datagram write to the broker not follow the kafka protocol with appkey，version and the correlationId.

i wonder if i use sarama incorrect or the questions above are not nessary?

**Comment by fatsheng** [comment]
misstake ,  kafka protocol  is no need at SASLHandshakeV0

**Comment by chaoqun-wu** [comment]
How did you solve the problem? Can you please share?

**Comment by fatsheng** [comment]
> How did you solve the problem? Can you please share?

first, the issue i post is mistake , sarama use SASLHandshakeV0 , so no need to send messaget with appkey ,version and correlationId .

second, the encryption supported by the kerberos lib is less , so finally i give up to update it , and use logstash instead .
