### ISSUE TITLE
Group consumer : read from newest

### ISSUE THREAD

**Issue by harshana-pickme** [Shopify/sarama#1655]
##### Versions
Version : 1.26.1

| Sarama | Kafka | Go |

##### Problem Description

Using Sarama Group Consumer, we achieve two things
1. Kafka will do the partition assignment based on number of active members in a ConsumerGroup
2. Kafka will remember the last committed messages of partitions and resend from that offset.

I have a requirement to do 1, but not 2. Which means I want kafka to do the partition assignments for me, but I don't want to start from last committed, instead I want to start from the Newest. (eg: my topic has heartbeat messages which comes at high rate. When my instance starts, I'm only interested in current HBs not old ones, so trying to process from last committed is not required)

From what I understand from Sarama API, currently this is not possible. Please conform.

Thanks,
Harshana

**Comment by dnwe** [comment]
@harshana-pickme one way to achieve this is via the `Setup` func in your `ConsumerGroupHandler`

https://github.com/Shopify/sarama/blob/af1423ad225e4416e277b5f9670ec34710ab33e0/consumer_group.go#L777-L795

e.g.,

```go
func (consumer *Consumer) Setup(session sarama.ConsumerGroupSession) error {
	for topic, partitions := range session.Claims() {
		for _, partition := range partitions {
			offset, err := consumer.client.GetOffset(topic, partition, sarama.OffsetNewest)
			if err != nil {
				// XXX: if we couldn't get the newest offset just accept the committed and skip reset
				continue
			}
			log.Printf("Marking offset %d on %s-%d\n", offset, topic, partition)
			session.MarkOffset(topic, partition, offset, "")
		}
	}
	return nil
}
```

**Comment by harshana-pickme** [comment]
thanks @dnwe for the reply.

**Comment by leonardge** [comment]
> @harshana-pickme one way to achieve this is via the `Setup` func in your `ConsumerGroupHandler`
> 
> https://github.com/Shopify/sarama/blob/af1423ad225e4416e277b5f9670ec34710ab33e0/consumer_group.go#L777-L795
> 
> e.g.,
> 
> ```go
> func (consumer *Consumer) Setup(session sarama.ConsumerGroupSession) error {
> 	for topic, partitions := range session.Claims() {
> 		for _, partition := range partitions {
> 			offset, err := consumer.client.GetOffset(topic, partition, sarama.OffsetNewest)
> 			if err != nil {
> 				// XXX: if we couldn't get the newest offset just accept the committed and skip reset
> 				continue
> 			}
> 			log.Printf("Marking offset %d on %s-%d\n", offset, topic, partition)
> 			session.MarkOffset(topic, partition, offset, "")
> 		}
> 	}
> 	return nil
> }
> ```

Probably also need to have `close(consumer.ready)`.

**Comment by dnwe** [comment]
@harshana-pickme glad I was able to help 👍

**Comment by Morriaty-The-Murderer** [comment]
> ```go
> ConsumerGroupSession
> ```

However, when implementing `ConsumerGroupHandler `, `consumer.client` is a private property which cannot be accessd outside of the package

**Comment by harshana-pickme** [comment]
> Hi @dnwe , a little problem when implementing `ConsumerGroupHandler `, `consumer.client` is a private property which cannot be accessd outside of the package

I already had a client because I create the group consumer using NewConsumerGroupFromClient()
