### ISSUE TITLE
Let me confirm if this is a BUG

### ISSUE THREAD

**Issue by vperson** [Shopify/sarama#1663]
##### Versions 

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| master | 2.1.1 |1.12  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.WaitForAll
	config.Producer.Return.Successes = true

	producer, err := sarama.NewSyncProducer(strings.Split("xxxxxxxx:9092", ","), config)
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
2020/04/11 16:30:36 send message err: kafka: invalid configuration (Producing headers requires Kafka at least v0.11)
```

</p>
</details>

##### Problem Description

There is value in my headers, but if the judgment here is not empty, an error will be reported:

![image](https://user-images.githubusercontent.com/30188622/79039191-288ff500-7c12-11ea-82dd-15da5afc8070.png)

**Comment by vperson** [comment]
Problematic file： https://github.com/Shopify/sarama/blob/master/async_producer.go

**Comment by vperson** [comment]
I did not set the version number of kafka, I thought it could automatically recognize the version number

**Comment by dnwe** [comment]
Yes currently Sarama required manual version configuration. Eventually we will move to using ApiVersion request and response but it isn't implemented yet
