### ISSUE TITLE
I am confused by how sarama batches work.

### ISSUE THREAD

**Issue by rustysys-dev** [Shopify/sarama#1664]
I see mentioned [here](https://github.com/Shopify/sarama/blob/master/config.go#L199-L202) that:

```
		// ... By default, messages are sent as fast as possible, and
		// all messages received while the current batch is in-flight are placed
		// into the subsequent batch
```

What does this mean? I don't understand when a batch will be sent.

does in-flight mean to say that when one message is being sent to kafka all other messages that arrive will be placed in the same batch for the next transmission?

If I am using an async producer with a channel, would the batch size be 1 message?

**Comment by leilei3167** [comment]
I have the same question too!😂
