### ISSUE TITLE
[Query] Sarama managing connections.

### ISSUE THREAD

**Issue by harshana-pickme** [Shopify/sarama#1682]
##### Versions
Version : 1.26.1

| Sarama | Kafka | Go |

##### Problem Description

Hi all,

Is it a good idea to always create my producers and consumers with NewProducer(), NewConsumer() instead of NeProducerFromClient(), NewConsumerFromClient() ?

I think this creates multiple connections to kafka. From message rate point of view, kafka may not see a difference, will the number of connections be a significant overhead on kafka or sarama?

Biggest reason for using the first set of methods are individual topics need different configurations (eg: partitioner, ack method, AutoCommit, initial offset) which are attached to the Client, so if you need different configs, you need to create connections.

let us know your views.

Thanks,
Harshana

**Comment by harshana-pickme** [comment]
Can someone help me with this query ? Please...

**Comment by harshana-pickme** [comment]
Let me ask the question differently

Can I re-use the same sarama.Client to subscribe to two channels, one with sarama.OffsetNewest and the other with sarama.OffsetOldest ? or should I create two clients for this purpose ?

Thanks,
Harshana

**Comment by d1egoaz** [comment]
> Is it a good idea to always create my producers and consumers with NewProducer(), NewConsumer() instead of NeProducerFromClient(), NewConsumerFromClient() ?

It depends, how many instances of your app is going to be running at the same time?, how many producers/consumers objects are you planning to create on each instance? how many brokers does your cluster has? is the cluster busy regarding TCP connections?

**Comment by harshana-pickme** [comment]
> > Is it a good idea to always create my producers and consumers with NewProducer(), NewConsumer() instead of NeProducerFromClient(), NewConsumerFromClient() ?
> 
> It depends, how many instances of your app is going to be running at the same time?, how many producers/consumers objects are you planning to create on each instance? how many brokers does your cluster has? is the cluster busy regarding TCP connections?

Thank you d1egoaz for the response. 

There will be at maximum 6 instances running (normally 2). But there are about 50+ other similar apps. Each at least having 2 ~ 3 consumers and 1 or 2 producers. Which will end up 5 connections from each instance to kafka broker.

**Comment by d1egoaz** [comment]
TBH it seems it could be easily handle by kafka, and Sarama should no have issues as well.
Best thing to do, is to give it a try, service by service, and collect numbers on the kafka cluster side to see if there is any impact.

**Comment by harshana-pickme** [comment]
thanks @d1egoaz . My thinking was also in similar lines. Will go with the simplest possible solution and think of sophisticated client management if it is required.

Thanks,
Harshana

**Comment by d1egoaz** [comment]
let us know how it goes.
