### ISSUE TITLE
v1.26.2 TLS issue on latest version, tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

### ISSUE THREAD

**Issue by d1egoaz** [Shopify/sarama#1691]
##### Problem Description

Hey! some heads up!
We use internally a wrapper on top of Sarama that's using 1.26.1, however an app had the Sarama dependency and dependabot updated Sarama to 1.26.2, it broke the app, I've also tested and I tested with other app and the same error happened.
```
client/metadata got error from broker -1 while fetching metadata: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

It seems related to this PR https://github.com/Shopify/sarama/pull/1666

ping @bai @dnwe 
Could we mark the release as unsafe?

##### Versions
| Sarama | Kafka | Go |
|--------|-------|----|
| 1.26.2 | 2.3.x | 1.13.x and 1.14.x |

##### Logs
<details><summary>logs: CLICK ME</summary>
<p>

```
{"level":"info","msg":"Initializing new client","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker xxx-server-xxx:9093\n","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"Using tls","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"Connected to broker at xxx-server-xxx:9093 (unregistered)\n","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"client/metadata got error from broker -1 while fetching metadata: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config\n","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"Closed connection to broker xxx-server-xxx:9093\n","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"client/metadata no available broker to send metadata request to","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"client/brokers resurrecting 1 dead seed brokers","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"client/metadata retrying after 250ms... (3 attempts remaining)\n","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"client/metadata fetching metadata for all topics from broker xxx-server-xxx:9093\n","time":"2020-05-07T17:32:07Z"}
{"level":"info","msg":"Using tls","time":"2020-05-07T17:32:07Z"}

```

</p>
</details>

**Comment by d1egoaz** [comment]
I've updated v1.26.2 as pre-release to stop dependabot to telling people to upgrade Sarama while we work on this issue.

**Comment by dnwe** [comment]
😢 

do we not have any functional tests using TLS? Surprised this passed the builds

**Comment by dnwe** [comment]
This regression is because `tls.DialWithDialer` with a nil tls.Config creates a default config whereas tls.Client requires you to give it a non-nil tls.Config?

**Comment by d1egoaz** [comment]
This is the issue:
<img src="https://screenshot.click/2020-05-07_11-04-31_czn9s.png" width="100%" />

`tls.DialWithDialer` sets the `ServerName`
<img src="https://screenshot.click/2020-05-07_11-05-19_ok3qx.png" width="50%" />

**Comment by dnwe** [comment]
Yeah as per the doc — https://pkg.go.dev/crypto/tls?tab=doc#Client

**Comment by d1egoaz** [comment]
from: https://github.com/Shopify/sarama/pull/1666

> Note there seems to be an issue with the tls test where the server name was never set so Ive fixed that too.

https://github.com/Shopify/sarama/pull/1666#issuecomment-625414570
