### ISSUE TITLE
Connection with multiple TLS brokers fails to negotiate

### ISSUE THREAD

**Issue by Albibek** [Shopify/sarama#1700]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.26.{1-3} | 2.3 | 1.14 |

##### Configuration

``` 
Brokers = [broker01, broker02]
TLSConfig = {}
```
broker01 has certificate with cn=broker01
broker02 has certificate with cn=broker02

##### Logs

```
time="2020-05-12T14:05:57Z" level=error msg="consuming messages" error="kafka: error while consuming kubernetes/8: x509: certificate is valid for broker02, not broker01" 
```

</p>
</details>

##### Problem Description
Server name for TLS connection inferred incorrectly when multiple brokers are used.

We beleive, the bug is in the code below (`broker.go`)

When, in the first iteration of the cycle the cfg is changed, ServerName is never empty again. So all other connections will have incorrect ServerName and therefore fail the TLS negotiation. 

```
           // If no ServerName is set, infer the ServerName
            // from the hostname we're connecting to.
            // Gets the hostname as tls.DialWithDialer does it.
            if cfg.ServerName == "" {
                colonPos := strings.LastIndex(b.addr, ":")
                if colonPos == -1 {
                    colonPos = len(b.addr)
                }
                hostname := b.addr[:colonPos]
                cfg.ServerName = hostname
            }
            b.conn = tls.Client(b.conn, cfg)
```

**Comment by dselyuzhitskiy** [comment]
The problem in this PR https://github.com/Shopify/sarama/pull/1692/commits/ab525ed5db3267f633504c4e3506f922986af189

conf is a pointer to sarama.Config, so it set ServerName for the first broker and the remaining brokers try to use tls with wrong ServerName

**Comment by dnwe** [comment]
@d1egoaz ref https://github.com/Shopify/sarama/pull/1692 😢

**Comment by d1egoaz** [comment]
🤔 weird, we don't have that issue, I left running in one test app, and it's been running fine, that app connects to a 80 brokers cluster with no issues.

**Comment by d1egoaz** [comment]
he code can be modified to create a copy/clone `conf.Net.TLS.Config` instead of referencing it directly! I just realized this was a pointer 😞

**Comment by d1egoaz** [comment]
but it does work for us 🤷

**Comment by d1egoaz** [comment]
@dselyuzhitskiy Can you try https://github.com/Shopify/sarama/pull/1701 branch `diego_clone-tls-config`

**Comment by dselyuzhitskiy** [comment]
@d1egoaz i checked it and it works well. i left a comment about code improvement in PR

**Comment by dselyuzhitskiy** [comment]
I looked at https://github.com/Shopify/sarama/pull/1666 and i could not understand what is wrong with tls.DialWithDialer that solve all problems. For proxy support we just need correct dialer from config.getDialer and sends it to DialWithDialer, i think.

**Comment by d1egoaz** [comment]
@dselyuzhitskiy  I was trying to do the same actually, but `DialWithDialer`

```go
 broker.…   159  43 error           compiler: cannot use &dialer (value of type *proxy.Dialer) as *net.Dialer value in argument to tls.DialWithDialer (lsp)
```

`dialer` is not anymore a `net.Dialer`, it's now a `proxy.Dialer` because of `conf.getDialer()`

and `proxy.Dialer` only implements `Dial`, `tls.DialWithDialer` needs more than that 😞

**Comment by dselyuzhitskiy** [comment]
Thanks for the explanation, i missed it.

**Comment by joelschopp** [comment]
We are also having trouble publishing on 1.26.3, downgrading to 1.26.1 fixes for us.  We are using 3 tls servers.  Looking forward to a 1.26.4 with a fix.  Also happy to test any potential fixes.

**Comment by d1egoaz** [comment]
@joelschopp can you try https://github.com/Shopify/sarama/pull/1701?

**Comment by joelschopp** [comment]
> @joelschopp can you try #1701?

Added this to my go.mod at it works for me... note `5ff9581b104a` is the last commit in the branch you pointed to.

```
+replace github.com/Shopify/sarama => github.com/Shopify/sarama v1.26.4-0.20200514231448-5ff9581b104a
````
