### ISSUE TITLE
how can we use the below function to read message from multiple partition? as partition is a int field which accept only one value func (c *consumer) ConsumePartition(topic string, partition int32, offset int64) (PartitionConsumer, error)

### ISSUE THREAD

**Issue by kwl2211** [Shopify/sarama#1724]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

**Comment by kwl2211** [comment]
@eapache @mchmarny how can we use the below function to read message from multiple partition?
as partition is a int filed which accept only one value
func (c *consumer) ConsumePartition(topic string, partition int32, offset int64) (PartitionConsumer, error)

**Comment by d1egoaz** [comment]
@kwl2211 you'll need to create multiple consumers, one per partition?
if you're planning to consume all the partitions in a topic, you should consider using consumer groups
