### ISSUE TITLE
Revisit publishing of uncommited messages in functional_test

### ISSUE THREAD

**Issue by dnwe** [Shopify/sarama#1733]
One of the pieces of #1695 was to use a small jar for publishing uncommited messages as part of the functional test:

https://github.com/Shopify/sarama/blob/221ed1a25150fa98d750f2e2f33f58ff018238b4/functional_test.go#L343-L345

What's missing from https://github.com/Shopify/sarama/pull/1152 to allow us to do this in-house?

/cc @KJTsanaktsidis

**Comment by KJTsanaktsidis** [comment]
So I had originally thought that there was just no support for the nescessary calls to do transactional publishing at all, but actually the low-level support in the Broker/Protocol interface does exist, it's just not part of the high-level producer interface.

Just purely for the purpose of getting rid of the JAR, I wonder if something like this might work:

```
	transactionalID := "transactional.id config"
	coordRes, _ := controller.FindCoordinator(&FindCoordinatorRequest{
		Version: 2,
		CoordinatorKey: transactionalID,
		CoordinatorType: CoordinatorTransaction,
	})
	pidRes, _ := coordRes.Coordinator.InitProducerID(&InitProducerIDRequest{
		TransactionalID: &transactionalID,
		TransactionTimeout: 10 * time.Second,
	})
	_, _ = coordRes.Coordinator.AddPartitionsToTxn(&AddPartitionsToTxnRequest{
		TransactionalID: transactionalID,
		ProducerID: pidRes.ProducerID,
		ProducerEpoch: pidRes.ProducerEpoch,
		TopicPartitions: map[string][]int32{
			"uncomitted-topic-test-4": {0},
		},
	})
	ps := &produceSet{
		msgs:          make(map[string]map[int32]*partitionSet),
		parent:        &asyncProducer{
			conf: config,
		},
		producerID:    pidRes.ProducerID,
		producerEpoch: pidRes.ProducerEpoch,
	}
	_ = ps.add(&ProducerMessage{
		Topic: "uncomitted-topic-test-4",
		Partition: 0,
		Value: StringEncoder("uncomimtted message"),
	})
	produceReq := ps.buildRequest()
	produceReq.TransactionalID = &transactionalID
	_, _ = coordRes.Coordinator.Produce(produceReq)
	_, _ = coordRes.Coordinator.EndTxn(&EndTxnRequest{
		TransactionalID: transactionalID,
		ProducerID: pidRes.ProducerID,
		ProducerEpoch: pidRes.ProducerEpoch,
		TransactionResult: false,
	})
```

I haven't actually tried to run it but I can give it a shot when I get a moment and see how it goes.
