### ISSUE TITLE
[Documentation] Add keda.sh to users for Sarama

### ISSUE THREAD

**Issue by anirudhgarg** [Shopify/sarama#1735]
We are  using Sarama as the client library in the Keda project (keda.sh) for the Kafka scaler. - https://keda.sh/docs/1.4/scalers/apache-kafka/

**Comment by d1egoaz** [comment]
Added here: https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions
It doesn't seem that there are more files to update, if I missed some file please let me know
