### ISSUE TITLE
several consumer group can't consume

### ISSUE THREAD

**Issue by luckyweiwei** [Shopify/sarama#1757]
##### Versions

Sarama: v1.26.4
Kafka: 2.3.0
Go: 1.14.3

##### Configuration
There are two consumer groups.

The first:
{
      "Version": "2.3.0",
      "GroupID": "group_biz",
      "BrokerAddresses": [
        "192.168.88.206:9092",
        "192.168.88.208:9092"
      ]
}

The Second:
{
      "Version": "2.3.0",
      "GroupID": "group_external",
      "BrokerAddresses": [
        "192.168.88.206:9092",
        "192.168.88.208:9092"
      ]
}

##### Logs
There is no error log here

##### Problem Description
If there are multiple consumer groups and multiple brokers to consume multiple topics, messages on some brokers will not be consumed.

But when I combined these two consumers into one, it was all right again。
Configuration is：
{
      "Version": "2.3.0",
      "GroupID": "group_full",
      "BrokerAddresses": [
        "192.168.88.206:9092",
        "192.168.88.208:9092"
      ]
}

So my question is:
Does Samara support multi consumer group which contains several brokers？

**Comment by luckyweiwei** [comment]
My two brokers are not in the same cluster, which may be the reason that one of them does not consume。

func NewConsumerGroup(addrs []string, groupID string, config *Config) (ConsumerGroup, error) {}
So the addrs param should be in the same cluster？

**Comment by d1egoaz** [comment]
could you please expand on this:
> If there are multiple consumer groups and multiple brokers to consume multiple topics, messages on some brokers will not be consumed.

also:
> My two brokers are not in the same cluster, which may be the reason that one of them does not consume。

like two different kafka clusters? or what do you mean by cluster?

**Comment by luckyweiwei** [comment]
> could you please expand on this:
> 
> > If there are multiple consumer groups and multiple brokers to consume multiple topics, messages on some brokers will not be consumed.
> 
> also:
> 
> > My two brokers are not in the same cluster, which may be the reason that one of them does not consume。
> 
> like two different kafka clusters? or what do you mean by cluster?

My whole system is distributed deployment of microservices.
Kafka has multiple servers, which are also distributed.

Now I have a microservice need to subscribe different topics in multiple Kafkas at the same time.
I use Sarama's consumer group to consume messages of all the kafka.
My code like:
`
consumer, err := sarama.NewConsumerGroup(["192.168.88.206:9092","192.168.88.208:9092"], "group_full", &sarama.Config)
`

However, as a result, only one Kafka message can be consumed, and the other Kafka messages cannot be consumed..

**Comment by luckyweiwei** [comment]
The Kafka of my environment is distributed. Multiple Kafka are not managed by the same zookeeper.

Now i start multiple consumer groups and put a Kafka broker into each consumer group, and everything is ok.
`consumer1, err := sarama.NewConsumerGroup(["192.168.88.206:9092"], "group1", &sarama.Config)
consumer2, err := sarama.NewConsumerGroup(["192.168.88.208:9092"], "group2", &sarama.Config)`
