### ISSUE TITLE
[Question] How to Gracefully shutdown Kafka consumer process

### ISSUE THREAD

**Issue by alok87** [Shopify/sarama#1776]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  master | 2.5.0 | 1.14.6 |

How to gracefully shutdown the `processMessage()` on OS signals.
```go
func (c consumer) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
        for message := range claim.Messages() {
		err := c.processMessage(session, message)
        }
}
```
## Requirement
the `processMessage()` batches messages in memory and on reaching 100, it does some processing, uploads to s3 and then do a commit. 

## Problem
I want to shutdown this `processMessage()` gracefully by listening to OS signals in every loop of processing of message. But since the context signals are not passed to the `ConsumeClaim()`, I am not able to forward them to the `processMessage()` routine.  

Is not it possible to have context `ctx` in ConsumeClaim() defination ? 

`consumerGroupSession` has [ctx](https://github.com/Shopify/sarama/blob/master/consumer_group.go#L543).  But the idiomatic way in Go is to pass `ctx` (context) in functions and not use it from `struct{}`. 
Please let me know your thoughts on this.
 
Thank you for open sourcing the library 👍

**Comment by d1egoaz** [comment]
I don't _think_ you need to check the OS signals on the processing of the messages.

I _think_ you can simply defer the consumer group close function and make the OS signals handler end the execution of the main go routine.

something like:


```go

fun yourMainMethod {
...
	group, err := sarama.NewConsumerGroup...
	if err != nil {
		logrus.WithError(err).Error("Couldn't create a Kafka consumer")
		return
	}

	defer func() {
		err = group.Close()
		if err != nil {
			logrus.WithError(err).Error("Error closing consumer group")
			return
		}
	}()

signal handling here

}
```
signal handling can be similar to https://github.com/Shopify/sarama/blob/master/examples/consumergroup/main.go#L116-L126

having `ctx` on our methods would be nice though, we will need *new* methods to not break users' code

**Comment by d1egoaz** [comment]
> since the context signals are not passed to the ConsumeClaim(), I am not able to forward them to the processMessage()
you could also add a channel to your `consumer` and send the event when the signal handling is triggered.

**Comment by alok87** [comment]
Thanks for the suggestions. @d1egoaz (i will explore them)
I was thinking of using `Context()` in the session in the  `c.processMessage(session, message)` as it already has the session object. https://github.com/Shopify/sarama/blob/master/consumer_group.go#L532

Something like:

```go	
	for id, data := range memoryMessages {
		select {
		default:
			message := data.(*sarama.ConsumerMessage)
			b.processMessage(message, id)
		case <-b.session.ctx.Done():
			return false
		}
	}
	return true
}
```

Thoughts? Does this look the right way to do this.


```

**Comment by d1egoaz** [comment]
@alok87 right, yes, looks like a good idea!,so you can break the bulk processing if the consumer is going down!  @bai @dnwe  any more comments? 👀 


it also seems you can pass your own `Context` when calling `group.Consume(ctx, `....

**Comment by alok87** [comment]
We should definitely have an example for this https://github.com/Shopify/sarama/tree/master/examples

**Comment by d1egoaz** [comment]
@alok87 PR Welcomes :D 

it should be a great addition to our examples 🚀

**Comment by alok87** [comment]
Sure I will add that may be we can take the discussion of what would be better way to handle signal shutdown there...

**Comment by alok87** [comment]
Hey recently after enabling TLS i have started facing issue in which the context I passed to sarama is active. But sarama session context `session.Context().` gets closed.

When can sarama session context get closed?

**Comment by alok87** [comment]
Please help out here. Passing context as parameter is the right way still based on Golang documentation. https://github.com/golang/go/issues/22602

I have to go around this by putting context in the struct.

**Comment by alok87** [comment]
Closed in favour of https://github.com/Shopify/sarama/issues/1892
