### ISSUE TITLE
ConsumerGroupHandler.Setup called multiple times, panic on closing alredy closed ready channel

### ISSUE THREAD

**Issue by pavolloffay** [Shopify/sarama#1793]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.27.0 |  ? |  1.14

##### Configuration

What configuration values are you using for Sarama and Kafka?

The default configuration

##### Logs

None

##### Problem Description

The consumer group example closes ready channel in `ConsumerGroupHandler.Setup` This caused panic (closing already closed channel) see https://github.com/open-telemetry/opentelemetry-collector/issues/1692. 

Our implementation followd the example code from https://github.com/Shopify/sarama/blob/master/examples/consumergroup/main.go#L142. Is the code correct? Can be the `ConsumerGroupHandler` called twice? Shall we wrap the close into `sync.Once`?

**Comment by d1egoaz** [comment]
There is an issue with the example, as the `Setup` method could be called multiple times as part of when a member initially joins a group or a rebalance happens.

**Comment by d1egoaz** [comment]
nvm, the example is correct, the channel is recreated when the for-loop gets run, i.e. when `Consume` returns (rebalance)

![image](https://user-images.githubusercontent.com/950087/91745435-cf4c4200-eb6f-11ea-9c13-10d1ba90c04a.png)


```
consumer.ready = make(chan bool)
```

from the code you mentioned, the channel is not recreated
https://github.com/open-telemetry/opentelemetry-collector/blob/7f13eb66c33341f840f83f43a5fc2bf2f9c8628c/receiver/kafkareceiver/kafka_receiver.go#L98-L112

**Comment by pavolloffay** [comment]
I have missed that, thanks @d1egoaz !

**Comment by pavolloffay** [comment]
@d1egoaz one more thing. The exmaple produces 

```
==================
WARNING: DATA RACE
```

as the ready channel is initialized from different goroutine https://github.com/Shopify/sarama/blob/master/examples/consumergroup/main.go#L112. Would it be better to initialize it back in the cleanup? https://github.com/Shopify/sarama/blob/master/examples/consumergroup/main.go#L147
