### ISSUE TITLE
[question]How do I get a ConsumePartition based on IP

### ISSUE THREAD

**Issue by chen-ABC** [Shopify/sarama#1804]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  1.27| 2.1.0 | 1.15.1 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go

        config := sarama.NewConfig()
	config.Version = sarama.V2_1_0_0
	consumer, err := sarama.NewConsumer([]string{"localhost:9092"}, config)   // is ok

        pc, errorConsumePartition := consumer.ConsumePartition("test",0,0)  // error   dial tcp: lookup kafka-cluster: no such host


		
```

##### Problem Description
The online Kafka is configured with a domain name, but it cannot be resolved in practice. I want to connect through IP.

**Comment by gonejack** [comment]
没太看懂是什么问题，能补充一下吗？

Could you provide more details?

**Comment by chen-ABC** [comment]
@gonejack 
1.我用IP连接了kafka,获取连接成功
2.但是进一步获取分区的消费者时他会自动获取kafka配置的域名去再次连接kafka.但是那个域名是无法访问的.
我这边线上所有的kafka域名都是kafka-cluster.本地除非去配置host不然是无法访问的.
我的目的就是有没有只通过IP的方式去连接kafka.

**Comment by gonejack** [comment]
这个是因为，客户端实际使用的是服务器端给的地址，如果客户端连接上服务器后，服务器返回的是需要解析的地址，客户端无法解析的话是没有办法的。

The final address clients would regard with are the addresses returned by brokers, there seems no way out when the server returns some broker address that clients can not resolve.

**Comment by chen-ABC** [comment]
@gonejack  了解了,感谢
