### ISSUE TITLE
Consumer group ignores AutoCommit flag when it exits

### ISSUE THREAD

**Issue by hipper** [Shopify/sarama#1843]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.27.2 | 2.7.0 | 1.14 |

##### Problem Description
When consumer's AutoCommit flag is disabled by configuration and you mark offset during the process with `session.MarkMessage(msg, "")` it doesn't commit the offset as expected. However when you terminate the consumer (or rebalancing is triggered) it commits the offset ignoring the AutoCommit flag.

This is likely related to this PR: https://github.com/Shopify/sarama/pull/1699
This PR removes the check:
```
// flushToBroker is ignored if auto-commit offsets is disabled
func (om *offsetManager) flushToBroker() {
	if !om.conf.Consumer.Offsets.AutoCommit.Enable {
		return
	}
        ...
```

I test using Sarama `1.26.4` where that check is in place and it works as expected, but `1.27.2` commits the offset on `Close()` which is likely a bug.

**Comment by dnwe** [comment]
Fixed by https://github.com/Shopify/sarama/pull/1846
