### ISSUE TITLE
kafka 0.11.0.0 scram-sha-256 go-1.14 cannot work

### ISSUE THREAD

**Issue by shamohong1215** [Shopify/sarama#1845]
user exapmle  scram-client.go but not work.
err:
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

**Comment by dnwe** [comment]
@ismaelpuerto it's not obvious what you're trying to do here — you have kafka running on port 9092 on a host called kafka011 and you can't connect?

Re-run with the `-verbose` option and include the full log and we might be able to learn more:
```
./consumer -verbose -brokers=kafka011:9092" -topics="mytopic" -group="example"
```

**Comment by dnwe** [comment]
Note: the "consumergroup" simple example doesn't have cmdline options for configuring SSL and SASL and obviously won't be able to connect if your cluster is configured to require them.

The "sasl_scram_client" example does have support for SSL and SASL but only the SCRAM variants, not PLAIN.

**Comment by dnwe** [comment]
Cool, closing as fixed. Feel free to open another issue if you face more problems
