### ISSUE TITLE
why ListPartitionReassignments method not support less than version 2.4.0.0

### ISSUE THREAD

**Issue by cai-peng** [Shopify/sarama#1855]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description
// Alter the replica assignment for partitions.
// This operation is supported by brokers with version 2.4.0.0 or higher.
AlterPartitionReassignments(topic string, assignment [][]int32) error

// Provides info on ongoing partitions replica reassignments.
// This operation is supported by brokers with version 2.4.0.0 or higher.
ListPartitionReassignments(topics string, partitions []int32)

**kafka** manager(CMAK) support this operation，i think sarama can also support it

**Comment by dnwe** [comment]
@cai-peng ? These APIs were first introduced in Kafka 2.4.0.0

https://cwiki.apache.org/confluence/display/KAFKA/Kafka+APIs

**Comment by cai-peng** [comment]
oh thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dominic ***@***.***&gt;; 
发送时间: 2021年3月16日(星期二) 上午7:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Shopify/sarama] why ListPartitionReassignments method not support less than version 2.4.0.0 (#1855)





 
@cai-peng ? These APIs were first introduced in Kafka 2.4.0.0
 
https://cwiki.apache.org/confluence/display/KAFKA/Kafka+APIs
