### ISSUE TITLE
Does sarama support renaming consumer group?

### ISSUE THREAD

**Issue by alok87** [Shopify/sarama#1861]
## Question.

Kafka supports renaming consumer-group as mentioned [here](https://kafka-utils.readthedocs.io/en/latest/kafka_consumer_manager.html#:~:text=offset_rewind%20%2C%20and%20offset_advance%20.-,Copying%20or%20renaming%20consumer%20group,group%20using%20the%20copy_group%20subcommand.&text=They%20can%20be%20renamed%20using%20rename_group%20.&text=When%20the%20group%20is%20copied,that%20topic%20will%20be%20copied.)

I have a use case in which we need to rename a consumer group in Kafka. Please suggest if it is possible using sarama?

**Comment by jurestanic** [comment]
@alok87 have you found the solution?
