### ISSUE TITLE
Support for ConsumeClaimWithContext

### ISSUE THREAD

**Issue by alok87** [Shopify/sarama#1892]
##### Problem Description

```go
// consumerGroupHandler.ConsumeClaim() is called for every topic partition
type consumerGroupHandler struct {
	ctx   context.Context
}	

func (c *consumerGroupHandler) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
       // use c.ctx
}
```
At present `ConsumeClaim` function does not accept context. So the context needs to be kept in struct `consumerGroupHandler`.

Support for `ConsumeClaimWithContext()` would help.

Golang still recommends passing context to every function. https://github.com/golang/go/issues/22602
 
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx

**Comment by chanced** [comment]
Session has a context.

```go
func (p process) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	for msg := range claim.Messages() {
		_ := session.Context()
        }
}
```
session.Context()

**Comment by chanced** [comment]
I replied about `Session` having a `Context()` but I read through your other thread and it seems you know that.

I think I disagree with `ConsumeClaimWithContext` as it obscures the fact that `Context` is available with ConsumeClaim. You can always introduce your own method:

```go
func (*consumerGroupHandler) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
    return c.ConsumeClaimWithContext(session.Context(), session, claim)
}
func (c *consumerGroupHandler) ConsumeClaimWithContext(ctx context.Context, session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
       // use c.ctx
}

```
