### ISSUE TITLE
[Question] How to find why the session.Context() got Done?

### ISSUE THREAD

**Issue by alok87** [Shopify/sarama#1896]
```go
for {
  select {
  case <-session.ctx.Done():
			Logger.Printf("in which cases can this happen?")
  }
}
```

Our session keeps getting closed for a slow running consumer. We have tried increasing the maxProcessing time, session timeout and heartbeat for the consumer. But it has not helped.

We get `loop check partition number ` error a lot of times https://github.com/Shopify/sarama/issues/1685.  We are running the claim under endless for loop as suggested in #1685

But it keeps happening, until we restart or recreate one of the Kafka pod.

Please give some pointers on how to find why the session context is getting closed.

**Comment by bartek** [comment]
Are you sure this is Sarama doing something that you don't expect?

Kafka doesn't really concern itself with how fast messages are being consumed and won't get involved with slow consumers. It won't tell say, boot a consumer for being too slow.

To help you out, consider the following:

1. `ctx.Done` may be called on multiple occasions, e.g. when the parent context you provide the `Consume(...)` loop is cancelled or when a server-side rebalance happens. What does your infinite loop look like?
2. The Consumer Group can be [`closed`](https://github.com/Shopify/sarama/blob/master/consumer_group.go#L67) but Sarama will only close that on errors. Otherwise, it's up to you (e.g. closing it on exit signal)

**Comment by alok87** [comment]
For sure 

1. Did not happen as I have added logs everywhere if it did. I am handling main context also in the for loop. Here is the consumer handler code

```go
claimMsgChan := claim.Messages()

	for {
		select {
		case <-h.ctx.Done():
			klog.V(2).Infof(
				"ConsumeClaim gracefully shutdown for topic: %s (above)",
				claim.Topic(),
			)
			return nil
		case <-session.Context().Done():
			return fmt.Errorf("Session context done, recreate, err: %v", session.Context().Err())
		case message, ok := <-claimMsgChan:
			if !ok {
				klog.V(2).Infof(
					"topic:%s: ConsumeClaim ending, hit",
					claim.Topic(),
				)
				err = msgBatch.Process(h.ctx)
				if err != nil {
					return err
				}
				klog.V(2).Infof(
					"ConsumeClaim ended for topic: %s, partition: %d (would rerun by manager)\n",
					claim.Topic(),
					claim.Partition(),
				)
				return nil
			}

			select {
			default:
			case <-h.ctx.Done():
				klog.V(2).Infof(
					"ConsumeClaim gracefully shutdown for topic: %s",
					claim.Topic(),
				)
				return nil
			case <-session.Context().Done():
				return fmt.Errorf("Session context done, recreate, err: %v", session.Context().Err())
			}

			// Deserialize the message
			msg, err := h.serializer.Deserialize(message)
			if err != nil {
				klog.Fatalf("Error deserializing binary, err: %s\n", err)
			}
			if msg == nil || msg.Value == nil {
				klog.Fatalf("Got message as nil, message: %+v\n", msg)
			}

			// Process the batch by schemaID
			job := StringMapToJob(msg.Value.(map[string]interface{}))
			upstreamJobSchemaId := job.SchemaId

			if lastSchemaId == nil {
				lastSchemaId = new(int)
			} else if *lastSchemaId != upstreamJobSchemaId {
				klog.V(2).Infof(
					"topic:%s: schema changed, %d => %d\n",
					claim.Topic(),
					*lastSchemaId,
					upstreamJobSchemaId,
				)
				err = msgBatch.Process(h.ctx)
				if err != nil {
					return err
				}
			}
			// Process the batch by size or insert in batch
			err = msgBatch.Insert(h.ctx, msg)
			if err != nil {
				return err
			}
			*lastSchemaId = upstreamJobSchemaId
		case <-maxWaitTicker.C:
			// Process the batch by time
			klog.V(2).Infof(
				"topic:%s: maxWaitSeconds hit",
				claim.Topic(),
			)
			err = msgBatch.Process(h.ctx)
			if err != nil {
				return err
			}
		}
	}
```

2.  Can I log anywhere (may be in the sarama code?) to find why exactly the session got closed. As sarama logs many errors I see when the session closes. Some times the errors are like this https://github.com/Shopify/sarama/issues/1685 sometimes broker connection and many times `offset_manager.go:340  kafka server: The provided member is not known in the current generation.`  (which is the after affect of session closure)

**Comment by alok87** [comment]
I have only seen these problems when a single process has many many topics being handled https://github.com/Shopify/sarama/issues/1897

**Comment by alok87** [comment]
The issue were my old subscriptions were not dying fast, after fixing this, the only 2 reasons when session can go down are
1. The main context is cancelled, or the processes shutdown, then the session context gets cancelled.
2. The session closure happens as described here https://github.com/Shopify/sarama/issues/1897#issuecomment-795597419 the sessions usually close due to connection issues in the environment, or due to the rebalance getting  triggered or when the ConsumeClaim loop exits.

The code should be designed and run as for loop to run Consume() under for loop as described here https://github.com/Shopify/sarama/issues/1685#issuecomment-652537977 to rerun on session closure. And all the existing ConsumeClaim should die fast to quickly get new subscription.
