### ISSUE TITLE
Slow consumers, subscription stuck problem

### ISSUE THREAD

**Issue by alok87** [Shopify/sarama#1897]
Our consumer group is handling 100+ topics (only one partition for all of them, partition0 for all 100 topics)

For example in the loader handler processes in batches. It batches and processes based on message count and also on time. The loop keeps going to the ticker case and since the batch size = 0 due to no inserts, nothing ever gets processed. **We are stuck in this loop.**

```go
func (h *handler) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
  claimMsgChan := claim.Messages()
  for {
      select {
          case message, ok := <-claimMsgChan:
                     // insert message in batch and process if batch > 0 
          case <-maxWaitTicker.C:
                    // process if batch > 0 
      }
  }
}
```

Out of 100+ topics only 57 topics got message `[sarama] added subscription to`, rest 43 never got subscribed so they are stuck in the endless loop waiting for messages to come to read channel.

Please suggest if this is an expected behaviour and how we can fix it. Is there some configuration I am missing?

**Comment by alok87** [comment]
This is happening when the ConsumeClaim is starting for the topic and we dont see 
`[sarama] 2021/03/09 18:53:11 consumer/broker/1 added subscription to loader-5768b1-ts.inventory.customers/0` message

but when this message comes and the ConsumeClaim starts after it, we dont see this issue.

🤔

**Comment by alok87** [comment]
Cant we wait for all subscription to happen before starting?

**Comment by alok87** [comment]
@dim please helpout here.

**Comment by dim** [comment]
@alok87 sorry, I have no idea what's going on here tbh. I think that there is a rebalancing issue in your cluster and your handlers cannot exit the loop quickly enough. Can you try and reduce your `ConsumeClaim` to just:

```go
for msg := range claim.Messages() {
  ...
}
```

and see if this fixes things. If it does, you can try and increase your timeout configs (this is usually the culprit). If it doesn't, you will need to do some lower-level debugging yourself (sorry), as it's really impossible for me to go through your specific use case. I am more than happy to review the PR if are able to isolate the problem.

**Comment by alok87** [comment]
thanks for the reply. I would try what you suggested.

I have been trying to figure out why only few topics out of many receive this message
`sarama] 2021/03/10 10:52:20 consumer/broker/1 added subscription to ts.inventory.customers/0`
but many never receivies it. Why could this happen?

**Comment by alok87** [comment]
@dim
thanks for the reply. I would try what you suggested.

I have been trying to figure out why only few topics out of many receive this message
`sarama] 2021/03/10 10:52:20 consumer/broker/1 added subscription to ts.inventory.customers/0`
but many never receivies it. Why could this happen?

**Comment by alok87** [comment]
Keeping `for msg := range claim.Messages() {` this did not help.

My consumers are really slow which all values would require tuning?
I have kept maxProcessTime to 20mins, sessionTimeout to 2mins, heartBeat at 2seconds and reBalance timeout to 5mins

I keep seeing these messages still https://github.com/Shopify/sarama/blob/master/consumer.go#L826

also `added subscription` comes for few topics only and not all.

**Comment by dim** [comment]
Sorry, I haven't worked with Kafka for quite some time, but timeouts are documented e.g. in https://github.com/Shopify/sarama/blob/master/config.go#L261 and you can find more information at https://kafka.apache.org/documentation/ as the server and client settings need to be aligned.

The `"consumer/broker/%d closed dead subscription ..."` messages are triggered when the subscription is closed in https://github.com/Shopify/sarama/blob/master/consumer_group.go#L686 or https://github.com/Shopify/sarama/blob/master/consumer_group.go#L695. This happens when the first of your `ConsumeClaim` loops exists. Please note that whatever happens in `ConsumeClaim`  MUST be thread-safe, as it's called once per topic/partition claim.

The fact that `"added subscription"` comes up for a few and not all topic/partitions could just mean that the other topic/partitions are still claimed by a previous process. The algorithm for consumer groups is complex, but TLDR:

1. a consumer issues a `JoinGroup` request and receives a list of members + the ID of the elected group leader
2. if the consumer is the leader, it works out an "assignment plan" to distribute the partitions across the members
3. all consumers within a group issue a `SyncGroup` request, the elected leader also includes the "assignment plan"
4. each consumer receives the "assignment plan" an part of the `SyncGroup` response and subscribes to the topics/partitions it has been allocated

Obviously, there are various timeouts, e.g. all consumers within a group must issue a `SyncGroup` request in time and also must continue their heartbeat, etc. You should check the logs of your broker too. They are verbose but they will eventually tell you what happens and why. 

Hope that helps!

**Comment by alok87** [comment]
Thank you @dim. Your TLDR; really helped me understand the complicated operation here. 👍🏽  👍🏽 

I added many debug prints to find the cause of this issue. I feel I am very close this time. 

Logs for the subscription manager with debug flags. [Code with debug info added, v1.27.2](https://gist.github.com/alok87/d9d08a95b3af38eea7e374339f66c199)
```
I0311 10:53:17.214777 767] subscriptionManager() received db.inventory.my_customers, buffer(0)=[]
I0311 10:53:17.214788 769] subscriptionManager() received db.inventory.my_customers, buffer(1)=[0xc0000a6a00] (appended)
I0311 10:53:17.214834 758] subscriptionManager() bc.wait()
I0311 10:53:17.214972 755] subscriptionManager() sent buffer(1)=[0xc0000a6a00], buffer set nil
I0311 10:53:17.214987 767] subscriptionManager() received db.inventory.payment_transactions, buffer(0)=[]
I0311 10:53:17.214996 769] subscriptionManager() received db.inventory.payment_transactions, buffer(1)=[0xc0000a68c0] (appended)
I0311 10:53:17.215049 751] subscriptionManager() received db.inventory.user_profile, buffer(1)=[0xc0000a68c0]
I0311 10:53:17.215057 753] subscriptionManager() received db.inventory.user_profile, buffer(2)=[0xc0000a68c0 0xc0000a7040] (appended)
I0311 10:53:17.215329 751] subscriptionManager() received db.inventory.products, buffer(2)=[0xc0000a68c0 0xc0000a7040]
I0311 10:53:17.215339 753] subscriptionManager() received db.inventory.products, buffer(3)=[0xc0000a68c0 0xc0000a7040 0xc0002ea640] (appended)
I0311 10:53:17.215424 751] subscriptionManager() received db.inventory.order, buffer(3)=[0xc0000a68c0 0xc0000a7040 0xc0002ea640]
I0311 10:53:17.215440 753] subscriptionManager() received db.inventory.order, buffer(4)=[0xc0000a68c0 0xc0000a7040 0xc0002ea640 0xc0002ea320] (appended)
I0311 10:53:17.230462 767] subscriptionManager() received db.inventory.calls, buffer(0)=[]
I0311 10:53:17.230484 769] subscriptionManager() received db.inventory.calls, buffer(1)=[0xc0002ea1e0] (appended)
I0311 10:53:17.230498 758] subscriptionManager() bc.wait()
I0311 10:53:17.230581 755] subscriptionManager() sent buffer(1)=[0xc0002ea1e0], buffer set nil
```

Subscription happened to 3 out of 14.
```
[sarama] 2021/03/11 10:53:17 consumer/broker/2 added subscription to db.inventory.my_customers/0
[sarama] 2021/03/11 10:53:17 consumer/broker/1 added subscription to db.inventory.calls/0
[sarama] 2021/03/11 10:53:17 consumer/broker/0 added subscription to db.inventory.vn_call_forwardings/0
```

The buffer is getting reset to 0, without being flushed to the `bc.newSubscriptions` channel. I am still debugging if it is due to the issue in my enviroment or not.

But it could be because the buffer slice is being passed to `bc.newSubscriptions` channel. And the slice is being changed by some other downstream code. 

Please suggest. I am continuing to debug.

**Comment by alok87** [comment]
Update: Found the `subscriptionManager()` and `subscriptionConsumer()` repeatedly getting called which is leading to buffer getting reintialized. What is `withRecover()`. Trying to figure out why it is repeatedly getting called?

**Comment by alok87** [comment]
@dim Thank you for the TLDR;  and taking time to explain this. Means a lot.

I have tried to debug this issue and have found `subscriptionManager()` and `subscriptionConsumer()` are being called for all 3 brokers. And each are trying to make subscription live for the topics they have under.

Below is the log for `subscriptionManager()` and `subscriptionConsumer()` for one of the brokers: [Code for the extra debug prints.](https://gist.github.com/alok87/54d0717a241f68f26d9c0375945f4175)
```
I0311 15:19:56.201188  790] subscriptionConsumer(broker2) STARTING FOR LOOP
I0311 15:19:56.201251  792] subscriptionConsumer(broker2) waiting
I0311 15:19:56.201151  742] subscriptionManager(broker2) STARTING FOR LOOP
I0311 15:19:56.201330  768] subscriptionManager(broker2) received loader-5768b1-ts.fabric.payment_transactions, buffer(0)=[]
I0311 15:19:56.201377  770] subscriptionManager(broker2) received loader-5768b1-ts.fabric.payment_transactions, buffer(1)=[0xc000134c80] (appended)
I0311 15:19:56.201443  759] subscriptionManager(broker2) bc.wait()
I0311 15:19:56.201453  794] subscriptionConsumer(broker2) resuming...
I0311 15:19:56.201461  797] subscriptionConsumer(broker2) updating newSubscription=[0xc000134c80]
I0311 15:19:56.201468  829] updateSubscriptions(loader-5768b1-ts.fabric.payment_transactions)
[sarama] 2021/03/11 15:19:56 consumer/broker/2 added subscription to loader-5768b1-ts.fabric.payment_transactions/0
I0311 15:19:56.201483  808] subscriptionConsumer(broker2) fetchNewMessages()
I0311 15:19:56.201553  756] subscriptionManager(broker2) sent buffer(1)=[0xc000134c80], buffer set nil
I0311 15:19:56.201689  768] subscriptionManager(broker2) received loader-5768b1-ts.fabric.my_doctors, buffer(0)=[]
I0311 15:19:56.201700  770] subscriptionManager(broker2) received loader-5768b1-ts.fabric.my_doctors, buffer(1)=[0xc000134a00] (appended)
I0311 15:19:56.202710  752] subscriptionManager(broker2) received loader-5768b1-ts.fabric.appointments, buffer(1)=[0xc000134a00]
I0311 15:19:56.202818  754] subscriptionManager(broker2) received loader-5768b1-ts.fabric.appointments, buffer(broker2)=[0xc000134a00 0xc000134b40] (appended)
I0311 15:19:56.202831  752] subscriptionManager(broker2) received loader-5768b1-ts.fabric.practices, buffer(broker2)=[0xc000134a00 0xc000134b40]
I0311 15:19:56.202839  754] subscriptionManager(broker2) received loader-5768b1-ts.fabric.practices, buffer(3)=[0xc000134a00 0xc000134b40 0xc000134f00] (appended)
I0311 15:19:56.202846  752] subscriptionManager(broker2) received loader-5768b1-ts.fabric.user_profile, buffer(3)=[0xc000134a00 0xc000134b40 0xc000134f00]
I0311 15:19:56.202945  754] subscriptionManager(broker2) received loader-5768b1-ts.fabric.user_profile, buffer(4)=[0xc000134a00 0xc000134b40 0xc000134f00 0xc000135400] (appended)
```


This is happening for all 3 brokers we have.
The subscription manager is stuck waiting for the buffer to be sent to bc.newSubscriptions after we have set the buffer = nil once.

Please suggest if you see a problem here.

**Comment by alok87** [comment]
Found the second batch of buffer is not going because the previous subscriptionConsumer is stuck waiting for ACK `bc.acks.Wait()` https://gist.github.com/alok87/d9d08a95b3af38eea7e374339f66c199#file-gistfile1-go-L83

why it is stuck there 😢

**Comment by alok87** [comment]
@dim I found the problem.

I have slow consumers and my `maxProcessingTime` is huge due to that.

##Problem
If say a broker is handling 10 topics and we want all to get subscribed. But suppose in the first flush of buffer (`bc.newSubscriptions <- buffer`) only one topic went. Then the other 9 can never get subscribed until the maxProcessingTime passes.

How to go around this problem?

**Comment by dim** [comment]
@alok87 glad to hear. As said before, I am not a core maintainer of Sarama, I just contributed the original consumer group patch, but looking at https://github.com/Shopify/sarama/pull/1899 you seem to be in good hands :)

**Comment by alok87** [comment]
thanks @dim again for the help.

**Comment by jasimsulaiman** [comment]
One suggestion to workaround this is:
`func (c *consumer) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	for {
		select {
		case <-session.Context().Done():
			return nil

		case message := <-claim.Messages():
			if message == nil || session.Context().Err() != nil { // if context was cancelled and claim has messages select is random
				return nil
			}

			ch := make(chan bool)
			go func() {
				ch <- c.handleMessage(session.Context(), message)
			}()

			select {
			case <-session.Context().Done():
				shouldCommit := <-ch // wait for current processing message to complete - do not do this if processing time can be more than rebalance timeout
				commitOffset(shouldCommit, session, message)
				return nil

			case shouldCommit := <-ch:
				commitOffset(shouldCommit, session, message)
				continue
			}
		}
	}
}`

**Comment by SakalyaDeshpande** [comment]
I also have a long running process that takes 5 minutes and maxprocessing time is adjusted accordingly(set to 10 minutes). Our kafka consumer group is consuming same message again and again when our application in crashed/panics and kubernetes is restarting it. it generally works fine if we do a restart of application but if application is in crash state, it keeps on replaying the same last message

**Comment by dnwe** [comment]
This should now be fixed on main
