### ISSUE TITLE
Route53 issues

### ISSUE THREAD

**Issue by jackingle** [Shopify/sarama#1915]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|v1.27.1|aiven 2.7|1.14|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
tlsConfig := tls.Config{}
caCertPool := x509.NewCertPool()
	caCertPool.AppendCertsFromPEM(caCertUSW2)
	caCertPool.AppendCertsFromPEM(caCertUSE1)
	tlsConfig.RootCAs = caCertPool
config := sarama.NewConfig()
	config.Producer.Return.Successes = true
	config.Net.TLS.Enable = true
	config.Net.TLS.Config = tlsConfig
	config.Version = sarama.V0_10_2_0
	config.Net.SASL.Handshake = true
	config.Net.SASL.Enable = true
	config.Net.SASL.User = "XXXXXX"
	config.Net.SASL.Password = "XXXXXX"
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.
* I wasn't aware of this logger and will include the terminal output.
<details><summary>logs: CLICK ME</summary>
<p>
NewSyncProducer <nil> kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

</p>
</details>

##### Problem Description

We are trying to utilize route53 with aiven kafka as the solution.  We have worked with their experts who are not sure why the overall solution won't work.  My code is fine for directly hitting the service.  There are two issues with using a route 53 endpoint as the broker URL.
One is that if you utilize t509 certificates then hostname validation will cause a failure.  The workaround is to set something like
```go
tlsConfig.ServerName = "dyanmciaivenurl"
```
The second issue we noticed is that providing this route53 URL to the SyncProducer results in a Kafka not leader for partition error.  

Could we get some help on these two issues?

To reproduce:
Setup a free account with aiven.
Setup route53 for aiven dynamic url.
Write a producer with your route53 url.
Attempt to produce messages.

**Comment by dnwe** [comment]
@jackingle you'd need to include the full logger output for us to diagnose further, and you haven't described your Route53 configuration, but I imagine that the issue you are seeing is that the initial connection to the hostnames you provide to Sarama are simply used to "bootstrap" connectivity to the cluster, and then the client will rely on the hostnames returned in the "advertised listeners" configuration on the server side for determining how to connect to each broker in the cluster. Unless you've a) got a 1:1 mapping of brokers to route53 hostnames and b) overridden the advertised listeners with the route53 hostnames, then you will be unlikely to be able to connect successfully

**Comment by jackingle** [comment]
Apologies for the miss. For Route53 we're strictly routing direct 
`route53uri.io > aivendyanmicurl.com`
One important piece to note if you haven't gotten the chance to check is that with Aiven Kafka you do not have access to brokers.  You provide an Aiven URL in the place you would provide a broker.  As such our 1:1 mapping is route53 hostname to aiven hostname.

**Comment by prem-aiven-io** [comment]
@dnwe -
The use case @jackingle is referring to is a small extension to Sarama go library to disable hostname validation. Kafka SASL client library allows for this by setting property "ssl.endpoint.identification.algorithm" to "" essentially asking to disable hostname validation. Why would one need to disable hostname validation? It is for cases where you would like a CNAME mapping like "kafka.mydomain" (in for e.g. route53) to point to the actual Kafka cluster with "actual.kafka.cloud.com". Is this making sense?

**Comment by prem-aiven-io** [comment]
@jackingle - the following will do what you are looking for. I've verified it. No changes in Sarama go is required.
https://github.com/digitalbitbox/bitbox-wallet-app/blob/b04bd07852d5b37939da75b3555b5a1e34a976ee/backend/coins/btc/electrum/electrum.go#L76-L111
