### ISSUE TITLE
SASL SCRAM is not working with Kafka 0.11.0.0 cluster (works with 2.0.0.0)

### ISSUE THREAD

**Issue by sunyu129** [Shopify/sarama#1918]
kafka version: 0_11_0_0
go version: 1.12
sarama version: v1.28.0
command: ./... -brokers x.x.x.x:9094,x.x.x.x:9094,x.x.x.x:9094-username xxxx -passwd xxxx@123 -algorithm sha256

logs:
[Sarama] 2021/04/22 09:33:03 Initializing new client
[Sarama] 2021/04/22 09:33:03 client/metadata fetching metadata for all topics from broker x.x.x.x:9094
[Sarama] 2021/04/22 09:33:03 Failed to read SASL handshake header : EOF
[Sarama] 2021/04/22 09:33:03 Closed connection to broker x.x.x.x:9094
[Sarama] 2021/04/22 09:33:03 client/metadata got error from broker -1 while fetching metadata: EOF
[Sarama] 2021/04/22 09:33:03 client/metadata fetching metadata for all topics from broker x.x.x.x:9094
[Sarama] 2021/04/22 09:33:04 Failed to read SASL handshake header : EOF
[Sarama] 2021/04/22 09:33:04 Closed connection to broker x.x.x.x:9094
[Sarama] 2021/04/22 09:33:04 client/metadata got error from broker -1 while fetching metadata: EOF
[Sarama] 2021/04/22 09:33:04 client/metadata fetching metadata for all topics from broker x.x.x.x:9094
[Sarama] 2021/04/22 09:33:04 Failed to read SASL handshake header : EOF
[Sarama] 2021/04/22 09:33:04 Closed connection to broker x.x.x.x:9094

when i upgrade kafka version to 2_0_0_0 
it is working
[Sarama] 2021/04/22 09:32:59 Initializing new client
[Sarama] 2021/04/22 09:32:59 client/metadata fetching metadata for all topics from broker x.x.x.x:9094
[Sarama] 2021/04/22 09:32:59 Successful SASL handshake. Available mechanisms: [PLAIN SCRAM-SHA-512 SCRAM-SHA-256]
[Sarama] 2021/04/22 09:32:59 SASL authentication succeeded
[Sarama] 2021/04/22 09:32:59 Connected to broker at x.x.x.x:9094 (unregistered)

**Comment by zhaomoran** [comment]
Sarama only support SaslHandshakeRequest V,but Kafka 0.11.0.0 needs SaslHandshakeRequest V0,refer to [kafka protocol](https://kafka.apache.org/protocol.html#sasl_handshake). I have finish the code , and I will commit it later!
