### ISSUE TITLE
Can't build in 32-bit

### ISSUE THREAD

**Issue by aaronbee** [Shopify/sarama#1943]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.29.0 | * | v1.16.4 |

##### Problem Description

Sarama fails to build in 32-bit mode.

```
github.com/Shopify/sarama/gssapi_kerberos.go:62:10: constant 4294967295 overflows int
```

This is the code from gassapi_kerberos.go:
```go
func (krbAuth *GSSAPIKerberosAuth) writePackage(broker *Broker, payload []byte) (int, error) {
	length := len(payload)
	size := length + 4 // 4 byte length header + payload
	if size > math.MaxUint32 { // <<< math.MaxUint32 overflows `int` in 32-bit
		return 0, errors.New("payload too large, will overflow uint32")
	}
```

You could change the line setting length to be: `length := uint64(len(payload))`

**Comment by dnwe** [comment]
Fix is merged and can be used straight away with `go get github.com/Shopify/sarama@HEAD` — will spend a few days seeing if there are any other merges to make before cutting another point release
