### ISSUE TITLE
How can the consumer manually confirm the message and retry if it fails?

### ISSUE THREAD

**Issue by liuaiyuan** [Shopify/sarama#1958]
How can the consumer manually confirm the message and retry if it fails???? 

```go

func (h *Handler) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {

	for msg := range claim.Messages() {
		log.Printf("Message claimed: value = %s, timestamp = %v, topic = %s", string(msg.Value), msg.Timestamp, msg.Topic)
		if err := h.Find(); err != nil {
			// Retry ????
		} else {
			session.MarkMessage(msg, "")
		}
	}
	return nil
}

```

**Comment by nordicdyno** [comment]
you can return nil from ConsumeClaim, probably it can lead to rebalance, because this is effectively a session recreation, but I'm not sure is it always true and how dangerous it's in terms of performance (especially with a lot of consumers)
