### ISSUE TITLE
probably a dead cycle bug in subsciptionManager, which make cpu cost high in idle status

### ISSUE THREAD

**Issue by leiminghany** [Shopify/sarama#1976]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

##### Problem Description

When I use saram to consumer for a consumer group, there is no new message. but the cpu cost is alway 1%
I already set `config.Consumer.MaxProcessingTime = time.Second * 5`

after research, I find the codes that using cpu is in the function `subscriptionManager`， and the following line is alway executed
https://github.com/Shopify/sarama/blob/0676fc297fca0c5dfba927c0c4f6925ce2ae1e77/consumer.go#L778

which made the cycle  https://github.com/Shopify/sarama/blob/0676fc297fca0c5dfba927c0c4f6925ce2ae1e77/consumer.go#L795  is alway run without even a sleep.

maybe, the `<-bc.wait // wait for our first piece of work` should moved into the for cycle。as followwed:
```
func (bc *brokerConsumer) subscriptionConsumer() {
	for newSubscriptions := range bc.newSubscriptions {
                <-bc.wait // wait for our first piece of work
		bc.updateSubscriptions(newSubscriptions)
```

**Comment by j3st5x** [comment]
This is the main worker go routine that constantly fetches new messages from the broker and it should only block on `bc.wait` if there are no "active" `subscriptions` yet. In case new subscriptions arrive, the `subscriptionConsumer` will pick them up and update the `subscriptions` after finishing it's last fetch and otherwise should keep fetching data.

**Comment by leiminghany** [comment]
> This is the main worker go routine that constantly fetches new messages from the broker and it should only block on `bc.wait` if there are no "active" `subscriptions` yet. In case new subscriptions arrive, the `subscriptionConsumer` will pick them up and update the `subscriptions` after finishing it's last fetch and otherwise should keep fetching data.

why give the nil to the bc.newSubscriptions ?  could this line https://github.com/Shopify/sarama/blob/0676fc297fca0c5dfba927c0c4f6925ce2ae1e77/consumer.go#L778  be deleted?

**Comment by j3st5x** [comment]
> > This is the main worker go routine that constantly fetches new messages from the broker and it should only block on `bc.wait` if there are no "active" `subscriptions` yet. In case new subscriptions arrive, the `subscriptionConsumer` will pick them up and update the `subscriptions` after finishing it's last fetch and otherwise should keep fetching data.
> 
> why give the nil to the bc.newSubscriptions ? could this line
> 
> https://github.com/Shopify/sarama/blob/0676fc297fca0c5dfba927c0c4f6925ce2ae1e77/consumer.go#L778
> be deleted?
> 
> it cause the wast of cpu

When you delete this line the range loop over the new subscriptions would block until new subscriptions arrive which is, again, not what you want. Instead, if there are no new subscriptions (`nil` in `newSubscriptions`) you just want to go on with fetching data. On the other hand, as soon as new subscriptions arrive, you want to finish the ongoing fetch, then update the `subscriptions` and go on with fetching data, as explained in the comment of `subscriptionManager`.
