### ISSUE TITLE
Allow disable auto topic creation on client side

### ISSUE THREAD

**Issue by zifengyu** [Shopify/sarama#1982]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
|  v1.29.0 |  2.7.0  |  1.16.5  |

##### Configuration

What configuration values are you using for Sarama and Kafka?

Both arewith default settings. (Broker has `auto.create.topics.enable` = true)

##### Problem Description

In our environment, Kafka topics are manually created and deleted by one management program. We do not wish the other client programs with sarama to create new topics when producing to/subscribing a no longer exsiting topic. It is also not an option for us to disable the auto topic creation on broker level as this will impact other business department.

##### Proposal 
Allow user to set `allow_auto_topic_creation` argument in the metadata request and expose it as a configuration.

**Comment by dnwe** [comment]
Closed via #1983 - thanks @zifengyu
