### ISSUE TITLE
Offset Fetch/Commit Support

### ISSUE THREAD

**Issue by eapache** [Shopify/sarama#2]
The Consumer should make use of https://cwiki.apache.org/confluence/display/KAFKA/Offset+Management

The golang protocol backend already supports those request/response types, but the current Kafka 0.8 beta 1 seems to choke on them so I didn't add them to the API.

I suspect this will consist of doing a Fetch on construction of a Consumer, then adding a Commit(offset) api call that the consumer user can call as appropriate. The python bindings have an autocommit option, but I think that's overcomplicated for our needs, at least to start.

**Comment by sybrandy** [comment]
Has there been any recent work on this?  I got a copy of Sarama a couple weeks ago and I'm trying to do manual offset commits to Kafka, but when I do a OffsetFetch to confirm that I committed, I get back an empty map.  As far as I know, Kafka is configured correctly (offsets.storage=kafka), so I'm wondering if perhaps the version I have is missing something.

**Comment by wvanbergen** [comment]
There's no progress on this. You could check out https://github.com/wvanbergen/kafka/tree/master/consumergroup, which, besides load balancing and failover, manages offsets using zookeeper.

**Comment by sybrandy** [comment]
Any ETA on when manual commits will work?

**Comment by eapache** [comment]
Kafka 0.8.2.0 introduced a new version of this API which *still* has not been documented [1]. There's not much we can do until we know how it actually works.

That email thread seems to imply that the old v0 API should still work, but we do implement the documented spec so I'm not sure why it wouldn't be working for you.

[1] https://mail-archives.apache.org/mod_mbox/kafka-users/201502.mbox/%3CCAA4pprC67juiUrnhiv%2Bg9eQ9ZM12UjFyaEkC-Af22%3D6fHZ6QrA%40mail.gmail.com%3E

**Comment by jsvisa** [comment]
Thanks @wvanbergen I've got too much time in wounding my own kafka cluster's config,  I'm so curious about in kafka 0.8.2-beta I fetch `ConsumerMetadataRequest` , then get the `Coordinator`. But in 0.8.2.0 or 0.8.2.1, it always return  [ErrConsumerCoordinatorNotAvailable](https://github.com/Shopify/sarama/blob/master/errors.go#L89)

**Comment by wvanbergen** [comment]
Unfortunately we have no experience with this API ourselves. Your best guess is to ask on the kafka mailing list on how this API is usppoed to work: http://kafka.apache.org/contact.html

**Comment by joestein** [comment]
The Coordinator is being worked on apache kafka trunk now for next release. Some more details here https://cwiki.apache.org/confluence/display/KAFKA/Kafka+0.9+consumer+protocol about that. It doesn't have any overlap here except that the new consumer will also use this method of storage offset maybe even default that way.

Kafka 0.8.2.1 supports kafka as the storage for offsets. The storage of offets by kafka is the offset fetch and commit request/response usage. This is great because in your code you can subvert using zookeeper in consumers and use kafka https://github.com/stealthly/go_kafka_client/pull/80 for offset storage instead.

**Comment by wvanbergen** [comment]
I started working on this in https://github.com/Shopify/sarama/pull/379.

There's still some outstanding questions and gaps in the implementation, but it's mostly working. @jsvisa the reason why you get `ErrConsumerCoordinatorNotAvailable`, is that initially the coordinator does not exists. However, the request will trigger its creation, and if you retry the request you will get a useful response.

**Comment by eapache** [comment]
#461 (released in v1.6) implemented Kafka-based offset management. It's not fully integrated into the consumer yet, but there's not much point until the 0.9 consumer protocol is available.
