### ISSUE TITLE
write tcp . write: broken pipe issue while producing

### ISSUE THREAD

**Issue by anjulapaulus** [Shopify/sarama#2004]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|-----------|----------|--------|
| 1.29.1 | v2.0.0 | 1.15.6 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
        conf := sarama.NewConfig()
	conf.ClientID = fmt.Sprintf(`%s-%s`, config.Id, `simple-consumer`)
	conf.Version = sarama.V2_0_0_0
	conf.Producer.RequiredAcks = -1 //Wait for all
	conf.Producer.Return.Errors = true
	conf.Producer.Return.Successes = true
	conf.Producer.Idempotent = false
	conf.Net.MaxOpenRequests = 1
	conf.Producer.Compression = sarama.CompressionSnappy
	conf.Producer.Partitioner = sarama.NewHashPartitioner

	conf.Producer.Retry.Max = config.Retry
	conf.Producer.Retry.Backoff = config.RetryBackOff
```
These are the only configurations we hold in the library and rest we use the defaults.

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>
write tcp  127.0.0.1:9092: write: broken pipe
</p>
</details>

##### Problem Description
I am encountering a write tcp broken pipe error while producing to kafka in one of our services. We have a wrapper library for sarama that we use for our services. We had an upgrade done on sarama versions recently from 1.20.0 to 1.29.1 and it was working fine in our development environment. After keeping it in for days we started encountering problems producing due the write broken pipe issues on that service which we had the upgrade of the version with the changes done. Mind that we only changed the sarama version but our services with the older versions worked without any issues. Could I get a clarification on why it happens with the service that the sarama version upgrade was done? Sorry I can only provide the following line without the broker IP.

**Comment by anjulapaulus** [comment]
@varun06 Could you have a look and inform me if any changes are needed?

**Comment by varun06** [comment]
I see another issue related to this -> https://github.com/Shopify/sarama/issues/1565

**Comment by anjulapaulus** [comment]
@varun06 The issue was sorted. The producer retries were set to 0 by our library. We cannot always mitigate the chances of having a tcp timeout but having retries set could solve it to some extent.

**Comment by varun06** [comment]
Glad that it worked out.
