### ISSUE TITLE
GSSAPI Kerberos connection fails：Error while performing GSSAPI Kerberos Authentication: EOF

### ISSUE THREAD

**Issue by daysomeon** [Shopify/sarama#2027]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.29.1 | 2.0.1 | 1.13.11 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
config.Version = sarama.V2_0_1_0
config.Net.SASL.Enable = true
config.Net.SASL.Mechanism = sarama.SASLTypeGSSAPI
config.Net.SASL.GSSAPI = sarama.GSSAPIConfig{
    AuthType:           sarama.KRB5_KEYTAB_AUTH,
    ServiceName:        "kafka",
    KeyTabPath:         "/root/kafka.service.keytab",
    Realm:              "TEST.COM",
    Username:           "kafka/centos7",
    KerberosConfigPath: "/etc/krb5.conf",
}
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
[Sarama]2021/09/14 15:47:38 client.go:141: Initializing new client
[Sarama]2021/09/14 15:47:38 config.go:544: ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[Sarama]2021/09/14 15:47:38 config.go:544: ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[Sarama]2021/09/14 15:47:38 client.go:884: client/metadata fetching metadata for all topics from broker bmr-node8:9092
[Sarama]2021/09/14 15:47:38 gssapi_kerberos.go:246: Error while performing GSSAPI Kerberos Authentication: EOF
[Sarama]2021/09/14 15:47:38 broker.go:193: Closed connection to broker bmr-node8:9092
[Sarama]2021/09/14 15:47:38 client.go:927: client/metadata got error from broker -1 while fetching metadata: EOF
[Sarama]2021/09/14 15:47:38 client.go:938: client/metadata no available broker to send metadata request to
[Sarama]2021/09/14 15:47:38 client.go:674: client/brokers resurrecting 1 dead seed brokers
[Sarama]2021/09/14 15:47:38 client.go:868: client/metadata retrying after 250ms... (3 attempts remaining)
```

</p>
</details>

##### Problem Description
when i use latest sarama(1.29.1）to connection kafka fails，then set sarama.Logger，get following error：
[Sarama]2021/09/14 15:47:38 gssapi_kerberos.go:246: Error while performing GSSAPI Kerberos Authentication: EOF

so i seach keyword in issues，i got some information by #1658 and try  revert sarama version to 1.23.0，but it still has the same error，how to solve this problem？

**Comment by slivewo** [comment]
Can you tell me how you solved this problem, I ran into it too.
