### ISSUE TITLE
[Feature Request] Implement KIP-511

### ISSUE THREAD

**Issue by splett2** [Shopify/sarama#2043]
#### Is your feature request related to a problem? Please describe.
Many other commonly used clients(java clients, librdkafka clients) have implemented KIP-511 which helps kafka cluster operators identify client types, and client versions connecting to their cluster. Sarama clients not reporting the software name/version can get conflated with older clients that do not report this information at all, giving a cluster operator an inaccurate view of their cluster's clients.

#### Describe the solution you'd like
Implement client-side changes for KIP-511.

**Comment by splett2** [comment]
actually woops, just saw that #2025 was merged 2 weeks ago. sorry for the noise!

**Comment by dnwe** [comment]
@splett2 👋🏻 no worries — please test with the current code on the main branch and let us know if it is working for you, as we haven't yet cut a release with these changes in yet
