### ISSUE TITLE
Feature Suggestion: Make high water marks immediately available in partition consumers

### ISSUE THREAD

**Issue by joewreschnig** [Shopify/sarama#2056]
Currently the [high water mark of a `partitionConsumer` isn't filled in until it's processed at least one fetch response](https://github.com/Shopify/sarama/blob/712b6bb89287b4767557cc4bf9883148b4979a85/consumer.go#L639). This makes life hard for consumers e.g. reading compaction topics from the start that want to delay until they have reasonably "caught up" to the topic end, in the case when the topic is empty. You need to either detect this from the `Client` (which may not be available if you used e.g. `NewConsumer` or want your code to also work with mock consumers), or assume no HWM within some time span is an empty topic, or put a dummy first message in all such topics.

I think [during `chooseStartingOffset`, the HWM could be filled in from the `offsetNewest` lookup](https://github.com/Shopify/sarama/blob/v1.30.0/consumer.go#L397). This would make it available by the time `ConsumePartition` returns.

**Comment by grongor** [comment]
Hello, I also encountered this issue and was surprised that it works this way, and just worked around it. But now, after reading your great description with a solution basically in there, I went ahead and created PR: https://github.com/Shopify/sarama/pull/2082

**Comment by grongor** [comment]
Good point. To be honest, I'm not that deep into Kafka, or Sarama, so...not sure. But when I look at this:
```go
func (client *client) getOffset(topic string, partitionID int32, time int64) (int64, error) {
	broker, err := client.Leader(topic, partitionID)
	if err != nil {
		return -1, err
	}

	request := &OffsetRequest{}
	if client.conf.Version.IsAtLeast(V0_10_1_0) {
		request.Version = 1
	}
	request.AddBlock(topic, partitionID, time, 1)

	response, err := broker.GetAvailableOffsets(request)
```
... and this:
```go
type OffsetRequest struct {
	Version        int16
	IsolationLevel IsolationLevel
	replicaID      int32
	isReplicaIDSet bool
	blocks         map[string]map[int32]*offsetRequestBlock
}

func (r *OffsetRequest) encode(pe packetEncoder) error {
	if r.isReplicaIDSet {
		pe.putInt32(r.replicaID)
	} else {
		// default replica ID is always -1 for clients
		pe.putInt32(-1)
	}

	if r.Version >= 2 {
		pe.putBool(r.IsolationLevel == ReadCommitted)
	}
```
then I would say that all we need to do is use v2 (or newer, if any) when applicable. WDY?

**Comment by joewreschnig** [comment]
The `ReadCommitted` isolation level is only relevant for transactional producers/consumers, I think, not the general idea of data "committed" by completing replication.  But in the end I'm fine with what got merged, we don't depend on absolutely monotonic HWMs especially in such an edge case. Thanks for doing the actual work! :)
