### ISSUE TITLE
why not use ioutil package to support  go versions less than 1.16

### ISSUE THREAD

**Issue by ZQHcode** [Shopify/sarama#2062]

**Comment by dnwe** [comment]
k8s.io/client-go and others have similarly moved towards a minimum of Go 1.16 in recent months and we only test and maintain Sarama on the most event two major releases of Go. Unfortunately we don’t have a large enough pool of maintainers to cover more. Go 1.15 and earlier no longer receive security updates and are unsupported by the Go team so I’d strongly recommend that you update your toolchain
