### ISSUE TITLE
Can consumergroup set offset to consume messages?

### ISSUE THREAD

**Issue by xiyichan** [Shopify/sarama#2134]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.29.0 | 2.13-2.8.1 | 1.15 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	config := sarama.NewConfig()
	config.Producer.Return.Successes = true
	config.Consumer.Offsets.Initial = -2
	config.Version = sarama.V2_8_0_0
```
##### Problem Description
I can use kafka .sh to set consumergroup offset, can sarama do it?
https://gist.github.com/marwei/cd40657c481f94ebe273ecc16601674b

**Comment by tongyi24** [comment]
> > you can use `session.ResetOffset()` in the `Setup` method of the `ConsumerGroupHandler`你可以在 `ConsumerGroupHandler` 的 `Setup` 方法中使用 `session.ResetOffset()` 
> > i try to use this,but sometime it can't work. Maybe wait a few miute can work again.我尝试使用这个，但有时它不能工作。也许等待几分钟可以再次工作。
> 
> package main
> 
> import (
> 	"context"
> 	"fmt"
> 	"github.com/Shopify/sarama"
> 	"strconv"
> 	"time"
> )
> 
> type exampleConsumerGroupHandler struct{}
> 
> func (exampleConsumerGroupHandler) Setup(sess sarama.ConsumerGroupSession) error {
> 	sess.ResetOffset("test-8451455065652989673", 0, 0, "123112312321312321221213131")
> 	return nil
> }
> func (exampleConsumerGroupHandler) Cleanup(_ sarama.ConsumerGroupSession) error { return nil }
> func (h exampleConsumerGroupHandler) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
> 	for msg := range claim.Messages() {
> 		fmt.Printf("Message topic:%q partition:%d offset:%d\n", msg.Topic, msg.Partition, msg.Offset)
> 		sess.MarkMessage(msg, "")
> 	}
> 	return nil
> }
> 
> func consume() {
> 	config := sarama.NewConfig()
> 	config.Version = sarama.V3_1_0_0 // specify appropriate version
> 	config.Consumer.Return.Errors = true
> 
> 	group, err := sarama.NewConsumerGroup([]string{"localhost:9092"}, "aaaa", config)
> 	if err != nil {
> 		panic(err)
> 	}
> 	defer func() { _ = group.Close() }()
> 
> 	// Track errors
> 	go func() {
> 		for err := range group.Errors() {
> 			fmt.Println("ERROR", err)
> 		}
> 	}()
> 
> 	// Iterate over consumer sessions.
> 	ctx := context.Background()
> 	for {
> 		fmt.Println("1111")
> 		topics := []string{"test-8451455065652989673"}
> 		handler := exampleConsumerGroupHandler{}
> 
> 		// `Consume` should be called inside an infinite loop, when a
> 		// server-side rebalance happens, the consumer session will need to be
> 		// recreated to get the new claims
> 		err := group.Consume(ctx, topics, handler)
> 		if err != nil {
> 			panic(err)
> 		}
> 		fmt.Println("2222")
> 	}
> }
> func produce() {
> 	config := sarama.NewConfig()
> 	config.Version = sarama.V3_1_0_0 // specify appropriate version
> 	config.Consumer.Return.Errors = true
> 	config.Producer.Return.Successes = true
> 	producer, err := sarama.NewSyncProducer([]string{"localhost:9092"}, config)
> 	if err != nil {
> 		fmt.Println(err)
> 	}
> 	for i := 0; i < 10; i++ {
> 		msg := &sarama.ProducerMessage{
> 			Topic:     "test-8451455065652989673",
> 			Value:     sarama.StringEncoder(strconv.Itoa(i)),
> 			Metadata:  "test",
> 			Partition: 0,
> 		}
> 
> 		partition, offset, err := producer.SendMessage(msg)
> 		fmt.Println(partition, offset, err)
> 
> 	}
> }
> func main() {
> 	go consume()
> 	time.Sleep(5 * time.Second)
> 
> 	//produce()
> }

you should set AutoCommit.Enable to false and  use MarkMessage after ResetOffset(move to earlier) or MarkOffset(move to newest)
