### ISSUE TITLE
kafka server: The provider group protocol type is incompatible with the other members.

### ISSUE THREAD

**Issue by J-Orange-Sun** [Shopify/sarama#2136]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| 1.24.1 | 2.5.0 | 1.16.8 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
```

</p>
</details>

**Comment by dnwe** [comment]
@J-Orange-Sun unfortunately I can't see any logs or further description of your app layout in your issue report, so it's hard for me to respond without guessing.

However, an InconsistentGroupProtocolException usually occurs when you're mixing assignment types in your consumer group. You can see in Sarama we join and pass the strategy in the JoinGroupRequest (amongst the other consumer group protocol messages): https://github.com/Shopify/sarama/blob/358c6b61e4b2241312cf7de34bacc287aa2c8efc/consumer_group.go#L407-L410

If you're missing different strategies in the same group, or mixing slightly incompatible client versions as members of the same group, then you'll hit this error

**Comment by J-Orange-Sun** [comment]
> @J-Orange-Sun不幸的是，我在您的问题报告中看不到任何日志或对您的应用程序布局的进一步描述，因此我很难在没有猜测的情况下做出回应。
> 
> 但是，当您在使用者组中混合分配类型时，通常会发生 InconsistentGroupProtocolException。您可以在 Sarama 中看到我们加入并在 JoinGroupRequest 中传递策略（在其他消费者组协议消息中）：
> 
> https://github.com/Shopify/sarama/blob/358c6b61e4b2241312cf7de34bacc287aa2c8efc/consumer_group.go#L407-L410
> 
> 如果您在同一组中缺少不同的策略，或者将稍微不兼容的客户端版本混合为同一组的成员，那么您将遇到此错误

**Comment by J-Orange-Sun** [comment]
I found the cause of the problem, there are consumers in the consumer group who use different strategies, your answer was very helpful, thank you very much.
