### ISSUE TITLE
Hardcoded small maxMessageSize

### ISSUE THREAD

**Issue by mieczkowski** [Shopify/sarama#216]
Why there is hardcoded maxMessageSize in response_header.go (https://github.com/Shopify/sarama/blob/master/response_header.go#L10) ? Without possibility to change this size there is no way to handle events with size >32MB.
Previous was 2*math.MaxUint16, now is:
const maxMessageSize = 32 \* 1024 \* 1024 // 32MB

**Comment by SalleryWang** [comment]
i want to change  MaxResponseSize to 1000 * 1024 * 1024
