### ISSUE TITLE
The ClusterAdmin api AlterPartitionReassignments can't support kafka V2.0 

### ISSUE THREAD

**Issue by systemcia** [Shopify/sarama#2163]
dear all:
    pls pay attention to the issue ,and give me some solutions,thanks very much!
##### Versions
sarama v1.29.1
kafka V2.0 
go 1.16.5

##### Logs
if i use config sarama.V2_0_0_0,got error:
failed to reassign partitions for topic: 
            kafka server: The version of API is not supported.
if use config sarama.V2_4_0_0 or sarama.MaxVersion,got error:
failed to reassign partitions for topic: 
            EOF

##### Problem Description
The ClusterAdmin api AlterPartitionReassignments can't support kafka V2.0 
if i use config sarama.V2_0_0_0,got error:
failed to reassign partitions for topic: 
            kafka server: The version of API is not supported.
if use config sarama.V2_4_0_0 or sarama.MaxVersion,got error:
failed to reassign partitions for topic: 
            EOF

**Comment by dnwe** [comment]
@systemcia I'm not sure what to suggest? That remote kafka API ([AlterPartitionReassignments](https://kafka.apache.org/protocol#The_Messages_AlterPartitionReassignments)) was added in Kafka 2.4.0 so you would need to upgrade your brokers to Kafka 2.4.0 if you want to make use of it

Before Kafka 2.4.0 the only way to achieve the same (move partition replicas around) was to use the `kafka-reassign-partitions.sh` tool to submit a json file to zookeeper which listed the topic partitions and which brokers you wanted to host the replicas.

**Comment by systemcia** [comment]
@dnwe ok ,got it , thank you !
