### ISSUE TITLE
Is the there any way to authenticate and authorize users connecting to channels and how to prevent users from pushing to channel

### ISSUE THREAD

**Issue by zytell3301** [Shopify/sarama#2179]
Hey. Sorry i am a little bit new to these stuff. I wanted to implement a chat system for exercise. What i have in mind is
the path of Telegram.
As you know such this project requires push from server to client. My problem is that:
1- How may i authenticate and authorize users that are connecting to every channel.
Lets assume that there is a channel for every group that the messages are being pushed inside it.
The problem is that if someone leaves the channel, he still can listen the channel for the messages
that are being sent.
2- I just want to push the messages just from the servers and users don't be authorized for sending 
any data from server or otherwise the users will be sending messages that are not being recorded in database.

Is there anything that supports something like this? And I'm using golang for my project.

**Comment by dnwe** [comment]
@zytell3301 thanks for looking into Sarama for your application. However, this is more of a general kafka question that anything specific to Sarama. I’d suggest researching “kafka acls and SASL” as your search terms. There are numerous good articles and presentations on the topic from a selection of cloud vendors and their developer experience people that should be able to help with this

**Comment by zytell3301** [comment]
really really thanks for you help
