### ISSUE TITLE
device or resource busy

### ISSUE THREAD

**Issue by ahamedmulaffer** [Shopify/sarama#2206]
i am getting following error
sarama] 2022/04/06 13:40:43 Failed to connect to broker srvd072ebs01:9095: dial tcp: lookup srvd072ebs01: device or resource busy

but i am able to telnet successfully
Connected to srvd072ebs01.
Escape character is '^]'.

after publishing some data its throwing the busy error
this is a kafka cluster running behind HA Proxy
im using sarama latest version

Thanks
Mike

**Comment by dnwe** [comment]
Does srvd072ebs01 have a .local suffix? I know there are some unusual behavior with static Go binaries and the .local suffix not being treated the same as with the C resolver

**Comment by dnwe** [comment]
See https://pkg.go.dev/net#hdr-Name_Resolution for some details as well as some debugging env variables to set which will show what’s going wrong in the dns lookup
