### ISSUE TITLE
Failed to connect to AWS MSK with SASL/SCRAM 

### ISSUE THREAD

**Issue by matcha-highball** [Shopify/sarama#2216]
Hello, 
I recently want to use sarama to access to AWS MSK service with  SASL/SCRAM. 
However, the support of golang on AWS site is limited. The AWS site provides a java version. 
https://catalog.us-east-1.prod.workshops.aws/workshops/5e7795af-4545-4711-9c19-b85bfd6455a9/en-US/securityencryption/saslscram/authorization

In golang side, I have input 3 parameters. 
sasl.mechanism=SCRAM-SHA-512
username="alice",
password="alice-secret"

Error: 
["Connected to broker at b-1.xxxxxx.amazonaws.com:9096 (unregistered)"] 
 ["client/metadata got error from broker b-1.xxxxxx.amazonaws.com:9096  while fetching metadata: unexpected EOF"] 

Any attempts of using SASL/SCRAM to access AWS MSK? 

Many thanks.

**Comment by matcha-highball** [comment]
I've found a way to solve it.

**Comment by d-baranowski** [comment]
Can you share?

**Comment by vjakka-intel** [comment]
@matcha-puddings ,  Could you please let me know Sarama Client code which resolved the SASL/SCRAM issue ?  I am getting similar issue .
