### ISSUE TITLE
Any ETA for a new 1.33.0 release?

### ISSUE THREAD

**Issue by ppatierno** [Shopify/sarama#2224]
Hi,
I was wondering if there is any plan and ETA for a new 1.33.0 release including interesting new stuff like the [KIP-368 support](https://github.com/Shopify/sarama/pull/2197).

@dnwe ?

**Comment by ppatierno** [comment]
@dnwe thanks! Any chance to quantify roughly "soon"? Days, weeks, months? It's just because I would like to plan a new release of the Strimzi Canary which uses Sarama and I would love to have the new improvements. Thanks!

**Comment by dnwe** [comment]
@ppatierno I'd say within the next 24-48h — I'd like to merge https://github.com/Shopify/sarama/pull/2226 and https://github.com/Shopify/sarama/pull/2227 and then cut a release
