### ISSUE TITLE
FetchOffset/CommitOffset error handling

### ISSUE THREAD

**Issue by piotrkowalczuk** [Shopify/sarama#227]
Kill me if its not related to sarama.

I have localy Kafka 8.2, im trying to fetch/commit offset. In both cases there is an error:

*Initialization*

	const (
		client        = "actions-worker-1"
		consumerGroup = "actions-workers"
		topic         = "actions"
	)

	startingOffset := int64(0)
	broker := sarama.NewBroker("localhost:9092")

	err := broker.Open(nil)
	if err != nil {
		aw.Logger.Error(err)
		return
	}
	defer broker.Close()

*Fetch Offset*

	offsetFetchRequest := sarama.OffsetFetchRequest{ConsumerGroup: consumerGroup}
	offsetFetchRequest.AddPartition(topic, 0)
	offsetFetchResponse, err := broker.FetchOffset(client, &offsetFetchRequest)
	if err != nil {
		aw.Logger.Error(err)
		return
	}

	if offsetFetchResponse.Blocks[topic][0].Err != sarama.NoError {
		aw.Logger.Error(offsetFetchResponse.Blocks[topic][0].Err) // NotCoordinatorForConsumerCode
	} else {
		startingOffset = offsetFetchResponse.Blocks[topic][0].Offset
	}

*Commit Offset*

	offsetCommitRequest := &sarama.OffsetCommitRequest{ConsumerGroup: consumerGroup}
	offsetCommitRequest.AddBlock(
		topic,
		0,
		event.Offset,
		sarama.ReceiveTime,
		"",
	)

	response, err := broker.CommitOffset(client, offsetCommitRequest)
	if err != nil {
		aw.Logger.Error(err)
		return
	} else if response == nil {
		aw.Logger.Error("Brocker returns no response")
		return
	} else if response.Errors[topic][0] != sarama.NoError {
		aw.Logger.Error(response.Errors[topic][0]) // ConsumerCoordinatorNotAvailableCode
		return
	}

I struggle with that since yesterday. Is my implementation wrong in any way? Any advice welcome :)

*Update*
Calling `bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic __consumer_offsets` helps. I would expect that it will be created automaticaly.

**Comment by edenhill** [comment]
I'm seeing this behaviour aswell.
The OffsetCommit API did not trigger this error in 0.8.1, but does in 0.8.1.1.
My bet is that we might have been a little quick on implementing the OffsetCommit API and it will not really be functional until the proper 0.9 consumer group coordinator.

**Comment by eapache** [comment]
I do not believe these APIs are functional pre-0.8.2 at all, so I wouldn't read too much into errors from 0.8.1.1. Given the edit/update on OP's original post I assume that this can effectively be closed - there's nothing here for us to do anyways besides wait for kafka to support their own API :)
