### ISSUE TITLE
Support multiple offering GroupBalancers to coordinator

### ISSUE THREAD

**Issue by ekeric13** [Shopify/sarama#2332]
When creating a consumer you specify what balancer strategy to use:

https://pkg.go.dev/github.com/Shopify/sarama#Config.Consumer

In other clients such a parameter is an array of balancers in case other consumers don't implement one of the balancers:
https://pkg.go.dev/github.com/segmentio/kafka-go#ConsumerGroupConfig

Is there a way to do this in sarama? If not this would be a good feature

**Comment by Jacob-bzx** [comment]
We also need this feature. And I create a pull request in #2339.

**Comment by dnwe** [comment]
Fixed by https://github.com/Shopify/sarama/pull/2339 (thanks [Jacob-bzx](https://github.com/Jacob-bzx)) — will be included in the next release version
