### ISSUE TITLE
Configure backward compatibility on Group.Rebalance.GroupStrategies

### ISSUE THREAD

**Issue by spongecaptain** [Shopify/sarama#2351]
In d66826a0 commit, new configuration options `Group.Rebalance.GroupStrategies` have been introduced.

But it is not backward compatibility.

If I do the below starategy set in my older code, but use the latest sarama package, will encounter `Consumer.Group.Rebalance.GroupStrategies and Consumer.Group.Rebalance.Strategy cannot be set at the same time` error. Please see https://github.com/Shopify/sarama/blob/v1.37.0/config.go#L808

```go
// config setting in my older setting
kconfig.Consumer.Group.Rebalance.Strategy = sarama.BalanceStrategyRoundRobin
```

That is because sarama always set a default value on `Group.Rebalance.GroupStrategies`. Please see https://github.com/Shopify/sarama/blob/v1.37.0/config.go#L542

The code is very confusing, util I read d66826a0 commit. Does it a violated Object-oriented design pattern? The Config should not exposed, so set `Consumer.Group.Rebalance.Strategy` and `Consumer.Group.Rebalance.GroupStrategies` can be atomic.
Just setting `Consumer.Group.Rebalance.Strategy` Deprecated is not enough.

**Comment by Jacob-bzx** [comment]
My bad. I think we can just delete this validation
```
case c.Consumer.Group.Rebalance.Strategy != nil && len(c.Consumer.Group.Rebalance.GroupStrategies) != 0:
	return ConfigurationError("Consumer.Group.Rebalance.GroupStrategies and Consumer.Group.Rebalance.Strategy cannot be set at the same time")
```
to make it compatible. 

Because `c.Consumer.Group.Rebalance.Strategy` takes precedence of `c.Consumer.Group.Rebalance.GroupStrategies`.
wdyt?

**Comment by spongecaptain** [comment]
> My bad. I think we can just delete this validation
> 
> ```
> case c.Consumer.Group.Rebalance.Strategy != nil && len(c.Consumer.Group.Rebalance.GroupStrategies) != 0:
> 	return ConfigurationError("Consumer.Group.Rebalance.GroupStrategies and Consumer.Group.Rebalance.Strategy cannot be set at the same time")
> ```
> 
> to make it compatible.
> 
> Because `c.Consumer.Group.Rebalance.Strategy` takes precedence of `c.Consumer.Group.Rebalance.GroupStrategies`. wdyt?

I does not know the internal mechanism of  saram well, If delete it has no side effect, we could delete the above `case` segment.
May u or matainer do code review on https://github.com/Shopify/sarama/pull/2352?

**Comment by dnwe** [comment]
Fixed by 2352 — thanks for raising this
