### ISSUE TITLE
SASL_SCRAM issue with AWS MKS

### ISSUE THREAD

**Issue by vjakka-intel** [Shopify/sarama#2363]
##### Versions

Sarama version    github.com/Shopify/sarama v1.37.2

| Sarama | Kafka | Go |
|--------|-------|----|
|  |  |  |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	pid, _ := uuid.GenerateUUID()
	log.Println(" ========== PID is %s ", pid)
	config.ClientID = pid
	config.Net.SASL.Enable = true
	config.Net.SASL.User = "xxxxxxxx"
	config.Net.SASL.Password = "xxxxxxxx"
	config.Net.TLS.Enable = true
	tlsConfig := &tls.Config{
		InsecureSkipVerify: true,
		ClientAuth:         0,
	}
	config.Net.TLS.Config = tlsConfig
	config.Producer.Retry.Max = 5
	config.Producer.RequiredAcks = sarama.WaitForAll
	config.Net.SASL.SCRAMClientGeneratorFunc = func() sarama.SCRAMClient { return &XDGSCRAMClient{HashGeneratorFcn: SHA512} }
	config.Net.SASL.Mechanism = sarama.SASLTypeSCRAMSHA512


```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>

2022/10/14 23:11:52 Starting a new Sarama consumer
2022/10/14 23:11:52  ========== PID is %s  40a18eb1-ddcf-788c-9bac-e6c61791f90b
[sarama] 2022/10/14 23:11:52 Initializing new client
[sarama] 2022/10/14 23:11:52 client/metadata fetching metadata for all topics from broker b-2.vjmskkafkaprisubnet.qbh0ve.c2.kafka.us-west-1.amazonaws.com:9092
[sarama] 2022/10/14 23:11:52 Failed to send SASL handshake b-2.vjmskkafkaprisubnet.qbh0ve.c2.kafka.us-west-1.amazonaws.com:9092: EOF
[sarama] 2022/10/14 23:11:52 Closed connection to broker b-2.vjmskkafkaprisubnet.qbh0ve.c2.kafka.us-west-1.amazonaws.com:9092
[sarama] 2022/10/14 23:11:52 client/metadata got error from broker -1 while fetching metadata: EOF
[sarama] 2022/10/14 23:11:52 client/metadata fetching metadata for all topics from broker b-1.vjmskkafkaprisubnet.qbh0ve.c2.kafka.us-west-1.amazonaws.com:9092
[sarama] 2022/10/14 23:11:52 Failed to send SASL handshake b-1.vjmskkafkaprisubnet.qbh0ve.c2.kafka.us-west-1.amazonaws.com:9092: EOF
[sarama] 2022/10/14 23:11:52 Closed connection to broker b-1.vjmskkafkaprisubnet.qbh0ve.c2.kafka.us-west-1.amazonaws.com:9092
[sarama] 2022/10/14 23:11:52 client/metadata got error from broker -1 while fetching metadata: EOF
[sarama] 2022/10/14 23:11:52 client/metadata no available broker to send metadata request to
[sarama] 2022/10/14 23:11:52 client/brokers resurrecting 2 dead seed brokers
[sarama] 2022/10/14 23:11:52 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama] 2022/10/14 23:11:52 client/metadata fetching metadata for all topics from broker b-2.vjmskkafkaprisubnet.qbh0ve.c2.kafka.us-west-1.amazonaws.com:9092
<p>

```
```

</p>
</details>

##### Problem Description

For AWS MSK, we have SASL/SCRAM authentication enabled. Associated secrets from AWS Secrets Manager .  The same username , passwrod , i am passing in GO  SASL.Username and password and set Mechanism as SCRAM512.

I am getting above error.  

Do we need to add any other configuration in Client code to connect to AWS MSK Server in SASL/SCRAM method ?

Please help me.

**Comment by vjakka-intel** [comment]
resolved myself

**Comment by fqlx** [comment]
How did you resolve?

**Comment by Neustradamus** [comment]
@vjakka-intel: Have you seen the question of @fqlx?
Very important...

How did you solved it?

**Comment by thom-vend** [comment]
SASL isn't enabled on port 9092 with AWS MSK
