### ISSUE TITLE
implement zero copy for performance gains

### ISSUE THREAD

**Issue by joestein** [Shopify/sarama#238]
In Kafka upstream zero copy https://www.ibm.com/developerworks/linux/library/j-zerocopy/ is used for efficiency gains https://kafka.apache.org/documentation.html#maximizingefficiency

The c librdkafka does this too.

Looking quick Go does have this ability too (I think this is it https://golang.org/src/net/sendfile_linux.go) and I believe Sarama would greatly benefit from a huge performance bump with it in place.

I have been running some tests on an 8 core machines and getting ~ 380,000 message / sec (on a kafka cluster with default settings no compression used so I can definitely tune and squeak out more) so implementing zero copy should have a really nice bump here I believe.

**Comment by simar7** [comment]
@eapache, @joestein  Is there a way out here? I would like to work on this if someone had an idea in mind that we could try implementing/testing.

**Comment by eapache** [comment]
AFAIK this is not possible until upstream implements https://github.com/golang/go/issues/9402

**Comment by eapache** [comment]
Go upstream does not seem interested in doing this, and we haven't received any complaints that the current performance is actually insufficient in regular cases.
