### ISSUE TITLE
Ability for a consumer of ConsumerGroup to commit offset (when auto_commit=false) for the respective partition

### ISSUE THREAD

**Issue by nbajaj90** [Shopify/sarama#2383]
When a consumer of ConsumerGroup is reading messages from kafka, need to commit the offset after processing of a message is completed by the application (Otherwise, if offset gets committed and processing fails, for example the instance went down, the message is lost and the processing gets skipped for the message). 
At present, it looks like, a consumer can consume from multiple partitions, and thus committing offset after processing of a message would cause the offset commit for other partitions as well(in the same ConsumerGroup), and if processing of message in those partitions fails (for example instance restart), the messages are lost.
So need the ability to commit the offset for the partition, from which the message was read.

**Comment by nbajaj90** [comment]
@dnwe Please review, if this is already supported...

**Comment by billygout** [comment]
@nbajaj90 I think this might be want you want to call after processing each message https://github.com/Shopify/sarama/blob/v1.37.2/consumer_group.go#L707

**Comment by nbajaj90** [comment]
@billygout Thanks. 

Offset commit commits for particular partition only. Looks good.
