### ISSUE TITLE
[Bug] Infinity loop in Consume() method

### ISSUE THREAD

**Issue by vitalygudza** [Shopify/sarama#2426]
##### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.34.1 | - | 1.18 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
        // default reader configuration
        readerOptions := make([]kafka.ReaderOption, 0)
        readerOptions = append(readerOptions, kafka.WithReaderTlSConfig(nil))
	readerOptions = append(readerOptions, kafka.WithReaderSaslConfig(user, password, kafka.SaslAlgorithm("SHA512")))

	reader, err := kafka.NewReader(brokers, consumerGroup, readerOptions...)
```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```
[Sarama] 2023/01/25 15:27:40 client/coordinator retrying after 250ms... (3 attempts remaining)
[Sarama] 2023/01/25 15:27:40 client/coordinator requesting coordinator for consumergroup kafka-demo from <ip>
[Sarama] 2023/01/25 15:27:40 client was not authorized to access group kafka-demo while attempting to find coordinator
[Sarama] 2023/01/25 15:27:40 client/coordinator retrying after 250ms... (2 attempts remaining)
[Sarama] 2023/01/25 15:27:40 client/coordinator requesting coordinator for consumergroup kafka-demo from <ip>
[Sarama] 2023/01/25 15:27:41 client was not authorized to access group kafka-demo while attempting to find coordinator
[Sarama] 2023/01/25 15:27:41 client/coordinator retrying after 250ms... (1 attempts remaining)
[Sarama] 2023/01/25 15:27:41 client/coordinator requesting coordinator for consumergroup kafka-demo from <ip>
[Sarama] 2023/01/25 15:27:41 client was not authorized to access group kafka-demo while attempting to find coordinator
[Sarama] 2023/01/25 15:27:43 client/coordinator requesting coordinator for consumergroup kafka-demo from <ip>
[Sarama] 2023/01/25 15:27:43 client was not authorized to access group kafka-demo while attempting to find coordinator
[Sarama] 2023/01/25 15:27:43 client/coordinator retrying after 250ms... (3 attempts remaining)

...infinity loop...
```

</p>
</details>

##### Problem Description
If the client is not authorized to access the consumer group, the Consume() method is expected to return an error, but this does not happen. Instead, the Consume() method freezes. 

Suggested error location: from the analysis of the sarama code, it can be seen that the code execution is endlessly looping on the `func (c *consumer Group) retryNewSession()` method (file `consumer_group.go`). Inside this method, a recursive construction is performed, which in this case leads to an infinite attempt to update the session in 3 attempts (default value: 3). After three attempts, an error is expected to return, but instead, the retryNewSession() method is recursively called again, which again fails with an error.

**Comment by dnwe** [comment]
@vitalygudza thanks for reporting this, good catch — have pushed up a PR that should hopefully resolve this for you

**Comment by vitalygudza** [comment]
Thank you very much! Now it works!
