### ISSUE TITLE
SimpleProducer safety

### ISSUE THREAD

**Issue by mihasya** [Shopify/sarama#243]
From https://github.com/Shopify/sarama/issues/180:

> Sorry, I was unclear: it is not currently safe to call SimpleProducer from multiple goroutines. You can do it, but it will probably break.

I would like to follow up on this and see if the issues can be addressed. Was wondering if you had particular issues/bugs in mind or if you'd seen something in particular with `-race` enabled.

edit: cc @eapache

**Comment by eapache** [comment]
There was a known race, but it was fixed at the end of November (497df757405506adb4bf98f59e70d7b6296730fc). It is now safe to call SimpleProducer from multiple goroutines. If you find a case where it isn't, please file a specific bug.

**Comment by mihasya** [comment]
:+1: :+1: :+1: awesome news
