### ISSUE TITLE
Want to make sure I understand the update sarama client wrt Errors -> RefreshTopicMetadata

### ISSUE THREAD

**Issue by schleppy** [Shopify/sarama#247]
With the old client (with QueueMessage) I had patched sarama producer to return the "Failed Messages" similar to what you are doing now.  The big difference is that I was returning a batch via `*[]*sarama.ConsumerEvent`.  In my handling for the error batch I would call RefreshTopicMetadata, and re-enqueue the failed messages.

While updating to the new client I noticed you are returning a failed message on a per-message basis.  That initially had me concerned as that could mean (with my current implementation) that I would be refreshing the topic metadata N times where N = number of failed messages.

However, upon further inspection, it appears sarama client (producer) already does this now.  I am looking specifically at `doUpdate` in Producer.leaderDispatcher.  Am I correct in assuming I can remove this logic on my end now and that the producer will take care of the metadata refreshes before sending down the failed messages on the Errors() channel?

**Comment by eapache** [comment]
Yes, the new producer will only deliver errors if it retries the message (including refreshing the metadata if necessary) and it fails a second time. There's also an experimental PR at #234 to permit it to retry an arbitrary number of times before giving up.

I thought the old producer did this too, so I'm not sure why your patch was ever necessary, but perhaps I'm mistaken.
