### ISSUE TITLE
Thoughts on adding an interface{} field to MessageToSend struct

### ISSUE THREAD

**Issue by schleppy** [Shopify/sarama#249]
I have the need to track some information on a message-by-message basis.  For example, I have an `ID` for each message (which is not part of the message) and I want to track the `ack` for each message so I can in turn ack the system that sent the message to me.

Having an additional field on the MessageToSend struct of type interface{} (named something like `metadata`) would allow arbitrary data to be added to the message wrapper, and have that data available in the errors and acks channels.  

This is of course a very simple change (which I could do the PR for) but I wanted to get your thoughts on it before I submit the PR.  The biggest issue I see is it would force users to use named literals when creating a MessageToSend or they would be forced to provide a 4th argument of nil.

Thoughts?

**Comment by eapache** [comment]
Can you not just use the address of the MessageToSend structure for an additional ID?

**Comment by schleppy** [comment]
That won't work because the IDs are supplied to me so I would still need to maintain some sort of lookup map.

The point of the interface is the user (me in this case) could stick whatever field or strict they needed in there be it an ID, a "start time" to calculate round trip from send to Kafka back, a total retries count (outside of the auto retry in the client), etc, etc.

**Comment by eapache** [comment]
My gut says that we don't want to make `MessageToSend` any bigger, and that maintaining an external `map[*MessageToSend]myData` is simpler and more type-safe anyways. I'm open to counter-arguments though.

> The biggest issue I see is it would force users to use named literals when creating a MessageToSend or they would be forced to provide a 4th argument of nil.

FWIW, I believe you are already required to use named literals here because it contains unexported fields.

**Comment by schleppy** [comment]
I don't discount the type-safety (using myData vs an interface) though the type represented by the interface{} would be supplied by the user so would be easily converted back to the original with almost zero chance of getting it wrong (assuming users stick to a single type for their metadata.)

I am not sure I agree that it is simpler.  One thing I have learned in my years working with async systems is it is far easier (and often much more reliable) to include extra data in a request that you will need when handling a response and simply have the provider fulfilling the request send back the data you care about, rather than maintaining state at the request site.

For example, this seems far easier to me:

```
myMetadata := &MyMetadata{startTime: time.Now(), id: uint64(222)}
producer.Input() <- &sarama.MessageToSend{Topic: topic,
                                          Key: key,
                                          Value: dataz,
                                          Metadata: &myMetadata}
```

and then when acking, or error handling...

```
case failedMessage := <-producer.Successes():
    metadata := failedMessage.Msg.Metadata.(MyMetaData)
    ackSenderOfThisMessage(metadata.id)
    logTimeForRoundtrip(time.Now().Sub(metadata.startTime))
```

vs. the alternative of tracking a map and using locking or synchronized goroutine/channel based access.  Obviously the lock based or synchonized access based solution will work (and is probably how I would have handled this anyway - or will handle it without this addition) but I figured it was worth it to ask.  I certainly don't want to maintain a fork if I don't have to the way I did with the previous client before there was built in acking support.

Thanks.

**Comment by eapache** [comment]
@wvanbergen @drdee other opinions?

**Comment by wvanbergen** [comment]
I kind of like this idea. It's trivial to add to sarama because we already have all the bookkeeping to track messages in place, while having to set up the bookkeeping yourself is a potential source of bugs.

**Comment by schleppy** [comment]
The addition was super easy (literally adding a new field to the struct) and I used an existing test as a base to add a test that verifies one of the fields in the Metadata field in acked messages.  

PR at https://github.com/Shopify/sarama/pull/250

**Comment by zowens** [comment]
If you're tracking an ID, you could create your own `sarama.Encoder` that carries the extra information. I've done something similar for partitioning based on an ID:

```go
type PartitionedKey struct {
     PartitionKey []byte
     MessageId   sarama.Encoder
}

func (p *PartitionKey) Encode() ([]byte, error) { return p.MessageId.Encode() }
func (p *PartitionKey) Length() int { return p.MessageId.Length() }
```

(Plus a trivial partitioner, which type-asserts and uses the partition key rather than the message ID)

Then when you're looking at `MessageToSend` on the success channel, you can type-assert and pull out the extra info:

```go
select {
case e := <- p.Successes():
    if part, ok := e.(*PartitionKey); ok {
         // ...
   }
}
```
