### ISSUE TITLE
Support lz4 compression

### ISSUE THREAD

**Issue by eapache** [Shopify/sarama#256]
https://github.com/cloudflare/golz4 should be simple enough

https://issues.apache.org/jira/browse/KAFKA-1456
https://issues.apache.org/jira/browse/KAFKA-1493

**Comment by eapache** [comment]
And yet as with snappy, the framing format kafka uses is not supported by the "normal" go lz4 package.

http://fastcompression.blogspot.ca/2013/04/lz4-streaming-format-final.html

**Comment by edenhill** [comment]
Again? That's annoying...

**Comment by eapache** [comment]
This is still not documented on the official protocol page, we don't need it, and nobody else seems to be asking for it. I'm gonna icebox this until somebody actually wants it.

**Comment by cdstelly** [comment]
Kafka v 0.10 supports LZ4 with correct offsets:
[https://cwiki.apache.org/confluence/display/KAFKA/KIP-57+-+Interoperable+LZ4+Framing
](https://cwiki.apache.org/confluence/display/KAFKA/KIP-57+-+Interoperable+LZ4+Framing
)[https://issues.apache.org/jira/browse/KAFKA-3160](https://issues.apache.org/jira/browse/KAFKA-3160)

Can this be reopened?

**Comment by eapache** [comment]
I'll re-open, but I don't have any time to implement this in the next little while so it won't mean much.

**Comment by rtreffer** [comment]
See #786

**Comment by rtreffer** [comment]
@eapache I guess this can be closed. I tried the LZ4 on our 0.10.0.1 cluster. It didn't outperform GZIP for our usecase but it works.

**Comment by eapache** [comment]
Yup, thanks. If anybody really wants the weird framing support then that can be another ticket but I doubt anyone cares.
