### ISSUE TITLE
Consumer can spin on misbehaving broker

### ISSUE THREAD

**Issue by eapache** [Shopify/sarama#261]
This is a very minor robustness issue that occurred to me while I was reviewing #222, but it applies equally to the old and new consumer code. There are a handful of ways for a severely misbehaving (or malicious) broker/cluster to cause a consumer to spin in a tight loop and chew CPU.

The most obvious way is simply to not respect the `MaxWaitTime` value - a "broker" which always responds to fetch requests as fast as possible with no messages will cause the consumer to spin. There are also cases where the cluster consistently shuttles a partition between brokers, and other such things.

If the cluster regains sanity the consumer should always recover, but ideally after a few failed attempts we would back off and only try again once per second or something.

**Comment by wvanbergen** [comment]
It might be good to describe what we can and cannot expect from brokers. In general, should we guard for for brokers being malicious? Should we guard for the fact that brokers do not behave as designed/described? Is failing hard acceptable in these cases, or do we need to gracefullt handle these scenarios so that we can continue to run?

**Comment by eapache** [comment]
When a broker behaves outside of spec:

We must:
- return an error to the user

We must not:
- panic
- spin in a tight loop (this ticket)

We may:
- retry
- shutdown

**Comment by eapache** [comment]
Upon review: my previous comment calling this "effectively livelock" wasn't really accurate. Yes, it would be inefficient and burn CPU but we would not get stuck; we would make progress again once the broker recovered. Given that we have never seen brokers misbehave like this and the problem is so minor even if they would, I'm closing this as "too minor to actually care about".
