### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by eapache** [Shopify/sarama#302]
We only have a few remaining PRs and/or ideas that require breaking API changes, several of which are almost ready to go. When I started this project, https://gopkg.in was not a thing, so I stuck the current note about versioning in the README to give me some flexibility as we developed:

> A word of warning: the API is not 100% stable. It won't change much (in particular the low-level Broker and Request/Response objects could probably be considered frozen) but there may be the occasional parameter added or function renamed. As far as semantic versioning is concerned, we haven't quite hit 1.0.0 yet. It is absolutely stable enough to use, just expect that you might have to tweak things when you update to a newer version.

Now that we have a sane way of semantically versioning the library and we've settled on a relatively sane API for both the consumer and the producer, we should think about tagging a v1 and following a more proper release process than just "use master".

TODO:
- [x] fix or officially defer all other tickets in https://github.com/Shopify/sarama/milestones/1.0.0
- [x] add a `HISTORY.md` or `CHANGELOG.md` file - #358
- [x] tag `v1.0.0`
- [x] update README to mention API stability via gopkg.in #361  

@Shopify/kafka

**Comment by wvanbergen** [comment]
API breaking changes that I would still like to tackle:

- [ ] Consumer: split `Events()` channel into `Messages()` and `Errors()`
- [ ] See if we can make the `KError` types instead of values so we can add context

**Comment by wvanbergen** [comment]
Also, I feel we export way too many values to be able to effective maintain backwards compatibility while refactoring. E.g., all the messages, and the Broker type are mostly for internal use and greatly reduce our flexibility for refactoring if they all under our semantic versioning policy. 

I'd like to keep the API compatibility to be just the Client, Consumer, Producer, SimpleProducer, and the error types those return. How we achieve this I don't know. We can just write this down, un-export all the other stuff, or create subpackages. Pros and cons for all of these.

**Comment by wvanbergen** [comment]
Ideally, we would specify interfaces for the types we promise backwards compatibility for. Side benefit is that we can easily use those interfaces for dependency injection as well.

**Comment by eapache** [comment]
> Also, I feel we export way too many values to be able to effective maintain backwards compatibility while refactoring. E.g., all the messages, and the Broker type are mostly for internal use and greatly reduce our flexibility for refactoring if they all under our semantic versioning policy. 

I'm not sure what you mean - these types map to the protocol, so the only time they'd change is if kafka upstream changed the protocol, which would dictate a new major version on our end anyways.

**Comment by eapache** [comment]
> Ideally, we would specify interfaces for the types we promise backwards compatibility for.

1. Why? What does that win us as an API (besides dependency injection testing).
2. I'm not saying we should freeze the API (that will never happen because upstream kafka will keep changing things and we need to adapt). I'm saying we should tag versions occasionally so people have something slightly more stable to follow than tip of master, and so that people upgrading can *know* if the upgrade they're making will break the api (new major version) or not.

**Comment by wvanbergen** [comment]
I looked into it and I see that all the encoding/decoding functions are not exported, so we are probably good there if we ever want to refactor encoding/decoding packets. My point stands for the Broker type.

**Comment by wvanbergen** [comment]
Related: is there a way to get a list of exported symbols from a package easily?

**Comment by eapache** [comment]
read the godoc

**Comment by eapache** [comment]
I don't foresee the need to refactor the `Broker` type at all (beyond perhaps adding configuration or additional methods, neither of which break the API).

**Comment by wvanbergen** [comment]
W.r.t. releases: I don't really want to support more than one release at the same time. So I'd say let's use tags. If absolutely necessary we can branch off a tag in certain cases, but only as a last resort

**Comment by eapache** [comment]
I agree, and I've updated the todo list appropriately

**Comment by wvanbergen** [comment]
I'd like to break out MockBroker to be separated out into a `sarama/kafkamocks` package. 

- I am not quite ready to declare API stability on what we have now yet
- I would also like to add a MockConsumer and MockProducer that people can use for their testing purposes.

**Comment by eapache** [comment]
AFAICT, the only internal type that the mockbroker accesses is the `encoder` type, and we can work around that by having the tests encode their responses before sending them to the mockbroker. Otherwise we'd end up with an import cycle.

**Comment by wvanbergen** [comment]
Brain dump (so I can go on vacation with an empty brain):

- Consumer should have `Close` method, to close all outstanding PartitionConsumers.
- (Async) Producer: needs `HaltOnError` option, to ensure no messages gets produced as soon as the first error is returned. Use case: producing a replication log, in which ordering and completeness is important.
- SimpleProducer: rename to SyncProducer
- SimpleProducer's `SendMessage` should return the ProducerMessage, because it contains the Partition and the Offset which can be useful.

**Comment by eapache** [comment]
All of those make some sense, but only the last two require API breaks :)

The first two we can implement at any time even after 1.0.0.

**Comment by eapache** [comment]
And I think I'd just prefer three return values for the SyncProducer, as opposed to exposing the struct.

**Comment by wvanbergen** [comment]
Final potentially bad idea: allow opting out of consuming the errors
channel (at least the consumer)

**Comment by eapache** [comment]
Again: that's an additional config, which is not a breaking API change.

Also, given you can just launch a goroutine to drain the channel and do nothing with it, I'm not particularly inclined to add complexity to the producer/consumer.

**Comment by eapache** [comment]
Possible additional to-do item here: we currently support kafka 0.8.0+ and golang 1.2+, we should officially declare support lifetimes for old versions so we can legitimately drop support for old versions and clean up cruft.

**Comment by wvanbergen** [comment]
Let's use milestones for managing issues related to releases.

**Comment by eapache** [comment]
I've created a milestone and moved all the todo-before-1.0 tasks to separate tickets on that milestone. This ticket can remain to track the actual existence of 1.0 and the few doc changes needed for it.

**Comment by sybrandy** [comment]
Can you add #301 and #323 to the list of things to do for 1.0?  Having updated documentation will make it much easier for people to use this.

**Comment by wvanbergen** [comment]
#358

**Comment by eapache** [comment]
Tag pushed
