### ISSUE TITLE
Unify ConsumerEvent and ProducerEvent

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/sarama#305]
Can we use one message type instead?

See #273.

**Comment by eapache** [comment]
There are two main differences between them at the moment:
- `ProducerMessage` has some additional fields (retries, flags, Metadata) which the `ConsumerMessage` doesn't have or need
- `ProducerMessage` takes `Encoder`s for key/val, whereas `ConsumerMessage` provides `[]byte`s

The `retries` and `flags` fields are never used by the user, so we could remove them from the shared struct and use a wrapper struct which adds them to the base message. I'd be ok with that.

Forcing people to materialize their key/val pairs in advance is on one hand slightly simpler, but on the other is a fairly substantial breaking API change. It also has some potential performance implications (more memory, perhaps). It also has major API implications for the partitioners.

There's also the question of: what do we call it? `Message` is already taken by the protocol-level message type. I think jvm-land has a type called `MessageWithMetadata` or something, but I find that long/ugly.

**Comment by eapache** [comment]
I'm not necessarily against, but it raises some difficult questions which will need satisfactory answers before we go forward.

**Comment by wvanbergen** [comment]
Maybe we can at least make them implement the same interface? E.g. `Topic()`, `Partition()`, `Offset()`, `Key()` and `Value()` return the values you expect. One tricky part is that right now, some of these are struct fields, while others are functions.

**Comment by eapache** [comment]
Making them implement the same interface would be a very nice compromise. The only motivating use case I can think of for this (beyond cleanliness/consistency) is the ability to easily implement a mirror-maker like program in Go, and I think a single shared interface nicely covers that?

**Comment by eapache** [comment]
(I guess it doesn't completely simplify it, since you wouldn't be able to feed messages from the consumer straight to the producer... but almost)

**Comment by wvanbergen** [comment]
If only we had `io.Reader` and `io.Writer` wrappers around the Consumer and Producer respectively :trollface:

**Comment by wvanbergen** [comment]
If we want the same interface, the current problems:
- ProducerEvent already has `Topic`, `Key`, and `Value` as fields.
- ConsumerEvent already has all of them as fields.

If we want to make it an interface, they have to be turned into functions, so the existing fields have to be renamed.

**Comment by eapache** [comment]
`ProducerEvent` has those as fields so that you can construct a literal to pass to the producer... they still have to be public even if we rename them.

**Comment by eapache** [comment]
The more I think about this, the more I don't really mind the way things currently are. We have consistent naming now at least, and there aren't any real use cases I can think of (besides mirror-maker, and why not just use mirror-maker for that) where it's actually beneficial to have them be the same type.

@Shopify/kafka for other opinions? (I just realized nobody else was ever pinged on this, sorry). I'm leaning towards closing this, but there is certainly an argument to be made the other way.

**Comment by yagnik** [comment]
I might be missing some pieces, but why not use inheritance for this? Event have common field and then producer and cusmer events have their own specific fields.
That way they both implement common interface with producer adding some niceties around it.

**Comment by eapache** [comment]
Go doesn't really have inheritance, it has [embedding](http://golang.org/doc/effective_go.html#embedding) instead, which is subtly different in some ways. The biggest question for me (and the one that embedding doesn't solve) is the fact that right now the producer key/value fields are `Encoder`s and the consumer key/value fields are `[]byte`s.

**Comment by yagnik** [comment]
Yep embedding is what I meant (in my head that's how you do inheritance)
I think the key value should be same type irrespective of embedded type.

**Comment by eapache** [comment]
What do you mean? How do you propose to make them the same type?

**Comment by eapache** [comment]
Additional data: upstream uses two different types for this as well. [ProducerRecord](https://kafka.apache.org/082/javadoc/org/apache/kafka/clients/producer/ProducerRecord.html) for input to the producer, and [MessageAndMetadata](https://people.apache.org/~junrao/kafka-0.8.2.0-candidate2/scaladoc/index.html#kafka.message.MessageAndMetadata) for output from the consumer.

**Comment by wvanbergen** [comment]
Yeah, after looking this I tend to agree. One final thing that we *could* do is change `Offset()` and `Partition()` to be normal struct fields, so that they are consistent with a `ConsumerMessage`, but I am on the fence about this one.

**Comment by eapache** [comment]
I don't want them to be settable when being fed into the producer (although in principle it shouldn't make a difference). Closing.
