### ISSUE TITLE
Error context

### ISSUE THREAD

**Issue by eapache** [Shopify/sarama#318]
As discussed a couple of times, it would be useful to have more context (e.g. topic/partition/broker etc) as part of the errors we return to high-level consumer/producer users.

What this means for implementation is still undefined. My (weak) preference at the moment is to add a higher-level type that wraps arbitrary `error`s with this information, for maximum flexibility and API stability, but we've also discussed just beefing up the `KError` type.

Targeting to 1.0.0 since this may involve API breakage depending on the approach taken.

**Comment by wvanbergen** [comment]
Some new thoughts on this:

- The additional context is primarily nice for `sarama.Logger`. There's not really a direct need to expose this as part of the API.
- We already have consumer facing error types for this: `ConsumerError` and `ProducerError`. 
- We might want to add `ClientError` and `BrokerError` for the other exported APIs.

**Comment by eapache** [comment]
Hmm, I kind of like the idea of a `BrokerError`, I don't think there's as much need for a `ClientError` (the client doesn't really add any information that's not already present in either the broker or the producer/consumer).

My concern is then in the case of e.g. a decoding error we might return a `ConsumerError` wrapping a `BrokerError` wrapping a `PacketDecodingError` and it just seems overly-abstracted at that point...

**Comment by wvanbergen** [comment]
alternative idea: Add an ErrorContext struct that we can add to ConsumerError and friends; this way we can just copy the context instead of wrap the entire error.

**Comment by eapache** [comment]
Alternative proposal I'm still exploring (don't know how much sense it actually makes):
- replace `ProducerError` and `ConsumerError` with
```go
type Error struct {
    Err       error
    Topic     string
    Partition int32
    Broker    *broker
    Msg       *ProducerMessage
}
```

And return that from anywhere it makes sense, leaving fields blank or -1 or nil where appropriate.

**Comment by eapache** [comment]
Or even:
```go
type Error interface {
    Root() error
    Topic() string
    Partition() int32
    Broker() *Broker
}
```

Implemented by `ProducerError` (in its current shape) and some other internal type that is used for everything else?

**Comment by wvanbergen** [comment]
Is this actually needed? For the client facing ProducerError and ConsumerError; we have context. I think the main issue is the logging is not great, but that's internal.

**Comment by eapache** [comment]
There are a couple of potential directions we could take here, but the primary concern that led to this ticket was a lack of logging in certain cases. Some of that has already been fixed, but none of it requires API breakage, so untargetting from 1.0.

**Comment by eapache** [comment]
With improved logging and other changes this has proved to be probably unnecessary. We can always revisit if something changes.
