### ISSUE TITLE
Add examples to godocs.

### ISSUE THREAD

**Issue by sybrandy** [Shopify/sarama#323]
Hello,

As someone who has worked with Kafka before, the way the API works is different from the Java/Scala API.  I'm not saying it's wrong: I actually like it.  However, you have to think about things differently.  I'd like to see examples of how to create consumers/producers, configuring partitioners, etc. in the Godocs to not only help with the transition, but to also make sure that the API is being used how it is meant to be used.  I know I can look through unit tests, but that's really a terrible way to do things when you want to get started.

**Comment by eapache** [comment]
Hi @sybrandy there are already five examples at https://godoc.org/github.com/Shopify/sarama#pkg-examples including two for the consumer and two for the producer. What else are you looking for?

**Comment by sybrandy** [comment]
Dammit...I think I spent so much time looking at the individual methods, I completely missed them.  Sorry.

**Comment by wvanbergen** [comment]
I feel we should make http://shopify.github.io/sarama/ more useful though.

**Comment by eapache** [comment]
ya, I didn't write that, that was part of Shopify's push to give all our open-source projects nice homepages... I'm not sure it really stuck

**Comment by sybrandy** [comment]
Dammit, I just remember what was bothering me: examples for using the MockBroker.  I can't recall the one case off the top of my head, but there was one thing I wanted to test but couldn't figure out how.

**Comment by wvanbergen** [comment]
More reason to move the mock broker/producer etc to a separate package where it will be a first class citizen. See #312 .

**Comment by wvanbergen** [comment]
I added an example for testing using dependency injection to the wiki: https://github.com/Shopify/sarama/wiki/Testing-using-mocks

**Comment by wvanbergen** [comment]
@sybrandy What other areas of Sarama do you think would be helped by adding examples?

**Comment by sybrandy** [comment]
The copy of Sarama I downloaded does not have the mocks, so I can't comment on them.  I don't want to pull down a new version yet as what I have is working for us and I'd rather wait til 1.0 before upgrading.  However, most of my issues were with trying to get the tests working correctly, so documentation on how to do that would be great.  For example, I had to stare at code for a while before I figured out how to properly have the MockBroker respond with multiple results.  Ideally, I'd like to see something like a cookbook where each recipe shows you how to test a certain situation.  Such as "Testing a failure when retrieving a message from the broker." or "Testing a timeout when there are no messages to be retrieved."

**Comment by wvanbergen** [comment]
Hey, we just declared a v1.0. The API should be stable now. We also added a bunch of examples to out [godoc documentation](http://godoc.org/github.com/Shopify/sarama) to make it easier to get started.

For testing, we now have a [mocks subpackage](https://github.com/Shopify/sarama/tree/master/mocks) that makes it a lot easier to test applications that consume and produce using high-level mock objects.

I am going to close this issue; if you have any questions about the stable version, please let us  know, so we can keep improving the documentation and examples.

**Comment by sybrandy** [comment]
O.K.  I'll check this out and let you know.  I may be a few days as there are other priorities.
