### ISSUE TITLE
Flush producer on demand

### ISSUE THREAD

**Issue by josselin-c** [Shopify/sarama#332]
Hello, In my usecase I would like to be sure some data are written to Kafka before commiting their offset in a database.
Using the async producer I don't think it is possible yet to force a flush of the queued messages so I have to wait until the periodic flush is performed. I would rather have the possibility to call flush() on it and avoid waiting.

**Comment by eapache** [comment]
By default the producer sends messages as fast as it can, batching appropriately. Is that not sufficient for your use case? Regardless of when the messages are flushed, you can find out that they *have* been flushed by setting `AckSuccesses` to true and monitoring the `Successes` channel.

**Comment by eapache** [comment]
Also, it's not clear what exactly you want to flush - all messages to a broker, all messages to a partition, or all messages to a topic?

**Comment by josselin-c** [comment]
I didn't know the producer was sending messages as fast as it could. I though it relied on ```FlushMsgCount```, ```FlushByteCount``` and ```FlushFrequency```.
I want to implement http://ben.kirw.in/2014/11/28/kafka-patterns/ so the flush would be all messages to a partition.
For now, when I want to do a commit I poll ```GetOffset()``` until the offset is equal or above the target offset.

**Comment by eapache** [comment]
The documentation on `Producer.Flush` in https://godoc.org/github.com/Shopify/sarama#Config explains the behaviour fairly well I think, let me know if anything is unclear.

**Comment by josselin-c** [comment]
I didn't have the latest documentation. Now I understand why a flush command isn't required. 
Thanks for your help.
