### ISSUE TITLE
Async Producer: halt on error

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/sarama#351]
Add a Config option that ensure sthta no events will be produced after an initial error. This is important for applications that want to ensure completeness & ordering.

- All messages that are currently in flight will not be produced, but sent to the `Errors()` channel.
- New message on the Input() channel will be  sent directly to the `Errors()` channel

Once this happens, it is not possible to produce messages from the producer instance anymore. If you want to resume producing messages, you'll have to create a new producer instance (or restart your app)

**Comment by eapache** [comment]
This is in principle impossible since messages may already be in-flight to other brokers in the cluster... we could certainly manage it for specific partitions though.

**Comment by wvanbergen** [comment]
IO think this is still a useful thing if we can guarantee this for a specific message key. I guess that would only work using a consistent partitioning scheme like HashPartitioner.

**Comment by eapache** [comment]
Nobody else has ever asked for this (here or upstream, AFAIK) and we never had a real use case for this anyways it was just a thought. Closing until somebody actually needs it.
