### ISSUE TITLE
Add Consumer.ConsumeTopic(topic, offset)

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/sarama#366]
Or another way to make the common case of consuming all partitions of a topic easier, without having to construct a `Client` object

**Comment by wvanbergen** [comment]
As an alternative, we can expose `Topics()` and `Partitions(topic)` from Client on the Consumer, so it's not necessary to instantiate a Client anymore for this common use case.

**Comment by eapache** [comment]
I'd prefer to just implement `ConsumerTopic` - that covers the common case, and it's really not that much work to call `NewClient` and then `NewConsumerFromClient`.

**Comment by wvanbergen** [comment]
It makes testing a lot harder, because you need to mock the entire Client.

**Comment by eapache** [comment]
That just means we should really provide a mock client :P
