### ISSUE TITLE
Safely consuming batch of messages

### ISSUE THREAD

**Issue by arnaudbriche** [Shopify/sarama#39]
Hi,

I'm new to kafka so I might miss something; but here's what I want and think I cannot achieve with the Consumer type.
I'd like to be able to fetch 100 messages, process them, and only then notify Zookeeper that it can move my consumer group offset. This would allow my process to   fail in the middle of a batch processing safely: so that the next time I start it, I can start processing the same batch again.
Is this possible with the current state of the library ?

**Comment by sanchitlohia-ovo** [comment]
@eapache How can I reread the same batch again
