### ISSUE TITLE
Async producer failed to deliver message

### ISSUE THREAD

**Issue by chenziliang** [Shopify/sarama#391]
I was using the following code to do testing against AsyncProducer. I compiled the code into bin async_producer_main, and then executed **./async_producer_main --brokers=172.16.107.153:9092,172.16.107.153:9093,172.16.107.153:9094**. It reported **"2015/03/24 22:38:24 Failed to write access log entry: kafka: Failed to produce message to topic test_topic: dial tcp 127.0.0.1:9092: connection refused"** errors. All the brokers are in good states (I can use the Kafka shell CLI to produce and consume messages). BTW, telnet to 127.0.0.1 9092 on server 172.16.107.153 also works.

```
package main

import (
	"github.com/Shopify/sarama"
	"log"
	"os"
	"strings"
	"flag"
	"time"
)

func main() {
	brokers := flag.String("brokers", "", "The Kafka brokers, separated by comma")
	flag.Parse()
	if *brokers == "" {
		flag.PrintDefaults()
		os.Exit(1)
	}

	brokerList := strings.Split(*brokers, ",")
	log.Printf("Kafka brokers: %s", strings.Join(brokerList, ","))

	config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.WaitForLocal
	config.Producer.Flush.Frequency = 500 * time.Millisecond 
	producer, err := sarama.NewAsyncProducer(brokerList, config)
	if err != nil {
		panic(err)
	}

	for i := 0; i < 10; i++ {
		producer.Input() <- &sarama.ProducerMessage {
			Topic: "test_topic",
			Key: sarama.StringEncoder("172.16.107.153"),
			Value: sarama.StringEncoder("This is a test"),
		}
	}

	go func() {
		for err := range producer.Errors() {
			log.Println("Failed to write access log entry:", err)
		}
	}()

	time.Sleep(time.Millisecond * 10000)
	defer func() {
		if err := producer.Close(); err != nil {
			log.Fatalln(err)
		}
	} ()
}
```

**Comment by wvanbergen** [comment]
Looks like your Kafka brokers are not registering the proper hostname in Zookeeper. Kafka reports the names of all the brokers in the cluster, and we try to connect from them on the client. Obviously connecting to `127.0.0.1:9092` from the client will fail because the broker doesn't run on the same machine.

You will have to check your Kafka broekr's `server.properties` file.

**Comment by chenziliang** [comment]
Thanks a lot, @wvanbergen. Problem solved after revisting the server.properties
