### ISSUE TITLE
Add wiki page to interpret stack traces

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/sarama#397]
For debugging purposes, having a reference of all the goroutines that show up in a stack trace would be very useful.

**Comment by eapache** [comment]
Created https://github.com/Shopify/sarama/wiki/Reading-Backtraces

Still need to actually put content on it.

**Comment by eapache** [comment]
Prelim. content. Somebody other than myself should review and see if it's coherent or what other info would be helpful.

**Comment by wvanbergen** [comment]
The grapevine tell me that @alanctgardner is interested in this.

**Comment by wvanbergen** [comment]
Closing this given that we have a decent start; we can expand the wiki page as we see fit
