### ISSUE TITLE
doesn`t the consumer fetch brokerlist from zookeeper?

### ISSUE THREAD

**Issue by thinkboy** [Shopify/sarama#406]
hi~
    i saw the "tools/kafka-console-partitionconsumer" code, and the question is why consumer use brokelist rather than zookeeper address list? i saw the consumer example of java is just zookeeper address list as paramerter, seems the logic of consumer is the first need fetch brokerlist, topic list and so on.
   i discovered this question is because of deleted a topic through "kafka-run-class.sh kafka.admin.DeleteTopicCommand(i know this is not really delete the data)" at server-side, and "kafka-console-partitionconsumer" could still fetch the messages, but java example can not.
   so i am confused why has the difference between jave`s and go`s demo.

**Comment by wvanbergen** [comment]
Sarama, and the go console consumer, never talk to Zookeeper, only to Kafka itself. So no matter whether the topic is removed from Zookeeper or not: if Kafka still has it the console consumer will continue to work.

I started working on a library to talk to the Kafka metadata in Zookeeper: https://github.com/wvanbergen/kafka/tree/master/kazoo. I don't have plans of updating this command line tool with it at this point.

**Comment by simon-xia** [comment]
@wvanbergen  the url you gave doesn't exist

**Comment by wvanbergen** [comment]
I extracted it to a separate repo: https://github.com/wvanbergen/kazoo-go
