### ISSUE TITLE
adding tcp keepalive support for the broker's tcp connection

### ISSUE THREAD

**Issue by epsniff** [Shopify/sarama#407]
We've been using the sarama client on Google Compute Engine (GCE) and it works well, expect that once in a while we get `read tcp 10.240.20.4:9093: i/o timeout`.   This occurs often with Go sockets on GCE, because GCE kills idle connections after 10 mins and by default Go's net package turns off tcp keepalives.   

I've created a small patch to support keepalives: https://github.com/lytics/sarama/commit/76aa5518b0b64a801bf534958ed98ce83999d828.   Let me know if you have any feedback?  We're currently running these changes through our staging environment to see this fixes the issue.  

Ref: https://cloud.google.com/compute/docs/troubleshooting#communicatewithinternet

thanks for all your hard work!!!

**Comment by eapache** [comment]
Sounds like a good idea, although based on http://felixge.de/2014/08/26/tcp-keepalive-with-golang.html it looks like keepalives in golang are rather inconsistent across platforms. For style, you may want to take a look at #154 which also adds parameters to the dialer; it may be cleaner to follow that pattern than to wrap it up in an extra function.

**Comment by epsniff** [comment]
Thank you for looking.   Ill look at both and clean up the code accordingly.

**Comment by epsniff** [comment]
Closing the ticket after my PR got merged.
