### ISSUE TITLE
Consumer Group Example

### ISSUE THREAD

**Issue by trotha01** [Shopify/sarama#410]
An example of how to create a consumer with a specific consumer group would be nice.

I didn't see it in the *Config that is passed into NewConsumer(), so I'm not sure how I would create a consumer for a specific consumer group.

**Comment by eapache** [comment]
At the moment sarama doesn't include the zookeeper logic necessary to register and consume as part of a consumer group. That logic is currently in a separate package (https://github.com/wvanbergen/kafka) though we do hope to integrate it eventually.

**Comment by trotha01** [comment]
I'll check out that package. Thank you for the very quick response!

**Comment by wvanbergen** [comment]
An example of said library can be found here: https://github.com/wvanbergen/kafka/blob/master/examples/consumergroup/main.go

It's definitely more experimental than sarama, feedback is welcome!

At the same time, we're also brainstorming on how to make it easier to consume all partitions of a topic in #366, and implement offset management in #379

**Comment by dzlab** [comment]
Has this package been integrated to sarama or not yet??

**Comment by eapache** [comment]
No, we are still waiting on upstream Kafka to release a version of the final API for consumers that does not depend on zookeeper.

**Comment by felipejfc** [comment]
bump

**Comment by eapache** [comment]
See https://github.com/Shopify/sarama/issues/597
