### ISSUE TITLE
Is there any real benefit to using the AsyncProducer in Go?

### ISSUE THREAD

**Issue by deckarep** [Shopify/sarama#412]
Please correct me if I'm wrong here but could we theoretically get the same performance out of the sync-producer by spinning up many goroutines to produce data?

I can see how using the AsyncProducer can give you benefits in other languages such as Python but in Go since we can spin up many goroutines which are extremely light-weight would this act fundamentally the same as an AsyncProducer?

The reason I ask is because we're trying to determine which Producer we should utilize.  The SyncProducer is more straightforward per our design.

**Comment by eapache** [comment]
The `SyncProducer` is a very thin wrapper around the `AsyncProducer` - the `SendMessage` method simply pushes the message onto the underlying async queue, then waits for the response. As such, you should get effectively identical performance with either.

Something to note is that go does not guarantee that goroutines will run in any particular order - if you want to produce many messages efficiently in a specific order then you probably need the async producer. Sending serially via the sync producer would preserve order, but would of course require a complete network round-trip per message, which would be slow. Spinning up multiple goroutines would permit efficient concurrent sending with the sync producer, but would lose any ordering guarantees you need.

**Comment by deckarep** [comment]
@eapache  - excellent...thank you for that insight!
