### ISSUE TITLE
the Client.Topics() is always return empty and no err for kafka_2.9.2-0.8.1.1

### ISSUE THREAD

**Issue by nashtsai** [Shopify/sarama#421]
Hi,

It appears to me that  Client.Topics() is always return empty list and have tried explicitly call Client.RefreshMetadata(), is there a compatibility issue with kafka_2.9.2-0.8.1.1?

**Comment by wvanbergen** [comment]
Can you clarify: does `Topics()` work after calling `RefreshMetadata()`, or is it still returning an empty list afterwards?

**Comment by wvanbergen** [comment]
Can you enable the logger and capture the output, e.g.: 
```
sarama.Logger = log.New(os.Stdout, "[sarama] ", log.LstdFlags)
client, err := sarama.NewClient('localhosy:9092')
topics, err := client.Topics()
log.Println(topics, err)
log.Println(client.RefreshMetadata())
topics, err = client.Topics()
log.Println(topics, err)
client.Close()
```

**Comment by nashtsai** [comment]
still empty list after calling RefreshMetadata()

**Comment by nashtsai** [comment]
2015/04/15 23:29:42 [ 0 ] connecting
[sarama] 2015/04/15 23:29:42 Initializing new client
[sarama] 2015/04/15 23:29:42 Fetching metadata for all topics from broker 10.97.248.52:9092
[sarama] 2015/04/15 23:29:42 Failed to connect to broker 10.97.248.52:9092: dial tcp 10.97.248.52:9092: connection refused
[sarama] 2015/04/15 23:29:42 Error from broker while fetching metadata: dial tcp 10.97.248.52:9092: connection refused
[sarama] 2015/04/15 23:29:42 Fetching metadata for all topics from broker 10.97.228.28:9092
[sarama] 2015/04/15 23:29:42 Connected to broker 10.97.228.28:9092
[sarama] 2015/04/15 23:29:42 Successfully initialized new client
2015/04/15 23:29:42 [ 0 ] connected
2015/04/15 23:29:42 [ 0 ] Kafka get topics: []
[sarama] 2015/04/15 23:29:52 Fetching metadata for all topics from broker 10.97.228.28:9092
2015/04/15 23:29:52 [ 0 ] Kafka metadata refreshed
2015/04/15 23:29:52 [ 0 ] Kafka get topics: []


And I am certain that my topics aren't empty as I've verified with "kafka-topics.sh" cmd

**Comment by wvanbergen** [comment]
Looks like it cannot connect to your kafka broker from where you're running this script. E.g. try `nc 10.97.248.52 9092` to verify connectivity between your machine and the kafka broker.

Note: `NewClient` should return an error (`ErrOutOfBrokers`); `Topics()` and `RefreshMetadata()` as well (`ErrClosedClient`). If they don't in this case, that would be a bug.

**Comment by nashtsai** [comment]
I gave it a list and it then connected to 10.97.228.28:9092

**Comment by nashtsai** [comment]
right after I brought back 10.97.248.52 9092, among all 4 nodes, the getTopics() is working fine now, sorry about the mis-report

**Comment by wvanbergen** [comment]
OK, glad it is resolved!

**Comment by nashtsai** [comment]
It looks like the problem I've encountered is a server problem, are you able to confirm this? I am hoping if this does happen that client is able to tell it's server related errors.

**Comment by wvanbergen** [comment]
To me, it looks like sarama is handling the response from the broker just fine. I have some theories that are based on nothing but gut feel.

- Broker configuration issue. Are `10.97.248.52` and `10.97.228.28` talking to the same zookeeper cluster?
- Some kind of split brain.
- All topics are completely unavailable. In this case sarama should return an error.

It's hard for me to say anything with certainty with just these logs.
