### ISSUE TITLE
Panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by epsniff** [Shopify/sarama#422]
Hi all, 

I'm still digging in (updates to come) but we are seeing this panic from the sarama client: 

```
panic: assignment to entry in nil map

goroutine 3857 [running]:
github.com/Shopify/sarama.(*client).registerBroker(0xc21e3a3f80, 0xc242620230)
	/home/mdmarek/go/root/src/github.com/Shopify/sarama/client.go:367 +0xac
github.com/Shopify/sarama.(*client).updateMetadata(0xc21e3a3f80, 0xc234acde30, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mdmarek/go/root/src/github.com/Shopify/sarama/client.go:611 +0x127
github.com/Shopify/sarama.(*client).tryRefreshMetadata(0xc21e3a3f80, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0)
	/home/mdmarek/go/root/src/github.com/Shopify/sarama/client.go:563 +0x2d2
github.com/Shopify/sarama.(*client).tryRefreshMetadata(0xc21e3a3f80, 0x0, 0x0, 0x0, 0x3, 0x0, 0x0)
	/home/mdmarek/go/root/src/github.com/Shopify/sarama/client.go:595 +0xb86
github.com/Shopify/sarama.(*client).RefreshMetadata(0xc21e3a3f80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mdmarek/go/root/src/github.com/Shopify/sarama/client.go:301 +0x161
github.com/Shopify/sarama.(*client).backgroundMetadataUpdater(0xc21e3a3f80)
	/home/mdmarek/go/root/src/github.com/Shopify/sarama/client.go:541 +0x10a
github.com/Shopify/sarama.*client.(github.com/Shopify/sarama.backgroundMetadataUpdater)·fm()
	/home/mdmarek/go/root/src/github.com/Shopify/sarama/client.go:135 +0x27
github.com/Shopify/sarama.withRecover(0xc21db856d0)
	/home/mdmarek/go/root/src/github.com/Shopify/sarama/utils.go:42 +0x3a
created by github.com/Shopify/sarama.NewClient
	/home/mdmarek/go/root/src/github.com/Shopify/sarama/client.go:135 +0x794
```

**Comment by wvanbergen** [comment]
Can you run it while capturing `sarama.Logger` output?

**Comment by eapache** [comment]
Hmm, based on the backtrace alone, if we close the client while the background metadata updater is running there might be a race that looks something like this...

**Comment by epsniff** [comment]
@eapache  thats a good possibility.   The client is running in a [Metafora](https://github.com/lytics/metafora) task that can get moved between nodes in our cluster a number of times per day...

**Comment by epsniff** [comment]
@wvanbergen Ill turn on logging, but it could take a couple of days before we hit it again :)

**Comment by epsniff** [comment]
@eapache - I can see in our logs that we closed the client a few seconds before the panic.

**Comment by epsniff** [comment]
Our broker list is static, so Im going to just disable to background updater by setting the RefreshFrequency to zero. https://github.com/Shopify/sarama/blob/9b048b0f558f2e7f420b11688d669aaa22d77d6a/config.go#L136 as a workaround.

**Comment by wvanbergen** [comment]
Looks like we need to properly stop the background updated before we can continue the shutdown process.

@epsniff FYI: we always turn on sarama logging even in production. In normal operation, you will only see a single log line every 10 minutes, but when shit hits the fan the information is invaluable.

**Comment by eapache** [comment]
I have a unit test that reproduces this stack trace. Fix incoming shortly.

**Comment by epsniff** [comment]
Thanks to both of you!  And I'll have sarama logging on in the future :).
