### ISSUE TITLE
multiple producers with same client

### ISSUE THREAD

**Issue by ssahukar** [Shopify/sarama#445]
It seems it is not possible to create multiple AsyncProducers with different Partitioners using the same Client object as the would be referring to same config object. The only way to get multiple producers with different partitioners is to use different clients. This option, however, would create multiple connections with Kafka brokers and Zookeeper, so it is not a preferred option.

Is there any particular reason for this design?

**Comment by eapache** [comment]
We simply haven't needed anything like this so far. Ideally I think you wouldn't even need to create multiple producers in the first place, you'd just be able to specify multiple different partitioners depending on your needs. Creating multiple producers (even if they somehow shared the same client) would still lose some efficiency due to reduced message batching.

I assume you just want different topics partitioned in different ways? Or do you need something more complex? You can already theoretically do anything you want by implementing a custom `Partitioner` whose `Partition` method simply dispatches out to other partitioners depending on your criteria.

**Comment by eapache** [comment]
Slight tangent: Sarama does not connect to zookeeper at all currently. Creating multiple clients would create multiple connections to the kafka brokers however.

**Comment by wvanbergen** [comment]
For partitioning, you have two options.
- By using the `ManualPartitioner`, and setting the `ProducerMessage.Partition` field for every message you want to produce yourself. See [this example](http://godoc.org/github.com/Shopify/sarama#example-Partitioner--Manual)
- By implementing the [`Partitioner` interface](http://godoc.org/github.com/Shopify/sarama#Partitioner) yourself.

**Comment by ssahukar** [comment]
Thanks Evan, Willem for the quick responses.

My use case is to use the same client for Producers of "different topics"
and not for the same topic. In this case, I would want to have the
flexibility of each producer using different partitioners (for ex, one with
hash partitioner and other with random partitioner).

I think I could explore your suggestion of using a custom partitioner which
could dispatch to other partitioners based on the topic name.

You mentioned that doing so could reduce the performance in terms of
batching? Is batching done at a connection level or per topic level?

Thanks,
Shridhar

**Comment by wvanbergen** [comment]
The batching is done on a per broker/connection basis. So all messages for partitions that are led by the same broker will be batched together, and is independent of the partitioner.

**Comment by ssahukar** [comment]
Thanks Willem.

**Comment by eapache** [comment]
Actually, I went digging into this a little more and realized you don't even have to implement the `Partitioner` yourself; past me had already thought of this use case it seems :)

All you have to do to accomplish what you want is to set `config.Producer.Partitioner` to a custom implementation of a [PartitionerConstructor function](https://godoc.org/github.com/Shopify/sarama#PartitionerConstructor) which is much simpler.

Something like this should do the trick:
```go
conf := sarama.NewConfig()
conf.Producer.Partitioner = func (topic string) sarama.Partitioner {
    switch topic {
    case "foo", "bar":
        return sarama.NewHashPartitioner(topic)
    default:
        return sarama.NewRandomPartitioner(topic)
    }
}

**Comment by ssahukar** [comment]
Thanks Evan.

I implemented something similar and it works fine. Thanks.

Btw, is there a mailing list to which I can send general
questions/clarifications? The google group mentioned on Sarama git page
seems generic for all Kafka clients, so I was wondering if there is
something specific to Sarama.

Thanks,
Shridhar

**Comment by eapache** [comment]
Depending on the technicality of the question, the google group works fine (I am subscribed) or filing a ticket here also works. You could probably also manage to get an answer on the kafka-users mailing list.

Sarama itself doesn't seem big enough at the moment to have its own dedicated mailing list. If that changes we'll create one.
