### ISSUE TITLE
what if "consumergroup" unexpected shut down?

### ISSUE THREAD

**Issue by thinkboy** [Shopify/sarama#448]
hi.
i saw the code that use "FinalizePartition" in https://github.com/wvanbergen/kafka/blob/master/consumergroup/consumer_group.go,
and the question is that if my process unexpected shut down then we will lost "lastOffset"?

what about make a config that control the frequency of call "FinalizePartition", eg: every time or 10 seconds one time

**Comment by wvanbergen** [comment]
This option already exists: [CommitInterval](https://github.com/wvanbergen/kafka/blob/master/consumergroup/consumer_group.go#L22-L26)

NB: if you find other issues for the consumergroup library, please file them [here](https://github.com/wvanbergen/kafka/issues) instead.

**Comment by thinkboy** [comment]
thanks
