### ISSUE TITLE
kafka consumer group expired?

### ISSUE THREAD

**Issue by jaredye** [Shopify/sarama#452]
Immediately after I commitoffset.   

	./kafka-consumer-offset-checker.sh --zookeeper=localhost:2181 --topic=my-replicated-topic --group=ib --broker-info 
	
	Group           Topic                          Pid Offset          logSize         Lag             Owner
	
	ib              my-replicated-topic            0   12              12              0               none
	
	BROKER INFO
	
	1 -> localhost:9093

However, after several minute, I run the same checker command.

	./kafka-consumer-offset-checker.sh --zookeeper=localhost:2181 --topic=my-replicated-topic --group=ib --broker-info 
	
	
	Exiting due to: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /consumers/ib/offsets/my-replicated-topic/0.

And I check the zookeeper, the node never exists at any time, even when checker list the offset correctly.

It seems to me that the consumer group get expired. How can I make the consumer group persist?

sarama commit: 23d523386ce0c886e56c9faf1b9c78b07e5b8c90
kafka 0.8.2.1
golang 1.3

	kafka server config
	broker.id=1
	port=9093
	num.network.threads=3
	 num.io.threads=8
	socket.send.buffer.bytes=102400
	socket.receive.buffer.bytes=102400
	socket.request.max.bytes=104857600
	log.dirs=/tmp/kafka-logs-1
	num.partitions=1
	num.recovery.threads.per.data.dir=1
	log.retention.hours=168
	log.segment.bytes=1073741824
	log.retention.check.interval.ms=300000
	log.cleaner.enable=false
	zookeeper.connect=localhost:2181
	zookeeper.connection.timeout.ms=6000

**Comment by wvanbergen** [comment]
sarama doesn't support consumergroup registration in Zookeeper, so I am surprised it shows up at all? How are you committing offsets?

**Comment by jaredye** [comment]
I commit it using kafka.OffsetCommitRequest. 

	offsetReq := &kafka.OffsetCommitRequest{
		ConsumerGroup          : this.Config.ConsumerGroup,
		ConsumerGroupGeneration: 1,
		Version: 1,
	}

	offsetReq.AddBlock(msg.Topic, msg.Partition, msg.Offset+1, time.Now().Unix(), "")

	var offsetResp *kafka.OffsetCommitResponse
	offsetResp, err = this.OffsetBroker.CommitOffset(offsetReq)
	if err != nil {
		log.Error(err)
		return
	}

	errKaf := offsetResp.Errors[msg.Topic][msg.Partition]
	if errKaf != kafka.ErrNoError {
		err = errKaf
		log.Error(err)
		return
	}

**Comment by wvanbergen** [comment]
Sarama doesn't register a running consumer in Zookeeper, while the JVM consumer does. Most likely `kafka-consumer-offset-checker.sh` looks in Zookeeper to figure out what consumers are currently running, which explains why your consumer is not showing up in that tools output.

This behavior is sarama is unlikely to change for Kafka 0.8, because it doens't keep a connectiokn to Zookeeper at all (it only talks to kafka). If you want to register your running consumer in Zookeeper, you can use my [kazoo library](https://github.com/wvanbergen/kazoo-go) to do so, or use the high level [consumergroup library](https://github.com/wvanbergen/kafka) built on top of sarama.

**Comment by jaredye** [comment]
Thank you for pointing out.

**Comment by simon-xia** [comment]
@wvanbergen  is there a example to register a sarama consumer in Zookeeper with your kazoo lib?

**Comment by wvanbergen** [comment]
https://github.com/wvanbergen/kafka/blob/master/consumergroup/consumer_group.go is probably your best bet.
