### ISSUE TITLE
Installation Problem 

### ISSUE THREAD

**Issue by arpanshah29** [Shopify/sarama#463]
I am trying to do go get github.com/Shopify/sarama on a ubuntu machine

and I see the following error:

github.com/Shopify/sarama
Shopify/sarama/broker.go:73: unknown net.Dialer field 'KeepAlive' in struct literal

Any clues on what the issue could be here

**Comment by eapache** [comment]
Your version of go is too old. the `KeepAlive` field was added in go 1.3, which is the oldest version that Sarama officially supports right now.

**Comment by wvanbergen** [comment]
What go version are you using?
