### ISSUE TITLE
Does the current version of the Sarama client support storing the Offsets in Kafka itself?

### ISSUE THREAD

**Issue by deckarep** [Shopify/sarama#465]
I believe 0.8.2 of Kafa now supports storing offset in Kafka itself.

Does the current version of Sarama (or is it it planned) to support committing Offsets into Kafka directly?  I may have asked about this a month ago but having trouble tracking down the current status of this feature.

Thanks in advance and great project!

@deckarep

**Comment by eapache** [comment]
See #461 - it is a work in progress, but it is getting close to a usable state.

**Comment by deckarep** [comment]
Thanks @eapache!
