### ISSUE TITLE
Question about idiomaticness of "Codecs"

### ISSUE THREAD

**Issue by jaytaylor** [Shopify/sarama#471]
Why were the [codecs defined as](https://github.com/Shopify/sarama/blob/master/message.go#L17) `x = 1, y = 2, z = n...` rather than ` x = iota, y = iota, z = iota...`? As per [go's "iota" keyword](https://golang.org/ref/spec#Iota)?

**Comment by wvanbergen** [comment]
When you use iota, you basically say: I don't really care what the exact value is as long as all listed values are different. But we do care. They should have the value as defined by the Kafka protocol.

**Comment by jaytaylor** [comment]
I see, thank you@

On Wed, Jun 10, 2015 at 3:56 AM, Willem van Bergen <notifications@github.com
