### ISSUE TITLE
Performance comparisons between v1 and v2 sarama APIs

### ISSUE THREAD

**Issue by jaytaylor** [Shopify/sarama#472]
Do you know if anyone has done performance comparisons between v1 and v2 sarama APIs?

**Comment by eapache** [comment]
There is no v2 of the sarama API at the moment, so I'm not sure what you mean? Unless you're referring to the current version as v2 and the old unnumbered version as v1?

Either way, nobody's done any comparison benchmarking that I know of. We did enough to be sure that the current design could handle the throughput we needed (and more) but didn't compare it specifically to anything.

**Comment by jaytaylor** [comment]
Yes, I am referring to the current as "v2" and the old as "v1".  I figured this because of the massive breaking API changes..

Thank you for the info!
