### ISSUE TITLE
Coun't find example links

### ISSUE THREAD

**Issue by wgwi** [Shopify/sarama#479]
https://godoc.org/github.com/Shopify/sarama#pkg-examples link fail, with none documents at all. Where could I find the simple examples. thanks.

**Comment by eapache** [comment]
Those links work for me. They just link to subsections further down on the same page, so even if the links don't work for you for some strange reason, you should be able to see the examples just by scrolling down a lot.

**Comment by wgwi** [comment]
Oh, after change my browser from Firefox to IE, I could see it now, thanks.

**Comment by wgwi** [comment]
I find out what's the problem now, the page invoke ajax.google.com, that's blocked by China GFW.
