### ISSUE TITLE
Snappy dependency moved again

### ISSUE THREAD

**Issue by aaronbee** [Shopify/sarama#490]
The snappy dependency has moved from 

github.com/golang/snappy/snappy
to
github.com/golang/snappy

https://github.com/golang/snappy/commit/7a1576592b18c90a91ce2103ed37b515d194cb78

This is breaking go get of sarama

**Comment by mblair** [comment]
I'm not a maintainer, but this has already been fixed on master:

https://github.com/Shopify/sarama/pull/486

**Comment by aaronbee** [comment]
Oops, missed that. Thanks @mblair 

Can that change be ported to the version of sarama that gopkg.in/Shopify/sarama.v1 points to?

Thanks,
Aaron

**Comment by eapache** [comment]
I will release 1.4.3 (hopefully) tomorrow with this change, I just have a bit of misc. stuff to tidy up first.

**Comment by eapache** [comment]
1.4.3 released with this change and a few others.

**Comment by tnolet** [comment]
:+1:
