### ISSUE TITLE
Document/add an example for Consumer groups

### ISSUE THREAD

**Issue by ThomasAlxDmy** [Shopify/sarama#491]
I went through the documentation but I could not figure out how to use consumer groups. Is the feature working? If so can we document it properly and add examples?

**Comment by eapache** [comment]
If, by "consumer groups" you mean the auto-balancing offset tracking group management via a zookeeper, then that simply isn't implemented in this package. See https://github.com/wvanbergen/kafka which builds it on top of Sarama.

Once Kafka 0.9 implements those features directly into the API then we will add them to Sarama proper.
