### ISSUE TITLE
Single node failure prevents Sarama from using Kafka cluster

### ISSUE THREAD

**Issue by alberts** [Shopify/sarama#499]
Running some older versions of Sarama here.

We've run into an issue where a single node failure in the Kafka cluster can prevent Sarama from producing or consuming at all.

This is related to: https://issues.apache.org/jira/browse/KAFKA-1649

Summary: there are cases where a ReplicaNotAvailable error in MetadataResponse should not be treated as fatal. This can be reproduced using the procedure outlined in KAFKA-1649.

I think the code around this point:

https://github.com/Shopify/sarama/blob/master/client.go#L625

should treat ReplicaNotAvailable the same as NoError. There might be a more elegant way. The code has changed quite a bit in this area relative to what we're using internally.

More strings so people can Google this:

kafka server: Replica not available. No replicas are available to read from this topic-partition.

**Comment by wvanbergen** [comment]
This only caused issues when initializing the client. The fix is to update to a later sarama version. The method returns an error but this is properly handled by the client now.

**Comment by wvanbergen** [comment]
The error value is handled here: https://github.com/Shopify/sarama/blob/master/client.go#L130-L136
