### ISSUE TITLE
Split request/response code into subpackage

### ISSUE THREAD

**Issue by aaronkavlie-wf** [Shopify/sarama#500]
A large percentage of the files in the `sarama` package are dedicated to request/response implementations of the kafka protocol.

These could be split into a separate `protocol` subpackage to make the code base easier to navigate.

It would also clean up the godoc as a lot of undocumented public types (which are mostly only an internal concern) will be removed from the main doc.

**Comment by eapache** [comment]
Yup, this is one of the things already on our list as a potential option for a v2 (when we're allowed to break compatibility).

https://github.com/Shopify/sarama/wiki/Ideas-that-will-break-backwards-compatibility
