### ISSUE TITLE
How to comit the message and get the ACK

### ISSUE THREAD

**Issue by itnik** [Shopify/sarama#505]
like the title.I want to ask how can i do .I test the sarama find that everytime when i start the consumer ,it will get the msg from one to the last.I think if i comit the msg ,that the next time when start the consumer i should only get the msg not comit . And i also want to kown how can i get the ACK,or how can i set the ACK.

**Comment by eapache** [comment]
A higher-level offset manager is in progress at https://github.com/Shopify/sarama/pull/461 but it is not guaranteed to be stable yet. In the meantime you can use the consumergroup manager at https://github.com/wvanbergen/kafka/.

I don't know what you mean but "get the ACK" or "set the ACK"?

**Comment by itnik** [comment]
I do not understand the ACK in kafka .How does it work？Should i get the value of it and do something or it was resoveld by kafka it's self? And can you give me a fully sample project in use sarama. thx a lot

**Comment by wvanbergen** [comment]
I assume you are producing messages, not consuming. A good example of both the async and sync producer can be found here: https://github.com/Shopify/sarama/tree/master/examples/http_server

As for ACKs: you can specify how many brokers should ACK a message before your produce request is considered successful. On the client/sarama, this is just a setting: `config.Producer.RequiredAcks` (see http://godoc.org/github.com/Shopify/sarama#Config). This is handled fully on the broker side. Also see [the official kafka documentation](http://kafka.apache.org/documentation.html#producerconfigs)
