### ISSUE TITLE
Provide replacement for kafka.admin.AdminUtils

### ISSUE THREAD

**Issue by CAFxX** [Shopify/sarama#507]
Being able to programmatically perform some admin operations would be very useful.
https://apache.googlesource.com/kafka/+/trunk/core/src/main/scala/kafka/admin/AdminUtils.scala

**Comment by wvanbergen** [comment]
Are these operations standardized and/or documented? Do they require interaction with Zookeeper?

**Comment by eapache** [comment]
They are things like reassigning partitions and changing topic config, so they require zookeeper. Sarama does not speak zookeeper so they would be a better fit for https://github.com/wvanbergen/kazoo-go I think
