### ISSUE TITLE
Assign valid partitions for messages with leaderless partitions

### ISSUE THREAD

**Issue by wkuranowski** [Shopify/sarama#514]
Don't fail messages assigned to partitions which are now leaderless. Just assign an available partition and try to send them again. Producer has to use round robin / random partitioner, where ordering is not important.

**Comment by eapache** [comment]
This is extremely difficult to accomplish with our current architecture for various reasons. It's definitely not going to happen in the short term, though maybe long-term we'll rewrite the producer and fix this along with a bunch of other minor issues.

**Comment by CAFxX** [comment]
We would be very interested in this. From a cursory check it seems feasible. If we worked on it would you accept a PR?

**Comment by eapache** [comment]
I'm happy to take PRs, with a few caveats:
- I'm very busy right now with other things, so feedback is going to be slow or non-existent for probably the next month
- Per my previous comment on this PR I expect this to be a fairly substantial undertaking. If you think you've found a less intrusive way to accomplish it that's great, but I remain skeptical. It's probably best if you propose specific changes here before spending too much time coding.

**Comment by CAFxX** [comment]
We solved by using round-robin and resubmitting failed messages up to N times (we can tolerate out-of-order messages)
