### ISSUE TITLE
Producer : AsyncProducer (Select) block port in OS

### ISSUE THREAD

**Issue by aresetian** [Shopify/sarama#516]
Using the example code find it in AsyncProducer (Select) ( https://godoc.org/github.com/Shopify/sarama#example-AsyncProducer--Select) in my project I noticed that  code below, block the port of the OS where Sarama was added it.

........

// Trap SIGINT to trigger a shutdown.
signals := make(chan os.Signal, 1)
signal.Notify(signals, os.Interrupt)

...
    case <-signals:
       ...

In other words,  when I wish finish executing my project with command + c, this never end it, I've got to use kill -9 because  the channel is waiting for one signal in the line   case <-signals that never arrive. 

Note : When I deleted those code lines,  This problem is not present and the port is not further  attachment to the execution.

My question is if is possible to delete this code from the producer Samara and what consequences will have if I delete them?

**Comment by wvanbergen** [comment]
If you delete those lines, your application will exit immediately and sarama will not have a chance to properly shut down. This means that potentially, not all messages you have enqueued will be produced.

**Comment by aresetian** [comment]
I understood, but how my application will exit  if  case <-signals does not allowed me and leave the daemon in memory and I Know that there are not messages enqueued, as they have already been published. I have waited for 5 and 10 minutes a TimeOut or something like that but  it does not happened and is in that moment when I've got to use killed -9

**Comment by eapache** [comment]
When you `ctrl-c` then `signals` should provide a message and allow the program to exit.

**Comment by wvanbergen** [comment]
- Are you sure `<-signals` is what is blocking, and not something else in your code?
- What OS are you using?
- Maybe you can try to trap some other signals as well by using the `syscall ` package, e.g. `signal.Notify(signals, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)`.
- Capture a stack trace by terminating your app with `Ctrl + \`, and paste it here so we can have a better idea of what is going on.

**Comment by aresetian** [comment]
What OS are you using?

Linux  3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

@eapache  when   I execute  control + c(^C) ,  signals don't show anything
<img width="910" alt="screen shot 2015-08-17 at 22 57 35" src="https://cloud.githubusercontent.com/assets/1524461/9317657/1ce3602a-4535-11e5-9eb9-60ba8bc4da8f.png">

Are you sure <-signals is what is blocking, and not something else in your code?

My code is  :
<img width="1485" alt="screen shot 2015-08-17 at 23 00 56" src="https://cloud.githubusercontent.com/assets/1524461/9317700/575ec398-4535-11e5-8684-2acfaff09142.png">

With that code I have to use kill -9

With the code below(comment signal lines )  the project finish without problem as is show is Result, but will have the problem that @wvanbergen commented before (sarama will not have a chance to properly shut down)
<img width="1517" alt="screen shot 2015-08-17 at 23 01 38" src="https://cloud.githubusercontent.com/assets/1524461/9317808/e89bb384-4535-11e5-9837-18339154623d.png">

Result : 
<img width="903" alt="screen shot 2015-08-17 at 23 05 54" src="https://cloud.githubusercontent.com/assets/1524461/9317862/3a8d5cec-4536-11e5-95ae-50c68509a3ea.png">

**Comment by wvanbergen** [comment]
are you calling your `sendMessage()` function multiple times? If so, that is likely the problem, because you end up trying to trap signals multiple times in a single process and you can't do that.

Also, there's a much easier way to produce a single message:  `SyncProducer`:

``` go
producer, err := sarama.NewSyncProducer(WrapperKafka.Address, nil)
if err != nil {
    log.Error("Error al enviar a Kafka: ", string(pMessage))
}

partition, offset, error := producer.SendMessage(&sarama.ProducerMessage{...})
// ...

producer.Close()

```

You also want to make sure that you only create one (Async/Sync)Producer, and reuse it to 

Anyway, this is outside the scope of sarama: signal trapping and handling is a unix concept, and has nothing to do with sarama/kafka. As long as you make sure that the process waits with exiting for the `producer.Close()` call to complete you won't have data loss.
