### ISSUE TITLE
Support for consumer groups?

### ISSUE THREAD

**Issue by peterbourgon** [Shopify/sarama#533]
On the roadmap, any hope? :)

**Comment by eapache** [comment]
It exists in a separate repository (https://github.com/wvanbergen/kafka) to avoid pulling in all the ZooKeeper dependencies for the simple case. When ZooKeeper is no longer required (Kafka is promising an API upgrade to hide ZK entirely) then we will build it in here.

**Comment by eapache** [comment]
Also if you're building a new tool around it, you may want to just start with https://github.com/wvanbergen/kafka/pull/72 which is nearly ready.
