### ISSUE TITLE
Find current offset of broker/topic

### ISSUE THREAD

**Issue by sathishvj** [Shopify/sarama#534]
Would anybody have the code to find the latest offset for a broker/topic?  While we are in the dev phase, we are seeing an issue where restarts on the kafka side resets the offset but our client is waiting at offset 10 (or something like that).  

We want to be able to intelligently/automatically reset to 0 or the latest offset when the kafka server is reset.

**Comment by wvanbergen** [comment]
See [Client#GetOffset](http://godoc.org/github.com/Shopify/sarama#Client)
