### ISSUE TITLE
The max producer message size 

### ISSUE THREAD

**Issue by wenzuojing** [Shopify/sarama#536]
I set the max message size (Producer.MaxMessageBytes = 2 * 1024) , using AsyncProducer send a message length beyond limit  ,  however the rest message  that not beyond  limit can not be send

**Comment by eapache** [comment]
Hi Wens, the `MaxMessageBytes` value is applied to the total serialized size of the message, including the key, the value, and 26 bytes of metadata overhead. If your value is under the limit but very close, it is entirely possible that the message will end up too long.

I would also note that 2KiB is unusually small. Kafka brokers by default accept messages up to 1MB, so unless you have a good reason to limit your message size I would consider raising it.

Hope the above solves your problem. If it doesn't, please provide the information requested at https://github.com/Shopify/sarama/blob/master/CONTRIBUTING.md#reporting-issues so we can help further.

**Comment by wenzuojing** [comment]
Hi Evan Huus ,thank you for reply .I wrote a test case .
```golang
package main

import (
	"time"
	"os"
	"os/signal"
	s "github.com/Shopify/sarama"
	"fmt"
)

func main() {


	kconf := s.NewConfig()
	kconf.Producer.MaxMessageBytes = 2 * 1024
	kconf.Producer.Retry.Max = 2
	kconf.Producer.Timeout = time.Second * 6
	kconf.Producer.Flush.Frequency = time.Second * 1
	kconf.Producer.Flush.Messages = 1

	kclient, err := s.NewClient( []string{"192.168.199.212:9092"}, kconf )

	if err != nil {
		panic(err)
	}

	defer kclient.Close()


	producer, err := s.NewAsyncProducerFromClient(kclient)
	if err != nil {
		panic(err)
	}
	defer producer.Close()

	msg1 := []byte("message1")
	msg2 := []byte("message2")
	msg3 := []byte("message3")

	for i := 0 ; i < 1024 ; i++ {
		msg2 = append(msg2 , []byte("Go")... )
	}

	producer.Input() <- &s.ProducerMessage{
		Value:s.ByteEncoder(msg1),
		Topic:"test" ,
	}

	fmt.Println("Send msg1 complete")

	producer.Input() <- &s.ProducerMessage{
		Value:s.ByteEncoder(msg2),
		Topic:"test" ,
	}

	fmt.Println("Send msg2 complete")

	producer.Input() <- &s.ProducerMessage{
		Value:s.ByteEncoder(msg3),
		Topic:"test" ,
	}

	fmt.Println("Send msg3 complete")

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, os.Kill)
	<-c

}
```
output ：
```
Send msg1 complete
Send msg2 complete
```
The main goroutine blocking at sending msg3 forever , and the consumer only receive one message (message1)

My environment  is 

* Golang 1.4.2
* kafka_2.9.1-0.8.2.1

**Comment by eapache** [comment]
The async producer returns errors (such as too-large messages) over the `Errors()` channel. Clients are required to either read from this channel, or set `Producer.Return.Errors = false` to indicate that they don't care about any errors.

Since you never read from this channel, Sarama blocks trying to write to it, and stops processing messages.
