### ISSUE TITLE
Line Breaks in Log Messages

### ISSUE THREAD

**Issue by sudorandom** [Shopify/sarama#537]
I'm trying to use a custom logger with sarama (logrus, github.com/Sirupsen/logrus) and the way sarama adds line breaks to the end of Logger.Printf calls is causing the extra context that logrus adds to the end of logs to appear on the next line. The standard library logger will automatically add a line break at the end if it does not already have a line break. Can the line breaks be removed to play a little bit nicer with loggers that want to add context to the end of the line?

```
> grep -r "Logger.Printf" . | grep "\\\n" | wc -l
37
```

**Comment by eapache** [comment]
@Sirupsen thoughts? It feels weird to me for some log statements to use `Println` and some to use `Printf` without a trailing `\n`. Does it make more sense do you think for logrus to handle format strings that end in `\n`?

**Comment by Sirupsen** [comment]
@eapache this sounds like a problem in Logrus with it automatically appending a line break because of how the default logger is. It should maybe just ignore it.

**Comment by sudorandom** [comment]
To be clear, the issue isn't logrus appending a line break. It's the fact that it's appending to the log line after sarama's messages and some of saramas message already have a line break.

Here's an example:
```
INFO[2015-09-24T10:55:04-05:00] producer/flusher/0 starting up
               service=sarama
```

The format is roughly this:
```
{logrus info} {sarama's log message}{logrus context}
```

With just the sarama log message populated:
```
{logrus info} producer/flusher/0 starting up\n{logrus context}
```

I can see it possibly being a logrus issue because it assumes it can append text to a log message without checking for an \n at the end of the log message like the standard library does.

**Comment by sudorandom** [comment]
I agree that this is a logrus issue, I'll close this issue. Thanks for the discussion.

**Comment by horkhe** [comment]
@sudorandom I faced the same problem when I was making sarama work with [mailgun/log](https://github.com/mailgun/log). A simple [adaptor](https://github.com/mailgun/kafka-pixy/blob/master/pixy/logging.go) helped in my case.

**Comment by sudorandom** [comment]
Yeah, we fixed this problem with logrus in a similar way using a custom formatter:

```go
type logFormatter struct {
	parentFormatter logrus.Formatter
}

func (logFormatter *logFormatter) Format(entry *logrus.Entry) ([]byte, error) {
	if len(entry.Message) > 0 && entry.Message[len(entry.Message)-1] == '\n' {
		b := []byte(entry.Message[0 : len(entry.Message)-1])
		entry.Message = string(b)
	}
	return logFormatter.parentFormatter.Format(entry)
}
```
