### ISSUE TITLE
Relation between consuming multiple topics && partitions with connection number?

### ISSUE THREAD

**Issue by let4be** [Shopify/sarama#541]
Hi!

I'm considering using kafka and sarama in my golang project, specific is so I have a lot of topics and partitions by design and do not have a luxury dedicating a separate connection for consuming a particular topic/partition. From checking some other issues(https://github.com/Shopify/sarama/issues/140) I came to conclusion this should be possible to do.

Would it be possible to consume multiple topics(and partitions within those topics) using the same single tcp connection to kafka? If it's possible are there any restrictions I should be aware of?

p.s. I came from NSQ and here there is a strict limitation of one physical connection per consumer with single topic.

Thanks!

**Comment by wvanbergen** [comment]
This should work automatically by just using a single `Consumer`, and calling `ConsumePartition` on it for all your partitions. It will open one connection per broker and share it for all partitions that live on it.

**Comment by let4be** [comment]
This cleared the question :)
Thank you Willem!

**Comment by sathishvj** [comment]
@wvanbergen We have a similar problem ... apparently "calling ConsumePartition on it for all your partitions" is the answer, but how do we do this?  The api allows to set only one partition.

@let4be: were you able to resolve this?  Do you have any code to demonstrate how it works?

**Comment by wvanbergen** [comment]
`consumer.Topics()` gives you all the topics, `consumer.Partitions(topic)` gives you the partitions for a topic. You can then call `ConsumePartition` for one partition at a time, e.g. using a goroutine for every partition.

**Comment by sathishvj** [comment]
How do we keep track of the various offsets in these partitions then?  If our service went down and we restarted it after a while, how do we know which partition+offset to restart listening at?

On another line of enquiry, if we have a zookeeper setup, does using kazoo-go help to resolve this?

**Comment by wvanbergen** [comment]
You will have to store what offsets have been processed somewhere. You'll have to store one offset for every partition that you are consuming. Common ways are storing in in Kafkla (using offset managfer), or Zookeeper, but you can basically store these anywhere.
