### ISSUE TITLE
Performance of AsyncProducer

### ISSUE THREAD

**Issue by astrekalova** [Shopify/sarama#567]
My application is a simple http server that receives http requests, generates avro messages and sends them to a Kafka server. The server receives around 350K requests per minute and the bottleneck seems to be sending messages to Kafka. Kafka server is in the same data center but on a different server, it has 8 partitions for the topic. I can see that sending a message to Kafka can take up to 2 seconds. I'm wondering if there is a way to tune the configuration that I can use. 
I am using the AsyncProducer:

        config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.NoResponse         
	config.Producer.Compression = sarama.CompressionSnappy   // Compress messages
	config.Producer.Flush.Frequency = 500 * time.Millisecond // Flush batches every 500ms
	config.Producer.Retry.Max = 5                            // Retry maximum 5 times
	config.ChannelBufferSize = 1000                          // number of events to buffer in internal and external channels

	producer, err := sarama.NewAsyncProducer(brokerList, config)
	if err != nil {
		Error.Fatalln("Failed to start Sarama producer:", err)
	}

	go func() {
		for err := range producer.Errors() {
			Error.Print("Failed to write request to Kafka: ", err)
		}
	}()

And here is the snippet where I send the message:

        start := time.Now()
	s.Producer.Input() <- &sarama.ProducerMessage{
		Topic: *topic,
		Value: sarama.ByteEncoder(message),
	}
	elapsed := time.Since(start)
	if elapsed.Nanoseconds() > 300000000 {
		Error.Printf("sending to channel took %s", elapsed)
	}

Is there a way to optimize the configuration? I will be grateful for any hints!

**Comment by eapache** [comment]
A few questions:
- Are your messages small (hundreds of bytes) or large (hundreds of KB) on average?
- What version of sarama are you running?

A few suggestions:
- Is your kafka server at max capacity? 350k/min is probably fine but if the server has (for example) a slow disk you might be hitting a limit of the broker. It may be worth checking the server load and IO throughput.
- 350k/minute is roughly 6k/second is roughly 3k/500ms which can be quite a bit to shove in a single batch (especially if your messages are large). You might see an improvement just by also setting `Producer.Flush.Bytes` to keep your batches smaller.
- Go has excellent profiling utilities (see https://blog.golang.org/profiling-go-programs) if there is a CPU bottleneck somewhere then profiling might reveal where it is.

**Comment by astrekalova** [comment]
Here is the version I'm using (because of the mock package):
"ImportPath": "github.com/Shopify/sarama",
"Comment": "v1.6.1-8-g4a6acf4",
"Rev": "4a6acf4728d546c047a168a1ec4160f39b73ad30"

The messages are small with a couple of hundreds of bytes. What values for Producer.Flush.Bytes would you suggest? 

Thanks for the profiling tip!

**Comment by eapache** [comment]
I would try perhaps 64KB to start? If your messages are small it probably won't make as much of a difference.

4a6acf4728d546c047a168a1ec4160f39b73ad30 is not the best rev to be running, it was right in the middle of a refactor so there are a few things that are in kind of a half-way state and I expect to be slow.

I suggest going back to 35093741160a61deca1a9b08fb5f508c6cece9c8, which corresponds to v1.6.1 - you're usually safe if you stick to the SHA corresponding to a given release, even if you're not using the release branch directly. Alternatively you could go forward to the current tip of master (5624c4bf8e694bce7987a90fe7a8d3c43be8d249) which should be stable and will probably become v1.7.0 whenever I get around to releasing it.

**Comment by astrekalova** [comment]
Works much better now, not sure if it is because of the new version, Producer.Flush.Bytes configuration or because I restructured the program. But thanks anyway!
