### ISSUE TITLE
does sarama provided code/utility to alter kafka partition in golang

### ISSUE THREAD

**Issue by lokeshverizon** [Shopify/sarama#576]
I wanted to know if you have code which can alter kafka partitions. code literally uses: 

/bin/kafka-topics.sh --zookeeper <zk>  --alter --topic <name> --partitions <no>

**Comment by wvanbergen** [comment]
We don't have it in sarama. All the administrative actions, including adding partitions, are done through zookeeper. Sarama only talks to Kafka, and not Zookeeper, so it cannot implement these administrative actions. 

I have a library called [Kazoo](https://github.com/wvanbergen/kazoo-go) that talks to Zookeeper, but currently doesn't implement this action. It could be added there though.
