### ISSUE TITLE
SSL support (Kafka 0.9+)

### ISSUE THREAD

**Issue by Ormod** [Shopify/sarama#581]
Kafka 0.9+ supports using TLS with client certificate authentication. Adding support for that would be great.

**Comment by eapache** [comment]
We do have a form of TLS support already (the `Net.TLS` struct in the config) but it was added to support proxies. I haven't tried it against 0.9 yet but I wouldn't be surprised if it Just Works. If this is something you're interested in, I'd start there and see if it does what you want.

**Comment by Ormod** [comment]
Ah ok, I wasn't aware. Thanks for the tip.

**Comment by tcrayford** [comment]
I've tested Kafka 0.9's SSL support with Sarama, and it works just fine. Even SSL client certs (which Kafka uses for authentication) works well. I think this issue can be closed.

**Comment by wvanbergen** [comment]
Awesome, thanks for reporting!
