### ISSUE TITLE
async_producer.go:624:syntax error: unexpected :, expecting semicolon or newline or }

### ISSUE THREAD

**Issue by polym** [Shopify/sarama#582]
I met problem when go get this project. Go version is 1.5.2. After replaced `shutdown` in line 624,  go install successfully.

**Comment by eapache** [comment]
I can build sarama locally fine with version 1.5.2 and it also passes on CI (see #583). Are you sure you don't have some other version installed, or that you haven't made local modifications to Sarama?

**Comment by potocnyj** [comment]
For what it's worth, I saw this error the other day trying to build with Go tip (rebased on commit `251e50065b99eb6c40b6cc549b3bea9126e96bde`). But that's an unstable version (and I'm also not using the latest version of Sarama), so I didn't think much of it.

**Comment by eapache** [comment]
AFAICT we are compliant with the published grammar, so unless tip is intentionally making backwards-incompatible grammar changes I suspect this to be a temporary bug.

**Comment by eapache** [comment]
This is an upstream bug which looks like it will be fixed by the time Go 1.6 is released: https://github.com/golang/go/issues/13684

However, we have worked around it for now: #587
