### ISSUE TITLE
Sarama Snappy Compression

### ISSUE THREAD

**Issue by rphillips** [Shopify/sarama#593]
Does anyone have any figures on how fast you can process snappy [edit] encoded messages? In my environment, I am only able to process 500 messages a second. Nodejs will process around 5000 messages a second. Are there any tips or tricks to get faster performance from Sarama?

**Comment by rsrsps** [comment]
Tens of thousands per second per handoff thread.  We stopped optimizing above 70k/sec.  Getting to 25k was straightforward then it took some work.

protobuf format; non-trivial messages sent to a worker pool via a shared channel; 

to do it, though, we had to crank down the max wait time and do a client per t,p stream.  we also needed to write a python tool that just sends huge blocks of messages to fill up a topic,partition prior to a test run so writer side didn’t interfere with testing.  the python test tool could also mimic some of the processing and tapped out at about 6k/sec.

(we are still on a somewhat older version of sarama so I guess it’s possible it got slower)

**Comment by eapache** [comment]
Unless you have extremely fat low-latency network connections and a slow CPU, network is more likely the bottleneck than snappy compression. Try increasing `Consumer.Fetch.Default`.

FWIW, consuming with snappy has almost certainly gotten faster over the last year, mainly due to #446, #485, and #527.

**Comment by rphillips** [comment]
I changed those options and am not seeing anything different. Am I doing anything outrightly terrible with this test case: https://play.golang.org/p/-KqXKBNlve

**Comment by eapache** [comment]
Looks ok to me, but since you're starting at the newest offset you'll only be able to consume as fast as messages are being produced... Could that be the bottleneck?

**Comment by eapache** [comment]
Looks ok to me, but since you're starting at the newest offset you'll only be able to consume as fast as messages are being produced... Could that be the bottleneck?

**Comment by rphillips** [comment]
I'll double check that the go version is doing the same thing as the node version in the morning. Thank you for the feedback.

**Comment by rphillips** [comment]
Thank you for the feedback! The node version was looking back to the oldest offset. For reference, I am now at parity with both applications and Sarama can process 43k messages a second without any optimizations. I appreciate the help. Thanks!
