### ISSUE TITLE
Sync Producer writing to same partition even when Key is set 

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [Shopify/sarama#594]
Even when different Keys are set in ProducerMessage the data goes into same partition, 

     sk := sarama.ProducerMessage{
		     Topic: "my_topic", 
		     Value: data, 
		    Key:   sarama.StringEncoder("another_key"),
	    }
    	partition, offset, err := s.DataCollector.SendMessage(&sk)

How do I write messages into different partitions ???

**Comment by wvanbergen** [comment]
The partition is assigned using a hash of the key value. This means that when you are using a low number of keys and a low number of partitions, you are more likely to have messages end up on the same partition. With more partitions, and/or more different key values, the messages will spread out more easily.

You can use different partitioners if the hash partitioning is not desirable for you: 
- You can use a random partitioner, which should send messages to random partitions and usually achieves a very even spread. https://github.com/Shopify/sarama/blob/master/partitioner.go#L49
- You can assign partitions statically, so you are in full control. https://godoc.org/github.com/Shopify/sarama#NewManualPartitioner

**Comment by Karthic-Hackintosh** [comment]
Just by changing the Partitioner to  ManualPartitioner is throwing a nil  
config := sarama.NewConfig()
	config.Producer.Partitioner = sarama.NewManualPartitioner

**Comment by wvanbergen** [comment]
You will also have to set `message.Partition`

**Comment by Karthic-Hackintosh** [comment]
I'm setting the Partition in `ProducerMessage`, but it still throws an error.

**Comment by wvanbergen** [comment]
Can you give us a larger code sample, and the output of `sarama.Logger`?

**Comment by Karthic-Hackintosh** [comment]
Here is the quick mock up code I'm using to test the  ManualPartitioner,  https://gist.github.com/Karthic-Hackintosh/27732ce9f597694dcc40 , I would first like to know whether you guys could run that code snippet and replicate the error .

**Comment by eapache** [comment]
The problem is with the lines
```
if errProducer != nil {
    panic(err.Error())
```
You check if `errProducer` is non-nil, but then you try to print `err` (which *is* nil) thus leading to the nil-pointer panic.

**Comment by Karthic-Hackintosh** [comment]
@eapache , Sorry, my bad, here is the error, `panic: kafka: partitioner returned an invalid partition index
`

**Comment by eapache** [comment]
That means your topic isn't configured with the right number of partitions on the broker. Check your kafka cluster and see how many partitions that topic actually has.
