### ISSUE TITLE
Consumer Groups/ Group Membership API in 0.9.x

### ISSUE THREAD

**Issue by mattes** [Shopify/sarama#597]
Are there any plans to implement a "high level" wrapper around `Group Membership API` for consumer partition assignments within consumer groups?

https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-GroupMembershipAPI
https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Client-side+Assignment+Proposal

refs: #574 #577

**Comment by wvanbergen** [comment]
It's definitely in scope of this project, but currently nobody is working on it AFAIK. We are definitely interested in contributions in this area!

**Comment by eapache** [comment]
There is a third-party implementation that is reasonably complete at this point: https://github.com/bsm/sarama-cluster.

**Comment by tcrayford** [comment]
@bsm is there any interest in upstreaming that work to Sarama itself?

**Comment by guangchl** [comment]
@tcrayford They discussed about it in #60

**Comment by varun06** [comment]
This is done. Closing.
