### ISSUE TITLE
panic: close of closed channel (possibly via https://github.com/bsm/sarama-cluster) 

### ISSUE THREAD

**Issue by jdness** [Shopify/sarama#598]
Yesterday we upgraded to Kafka 0.9 and the latest Sarama library.  We are using https://github.com/bsm/sarama-cluster to distribute/rebalance our four kafka running instances.  This morning, two of our four daemon instances crashed with "panic: close of closed channel".  I haven't been able to reproduce it yet but here is what I see in the logs:
```
[Sarama] 2016/01/22 07:47:29 client/metadata fetching metadata for all topics from broker localhost:9092
[Sarama] 2016/01/22 07:49:03 cluster/consumer -a9899ac7-1b49-40cf-848d-bb843b7231d7 rebalance
2016/01/22 07:49:03 kafka server: The provided member is not known in the current generation.
[Sarama] 2016/01/22 07:49:03 client/coordinator requesting coordinator for consumergoup backend from localhost:9092
[Sarama] 2016/01/22 07:49:03 client/coordinator coordinator for consumergoup backend is #0 (services.veramine.com:9092)
[Sarama] 2016/01/22 07:49:03 consumer/broker/2 disconnecting due to error processing FetchRequest: read tcp 192.168.10.4:54970->192.168.10.4:9094: i/o timeout
[Sarama] 2016/01/22 07:49:03 Closed connection to broker services.veramine.com:9094
2016/01/22 07:49:03 kafka: 1 errors while consuming
[Sarama] 2016/01/22 07:49:03 cluster/consumer -a9899ac7-1b49-40cf-848d-bb843b7231d7 rebalance
[Sarama] 2016/01/22 07:49:03 client/coordinator requesting coordinator for consumergoup backend from localhost:9092
[Sarama] 2016/01/22 07:49:03 client/coordinator coordinator for consumergoup backend is #0 (services.veramine.com:9092)
panic: close of closed channel
```
The close came from gopkg.in/bsm/sarama-cluster%2ev2.(*partitionConsumer).Close(0xcb3d2d8d20, 0x0, 0x0)

Here's the code there:

```
func (c *partitionConsumer) Close() (err error) {
        close(c.dying)
        <-c.dead

        if e := c.pcm.Close(); e != nil {
                err = e
        }
        return
}
```
Do you think I should suggest a change to first check the partitionConsumer to see if it is already closed before closing, or do you think something could be done on sarama side to avoid a panic?  I figured that even if a kafka instance died, eventually a rebalance would accomodate that so I'd rather not panic.  I would be happy to open a suggestion over on the sarama-cluster side if you guys think it belongs over there.  Thanks!

Jonathan

**Comment by eapache** [comment]
Since the crashing line of code is in sarama-cluster, my assumption is that the bug is in that code. Please file upstream and if their investigation suggests sarama is the root cause we'll take a look then.

**Comment by jdness** [comment]
Sure, will do.  Thanks!
