### ISSUE TITLE
Consumer registration and rebalancing

### ISSUE THREAD

**Issue by dim** [Shopify/sarama#60]
Are there plans for sarama to directly support automated consumer registration and rebalancing, as described on http://kafka.apache.org/documentation.html#distributionimpl.

Use case: assuming I have N topics with M partitions, and I would to run a consumer group and distribute these across O consumers as evenly as possible (with each message being consumed only once). 

The process steps are nicely documented, but is purely based on ZK communication. Should this be implemented directly into sarama or would it be better to create a wrapper library? 

I volunteer to help with the development, but I would like to know if there as any existing work or plans I can (should) rely on?

**Comment by dim** [comment]
I think it's better to keep this separate from the main sarama code and not pollute it with zk dependencies. I have created a new project for it: https://github.com/bsm/sarama-cluster

**Comment by arianitu** [comment]
@dim now that zookeeper isn't a dependency to implement consumer groups, what are the chances you can move this into the official sarama repo?

**Comment by dim** [comment]
@arianitu maybe, but there is quite a bit of effort involved and the integration is not 100% straight-forwards as the test cases/setups are more complicated. more importantly: I probably won't be able to find the time for such an effort any time soon, but help is more than welcome
