### ISSUE TITLE
snappy compression

### ISSUE THREAD

**Issue by culiangfanzi** [Shopify/sarama#615]
I used sarama AsyncProducer using snappy compression to send messageSet(5 messages per messageSet),I found that  the origin data were 3940 bytes, and the compressed data were 832 bytes.It indicated the snappy compression has worked..While I checked kafka log data，it showed "offset: 1047825 position: 484851876 isvalid: true payloadsize: 3607 magic: 0 compresscodec: SnappyCompressionCodec crc: 2412106187" and it seemed that the kafka broker had decode data and encode data again..
How can I store compressed data in kafka which should be 832 bytes per messageSet in this case ?

**Comment by eapache** [comment]
Kafka configuration is outside the scope of this project; if sarama is sending the data compressed, then there is nothing else we can do on our end. Please ask perhaps on the `kafka-users` mailing list.

**Comment by culiangfanzi** [comment]
ok。3ks.
