### ISSUE TITLE
Consumergroup Example

### ISSUE THREAD

**Issue by vishal24tuniki** [Shopify/sarama#619]
Can anyone of you provide a real clean example of usage of consumergroup with Shopify sarama. The docs alone aren't really clear. It would be of real help.

**Comment by eapache** [comment]
See #606.

**Comment by tcrayford** [comment]
@eapache you have any interest in bringing https://github.com/bsm/sarama-cluster inside the main codebase? I'm somewhat interested in making that a PR.

**Comment by eapache** [comment]
I'd be interested, if @dim is willing. I haven't reviewed the code in detail, but I'm curious why it's doing custom offset management instead of using sarama's `OffsetManager`.

**Comment by vishal24tuniki** [comment]
@eapache Juts curious, I thought sarama itself is sufficient for implementing consumer group. Is it not ? Having seen so many consumergroup methods in the codebase made me think so

**Comment by eapache** [comment]
No. sarama implements the low-level APIs but to have an automatically-balancing consumer group you need one of the extra packages linked in #606.

**Comment by vishal24tuniki** [comment]
@eapache Thank you :)

**Comment by IvanMalison** [comment]
@eapache Is there a distinction between "automatically-balancing consumer group" and a normal consumer group, or are you saying that sarama does not support consumer groups out of the box at all? If it is the later, can you clarify exactly why sarama seems to pass consumer group in its offset fetch requests as in https://github.com/Shopify/sarama/blob/68920ff1be3bbd31449ab1e2c255c50cedeb755c/offset_manager.go#L262 .

I feel like I am missing something here. If you don't use any of these extention libraries, how is the offset for a given partition being maintained at all?

**Comment by wvanbergen** [comment]
Sarama supports the low-level APIs that are needed to implement a consumergroup, but doesn't implement consumergroup itself.

**Comment by IvanMalison** [comment]
@wvanbergen can you elaborate.

It seems to pass the group in the offset fetch request. What effect is that having. What offset is being read if in the offset request?

**Comment by wvanbergen** [comment]
It's a low-level API. There is an API to store offsets, and there's an API to retrieve those offsets again. Offset management is only one part of a consumergroup. It also requires dividing all partitions over the different consumer instances, and  rebalancing when new instances join or leave the group. The low level requests for these operations are also implemented. 

What is missing is a high-level concept i that combines all these low level APIs into an easy to use consumergroup API. We would welcome a PR that contributes this.

**Comment by dim** [comment]
Would you be interested in merging sarama-cluster? It is pretty much what
you are looking for and it's (reasonably) battle tested. Please let me
know, I can submit a PR.

**Comment by wvanbergen** [comment]
Definitely. A PR would be great so we can make sure it fits in with sarama (w.r.t. API style etc). Once it merged we can make you co-maintainer of this repo.

**Comment by eapache** [comment]
:+1:

**Comment by dim** [comment]
So the code & API style, etc are similar already, as I tried to keep it close to the original style. Please feel free to take a look and comment. I can foresee only a few issues:

1. Tests! I am using a different testing/framework and methodology. Porting my tests could take a while I would really appreciate some help. 
2. sarama-cluster.v2 only supports new (0.8) offset and cluster management. I hope that's fine and doesn't collide with any compatibility promises.
3. Finally, I will have to rewrite parts of the current OffsetManager. I cannot remember why, but there was a particular reason why I had to roll my own for sarama-cluster. I need to revisit the API and establish what was missing, but it was something substantial, that would have required a major version change.

**Comment by eapache** [comment]
1 and 2 are fine, 3 is the part I'm curious about; let us know when you figure it out. Perhaps we should take the rest of this conversation to a separate ticket though since we've wandered a bit far from the original question that was asked here.
