### ISSUE TITLE
it's helpful if the log is classified with debug,info,notice, etc.

### ISSUE THREAD

**Issue by WanliTian** [Shopify/sarama#622]
it's helpful if the log is classified with debug,info,notice, etc.

**Comment by eapache** [comment]
Yes it can be, but Go's logging package (https://golang.org/pkg/log/) does not provide that functionality. Regardless, I think we've struck a pretty good balance in level of detail - Sarama is very quiet except when something interesting happens at which point it should provide enough detail to track down the issue.

**Comment by WanliTian** [comment]
we can create an interface with debug, info, notice. everyone who want use log should make an implement of this interface.

**Comment by eapache** [comment]
That would break API compatibility, so I've added it as an idea to our potential list for v2: https://github.com/Shopify/sarama/wiki/Ideas-that-will-break-backwards-compatibility
