### ISSUE TITLE
When to close the partitionconsumer

### ISSUE THREAD

**Issue by WanliTian** [Shopify/sarama#624]
i create a partition consumer form consumer.when using partitionconsumer for a while, i got this message: consumer/broker/%d closed dead subscription to %s/%d\n

when i find that the messages channel has been closed, i close the partitionconsumer. then i got an error : panic for the reason that close closed channel.

i dive into the code and find that: the error message i got is triggered when `Close` is called. But i never call this function before.

**Comment by eapache** [comment]
If the messages channel has been closed, you do not need to close the partition-consumer again; it is already closed.

The *only* thing that closes it is you calling `Close` or `AsyncClose` - please review your code because *something* must be calling one of those functions.
