### ISSUE TITLE
Question about consumer group when using sarama package

### ISSUE THREAD

**Issue by WanliTian** [Shopify/sarama#629]
hi all
i use sarama to interact with my kafka cluster.
i find one thing that => i cannot find consumer group id under /consumers path in zookeeper.
but i can use kafka-consumer-offset-checker.sh to list my offsets under this topic/consumer group id

how to explain this?

**Comment by wvanbergen** [comment]
Sarama doesn't implement the high-level consumergroup (yet).

- For kafka 0.9, you can use https://github.com/bsm/sarama-cluster
- For kafka 0.8, you can use https://github.com/wvanbergen/kafka
