### ISSUE TITLE
Unable to consumer new message after timeout error.

### ISSUE THREAD

**Issue by degendra** [Shopify/sarama#630]
After running go binary for few hours, I get this error
```[Sarama] 2016/03/16 14:51:37 consumer/broker/0 abandoned subscription to head_crawl/1 because consuming was taking too long```

Once i get his message, I am not able to receive any new messages. How can i handle this issue?
I don't have this problem in my other 5 binaries.

**Comment by eapache** [comment]
This indicates that the queue of messages for that topic/partition is not being read; whatever goroutine or worker you have that should be reading from that channel is stuck or else so slow as to appear stuck.

**Comment by degendra** [comment]
cgConfig := consumergroup.NewConfig()
	cgConfig.Offsets.Initial = sarama.OffsetNewest
	cgConfig.Offsets.ProcessingTimeout = 10 * time.Second
	zookeeperNodes, cgConfig.Zookeeper.Chroot = kazoo.ParseConnectionString(zookeeper)
	consumer, consumerErr := consumergroup.JoinConsumerGroup(consumerGroup, kafkaTopics, zookeeperNodes, cgConfig)
	if consumerErr != nil {
		log.Fatalln(consumerErr)
	}

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	go func() {
		<-c
		if err := consumer.Close(); err != nil {
			sarama.Logger.Println("Error closing the consumer", err)
		}
	}()

	go func() {
		for err := range consumer.Errors() {
			log.Println(err)
			if err := consumer.Close(); err != nil {
				sarama.Logger.Println("Error closing the consumer", err)
			}
		}
	}()

	offsets := make(map[string]map[int32]int64)

	for message := range consumer.Messages() {

		ConsumeMessage(message)

		if offsets[message.Topic] == nil {
			offsets[message.Topic] = make(map[int32]int64)
		}

		if offsets[message.Topic][message.Partition] != 0 && offsets[message.Topic][message.Partition] != message.Offset-1 {
			log.Printf("Unexpected offset on %s:%d. Expected %d, found %d, diff %d.\n", message.Topic, message.Partition, offsets[message.Topic][message.Partition]+1, message.Offset, message.Offset-offsets[message.Topic][message.Partition]+1)
		}

		offsets[message.Topic][message.Partition] = message.Offset
		consumer.CommitUpto(message)
	}

ConsumeMessage function sometimes take more than 5 minutes.

**Comment by eapache** [comment]
If `ConsumeMessage` can be slow, you should be setting `Consumer.MaxProcessingTime` (https://github.com/Shopify/sarama/blob/f26080eb84027ccbd6aca4565b540be1baafbc05/config.go#L173). However even at the default value, your consumer *should* resume automatically once `ConsumeMessage` finally returns.
