### ISSUE TITLE
questions about ConsumePartition

### ISSUE THREAD

**Issue by ZhangZhenhua** [Shopify/sarama#638]
Currently the only way for a consumer to retrieve messages from Kafka is calling ConsumePartition method. It needs three parameters: topic, partition and offset. I have some questions about partition and offset here and any help is appreciate. 

1. partition
Is there a way to consume messages without specifying the partition? Say if we have a topic with 6 partitions and we create only one consumer, then it will read 6 partitions. If we we create two consumers, then they will read three partitions each. And they will balance consumer-partition mapping themselves. 

1. offset
Kafka will not delete messages that had been consumed immediately. So it's common that one partition may have oldest offset at 100 and newest 300 and the consumer is now consuming at 200. In this case, what does the OffsetNewest and OffsetOldest mean? And if the consumer crashes and we start another to continue, it will be good if it starts at 200 so we can achieve exactly once semantic. So can we query the current offset out instead of letting applications storing it somewhere?

Thanks very much for help and comments!!

**Comment by wvanbergen** [comment]
Sarama only provides low level consumer APIs, and does not currently implement a high level consumer that manages partitions and offset state like you describe. See #619.

**Comment by ZhangZhenhua** [comment]
@wvanbergen Thanks for your quick reply!
