### ISSUE TITLE
How to delete a topic?

### ISSUE THREAD

**Issue by miaoyq** [Shopify/sarama#640]
Hi  All!
    How to delete a topic by sarama, like using command:
    "bin/kafka-topics.sh --zookeeper zk_host:port/chroot --delete --topic ..."
    
   Thanks!

**Comment by zxlzh2015** [comment]
I have the same question，help me please

**Comment by wvanbergen** [comment]
The kafka protocol doesn't have an API to delete topics, so sarama cannot do this.

You have to interact with Zookeeper to delete a topic. https://github.com/wvanbergen/kazoo-go can do this, or the command line tool that ships with the Kafka broker.

**Comment by kazhuravlev** [comment]
Kafka has API to delete topic.
You can use `sarama.Broker.DeleteTopic` method or use `sarama.ClusterAdmin.DeleteTopic`.

```go
clusterAdmin, _ := sarama.NewClusterAdmin([]string{"127.0.0.1:9092"}, sarama.Config{})
clusterAdmin.DeleteTopic("my-topic")
```

**Comment by kazhuravlev** [comment]
https://kafka.apache.org/protocol#The_Messages_DeleteTopics
