### ISSUE TITLE
Sarama Offset Management

### ISSUE THREAD

**Issue by myusuf3** [Shopify/sarama#644]
Hey guys, 

Been using sarama for sometime now in our processing pipeline! Loving it. I am making an effort to upgrade to the master and I noticed last I check there was some progress on enabling offset tracking, currently I am waiting for acknowledge  and storing that offset in memcached and going off that since offset tracking was reliable back in then. 

I was hoping to see an example of where I can reliably get latest offset in order to track my progress through various topics and partitions, also remain tolerant through restarts and consumers no where to start back up on. I would love to get rid of this offset storage mechanism I have built and hoping current sarama has a fix. 

If you could provide simple example of this, would be fantastic!

Thanks!

**Comment by eapache** [comment]
`OffsetManager` exists and is functional for storing/retrieving offsets on the kafka brokers themselves. However, you'd have to connect it to the consumer manually. https://github.com/bsm/sarama-cluster wraps that functionality to provide an automatic self-balancing consumer if that's more what you're looking for?

**Comment by myusuf3** [comment]
that says it supports 0.9+ we are still on 0.8.

**Comment by eapache** [comment]
Sarama itself only supports Kafka's built-in offset management, which is only available in kafka 0.9 and later. https://github.com/wvanbergen/kafka wraps it to use zookeeper for offset management.

**Comment by wvanbergen** [comment]
That library also has an example consumer that you could use as a starting point. Closing this issue.
