### ISSUE TITLE
SyncProducer does not seem to respect partition field in SendMessage method

### ISSUE THREAD

**Issue by bpatelcs** [Shopify/sarama#645]
I am using following code snippet to send the message to particular partition in the kafka,but it seems producer is sending in the radom partition irrespective of what I mention in the Partition field.

```
	producer.SendMessage(&sarama.ProducerMessage{Topic:topic,
		Partition:partition,
		Value:sarama.StringEncoder(body),
	})
```

**Comment by eapache** [comment]
Are you setting `Producer.Partitioner` in the config to `NewManualPartitioner`?

**Comment by bpatelcs** [comment]
Thanks eapache for quick replay,
`config.Producer.Partitioner =sarama.NewManualPartitioner`
Is this what I have to set?

**Comment by eapache** [comment]
I believe that should do the trick.

**Comment by wvanbergen** [comment]
Closing this - feel free to reopen if this didn't fix your issue.

**Comment by bpatelcs** [comment]
Thanks you guys, it worked.

**Comment by bpatelcs** [comment]
yes.
