### ISSUE TITLE
Does sarama support manual offset management in consumer?

### ISSUE THREAD

**Issue by bpatelcs** [Shopify/sarama#649]

**Comment by wvanbergen** [comment]
Yes. You can either use the `OffsetManager`, or call `CommitOffset` yourself to manage offsets.

**Comment by bpatelcs** [comment]
Do we need to turn on the manual offset management, and it would be great if you can point me to the sample code?

**Comment by wvanbergen** [comment]
By default, sarama implements a low level consumer that doesn't do offset management at all. So offset management is opt in: no need to turn it on besides starting to use it.
