### ISSUE TITLE
Consumer allocates a lot of memory when Consumer.Offsets.Retention has non-zero value

### ISSUE THREAD

**Issue by dimchansky** [Shopify/sarama#650]
Marking offset (calling `MarkOffset` method on partition offset manager) in Kafka 0.8.2 when `Consumer.Offsets.Retention` has non-zero value leads to system halt because application eventually uses all available memory. There are a lot of messages in log like:
```
Non-zero timestamp specified for OffsetCommitRequest not v1, it will be ignored
kafka: error while consuming topic_name/0: EOF
```
sarama version: https://github.com/Shopify/sarama/commit/68920ff1be3bbd31449ab1e2c255c50cedeb755c
Kafka version: 0.8.2
Go version: 1.6.2 windows/amd64

**Comment by eapache** [comment]
> Kafka 0.8.2 when `Consumer.Offsets.Retention` has non-zero value

We should document that this is not a valid configuration. Support for `Consumer.Offsets.Retention` was only added in Kafka 0.9. If you check your broker logs I suspect you will see them complaining about an unrecognized message format or something.

> application eventually uses all available memory

Even given the above misconfiguration, I don't see any reason for it to use all available memory. Can you provide more complete logs when this happens?

> Non-zero timestamp specified for OffsetCommitRequest not v1, it will be ignored

This indicates a very minor (totally harmless) issue which is not related to anything else, I'll fix it too.

**Comment by eapache** [comment]
If you can provide the needed information, I am happy to reopen.
