### ISSUE TITLE
How to commit offset to kafka in Broker

### ISSUE THREAD

**Issue by chzyer** [Shopify/sarama#662]
Hi, guys.
As we know, kafka provides a API that allows users to commit offset to it directly.

For the details of this API is referred in follows, or check in here [`A Guide To The Kafka Protocol - OffsetCommitRequest`](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetCommitRequest):
```
v0 (supported in 0.8.1 or later)
OffsetCommitRequest => ConsumerGroupId [TopicName [Partition Offset Metadata]]
  ConsumerGroupId => string
  TopicName => string
  Partition => int32
  Offset => int64
  Metadata => string
```

In sarama, it seems the corresponding API is 

```go

func (b *Broker) CommitOffset(request *OffsetCommitRequest) (*OffsetCommitResponse, error) {}

type OffsetCommitRequest struct {
    ConsumerGroup           string
    ConsumerGroupGeneration int32  // v1 or later
    ConsumerID              string // v1 or later
    RetentionTime           int64  // v2 or later

    // Version can be:
    // - 0 (kafka 0.8.1 and later)
    // - 1 (kafka 0.8.2 and later)
    // - 2 (kafka 0.8.3 and later)
    Version int16
    // contains filtered or unexported fields
}
```

But it's so weird that `OffsetCommitRequest` is quite different from the docs above.
I can't found where is the `TopicName/Partition/Offset`.

So, how can I commit offset to kafka ?

**Comment by wvanbergen** [comment]
See the `AddBlock` function of the OffsetCommitRequest type: https://github.com/Shopify/sarama/blob/master/offset_commit_request.go#L167-L177

Alternatively, use the high-level `OffsetManager` type. The implementation of that type should also serve as a good example on how to use the low level request type.

**Comment by chzyer** [comment]
@wvanbergen Thanks!
