### ISSUE TITLE
Error processing append operation on partition

### ISSUE THREAD

**Issue by jayeshsidhwani** [Shopify/sarama#663]
I have a load of ~10k messages/sec. As the load increases, I see a burst of following error in Kafka (before everything works fine again):
Error: `ERROR kafka.server.ReplicaManager: [Replica Manager on Broker 22]: Error processing append operation on partition _topic_name_-_partition_`
Pastebin: http://pastebin.com/QbkwHJ3W

Strangely, when I retry the same message again it works. I'm using Snappy Compression while publishing. 

Does this issue sound familiar to anyone?

**Comment by tcrayford** [comment]
This doesn't feel like a sarama issue, but more likely a Kafka one. I'd recommend asking on the user's mailing list: http://kafka.apache.org/contact.html

**Comment by eapache** [comment]
Yes, AFAICT this is an upstream issue.
