### ISSUE TITLE
Check the received message value in producer mocks

### ISSUE THREAD

**Issue by jacksilv** [Shopify/sarama#667]
Hi guys, not sure if this is a valid issue.
When developing a unit test for a program that uses the sync/asyc producer, I can only say that I expect to receive a message and that I want the mock response to be success/error.
For my test I need to check the value inside the message, so I propose to extend the `producerExpectation struct` in mocks.go and to add new methods to the producer mock, that receive in input a string (regexp) and check the received value against this regexp.
I am ok to propose an implementation if it makes sense.

**Comment by eapache** [comment]
Seems reasonable to me.

**Comment by jacksilv** [comment]
Thanks folks, I will start working on the implementation soon.
