### ISSUE TITLE
Retrieving Topic/Partition Log Size

### ISSUE THREAD

**Issue by marcosrmendezthd** [Shopify/sarama#675]
How could I get the log size to calculate the lag size for a partition?

Could something like this be implemented with the existing codebase?

https://apache.googlesource.com/kafka/+/0.8.1/core/src/main/scala/kafka/tools/ConsumerOffsetChecker.scala#72

**Comment by eapache** [comment]
Yes, quite easily. `Client.GetOffset()` should be the method you want.

**Comment by marcosrmendezthd** [comment]
thanks. will do.
