### ISSUE TITLE
leveled logging needed or StdLogger interface only used for log error message

### ISSUE THREAD

**Issue by NeoCN** [Shopify/sarama#686]
##### Versions

Sarama Version: *
Kafka Version: *
Go Version: *

##### Problem Description

I want to log sarama error messages to file, and error messages only; the comment description for StdLogger interface is _StdLogger is used to log error messages._. but the global Logger var as StdLogger impl is also used for log debug messages as we saw in the code.

Is there any plan to support leveled logging?  or any advice to get error messages only?

**Comment by wvanbergen** [comment]
We have put quite some efforts into finding the right balance between verboseness and usefulness. When sarama is not encountering any problems, you will only see one line of log every 10 minutes (or whatever you set the metadata refresh interval to). It only logs more when it has to deal will "problems", like a kafka broker going down. Most of these problems, sarama can deal with by retrying, so they don't surface as errors. However, when problems do surface as errors, the logs are very important to us to be able to debug what happened. So when people report issues to us, we usually start by asking: can you provide the logs?

The `StdLogger` interface was added to match the interface of the built in `Logger` type. My preference is that it should always possible for a user to send a standard logger instance to sarama to enable logging without any extra work, and get useful log output to debug issues.

I am OK with discussing changes to how we handle logging, but I don't want to sacrifice what I described above (nor backwards compatibility).

If you only want messages for errors that surface to the end user, my suggestion would be to log the contents of the `Errors` channel.

**Comment by NeoCN** [comment]
@wvanbergen Thanks. I got it. I will log the contents of the ```Errors``` channel as error messages and implement ```StdLogger``` interface to log debug messages to file.

**Comment by wvanbergen** [comment]
Sounds like a plan!
