### ISSUE TITLE
kafka server: The version of API is not supported.

### ISSUE THREAD

**Issue by boncheff** [Shopify/sarama#691]
##### Versions

Sarama Version: latest
Kafka Version: 2.10-0.9.0.1
Go Version: go1.6.2 linux/amd64

##### Configuration

What configuration values are you using for Sarama and Kafka?

clusterConf := cluster.NewConfig()  //cluster is "gopkg.in/bsm/sarama-cluster.v2"
if verbose {
    sarama.Logger = log.StandardLogger()
} else {
    clusterConf.Consumer.Return.Errors = true
    clusterConf.Group.Return.Notifications = true
}
clusterConf.Consumer.Offsets.Initial = sarama.OffsetOldest

consumer, err := cluster.NewConsumer(
    conf.KafkaHosts,
    conf.KafkaConsumerGroup,
    strings.Split(conf.KafkaTopic, ","),
    clusterConf)

##### Problem Description

Since the latest release of sarama we have started seeing this error all the time followed by a rebalance notification

ERRO[0000] Consumer Error: kafka server: The version of API is not supported.
INFO[0000] Consumer Rebalanced: &{Claimed:map[] Released:map[] Current:map[]}
ERRO[0000] Consumer Error: kafka server: The version of API is not supported.
INFO[0000] Consumer Rebalanced: &{Claimed:map[] Released:map[] Current:map[]}
ERRO[0000] Consumer Error: kafka server: The version of API is not supported.
INFO[0000] Consumer Rebalanced: &{Claimed:map[] Released:map[] Current:map[]}
INFO[0001] Consumer Rebalanced: &{Claimed:map[] Released:map[] Current:map[]}
ERRO[0001] Consumer Error: kafka server: The version of API is not supported.
INFO[0001] Consumer Rebalanced: &{Claimed:map[] Released:map[] Current:map[]}
ERRO[0001] Consumer Error: kafka server: The version of API is not supported.
...

The errors appear here

    // Handler for consumer errors
    go func() {
        for err := range consumer.Errors() {
            log.Errorf("Consumer Error: %s", err.Error())
        }
    }()

    // Handler for consumer rebalance notifications
    go func() {
        for note := range consumer.Notifications() {
            log.Infof("Consumer Rebalanced: %+v", note)
        }
    }()

This used to work prior to the release

The way we managed to get around this issue is to pin the Sarama version using Godep  to the following commit:

github.com/Shopify/sarama 4ba9bba6adb6697bcec3841e1ecdfecf5227c3b9

We heavily rely on Sarama so any advice will be greatly appreciated

**Comment by eapache** [comment]
As of recent changes on master you need to specify the version of your brokers in the sarama config so that it knows which protocol messages it can safely use. Setting `config.Version =  V0_9_0_1` should do the trick.

We will be documenting this properly before we push out another tagged version.

**Comment by boncheff** [comment]
Thanks, much appreciated

**Comment by Dieterbe** [comment]
cool. was also hitting this issue.
it's a bit unfortunate how github works / how people use github.. if you update the readme to correspond to latest master, the instructions are off for people using a stable release. if you update the readme when you do a stable release, instructions are off for people using latest git. people often don't use the tag/branch selector to see the readme for their particular version.
