### ISSUE TITLE
kafka 0.10 support?

### ISSUE THREAD

**Issue by Dieterbe** [Shopify/sarama#696]
according to the readme, 0.9 is the last version supported.
i see some activity in the repo and issues that relate to 0.10
does this mean 0.10 is supported? fully? is it recommended to use 0.10 over 0.9 ?

thanks!

**Comment by eapache** [comment]
Sarama 1.9 was released before Kafka 0.10 so I can't guarantee it will work, but Kafka has good backwards compatibility, so it *should*. It supports none of the new features (e.g. message timestamps) added in 0.10.

Sarama master definitely works with 0.10. It also supports some but not all of the new features added in 0.10. I have plans to release Sarama 1.10 fairly soon, and I'll update the supported versions in the README at that time.

**Comment by Dieterbe** [comment]
thanks @eapache , i use sarama master. is master considered stable or should i favor a specific release?

**Comment by eapache** [comment]
It should be pretty stable, but I would probably stick to tagged versions for critical production usage.

**Comment by lieut-data** [comment]
It's worth noting that without support for message timestamps, Kafka Streams will by default throw exceptions when processing messages produced by Sarama:
```
Exception in thread "StreamThread-1" org.apache.kafka.streams.errors.StreamsException: Extracted timestamp value is negative, which is not allowed.
```

See http://docs.confluent.io/3.1.0/streams/faq.html#invalid-timestamp-exception, but as a workaround you'll need to switch to a different timestamp extractor.

**Comment by eapache** [comment]
Sarama supports message timestamps since v1.10 released in August, although that had a bug when using timestamps with compression. v1.11 (released a few days ago) should support message timestamps correctly in all cases.

**Comment by lieut-data** [comment]
Aha, I see my mistake now. Unless Sarama is explicitly configured to use `config.Version = sarama.V0_10_1_0`, it currently defaults to semantics that leave the timestamp unset. Thank you for the clarification as to the underlying support!
