### ISSUE TITLE
error: reference to undefined identifier / error: unknown field 

### ISSUE THREAD

**Issue by nealbh** [Shopify/sarama#700]
Running Go version 1.6.2
Running Kafka version 0.9

When pulling down the code down from burrow using the command "go get github.com/linkedin/burrow" I'm getting the following error:

 github.com/Shopify/sarama
go/src/github.com/Shopify/sarama/broker.go:73:28: error: reference to undefined identifier ‘tls.DialWithDialer’
    b.conn, b.connErr = tls.DialWithDialer(&dialer, "tcp", b.addr, conf.Net.TLS.Config)
                            
go/src/github.com/Shopify/sarama/broker.go:69:4: error: unknown field ‘KeepAlive’ in ‘net.Dialer’
    KeepAlive: conf.Net.KeepAlive,

**Comment by eapache** [comment]
Those fields and methods were added in Go 1.3 (https://golang.org/doc/go1.3#minor_library_changes). Please double-check that you are using the go version you think you are.

**Comment by nealbh** [comment]
You're correct. The go version wasn't correct. I changed it to use 1.6 and everything is running fine.
