### ISSUE TITLE
Official support for Kafka 0.10 (Protocol)

### ISSUE THREAD

**Issue by andygrunwald** [Shopify/sarama#704]
##### Versions

Sarama Version: master
Kafka Version: 0.10.0
Go Version: *

##### Problem Description

Is there any plan to upgrade Sarama to be compatible with Kafka 0.10 (officially)?

I saw that the [TravisCI tests running for KAFKA_VERSION=0.10.0.0](https://travis-ci.org/Shopify/sarama/jobs/144225607) already.

##### References

* [Upgrading from 0.8.x or 0.9.x to 0.10.0.0](https://kafka.apache.org/documentation.html#upgrade_10)
* [Potential breaking changes in 0.10.0.0](https://kafka.apache.org/documentation.html#upgrade_10_breaking)
* [Release Notes - Kafka - Version 0.10.0.0](https://www-eu.apache.org/dist/kafka/0.10.0.0/RELEASE_NOTES.html)

**Comment by eapache** [comment]
Per the [Changelog](https://github.com/Shopify/sarama/blob/master/CHANGELOG.md) the next Sarama release will have Kafka 0.10 support (which means that the latest master already effectively does). Between a few remaining tasks and various vacation plans I don't have an ETA for that release yet unfortunately. Hopefully within the next few weeks.

**Comment by andygrunwald** [comment]
Thank you @eapache
