### ISSUE TITLE
OffsetManager should report error ErrUnknownTopicOrPartition

### ISSUE THREAD

**Issue by Kane-Sendgrid** [Shopify/sarama#706]
ErrUnknownTopicOrPartition at https://github.com/Shopify/sarama/blob/master/offset_manager.go#L460
should be logged and probably considered an error (propagate error back to Close()?)

##### Versions
Sarama Version: master
Kafka Version: 0.10
Go Version: 1.6.2

**Comment by eapache** [comment]
Off the top of my head, I think it depends if you have topic auto-create enabled on your broker? If you do, then retrying ErrUnknownTopicOrPartition is correct because the topic will have been created by the time you try again?

**Comment by Kane-Sendgrid** [comment]
@eapache you are right, it has use case when auto create topic is enabled. I think reporting the error is more correct behavior though. It could be behind the setting, with error reporting on by default. What you think?

**Comment by eapache** [comment]
It's actually easy enough to report the error *and* still retry so that should handle all the cases nicely.
