### ISSUE TITLE
Performance optimization in gzip decoding

### ISSUE THREAD

**Issue by nieksand** [Shopify/sarama#711]
I've found a pretty good performance lift from reusing the gzip Reader in message decoding when working at tens of thousands of RPS against a topic with 128 partitions.

From five runs...
sarama master: 42774 rps avg, stddev=2425
gzip reuse: 48772 rps avg, stddev=2034

The code changes are pretty minimal:
https://github.com/Shopify/sarama/compare/master...nieksand:a317191

Two questions:
1. Do you have any suggestions for a nicer / more holistic way of managing resource reuse across messages?  I suspect something further up the hierarchy could pass down this information rather than needing the synchronization overhead of a Go pool.
2. Is this interesting enough to be merged to mainline if I clean it up and pop a PR?

**Comment by eapache** [comment]
There are two distinct changes in that diff: one to use the pool and one to use `github.com/klauspost/compress/gzip`. Which is responsible for the speed-up?

1. Off the top of my head, maybe try creating/storing it in the `packetDecoder`? That way you'd be generating a new one per network packet instead of per kafka message.
2. Definitely.

**Comment by nieksand** [comment]
I used Klauspost because I remembered Reset() being a latter addition to gzip.  But turns out it's been around since roughly Go 1.4: https://github.com/golang/go/commit/193d09a659c8d0a894fa682a879adb8fac1a4d82

I'm re-running my benchmarks using sync.Pool + compress/gzip instead and will share those in a few hours.  I based on what I saw during development, I believe the pool is root of the performance lift but we'll see. :)

**Comment by nieksand** [comment]
Reran all the benchmarks.  The cluster was under less load this time, so the sigmas are much tighter:

```
No pool, stdlib gzip:
47301.455
48512.500
47864.864
48157.676
47904.564
mu=47948, sigma=444

With pool, stdlib gzip:
54867.219
54715.767
54734.439
55363.825
55278.008
mu=54992, sigma=307

With pool, Klaus gzip:
54537.344
54462.655
54518.672
54773.858
54831.950
mu=54625, sigma=166
```

Tests were done using go1.7rc2, which includes the flate performance enhancements from release notes:  https://tip.golang.org/doc/go1.7

Based on this:
1. There is a definite performance lift from re-using the gzip Reader
2. There is no real difference between stdlib and Klaus for decoding, so I will use stdlib gzip in my PR

**Comment by klauspost** [comment]
You should certainly re-use encoders. Maybe consider using the fastest compression setting. The speed difference to "standard" is big (like a factor of 2) and the compression difference usually only a few percent.

**Comment by nieksand** [comment]
That's good to know.  I'll run some tests on the encode path with std vs. fastest and include those numbers.  (Both size and speed).

I should be able to put together the PR tonight.

**Comment by eapache** [comment]
Did the PR never happen?

**Comment by eapache** [comment]
Appears abandoned.
