### ISSUE TITLE
How can I get offset by time?

### ISSUE THREAD

**Issue by mushenrs** [Shopify/sarama#715]
I use Client#GetOffset to get offset, but time do not effect

for example:
config := sarama.NewConfig()
client, err := sarama.NewClient([]string{"192.168.5.158:9092", "192.168.5.159:9092"}, config)
fmt.Println(client.GetOffset("kubernetes_logger", 0, sarama.OffsetOldest))
fmt.Println(client.GetOffset("kubernetes_logger", 0, sarama.OffsetNewest))
timeUnix := (time.Now().UnixNano() - 3600 * int64(time.Second))
fmt.Println(client.GetOffset("kubernetes_logger", 0, timeUnix))

The result is:
25815497 <nil>
13825148 <nil>
25815497 <nil>

Why the "time" param is not effect ?

**Comment by eapache** [comment]
Kafka only stores a single timestamp per log segment file, so the time param is an approximation. See https://cfchou.github.io/blog/2015/04/23/a-closer-look-at-kafka-offsetrequest/ for a more in-depth explanation (it assumes you're using the java client, but the principles are the same).

**Comment by tcrayford** [comment]
This will change once `KIP-35` is in, but for now yep.

**Comment by mushenrs** [comment]
@eapache
ohhh, I know... Thank you very much!!

**Comment by alexisvisco** [comment]
> Kafka only stores a single timestamp per log segment file, so the time param is an approximation. See [cfchou.github.io/blog/2015/04/23/a-closer-look-at-kafka-offsetrequest](https://cfchou.github.io/blog/2015/04/23/a-closer-look-at-kafka-offsetrequest/) for a more in-depth explanation (it assumes you're using the java client, but the principles are the same).

The link is dead, maybe there is a new solution to this ?
