### ISSUE TITLE
How do we set the maximum number of in-flight requests?

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#718]
Is `Net.MaxOpenRequests` ([link](https://godoc.org/github.com/Shopify/sarama#Config)) in the sarama library the equivalent of `max.in.flight.requests.per.connection` ([link](http://kafka.apache.org/090/documentation.html#producerconfigs)) in the original library?

**Comment by eapache** [comment]
I believe they are similar yes, I don't know the precise details of how the upstream value behaves.

**Comment by ackratos** [comment]
did we have conclusion here?

**Comment by gmaz42** [comment]
It is, according to https://github.com/Shopify/sarama/pull/1539
