### ISSUE TITLE
Question: Consumer to listen to new messages and notify

### ISSUE THREAD

**Issue by linusviking** [Shopify/sarama#719]
##### Versions

Sarama Version: master
Kafka Version: 0.8.2.2
Go Version: 1.6.3

##### Problem Description

I'd like to implement a pattern where the consumer would listen to new messages in a topic and if there's one, call an external REST endpoint to notify (with the message payload). I tried with Kafka REST proxy but the long polling (by setting timeout to max) doesn't work properly. Would appreciate if some guidance or example code on implementing such a notification pattern could be provided?

**Comment by eapache** [comment]
There is an example of consuming in the documentation: https://godoc.org/github.com/Shopify/sarama#Consumer. I'n afraid I can't help you with the REST/polling portion as that is well outside my area of expertise.
