### ISSUE TITLE
consume slow

### ISSUE THREAD

**Issue by simon-xia** [Shopify/sarama#726]
##### Versions

Sarama Version:   1.10.0
Kafka Version: 2.11-0.10.0.0
Go Version:   1.6.2
##### Configuration

What configuration values are you using for Sarama and Kafka?

default
##### Problem Description

my code is as follows:

```
consumer, err := sarama.NewConsumer([]string{kafka_host}, nil)
if err != nil {
    panic(err)
}

defer func() {
    if err := consumer.Close(); err != nil {
        log.Fatalln(err)
    }
}()

partitionConsumer, err := consumer.ConsumePartition(raw_topic, 0, sarama.OffsetOldest) // from head
if err != nil {
    panic(err)
}

defer func() {
    if err := partitionConsumer.Close(); err != nil {
        log.Fatalln(err)
    }
}()

// Trap SIGINT to trigger a shutdown.
signals := make(chan os.Signal, 1)
signal.Notify(signals, os.Interrupt)

consumed := 0
fmt.Printf("start at %v\n", time.Now())

    ConsumerLoop:
for {
    select {
    case <-partitionConsumer.Messages():
        consumed++
        if consumed%10000 == 0 {
            fmt.Printf("consume %v at %v\n", consumed, time.Now())
        }
    case <-signals:
        break ConsumerLoop
    }
}

log.Printf("Consumed: %d\n", consumed)
```

my kafka is full of messages, and the output is as follows:

```
      start at 2016-08-12 09:56:28.704023291 +0800 CST
      consume 10000 at 2016-08-12 09:56:50.771316475 +0800 CST
      consume 20000 at 2016-08-12 09:57:12.237980514 +0800 CST
      consume 30000 at 2016-08-12 09:57:33.174455169 +0800 CST
      ....
```

It tooks about 2~3ms to consume a message, is this normal? it is too slow for me

**Comment by eapache** [comment]
What is "normal" depends heavily on your specific environment: network latency, the speed of your broker, the average size of your messages, whether or not you're using compression, etc. etc. 2-3ms per message does not strike me as unusually slow.

It may help you to enable Sarama logging and see if the consumer is logging any warning messages. You may also want to try adjusting the `Consumer.Fetch.Default` configuration value.

If none of that helps, I suggest you try profiling your consumer. Go has excellent profiling capabilities built in: https://blog.golang.org/profiling-go-programs

**Comment by eapache** [comment]
Actually, my apologies I misread your numbers at first; 2-3ms per message (about 500 messages per second) does seem abnormally slow. http://bravenewgeek.com/dissecting-message-queues/ was able to achieve nearly 75k messages per second with Sarama.

Are you sure that your topic has lots of messages in it already? Perhaps try verifying that with the java-based console-consumer that ships with kafka?

**Comment by simon-xia** [comment]
yep, the topic has lots of message, and there is no error message from `partitionConsumer.Errors()`.  that parition has only have one partition, it this one of reasons?

**Comment by simon-xia** [comment]
[pprof-kafka-client.svg.zip](https://github.com/Shopify/sarama/files/415042/pprof-kafka-client.svg.zip)

**Comment by wvanbergen** [comment]
Are you reading from the beginning of the topic, or the end? If you are reading from the end (default IIRC) you will only see new messages which may not arrive at a very high frequency.

**Comment by simon-xia** [comment]
I use the arg `sarama.OffsetOldest` to read from the beginning, the code is as above

**Comment by eapache** [comment]
The profile you provided isn't very detailed but nothing looks CPU-bound on the client end. Is your network congested? Is your broker under heavy load from some other process? Are your messages extremely large? If you enable Sarama logging (by setting `sarama.Logger`) do you see anything unusual?

**Comment by simon-xia** [comment]
lots of log like this

  [sarama] 2016/08/12 22:49:45 consumer/broker/0 abandoned subscription to testtopic/0 because consuming was taking too long
  [sarama] 2016/08/12 22:49:45 consumer/broker/0 added subscription to testtopic/0
  [sarama] 2016/08/12 22:49:46 consumer/broker/0 abandoned subscription to testtopic/0      because consuming was taking too long
  [sarama] 2016/08/12 22:49:46 consumer/broker/0 added subscription to testtopic/0

**Comment by eapache** [comment]
If you revert the changes in https://github.com/Shopify/sarama/pull/712 does that fix the issue?

**Comment by simon-xia** [comment]
After revert, these logs were gone,  but it is still slow as before

**Comment by simon-xia** [comment]
PS: network is not congested, and there's about 30G messages, each message is less than 1k

**Comment by eapache** [comment]
I'm afraid I don't know what the problem could be. Normally when consuming is slow the bottleneck is either the consumer's configuration or the network.

Please try consuming with the java consumer; if it is just as slow, this is an issue with your kafka cluster and not with Sarama.

**Comment by nsd20463** [comment]
My experience with kafka has been that reading starting from the oldest message is often limited by the IO speed of the storage containing the logs, because it is uncommon, and those portions of the log files are not in the filesystem cache.

If this is your case, then re-reading some[1] messages a 2nd time should go much faster.

[1] some = enough to measure, but not so many that the size of all the messages is > the size of the filesystem cache.

**Comment by eapache** [comment]
I'm afraid I can't provide any other suggestions on this issue, sorry.

**Comment by danield137** [comment]
seeing same behaviour with same code (same code as examples).

Versions

Sarama Version: 1.11.0
Kafka Version: 9.0.1
Go Version: 1.8

OS (seeing slow perf on both):
1. amazon ec2 m3.xlarge 
2. macOS 10.12.2 , 2.2 intel i7, 16GB RAM 

Getting very slow performance on a single consumer on a single partition (out of 10)
averaging around 100ms per message consumed (sample size of around 10,000 messages consumed)

same code running python client with kafka-python and shows much better performance (more than 100 times faster)

Profiling on mac looks like so:

(pprof) top10
476ms of 510ms total (93.33%)
Dropped 51 nodes (cum <= 2.55ms)
Showing top 10 nodes out of 120 (cum >= 8ms)
      flat  flat%   sum%        cum   cum%
     104ms 20.39% 20.39%      104ms 20.39%  runtime.mach_semaphore_signal
      88ms 17.25% 37.65%       88ms 17.25%  runtime.usleep
      82ms 16.08% 53.73%      112ms 21.96%  syscall.Syscall
      58ms 11.37% 65.10%       58ms 11.37%  runtime.mach_semaphore_timedwait
      46ms  9.02% 74.12%       46ms  9.02%  runtime.freedefer
      34ms  6.67% 80.78%       34ms  6.67%  runtime.mach_semaphore_wait
      28ms  5.49% 86.27%       28ms  5.49%  runtime.kevent
      18ms  3.53% 89.80%       18ms  3.53%  crypto/elliptic.p256Mul
      12ms  2.35% 92.16%       12ms  2.35%  runtime.memmove
       6ms  1.18% 93.33%        8ms  1.57%  runtime.selectgoImpl

**Comment by eapache** [comment]
How large are your messages? Perhaps you need to adjust `Config.Consumer.Fetch.Default`?

**Comment by danield137** [comment]
0.5kb

**Comment by eapache** [comment]
Hmm... well based on that stacktrace the slowness could be garbage-collector related or something? Or maybe goroutine contention?

Unfortunately I have never been able to reproduce this issue and I don't have a clue what the cause could be. If you are willing to put some time into this, please open a new ticket and include as much debugging information as you can (logs, full code, etc). You might also want ot run through some of the debugging steps described at https://software.intel.com/en-us/blogs/2014/05/10/debugging-performance-issues-in-go-programs - that article covers a long list of interesting issues.

**Comment by WanliTian** [comment]
seeing same behaviour 

![_20171119123613](https://user-images.githubusercontent.com/2391020/32987430-78a7ad8c-cd26-11e7-8a13-e63ace31b502.png)

**Comment by WanliTian** [comment]
message is range from 1k to 5M
using default configure for sarama

**Comment by taozle** [comment]
I met the same issue, i tested java client and confluent-kafka-go, they both work normal, always catch up with the newest message, thounds of message per second, but sarama only consume hundreds of messages, and cpu is very low, I tried to set `config.Consumer.Fetch.Default = 1024*1024` and `config.Consumer.MaxWaitTime = 500 *time.Millisecond`, but seems no effect.

**Comment by pwaterz** [comment]
Same here. Getting about 300 messages every 30 seconds :(. I am running my binaries in a local docker container connecting to kafka hosted in a data center. Maybe docker is the issue?

**Comment by pwaterz** [comment]
My issue ended up being that I went with the default initial offset. Which is read newest first. Switch oldest and it's super fast now.

config.Consumer.Offsets.Initial = sarama.OffsetOldest

**Comment by dairongpeng** [comment]
I have a similar problem, is there an answer to that question?

**Comment by rhammonds1-kr** [comment]
I am facing a similar issue.
`
12/15/2022, 2:56:12.857 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long
12/15/2022, 2:56:12.478 PM
consumer/broker/1 added subscription to klog/9
12/15/2022, 2:56:12.478 PM
consumer/broker/1 accumulated 1 new subscriptions
12/15/2022, 2:55:32.704 PM
client/metadata fetching metadata for all topics from broker u060jaded101.kroger.com:9092
12/15/2022, 2:55:32.452 PM
client/metadata fetching metadata for all topics from broker krogercustomer-prod.servicebus.windows.net:9093
12/15/2022, 2:55:07.792 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long
12/15/2022, 2:55:06.674 PM
consumer/broker/1 added subscription to klog/9
12/15/2022, 2:55:06.674 PM
consumer/broker/1 accumulated 1 new subscriptions
12/15/2022, 2:54:03.893 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long
12/15/2022, 2:54:03.082 PM
consumer/broker/1 added subscription to klog/9
12/15/2022, 2:54:03.082 PM
consumer/broker/1 accumulated 1 new subscriptions
12/15/2022, 2:52:53.157 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long
12/15/2022, 2:52:52.722 PM
consumer/broker/1 added subscription to klog/9
12/15/2022, 2:52:52.722 PM
consumer/broker/1 accumulated 1 new subscriptions
12/15/2022, 2:51:49.094 PM
consumer/broker/1 abandoned subscription to klog/9 because consuming was taking too long`

github.com/Shopify/sarama v1.37.2

Kafka Version 3.2

My config:
`c.Admin.Retry.Max = 5
	c.Admin.Retry.Backoff = 100 * time.Millisecond
	c.Admin.Timeout = 3 * time.Second

	c.Net.MaxOpenRequests = 5
	c.Net.DialTimeout = 30 * time.Second
	c.Net.ReadTimeout = 30 * time.Second
	c.Net.WriteTimeout = 30 * time.Second
	c.Net.SASL.Handshake = true
	c.Net.SASL.Version = SASLHandshakeV0

	c.Metadata.Retry.Max = 3
	c.Metadata.Retry.Backoff = 250 * time.Millisecond
	c.Metadata.RefreshFrequency = 10 * time.Minute
	c.Metadata.Full = true
	c.Metadata.AllowAutoTopicCreation = true

	c.Consumer.Fetch.Min = 1
	c.Consumer.Fetch.Default = 1024 * 1024
	c.Consumer.Retry.Backoff = 2 * time.Second
	c.Consumer.MaxWaitTime = 500 * time.Millisecond
	c.Consumer.MaxProcessingTime = 100 * time.Millisecond
	c.Consumer.Return.Errors = false
	c.Consumer.Offsets.AutoCommit.Enable = true
	c.Consumer.Offsets.AutoCommit.Interval = 1 * time.Second
	c.Consumer.Offsets.Initial = OffsetNewest
	c.Consumer.Offsets.Retry.Max = 3

	c.Consumer.Group.Session.Timeout = 10 * time.Second
	c.Consumer.Group.Heartbeat.Interval = 3 * time.Second
	c.Consumer.Group.Rebalance.GroupStrategies = []BalanceStrategy{BalanceStrategyRange}
	c.Consumer.Group.Rebalance.Timeout = 60 * time.Second
	c.Consumer.Group.Rebalance.Retry.Max = 4
	c.Consumer.Group.Rebalance.Retry.Backoff = 2 * time.Second
	c.Consumer.Group.ResetInvalidOffsets = true

	c.ClientID = defaultClientID
	c.ChannelBufferSize = 256
	c.ApiVersionsRequest = true
	c.Version = DefaultVersion
	c.MetricRegistry = metrics.NewRegistry()`
