### ISSUE TITLE
Seeking to an offset on a partition that is already being consumed

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#728]
I am wondering whether sarama supports the ability to `seek()` to a specific offset on a partition that is **currently** being consumed.

Specifically, I am looking for the equivalent of these three Java methods: https://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#seek(org.apache.kafka.common.TopicPartition,%20long)

Note that this is different than setting the `Consumer.Offsets.Initial` config key before a consumer is created. (i.e. I know how to seek an offset when I **first** establish a connection to the broker)

Thank you.

**Comment by eapache** [comment]
We do not currently have any equivalent of that method, because as noted in the docs for the java methods, it is generally unsafe to call in the middle of consuming anyway. It is safer and more deterministic to close your current partition-consumer and re-open it with the desired offset.

**Comment by kchristidis** [comment]
Gotcha, thank you.
