### ISSUE TITLE
performance for sarama producer

### ISSUE THREAD

**Issue by chandradeepak** [Shopify/sarama#737]
##### Versions

Sarama Version:latest version
Kafka Version: 0.10.0.0
Go Version:1.6

##### Configuration
sconfig.Net.TLS.Enable = true
sconfig.Producer.RequiredAcks = sarama.WaitForAll
sconfig.Producer.Partitioner = sarama.NewRoundRobinPartitioner
sconfig.Producer.Compression = sarama.CompressionSnappy
sconfig.Consumer.Return.Errors = true
sconfig.Consumer.Fetch.Min = 512kb
sconfig.Consumer.Fetch.Max = 1MB

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

We are using Sync producer to write messages to kafka. We are gettting low performance. I have seen people discuss getting 6k/sec. our requirement is that we need to persist data to kafka before returning to client. we can't do async because client has to take appropriate action if messages are not written to kafka. Or is there a way we use aysnc Producer and achieve the same functionality.

write now we are using only one NewSyncProducer for writing to kafka. Does creating multiple of these per topic increase the performance ? 

Do i need to play with the Producer.Flush.Frequency  ,Producer.Flush.Bytes to get maximum performance. 

Any suggestions will be great help.

**Comment by eapache** [comment]
> Or is there a way we use aysnc Producer and achieve the same functionality

The async producer will return errors by default and can be set to return successes as well. If you want you can have a goroutine reading from the those channels and have it take the appropriate action when it receives an error. I don't know if this is sufficient for your use case.

>  now we are using only one NewSyncProducer for writing to kafka. Does creating multiple of these per topic increase the performance ?

It might, at the cost of very many network connections. You are better off trying to call `SendMessage` concurrently.

**Comment by chandradeepak** [comment]
thanks . i am trying to use asyncproducer now but i get this warning "maximum request accumulated, waiting for space" . I started using 
sconfig.Producer.Return.Successes = true
sconfig.Producer.Return.Errors = true
Assuming all data will be sent to kafka when this happens .  I ingested 1000K messages each of size 1K . But i am not getting the ack for all the 1000K .  To verify i am reading data from kafka some times i get 200K some times i get 250K but i never got all the messages back.

Is it some thing if that warning happens data is not guaranteed to be persisted in kafka and we should reduce throughput. How could i ever know that my buffer are full. ?

**Comment by eapache** [comment]
> maximum request accumulated, waiting for space

This simply means that you are trying to produce faster than the events can be sent on the network. You can probably make it go faster by changing the value of `RequiredAcks` but that depends on what your consistency requirements are.

> Assuming all data will be sent to kafka when this happens . I ingested 1000K messages each of size 1K . But i am not getting the ack for all the 1000K 

That is very strange. Are you sure you are waiting long enough? The acks may come back some time after the message has been sent depending on how long it takes Kafka to commit the message, but you should always get *either* a success or an error.

To ensure that all messages have been processed you should call `AsyncClose` and wait for the channels to be closed.

>  To verify i am reading data from kafka some times i get 200K some times i get 250K but i never got all the messages back.

Does this mean you are consuming from kafka in a separate process and not seeing all of the messages there either? This sounds like the producer process is being terminated before it can flush all its messages.

> Is it some thing if that warning happens data is not guaranteed to be persisted in kafka and we should reduce throughput

No, the warning and buffer speed have nothing to do with it.

**Comment by chandradeepak** [comment]
Thanks for your reply.
yeah my producer process is killed . so we need call the async close to make sure all messages are flushed  and i am consuming from different process. what if we never want to do the async close because i might get more messages in future.  Then is there a way to know when all the messages are pushed. 

Basically what can be the performance i can expect with async producer. if i have each message as some thing like 1kb.

**Comment by eapache** [comment]
> i might get more messages in future. Then is there a way to know when all the messages are pushed.

If you might get more messages then I don't know what you mean when "all" messages are pushed. Is it enough to keep an atomic counter, incremented when you send a message and decremented when you get a success or error?

> Basically what can be the performance i can expect with async producer. if i have each message as some thing like 1kb.

It depends a *lot* on your network, your kafka cluster's disks, etc. so it's hard to give specific numbers. For comparison though, http://bravenewgeek.com/dissecting-message-queues/ claims to have produced almost 100k messages per second.

**Comment by chandradeepak** [comment]
ok . i will try further with async producer and update the results here . Thanks for your patient replies

**Comment by Maqiushi** [comment]
@chandradeepak 
hi there, did you get any solution about this issue you opened up?
I'm currently facing the same issue as you described. By using async producer I can get 50k msg/s performance, but when using sync way it reduced to 6k.

In my case, I also 
> need to persist data to kafka before returning to client
and 
> client has to take appropriate action if messages are not written to kafka

appreciate any feedback!

**Comment by chandradeepak** [comment]
@Maqiushi ,  we basically switched to async producer by default for performance. For guaranteed delivery since the async producer returns acks we read acks. There are both positive and negative acks .   For negative ack you get back the full message . so we can resend the message again . But if you want sync producer only not async then one way to increase performance is to use a pool of sync producer connections to kafka and use them for writing to kafka. that way since each is not impacted by other u can get a slight improvement in performance if the topics being wrriten to are in different brokers  . But this is up to a extent. 

But if  u want performance then the key is to use async producer .

**Comment by sukkiCat** [comment]
> @Maqiushi , we basically switched to async producer by default for performance. For guaranteed delivery since the async producer returns acks we read acks. There are both positive and negative acks . For negative ack you get back the full message . so we can resend the message again . But if you want sync producer only not async then one way to increase performance is to use a pool of sync producer connections to kafka and use them for writing to kafka. that way since each is not impacted by other u can get a slight improvement in performance if the topics being wrriten to are in different brokers . But this is up to a extent.
> 
> But if u want performance then the key is to use async producer .

Hi chandradeepak,
I'm currently facing the same issue as you mention. I'm working on a recommendation engine api and every request must be write into kafka for etl processing. 
In order to improve api qps performance, i must find some way to improve the performance of kafka producer. Can you give me some advice， such as do I need create a connection pool to execute producing action or create a new NewSyncProducer at every request?

appreciate any feedback!
