### ISSUE TITLE
how to fetch consumer offset through sarama

### ISSUE THREAD

**Issue by simon-xia** [Shopify/sarama#738]
I know that with `OffsetManage` we can store/retrieve offsets on the kafka brokers, but how can I decide which broker to be connected?  

follow the doc: 
[https://cwiki.apache.org/confluence/display/KAFKA/Committing+and+fetching+consumer+offsets+in+Kafka
](https://cwiki.apache.org/confluence/display/KAFKA/Committing+and+fetching+consumer+offsets+in+Kafka)
It is how to achieve step 1 (to discover which broker keep the metadata of consumer) with sarama

**Comment by eapache** [comment]
You can use the `Coordinator` method on the `Client` if you want, but generally you shouldn't have to: the `OffsetManager` will connect to the appropriate broker automatically.
