### ISSUE TITLE
Is there a API for create a topic?

### ISSUE THREAD

**Issue by hjianhao** [Shopify/sarama#740]
I search the doc, can't find a function to create a topic.

**Comment by eapache** [comment]
No. Kafka does not let you do this directly via API.

**Comment by wvanbergen** [comment]
Topics are created using the Kafka CLI, which orchestrates it using Zookeeper. [My Ruby library](https://github.com/wvanbergen/kazoo) implements this, but AFAIK there is no go library that does at the moment.
