### ISSUE TITLE
Possible race condition with golang 1.7

### ISSUE THREAD

**Issue by bestbug456** [Shopify/sarama#742]
##### Versions

Sarama Version: Version 1.10.1 (2016-08-30)
Kafka Version: 0.10.0.0
Go Version: 1.7

##### Problem Description

Hello,

Today I've update the sarama lib to the latest version (1.10.1) and Golang to 1.7 and when I try to run my test I've got the following error: 
```
panic: Fail in goroutine after TestDispatcher has completed

goroutine 22 [running]:
panic(0x3d9980, 0xc420069d20)
       	/opt/local/lib/go/src/runtime/panic.go:500 +0x1ae
testing.(*common).Fail(0xc42008acc0)
       	/opt/local/lib/go/src/testing/testing.go:412 +0x182
testing.(*common).Errorf(0xc42008acc0, 0x458e37, 0x36, 0xc420069cd0, 0x1, 0x1)
       	/opt/local/lib/go/src/testing/testing.go:484 +0x95
testing.(*T).Errorf(0xc42008acc0, 0x458e37, 0x36, 0xc420069cd0, 0x1, 0x1)
       	<autogenerated>:10 +0x87
github.com/Shopify/sarama/mocks.(*SyncProducer).Close(0xc420066a00, 0x0, 0x0)
       	/path/togithub.com/Shopify/sarama/mocks/sync_producer.go:106 +0x1e9
xtn/messaging.(*worker).start.func1(0xc4200964b0)
```

Since I use sarama in a concurrent envairoment the first thing I did was to run `go test -race` and with this settings the `race` tool return the following info:

```
==================
WARNING: DATA RACE
Read at 0x00c42008ad04 by goroutine 9:
  testing.(*common).Fail()
      /opt/local/lib/go/src/testing/testing.go:411 +0x9f
  testing.(*common).Errorf()
      /opt/local/lib/go/src/testing/testing.go:484 +0x94
  testing.(*T).Errorf()
      <autogenerated>:10 +0x86
  github.com/Shopify/sarama/mocks.(*SyncProducer).Close()
       /path/to/Shopify/sarama/mocks/sync_producer.go:106 +0x1e8
  xtn/messaging.(*worker).start.func1()
      /path/to/messaging/worker.go:115 +0x6ef
[...]
==================
```

the line of code the `race` reference in worker do this task:

```
case <-w.quit:
				// releasing and stopping the worker
				if err := w.producer.Close(); err != nil {
					w.errorChannel <- err
				}
				return
			}
```

After some investigation seem the mock property `t` is no longer a valid pointer to a struct `testing.T`, even if I change the condition in `sync_producer` from:
```
if len(sp.expectations) > 0 {
		sp.t.Errorf("Expected to exhaust all expectations, but %d are left.", len(sp.expectations))
	}
```

To:
```
if len(sp.expectations) > 0 && sp.t != nil {
		sp.t.Errorf("Expected to exhaust all expectations, but %d are left.", len(sp.expectations))
	}
```

the panic remain. What I've done is to change the line of code inside the if as follow:
```
	if len(sp.expectations) > 0 {
		return fmt.Errorf("Expected to exhaust all expectations, but %d are left.", len(sp.expectations))
	}
```

Since I'm not sure if the error was my mistake or a bug with the new version of golang my first question is: "For what I report do you see anything wrong?" and if the answear is no my second question is: "Can I push my fix to sarama lib?"

Thanks for the support

**Comment by eapache** [comment]
I can't be sure without seeing more of your code, but I *think*, based on what you've said, that there is a bug in your tests. You must not return from your test method until after the (mock) producer has been closed, but it looks like you are doing that asynchronously.

**Comment by bestbug456** [comment]
I've defer the producer close but even if I explicit with a mutex the closing of the producer the result is the same. I didn't change the test and before today (using golang 1.6) work just fine, after the update of golang to 1.7 this test stop working, and this is why I create this issue. I close the producer asynchronously because I've a pool of worker which have to communicate with the kafka cluster so each worker has it's mock producer. If you let me know which part of code can help with the issue I'll be happy to share with you but, for what I see today, I don't think the problem can be in the test. Let me know and thanks for the support!

**Comment by eapache** [comment]
> I've defer the producer close but even if I explicit with a mutex the closing of the producer the result is the same.

Hmm, that's odd. The `Close` method on the mocks doesn't do anything asynchronous or fancy, so if it's complaining then it *must* be the caller that is the problem?

> I didn't change the test and before today (using golang 1.6) work just fine, after the update of golang to 1.7 this test stop working

It is possible that the problem existed before, but golang 1.7 is stricter here, and is scheduling goroutines differently which is exposing this bug.

If you run `go test -race` on golang 1.6 do you still see the issue? If you upgrade Sarama to 1.10.1 but leave golang at 1.6 do you still see the issue?

> I close the producer asynchronously because I've a pool of worker which have to communicate with the kafka cluster so each worker has it's mock producer.

That is fine normally, but you do have to ensure that all producers are completely closed before the test finishes.

**Comment by bestbug456** [comment]
> If you run go test -race on golang 1.6 do you still see the issue? If you upgrade Sarama to 1.10.1 but leave golang at 1.6 do you still see the issue?

with golang 1.6 no race condition detected using `-race` and the error don't appear with sarama 1.10.1

> That is fine normally, but you do have to ensure that all producers are completely closed before the test finishes.

And this is why I use defer on the worker close in order to be sure before the test exit the worker call the close on the producer. At the end of the test before return the producer will be close but the error persist. 

> Hmm, that's odd. The Close method on the mocks doesn't do anything asynchronous or fancy, so if it's complaining then it must be the caller that is the problem?

The `go test` talk quite clear: ` Fail in goroutine after TestDispatcher **has completed**` seem the go routine exit after the test finish even if I put them in a mutex block, I try to search some information about how golang change the goroutine managment, but I didn't find any reason how and why this test should now fail (a part the change of the garbage collector work in 1.7). Do you have any link I should check? Thanks

**Comment by bestbug456** [comment]
Good Morning,

Today I change part of the test initializing the mock producer in the test function and defering the close in the test, but the result was the same: panic after the test has complete, even if the close on the producer was explicit and the async worker was not invoke the quit call. Any tips?

**Comment by bestbug456** [comment]
After more investigation I decided to change how the test works and I fixed it, but imho what sarama is doing in the mock lib is quite dangerous since it uses a testing pointer passed by the developer without any security check on it, made suffer [the compiler](https://xkcd.com/371/). Thanks a lot for the support
