### ISSUE TITLE
bufferSize & large message consumption

### ISSUE THREAD

**Issue by linusviking** [Shopify/sarama#743]
##### Versions

Sarama Version: latest
Kafka Version: 0.10.0
Go Version: 1.7

##### Problem Description

The default bufferSize set in kafka-console-consumer.go is 256. If I increase it to consume large blobs from Kafka topics, does it mean that for smaller messages, the consumer will wait until the buffered channel gets full? What is the best way to dynamically accommodate varying message sizes?

**Comment by wvanbergen** [comment]
Buffersize of 256 is the number of messages in the internal go channels of the library, irregardless of message size. This cannot be changed after  the channels have been initialized.
