### ISSUE TITLE
unexpected result when call `Partitions` of client

### ISSUE THREAD

**Issue by WanliTian** [Shopify/sarama#749]
##### Versions

Sarama Version: master
Kafka Version: 0.8.2.2
Go Version: go1.6.2 linux/amd64
##### Configuration

What configuration values are you using for Sarama and Kafka?
##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.
##### Problem Description

`Partitions(topic string) ([]int32, error)
an empty partition slice and  nil error is returned

reason:
some partitions of kafka is leaderless

**Comment by eapache** [comment]
Sorry for the delay. Which SHA is `master` that you can reproduce this on? Can you provide logs as mentioned in the "Logs" section of the issue template?

**Comment by eapache** [comment]
Closing as stale, please reopen if more information is available.
