### ISSUE TITLE
asyncproducer:panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by WanliTian** [Shopify/sarama#751]
version: master

normal:
`
client, err := sarama.NewAsyncProducer(brokerList, nil)
`

panic:
```
conf := sarama.NewConfig()

conf.Producer.Partitioner=sarama.NewHashPartitioner

client, err := sarama.NewAsyncProducer(brokerList, conf)
```

**Comment by eapache** [comment]
Are you sure you're using the *latest* master? This seems awfully similar to a bug that was fixed a couple of months ago. Which SHA specifically are you using?

If you are using af0513c4d97979eb876d201391fac6475ec08268 (latest master) or bd61cae2be85fa6ff40eb23dcdd24567967ac2ae (latest stable) then please provide more information. A stack trace and the output of the logger would both be helpful.

It might also be helpful to know what you are using as the `Encoder` implementation for your message keys and values.

**Comment by eapache** [comment]
I find this particularly suspicious because the *default* value of `conf.Producer.Partitioner` is already `NewHashPartitioner` so manually setting that value should make no difference at all.

**Comment by WanliTian** [comment]
i used [15fe77a](https://github.com/Shopify/sarama/commit/15fe77a66802a6921e405f699a6dee2c135b68bf)
and i have updated it, it works now.
