### ISSUE TITLE
Kafka Custer/Topic availability to Sarama user

### ISSUE THREAD

**Issue by safiqueahemad** [Shopify/sarama#752]
##### Versions

Sarama Version:
**Kafka Version: 0.9
Go Version: 1.5**

##### Configuration

What configuration values are you using for Sarama and Kafka? 
**Nothing specific**

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

There is an application built on top of Sarama. So application receive messages from some other entity and process the message and finally write to Kafka.
We are trying to handle a situation when Kafka cluster or Topic goes down completely e.g all send start failing. 
Is there any way application to know if topic or Kafka cluster is completely down. Similarly, how application will come to know when it again become available? 

Here, we are trying to stop other interface from where application receiving messages.

- Kindly, suggest something.

Regards,
Safique Ahemad

**Comment by eapache** [comment]
Assuming you are using the `AsyncProducer`: errors from producing will come back on the `Errors` channel defined in the documentation. The producer retries messages on failure before giving up (this is configurable), so if you receive any errors at all you can usually assume that something has gone wrong with at least the one broker.

The kafka protocol does not provide an application-level method of determining when a cluster is reachable (that depends on lower-level networking behaviour) nor when a topic is functional (that is the wrong level of granularity). What it does (sort of) provide is a way of checking on individual partitions. With a `Client` you can `RefreshMetadata` for the relevant topic to ensure a fresh response, then ask for the `Leader` of a given partition. If it returns no error, than the partition should be functioning normally.
