### ISSUE TITLE
Handle ErrOffsetOutOfRange errors more gracefully

### ISSUE THREAD

**Issue by dim** [Shopify/sarama#762]
##### Versions

Sarama Version: 1.10.1
Kafka Version: 0.10.0.1
Go Version: 1.7.1
##### Problem Description

I have a particular issue handling auto-expiring topics with a relatively short TTLs  in [sarama-cluster](https://github.com/bsm/sarama-cluster) and need help/advice, as this will affect sarama in equal measure.

When consuming a partition with a normal `PartitionConsumer` while using an `OffsetManager`, Kafka may expire some of the older messages which may cause an `ErrOffsetOutOfRange` error on the next fetch request. The problem is that this error is (at best, if enabled) only emitted on the `Errors()` channel and it will cause the consumer to "lock up", i.e. no new messages will arrive on the `Messages()` channel and the consumer will simply remain idle until it is restarted. 

I am not entirely sure how to best deal with such scenario, especially if `config.Consumer.Return.Errors` is disabled. In that case I would image the consumer should simply log the error and resume from `config.Consumer.Offsets.Initial`. Any ideas?

Thanks,
dim

**Comment by eapache** [comment]
I was never quite sure how to handle these cases either which is why I just left it up to the client :)

The problem is that there are several possible reasons for an `ErrOffsetOutOfRange` and the ideal behaviour in each case is different.

- When it occurs because a very short TTL has expired the message, you ideally want to resume from `OffsetOldest` regardless of original starting point.
- When it occurs because a node failed (the consumer can end up ahead of the high-water-mark in certain relaxed-consistency configurations), you ideally want to resume from `OffsetNewest` regardless of original starting point.

We can potentially make that behaviour configurable, but I think it's probably still best if the user makes an explicit decision how they want to handle this case.

I'm curious how upstream handles this error?

**Comment by eapache** [comment]
Just checked the kafka docs, their new consumer has an `auto.offset.reset` key:

> What to do when there is no initial offset in Kafka or if the current offset does not exist any more on the server (e.g. because that data has been deleted):
> - earliest: automatically reset the offset to the earliest offset
> - latest: automatically reset the offset to the latest offset
> - none: throw exception to the consumer if no previous offset is found for the consumer's group
> - anything else: throw exception to the consumer.

Interestingly it defaults to `latest`. @edenhill I'd be curious to hear the rationale behind that decision.

**Comment by edenhill** [comment]
@eapache I think the reason for defaulting to latest is that it's likely less of a problem to miss messages (`..=latest`) than to process them twice (`..=earliest`) in the case where a stored offset could not be retrieved (or was unusable).

But it really is up to the application to define its policy for this case (earliest, latest or error).

**Comment by dim** [comment]
@eapache I - personally - think this should default to the setting in https://github.com/Shopify/sarama/blob/3f8bfbafaba08d203c680fe35f2eb9a46b49a509/config.go#L210

**Comment by eapache** [comment]
Makes sense to me, though we'll need to add an `OffsetError` option or something for users who want to preserve the current behaviour.

**Comment by dim** [comment]
@eapache this is something that's being reported as an issue time and time again, most recently in https://github.com/bsm/sarama-cluster/issues/152. Just as a reminder: if an `ErrOffsetOutOfRange` error is thrown it's only available on the `consumer.Errors()` channel which is off by default and causes the consumer to get stuck indefinitely (until restarted or rebalance is forced). 

Any chance you could look into this?

**Comment by eapache** [comment]
"stuck indefinitely" is a bit misleading I think; the consumer shuts down and e.g. the `Messages()` channel will be closed so the client should notice and be able to restart even if the `Errors()` channel is disabled.

**Comment by dim** [comment]
Unfortunately, I have not witnessed it myself but that's not what happens it seems. The consumer doesn't shut down, it keeps logging messages that would normally go to `Errors()` while `Messages()` is never closed. 

I tried to implement a work-around on my side and restart the consumer when this error occurs, but it requires users to always set `Config.Consumer.Return.Errors` to `true` then initialising the `Client`, otherwise I can never access this information.

**Comment by eapache** [comment]
> I have not witnessed it myself but that's not what happens it seems. The consumer doesn't shut down, it keeps logging messages that would normally go to Errors() while Messages() is never closed.

That isn't right. Perhaps there is a bug, or else this is a different case than we are assuming.
- The `ErrOffsetOutOfRange` handler closes the trigger and deletes the subscription https://github.com/Shopify/sarama/blob/3fee590c5568849516741670af9331a193bbe2a3/consumer.go#L684-L690
- Closing `trigger` causes the `dispatcher` loop to exit and close `feeder` https://github.com/Shopify/sarama/blob/3fee590c5568849516741670af9331a193bbe2a3/consumer.go#L333
- Closing `feeder` causes the `responseFeeder` loop to exit and close `messages` https://github.com/Shopify/sarama/blob/3fee590c5568849516741670af9331a193bbe2a3/consumer.go#L441

It's the exact same shutdown cycle that occurs in every other case (e.g. calling `AsyncClose`) so I would be surprised if there is some unexpected way for it to stick that we haven't found yet.

**Comment by dim** [comment]
@eapache thanks for the clarification, I have reviewed the code and it looks good to me too. I think this issue can marked as resolved. Thanks again
