### ISSUE TITLE
any plant for supporting message metadata?

### ISSUE THREAD

**Issue by WanliTian** [Shopify/sarama#763]
any plant for supporting message metadata?

**Comment by wvanbergen** [comment]
What exactly do you mean by "message metadata"?

Regardless, the answer is no, because nobody is actively working on new features at the moment. However, we gladly accept pull requests!

**Comment by WanliTian** [comment]
// ProducerMessage is the collection of elements passed to the Producer in order to send a message.
type ProducerMessage struct {
	Topic string // The Kafka topic for this message.
	// The partitioning key for this message. Pre-existing Encoders include
	// StringEncoder and ByteEncoder.
	Key Encoder
	// The actual message to store in Kafka. Pre-existing Encoders include
	// StringEncoder and ByteEncoder.
	Value Encoder

	// This field is used to hold arbitrary data you wish to include so it
	// will be available when receiving on the Successes and Errors channels.
	// Sarama completely ignores this field and is only to be used for
	// pass-through data.
	**Metadata interface{}**  /

	// Below this point are filled in by the producer as the message is processed

	// Offset is the offset of the message stored on the broker. This is only
	// guaranteed to be defined if the message was successfully delivered and
	// RequiredAcks is not NoResponse.
	Offset int64
	// Partition is the partition that the message was sent to. This is only
	// guaranteed to be defined if the message was successfully delivered.
	Partition int32
	// Timestamp is the timestamp assigned to the message by the broker. This
	// is only guaranteed to be defined if the message was successfully
	// delivered, RequiredAcks is not NoResponse, and the Kafka broker is at
	// least version 0.10.0.
	Timestamp time.Time

	retries int
	flags   flagSet
}

**Comment by WanliTian** [comment]
I mean `ProducerMessage.Metadata`

**Comment by WanliTian** [comment]
I want to store some information to `ProducerMessage.Metadata` and access this field within `ConsumerMessage`

**Comment by wvanbergen** [comment]
That's not what the Metadata field is used for. It's to attach metadata to a message for the async producer, which you will get back when you get the ack (or error). This metadata never gets sent to the Kafka broker, so it's for the producer only.

If you need to attach more data to your events, just change the schema of the events to include your metadata
