### ISSUE TITLE
Is Sarama  supported kafka stream?

### ISSUE THREAD

**Issue by weiboyiyou** [Shopify/sarama#768]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.10.1
Kafka Version: 0.10.0
Go Version: 1.6 

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
Is Sarama  supported kafka stream?

**Comment by eapache** [comment]
> Kafka Streams is a Java library for building distributed stream processing apps using Apache Kafka

Kafka streams is a separate java library for stream processing backed by kafka. It is not a feature of Kafka proper and not something that Sarama intends to support.
