### ISSUE TITLE
Partitioners: NewRandomPartitioner vs NewRoundRobinPartitioner

### ISSUE THREAD

**Issue by djiang** [Shopify/sarama#770]
##### Versions

regularly.*
Sarama Version: af0513c4d97979eb876d201391fac6475ec08268
Kafka Version: 0.10.0.0
Go Version: 1.7
###### Sarama

``` go
config := sarama.NewConfig()
config.Producer.RequiredAcks = sarama.WaitForAll
config.Producer.Retry.Max = 10
config.Producer.Partitioner = sarama.NewRandomPartitioner

producer, err := sarama.NewAsyncProducer(addrs, config)
```
###### Kafka

I have a topic with 6 partitions, with a replication factor of 3, across 3 instances. It looks like Kafka configures this so partition leadership is evenly distributed amongst the instances:

```
bin/kafka-topics.sh --describe --zookeeper XX.X.X.XX:2181 --topic segment-staging
Topic:segment-staging   PartitionCount:6    ReplicationFactor:3 Configs:
    Topic: segment-staging  Partition: 0    Leader: 0   Replicas: 0,1,2 Isr: 0,1,2
    Topic: segment-staging  Partition: 1    Leader: 1   Replicas: 1,2,0 Isr: 1,2,0
    Topic: segment-staging  Partition: 2    Leader: 2   Replicas: 2,0,1 Isr: 2,0,1
    Topic: segment-staging  Partition: 3    Leader: 0   Replicas: 0,2,1 Isr: 0,2,1
    Topic: segment-staging  Partition: 4    Leader: 1   Replicas: 1,0,2 Isr: 1,0,2
    Topic: segment-staging  Partition: 5    Leader: 2   Replicas: 2,1,0 Isr: 2,1,0
```
##### Problem Description

I currently have 3 Kafka instances running, and 2 producer instances with the configuration above. I thought that setting the `Partitioner` to `NewRandomPartitioner` would allow my producers to send messages to all 3 of my Kafka instances, but it looks like it's only sending to 2 of them. When I increase the # producers instances to 3, it successfully sends it to all 3.

Does `NewRandomPartitioner` decide which partition to send to when it's initialized and stay with that one? Or does it randomly pick a partition each time it sends a message?

If I wanted to only run 2 producers with 3 Kafka instances, and have messages evenly distribute amongst the partitions, should I use `NewRoundRobinPartitioner` instead?

Thanks in advance 😃:smiley: Also, is this the best place to post questions like this?

**Comment by eapache** [comment]
> Does NewRandomPartitioner decide which partition to send to when it's initialized and stay with that one? Or does it randomly pick a partition each time it sends a message?

It randomly picks one each time it sends a message.

> I currently have 3 Kafka instances running, and 2 producer instances with the configuration above. I thought that setting the Partitioner to NewRandomPartitioner would allow my producers to send messages to all 3 of my Kafka instances, but it looks like it's only sending to 2 of them.

It should be sending to all 6 partitions and therefore to all 3 brokers. Please check the Sarama logs, it's possible one of your brokers is not reachable on the network for some reason, or perhaps leadership for some partitions is flapping rapidly?

**Comment by eapache** [comment]
Closing as stale, please reopen if more information is available.

**Comment by Abdulhamid200130** [comment]
i have  problem with strategy 
s.KafkaConfig.Producer.Partitioner = sarama.NewRoundRobinPartitioner
when i use this strategy it only produces to 0 partition 
when i changed it to random it is using other partitions too
