### ISSUE TITLE
Is the SyncProducer concurrency-safe?

### ISSUE THREAD

**Issue by F21** [Shopify/sarama#773]
I am not sure where's the best place to ask this, so my apologies if this is the wrong place.

Is the SyncProducer concurrency-safe? In order words, can I create 1 SyncProducer and use it across multiple goroutines?

**Comment by wvanbergen** [comment]
Yes it is, and is encuraged. In the background it uses the async producer, so it can still batch messages from all goroutines together to get higher throughput.
