### ISSUE TITLE
Sarama client consumes very high CPU compared to Java client while producing messages in a tight loop

### ISSUE THREAD

**Issue by ssahukar** [Shopify/sarama#777]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.10.1 (the issue is observed in older versions as well)
Kafka Version: 0.9.0.1
Go Version: 1.6.3

##### Configuration
Sarama:
    saramaConfig.Producer.Flush.Frequency = 100 * time.Millisecond
    saramaConfig.Producer.Flush.Bytes = 10485760
    saramaConfig.Producer.RequiredAcks = sarama.WaitForLocal

Kafka:
    num.network.threads=8
    num.io.threads=8
    socket.send.buffer.bytes=1048576
    socket.receive.buffer.bytes=1048576
    socket.request.max.bytes=104857600
    queued.max.requests=500
    fetch.purgatory.purge.interval.requests=100
    producer.purgatory.purge.interval.requests=100
    num.replica.fetchers=8
    replica.fetch.max.bytes=1048576
    replica.fetch.wait.max.ms=500
    replica.high.watermark.checkpoint.interval.ms=5000
    replica.socket.timeout.ms=3000
    replica.socket.receive.buffer.bytes=1048576
    replica.lag.time.max.ms=10000
    controller.socket.timeout.ms=3000
    controller.message.queue.size=10
    min.insync.replicas=2
    message.max.bytes=1000000
    auto.create.topics.enable=true
    log.index.interval.bytes=4096
    log.index.size.max.bytes=10485760
    log.flush.interval.ms=10000
    log.flush.interval.messages=100000
    log.flush.scheduler.interval.ms=5000
    log.retention.hours=2
    log.retention.bytes=1073741824
    log.segment.bytes=1073741824 
    log.retention.check.interval.ms=300000
    log.roll.hours=24
    log.cleaner.enable=true
    zookeeper.sync.time.ms=2000
    zookeeper.connection.timeout.ms=6000
    zookeeper.session.timeout.ms=6000

##### Problem Description
I am comparing the performance of Sarama client Vs Java client for the Async producer message rate. My tests are done on 4 high end servers with 32 cores and 256G RAM and 4G bonded network.

3 and Kafka and Zookeeper instances are running on 3 servers and the clients are run from 4th server.

The test code creates an Async producer and starts sending messages in a tight loop. Another thread in the test application prints the rate at which the messages are sent. So its a simple test to see how fast we can send messages to Kafka.

The test scenarios include various number of partitions, and number of send threads in the test application. 

Sarama seems to provide a much better send rate compared to Java client and it uses way less memory. But the CPU utilization of Sarama client is way too higher than the Java client. So I wanted to know if it due to some configuration issue or if its a bug. Below is the comparison of Java client Vs Go client under various scenarios:

![image](https://cloud.githubusercontent.com/assets/11220843/19942112/d62581dc-a0ef-11e6-87a7-0cebf5a34871.png)

**Comment by ssahukar** [comment]
The producer settings are as below:
Java client has batch.size=5000 and flush.frequency=1 second. 

The numbers shown in the picture for Go client are when we set same setting for Sarama as well as when the settings are: saramaConfig.Producer.Flush.Frequency = 100 * time.Millisecond and saramaConfig.Producer.Flush.Bytes = 10485760.

The best setting indicates the latter case with Flush.Bytes=10485760

**Comment by eapache** [comment]
> So I wanted to know if it due to some configuration issue or if its a bug

I have no idea. It wouldn't surprise me if there is room for optimization somewhere, but it also wouldn't surprise me if this is just a function of Go's garbage-collector or something.

If you wanted to profile, Go has some very good tooling around that (https://blog.golang.org/profiling-go-programs). If you find something in Sarama that is consuming more CPU then it should I will definitely try to fix it, but without more specific information there isn't much I can do.
