### ISSUE TITLE
Can we create a topic with one partition using sarama api

### ISSUE THREAD

**Issue by chandradeepak** [Shopify/sarama#778]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:1.1.0.1
Kafka Version:0.10.0.1
Go Version:1.6

##### Configuration
Default no of paritions for kafka is 5.
What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
Assuming default partition for kafka is 5 is there a way we can create a topic with one partition using sarama?

**Comment by eapache** [comment]
No, Sarama does not perform cluster management tasks. You might try https://github.com/wvanbergen/kazoo-go instead.

**Comment by chandradeepak** [comment]
But the https://github.com/wvanbergen/kazoo-go is very specific to zoo keeper based kafka. I am using kafka  0.10.0.1 . 

So the kazoo-go won't help us right ?

**Comment by wvanbergen** [comment]
Every Kafka-version is Zookeeper based. AFAIK topic management is still not part of the Kafka protocol, and works through Zookeeper. It should be relatively easy to update kazoo-go to newer Kafka versions if there are any incompatibilities

**Comment by chandradeepak** [comment]
thanks for the update . it works .

**Comment by chandradeepak** [comment]
one more question. the current https://github.com/wvanbergen/kazoo-go  doesn't support topic creation by default . There is a pull request waiting for merging to master which had implementation of create topics and delete topics easily. are there any plans of merging it to master ?

https://github.com/wvanbergen/kazoo-go/pull/25

**Comment by wvanbergen** [comment]
My time is really limited. Best thing you can help is to start using it,
and leave feedback on the PR based on real usage.
