### ISSUE TITLE
How to use low-level Produce API with compression?

### ISSUE THREAD

**Issue by dmac** [Shopify/sarama#788]
##### Versions

Sarama Version: 1cf30ac936a588d74b36e107b9c572a23603bb52
Kafka Version: 0.8.2
Go Version: 1.7

##### Problem Description

> For lower-level needs, the Broker and Request/Response objects permit precise control over each connection and message sent on the wire;

Based on this line of the docs, I was hoping to be able to produce messages to Kafka using only the `Client`, `Broker`, `MessageSet`, and `Message` types, and not the higher-level producers. I have this working well for uncompressed payloads.

However, if I want to enable compression (say, gzip), I believe I would first need to get the raw bytes of an encoded `MessageSet`, and then wrap that in a `Message` with the appropriate codec. As far as I can tell, the necessary functions that would allow me to do this are not exported. [Here](https://github.com/Shopify/sarama/blob/124e7c647e529d5300c8716dc9ad5cbf6c08b396/produce_set.go#L88-L107) is where this happens in the `AsyncProducer`. Since I don't have access to the raw encoded bytes of a `MessageSet`, I don't see a way to use the low-level API with compression.

Is there a way to do this that I'm not seeing? Or is it simply not possible to use the low-level API with compression at this time?

**Comment by eapache** [comment]
It was an oversight that this is not currently possible. There was some discussion on potential solutions at https://github.com/Shopify/sarama/pull/727 that never went anywhere, but I'm still open to a PR to address this.

**Comment by dmac** [comment]
Ok, thanks for the fast response and clarification.
