### ISSUE TITLE
AddTopicPartition doesn't work as expected

### ISSUE THREAD

**Issue by yangpeng-chn** [Shopify/sarama#791]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

Sarama Version: "Comment": "v1.10.1-21-gfd49817", "Rev": "fd498173ae2bfc49a2b4eb19353241317785e7e6"
Kafka Version: kafka_2.11-0.10.0.0
Go Version: go1.7.1 darwin/amd64

##### Configuration

default

##### Problem Description

```
package main

import (
	"fmt"
	"github.com/Shopify/sarama"
	"log"
	"os"
	"sync"
)

var (
	wg         sync.WaitGroup
	logger     = log.New(os.Stderr, "[sarama]", log.LstdFlags)
	brokerAddr = "localhost:9092"
	topic      = "my_topic"
)

func addTopic() {
	broker := sarama.NewBroker(brokerAddr)
	err := broker.Open(nil)
	if err != nil {
		panic(err)
	}
	defer broker.Close()

	config := sarama.NewConfig()
	config.Metadata.Retry.Max = 3
	request := sarama.MetadataRequest{Topics: []string{topic}}
	metadataPartial, err := broker.GetMetadata(&request)

	replicas := []int32{0}
	isr := []int32{0}

	metadataResponse := &sarama.MetadataResponse{}
	metadataResponse.AddBroker(broker.Addr(), broker.ID())

	metadataPartial.AddTopic(topic, sarama.ErrNoError)
	metadataPartial.AddTopicPartition(topic, 0, broker.ID(), replicas, isr, sarama.ErrNoError)
	metadataPartial.AddTopicPartition(topic, 1, broker.ID(), replicas, isr, sarama.ErrNoError)
	client, err := sarama.NewClient([]string{brokerAddr}, config)
	if err != nil {
		panic(err)
	}
	defer client.Close()

	if err := client.RefreshMetadata(topic); err != nil {
		panic(err)
	}
	partitions, _ := client.Partitions(topic)
	fmt.Printf("Partitions: %v\n", partitions)
}

func main() {
	addTopic()
}
```

Expected Output:
⮀ go run test.go
Partitions: [0 1]

Actual Output:
⮀ go run test.go
Partitions: [0]
⮀ bin/kafka-topics.sh --describe --zookeeper localhost:2181 --topic my_topic
Topic:my_topic  PartitionCount:1        ReplicationFactor:1     Configs:
Topic: my_topic Partition: 0    Leader: 0       Replicas: 0     Isr: 0

Even though I have tried run 'go run test.go' several times, the output above didn't change.
Can anybody tell me what I missed?

**Comment by yangpeng-chn** [comment]
I have tried to make the all code highlighted, but couldn't make it...

**Comment by eapache** [comment]
You need three consecutive backticks (` ``` `) to highlight multi-line blocks of code.

Kafka does not support creating and manipulating topics through its normal API, so Sarama cannot perform these kind of changes. You might want to look at https://github.com/wvanbergen/kazoo-go instead.
