### ISSUE TITLE
Documentation for RequiredAcks.WaitForAll is wrong

### ISSUE THREAD

**Issue by CAFxX** [Shopify/sarama#793]
https://godoc.org/github.com/Shopify/sarama#RequiredAcks

```
    // WaitForAll waits for all replicas to commit before responding.
    WaitForAll RequiredAcks = -1
```

This is wrong. `WaitForAll` waits for `min.insync.replicas` to commit the message, as configured on the Kafka broker we're producing to. I would argue that the `WaitForAll` name itself is misleading and should likely be deprecated/changed.

**Comment by giner** [comment]
Different parts of Kafka documentation say conflicting things though:

min.insync.replicas
> When a producer sets **acks** to "all" (or "-1"), min.insync.replicas specifies the **minimum number of replicas that must acknowledge** a write for the write to be considered successful. If this minimum cannot be met, then the producer will raise an exception (either NotEnoughReplicas or NotEnoughReplicasAfterAppend).
> 
> When used together, min.insync.replicas and acks allow you to enforce greater durability guarantees. A typical scenario would be to create a topic with a replication factor of 3, set min.insync.replicas to 2, and produce with acks of "all". This will ensure that the producer raises an exception if a majority of replicas do not receive a write.

acks
> The number of acknowledgments the producer requires the leader to have received before considering a request complete. This controls the durability of records that are sent. The following settings are allowed:
> 
> acks=0
> If set to zero then the producer will not wait for any acknowledgment from the server at all. The record will be immediately added to the socket buffer and considered sent. No guarantee can be made that the server has received the record in this case, and the retries configuration will not take effect (as the client won't generally know of any failures). The offset given back for each record will always be set to -1.
> 
> acks=1
> This will mean the leader will write the record to its local log but will respond without awaiting full acknowledgement from all followers. In this case should the leader fail immediately after acknowledging the record but before the followers have replicated it then the record will be lost.
> 
> acks=all
> This means the leader will **wait for the full set of in-sync replicas to acknowledge the record**. This guarantees that the record will not be lost as long as at least one in-sync replica remains alive. This is the strongest available guarantee. This is equivalent to the acks=-1 setting.

**Comment by eapache** [comment]
Those two documentation fragments don't actually conflict though. When you specify -1 (or "all") Kafka will wait for the full set of in-sync replicas before replying. If there are fewer in-sync replicas than `min.insync.replicas` it will reply with an error, otherwise with a success.

I tend to agree that `WaitForAll` could probably be `WaitForAllInSync` or something, but changing the API at this point is more trouble than its worth. I'll definitely update the documentation though.

**Comment by giner** [comment]
> Those two documentation fragments don't actually conflict though

Let's say min.insync.replicas is set to 1 and number of replicas is 3 (all are in sync).
"min.insync.replicas specifies the minimum number of replicas that must acknowledge a write for the write to be considered successful" means 1 in this case and "full set of in-sync replicas to acknowledge the record" means 3.

I would expect the latter to be the case however I'm not sure about the exact behavior.

**Comment by eapache** [comment]
In the case you describe, it will try and wait for all 3 replicas to acknowledge the record. However, if certain replicas do *not* acknowledge the record they will eventually fall out of the in-sync set. As long as at least one replica remains in-sync, the request will still eventually succeed.
