### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by moxar** [Shopify/sarama#797]
Well, this is more a request than an issue.

I am currently trying to set-up a dev environment on docker, and I require a kafka 0.9.0.1 and a zookeeper 3.4.5. I tried to use [this repo](https://github.com/wurstmeister/kafka-docker) but I got stuck (I rolled back to a previous commit to get the proper kafka version)

Since you provided a Vagrant support, would it be possible to provide also a docker-compose support on this package ?

Thanks

**Comment by eapache** [comment]
This was proposed and discussed in https://github.com/Shopify/sarama/pull/725 a few months back. Since we already have vagrant, I really don't want to provide/maintain both.
