### ISSUE TITLE
Split ErrOffsetOutOfRange into 2 kinds of errors

### ISSUE THREAD

**Issue by kklipsch** [Shopify/sarama#804]
In consumer.ConsumePartition if the offset requested is lower than the earliest or higher than the latest offsets in the partition metadata a ErrOffsetOutOfRange is returned.

Generally speaking though, those are really 2 different classes of error.  It is common to request something before the earliest in the face of log cleanup/compaction and most client applications should be aware and written to handle this case.

Requesting an offset that is higher than the latest offset largely means that you are probably requesting from the *wrong* topic/partition.

It would be a nice enhancement to return different errors for each case or to return the offsets being used to make determining factors in the error. 

Given the error returned is part of the api (and client code is probably explicitly written to check against the instance of that error) you'd need to either:
- create a new function that returns the split errors, leaving the old one for backwards compatibility.
- get rid of ErrOffsetOutOfRange entirely from the package and replace all of its usages with something else (including the new split errors).  This would be a breaking change but a relatively obvious to fix one.  Just changing what the function returns would be much more difficult to detect.

**Comment by eapache** [comment]
quasi-related: #762 

> It is common to request something before the earliest in the face of log cleanup/compaction and most client applications should be aware and written to handle this case.

Yes

> Requesting an offset that is higher than the latest offset largely means that you are probably requesting from the wrong topic/partition.

Not necessarily. Depending on your broker setup this can happen fairly easily in fail-over scenarios.

**Comment by kklipsch** [comment]
You mean some sort of event where you've failed over to a different cluster where the topic is replicated?

**Comment by eapache** [comment]
It doesn't even have to be a different cluster. Just a normal cluster set up in high-availability (low-consistency) mode, when a single node fails the high watermark of the partition can move backwards.

**Comment by kklipsch** [comment]
Fair enough.  I still think you handle both of those cases differently.

**Comment by eapache** [comment]
Definitely agree we could be returning more useful error information here.

**Comment by tcrayford** [comment]
@eapache can

> when a single node fails the high watermark of the partition can move backwards.

happen even with `unclean.leader.election=false` and `min.insync.replicas=2`?

Kafka's docs say:

> A message is considered "committed" when all in sync replicas for that partition have applied it to their log. Only committed messages are ever given out to the consumer.

Which seems to indicate this shouldn't happen.

**Comment by eapache** [comment]
It depends on how many brokers you have, but I *think* so? Because unclean just means "really far behind", a broker can be a *little* bit behind and still considered clean (there is a config for this somewhere).

That is really a question better asked of the upstream kafka project though, it's not really specific to Sarama.
