### ISSUE TITLE
Include StringDecoder implementation

### ISSUE THREAD

**Issue by mcandre** [Shopify/sarama#806]
Please offer a StringDecoder so that the send & receive API are more similar.

**Comment by eapache** [comment]
To be honest, the `Encoder` interface and `StringEncoder` don't actually provide all that much benefit, so I'm planning to eventually remove them and have both send and receive use `[]byte` directly. This is a breaking API change however, so it is tracked at https://github.com/Shopify/sarama/wiki/Ideas-that-will-break-backwards-compatibility.
