### ISSUE TITLE
Vendor dependencies

### ISSUE THREAD

**Issue by mcandre** [Shopify/sarama#807]
Please vendor sarama's dependencies, so that users don't have to manually resolve missing deps.

Example:

```console
$ cd $GOROOT/src/github.com/pierrec/sarama
$ git submodule update --init --recursive
$ git submodule add git@github.com:pierrec/lz4.git vendor/github.com/pierrec/lz4
$ git add .gitmodules vendor
$ git commit -m 'vendor github.com/pierrec/lz4'
$ git push
```

**Comment by eapache** [comment]
Sarama is a library, not an application; different users will want to run it against different versions of its dependencies (within the bounds of what we support), so it does not make sense to vendor dependencies here.
