### ISSUE TITLE
Cannot specify JoinGroupRequest protocol priority

### ISSUE THREAD

**Issue by DanielMorsing** [Shopify/sarama#812]
##### Versions

Present on every version that supports JoinGroupRequest

##### Problem Description

The kafka protocol for JoinGroupRequest allows you to specify priority on group protocols for seamless rollout of new protocols while a consumer group is running. This is done by changing the ordering on the wire for the GroupProtocols. See [here](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-JoinGroupRequest) for more details

Sarama exposes this field as a [map](https://github.com/Shopify/sarama/blob/0fb560e5f7fbcaee2f75e3c34174320709f69944/join_group_request.go#L8), making it impossible to specify an ordering.

**Comment by eapache** [comment]
> Note that the join group request allows for multiple protocol/metadata pairs. This enables rolling upgrades without downtime. The coordinator chooses a single protocol which all members support.

This is what is in the wiki; I don't read that as implying that order is important. The coordinator should only choose a protocol once all of the group members support it, regardless of order?

**Comment by DanielMorsing** [comment]
Later in the wiki:
> Once all members have upgraded, the coordinator will choose whichever protocol is listed first in the GroupProtocols array.

If you're switching from `"protov1"` to `"protov2"`, you want to deploy your binaries such that they can handle both in the switchover, but once every consumer has been updated, you want to ensure that `"protov2"` is chosen. The protocol ordering allows for doing this.

**Comment by eapache** [comment]
Oh yes you're right I'm sorry I must have missed that the first read through.

Fixing this without breaking API compatibility will be a bit awkward but should be possible.
