### ISSUE TITLE
Partition consumer stops consuming

### ISSUE THREAD

**Issue by josselin-c** [Shopify/sarama#815]
##### Versions

Sarama Version: e03d23b5a4fa1a72c30eace0403d7c2c3b5de55e
Kafka Version: 0.9.2
Go Version: 1.7.3

##### Configuration
What configuration values are you using for Sarama and Kafka?
Sarama:
sarama.NewConfig()
Then:
config.Version = sarama.V0_9_0_0
config.Consumer.Offsets.Initial = sarama.OffsetOldest
config.Consumer.MaxProcessingTime = 6 * time.Second
config.Consumer.Fetch.Min = 1000
config.Consumer.Fetch.Default = 512000
config.Consumer.MaxWaitTime = 500 * time.Millisecond
config.Consumer.Return.Errors = true
config.ChannelBufferSize = 4

##### Logs
```
--
goroutine 1227882 [chan receive, 181 minutes]:
internal-git/jc/notifier/vendor/github.com/Shopify/sarama.(*partitionConsumer).dispatcher(0xc455984c80)
/go/src/internal-git/jc/notifier/vendor/github.com/Shopify/sarama/consumer.go:307 +0x5f
internal-git/jc/notifier/vendor/github.com/Shopify/sarama.(*partitionConsumer).(internal-git/jc/notifier/vendor/github.com/Shopify/sarama.dispatcher)-fm()
/go/src/internal-git/jc/notifier/vendor/github.com/Shopify/sarama/consumer.go:157 +0x2a
internal-git/jc/notifier/vendor/github.com/Shopify/sarama.withRecover(0xc4521e3ef0)
/go/src/internal-git/jc/notifier/vendor/github.com/Shopify/sarama/utils.go:46 +0x43
created by internal-git/jc/notifier/vendor/github.com/Shopify/sarama.(*consumer).ConsumePartition
/go/src/internal-git/jc/notifier/vendor/github.com/Shopify/sarama/consumer.go:157 +0x335
--
goroutine 1234026 [select, 181 minutes]:
internal-git/jc/notifier/vendor/github.com/Shopify/sarama.(*partitionOffsetManager).mainLoop(0xc44f511720)
/go/src/internal-git/jc/notifier/vendor/github.com/Shopify/sarama/offset_manager.go:219 +0x2e4
internal-git/jc/notifier/vendor/github.com/Shopify/sarama.(*partitionOffsetManager).(internal-git/jc/notifier/vendor/github.com/Shopify/sarama.mainLoop)-fm()
/go/src/internal-git/jc/notifier/vendor/github.com/Shopify/sarama/offset_manager.go:212 +0x2a
internal-git/jc/notifier/vendor/github.com/Shopify/sarama.withRecover(0xc447be5c20)
/go/src/internal-git/jc/notifier/vendor/github.com/Shopify/sarama/utils.go:46 +0x43
created by internal-git/jc/notifier/vendor/github.com/Shopify/sarama.(*offsetManager).newPartitionOffsetManager
/go/src/internal-git/jc/notifier/vendor/github.com/Shopify/sarama/offset_manager.go:212 +0x271
--
```
##### Problem Description

One of my kafka broker became unavailable for some time and my service stopped receiving messages from sarama.
I killed my program with the ABRT signal to get a stacktrace and I extracted theses goroutines that have been stuck for 181 minutes (the duration of my program not receiving data).
Data _was_ available as data consumption resumed right away as I restarted my service.

**Comment by eapache** [comment]
Those goroutines on their own do not provide any real information unfortunately - even in normal operation they will be idle the vast majority of the time, only waking up when partition leadership moves within the Kafka cluster.

Are there any sarama logs you can share? Are there any other blocked-looking goroutines with Sarama in the stack trace?

I notice you have set `Return.Errors` to true, are you reading from the error channel? If that fills up then sarama might block internally trying to notify of more errors.

**Comment by josselin-c** [comment]
That's the only two sarama-related goroutines in my trace. The other routines are consumer-group related/ application logic.
As for the logs, I unfortunately don't have them.

I have some code like this to watch for error and stop everything:
```	
select {
	case err = <-consumer.Errors():
		err = fmt.Errorf("sarama consumer error: %s", err)
	case err = <-errors:
}

consumer.Close()
```

I'll change my code to run a goroutine to loop over the Errors() channel until it's closed.

**Comment by eapache** [comment]
> That's the only two sarama-related goroutines in my trace.

Really? There should be at least one goroutine running `brokerConsumer.subscriptionManager` for every broker you consume from.

> I have some code like this to watch for error and stop everything

This code does not appear correct. Per the doc on `consumer.Close`: "It must be called after all child PartitionConsumers have already been closed".

**Comment by eapache** [comment]
> In this case, consumer is a consumer from github.com/wvanbergen/kafka.

Ah, then it's possible that the error is actually in that library instead. That might explain the lack of other blocked Sarama goroutines, if the balancing algorithm is stuck and sarama doesn't know which brokers to consume from.

**Comment by rickllyxu** [comment]
Sorry, I also meet this problem when the size of a message is set to 1KB(or bigger).
Consumer works well if sender sends a small amount of messages and size of each is 1KB. But when sender sends a big amount of messages, the consumer will halt. e.g. sender sends 10000 messages, each of which is 1KB, and consumer will halt. I try many times, and read related documents. I can't solve this problem.
