### ISSUE TITLE
TLS/SSL configuration question

### ISSUE THREAD

**Issue by meirwah** [Shopify/sarama#817]
##### Versions

Sarama Version: 574d3147eee384229bf96a5d12c207fe7b5234f3
Kafka Version: 0.10
Go Version: 1.7

##### Configuration

TLS , SSL, remote machine (public cloud)

##### Problem Description

I'm trying to fill the TLS config after setting up a kafka instance on remote machine with ssl.
On the kafka machine these files were created:
ca-cert  
ca-cert.srl  
ca-key  
cert-file  
cert-signed  
client.truststore.jks  
server.keystore.jks  
server.truststore.jks

Now question is, which do i use for the sarama tls configuration ??
which are certFile, keyFile, caFile ?

non of those seem to fit, how does this work?

**Comment by eapache** [comment]
The Sarama TLS configuration object uses the go built-in which is quite well documented: https://godoc.org/crypto/tls#Config.

**Comment by meirwah** [comment]
yes I know this...
But I don't know how to convert the kafka keystore/trustore files into certs , any idea how to do it?

**Comment by meirwah** [comment]
@eapache If you can provide some example for it...
it will be very useful...

**Comment by eapache** [comment]
I don't know, this is Java stuff which I have no experience with, but it sounds (according to https://en.wikipedia.org/wiki/Keystore) like you need to extract the cert from the keystore with a third-party tool.

**Comment by meirwah** [comment]
but which one?
client.truststore.jks ?
server.keystore.jks ?
server.truststore.jks ?

**Comment by irairdon** [comment]
Did you ever figure out the correct combination of commands to get the correct files for sarama to connect to kafka via SSL? I have tried for awhile with no success.

**Comment by meirwah** [comment]
yes, look at these:
https://github.com/confluentinc/confluent-platform-security-tools/blob/master/kafka-generate-ssl.sh
http://maximilianchrist.com/blog/connect-to-apache-kafka-from-python-using-ssl
