### ISSUE TITLE
Get offset by timestamp, kafka 0.10

### ISSUE THREAD

**Issue by nilsmagnus** [Shopify/sarama#831]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: fresh off github 15.feb 2017, 1416bd78f804d523005322194994f08c2a0ad797
Kafka Version: 0.10.1.1
Go Version: 1.7 

##### Problem Description

Is there planned support to get offset by timestamp, as supported by kafka 0.10?  I cannot see that it is supported by the current library. 

The java-equivalent would be 

     KafkaConsumer.offsetsForTimes(Map<TopicPartition, Long> timestampsToSearch) .

**Comment by eapache** [comment]
Starting in Sarama v1.11.0, the method `Client.GetOffset()` will automatically use the new precise timestamp fetching if your `Config.Version` is at least kafka version 0.10.1.
