### ISSUE TITLE
Message ordering and continuity of asynchronous producer

### ISSUE THREAD

**Issue by isethi** [Shopify/sarama#838]
Hi ,

I saw this question unanswered in the kafka client google group and had the same question so thought would post it here. 

I'm recently using Sarama and developing using kafka asynchronous producer. And there are two questions I'm confused of 3 questions about it:
1 As the messages are sent in batch, does the order the messages are sent to asyncproducer.Input() kept within 1 partition without retry and error? What if retry is performed?
2 If I put 10 messages to asyncproducer.Input(), is there the guarantee that the successfully messages are continuous? For example, if [1,2,3,4,5] are 5 messages put to asyncproducer.Input() in sequence, can the resulting successful message written be [1,2,4,5] with 3 missing?

Thanks

**Comment by eapache** [comment]
> 1 As the messages are sent in batch, does the order the messages are sent to asyncproducer.Input() kept within 1 partition without retry and error? What if retry is performed?

Yes, ordering is always kept within a partition, even when messages must be retried.

> 2 If I put 10 messages to asyncproducer.Input(), is there the guarantee that the successfully messages are continuous?

No. It is possible that some messages fail enough times that Sarama will return them as errors and continue to produce later messages.

**Comment by isethi** [comment]
Thanks!

**Comment by firnsan** [comment]
@eapache Hi, I have some question, can you help me to clear?

> 1. Yes, ordering is always kept within a partition, even when messages must be retried.

I don't understand why ordering is kept when messages must be retried? Like this: 
![image](https://user-images.githubusercontent.com/3955815/43991235-13807830-9d9b-11e8-8bcd-78d42a30116f.png)
When batch 3 is found timeout, the batch 4 is in flight (and is acked), so retry batch 3 result in [1,2,4,3,5,...] be written in kafka. This reordering is intolerable  for me.


> 2. No. It is possible that some messages fail enough times that Sarama will return them as errors and continue to produce later messages.

Is there some approach(for example, halt the producer) to avoid batch missing, ? [1,2,4,5,...] is  intolerable  for me.

**Comment by eapache** [comment]
> When batch 3 is found timeout, the batch 4 is in flight (and is acked), so retry batch 3 result in [1,2,4,3,5,...] be written in kafka. This reordering is intolerable for me.

Sarama avoids this case because it will never send a new batch (4) until after it has received the ack for the previous batch (3). So 4 will not be in flight.

> Is there some approach(for example, halt the producer until batch retry succeed, then continue to produce later messages) to avoid batch missing, ? [1,2,4,5,...] is intolerable for me.

Sarama does not currently support this case. However, it might be possible to add some sort of workaround. I would be willing to consider pull requests adding such a feature.

**Comment by firnsan** [comment]
Nice, thanks ! May be i will  raise a pull request if i have pretty workaround.

**Comment by july2993** [comment]
@firnsan 
do you have had any workaround yet? i want to avoid batch missing too.

i think i can set `config.Producer.Retry.Max` to a pretty high value like 1000, and `config.Producer.Retry.Backoff` = 1 second,  and stop producer when some msg not success before 1000 second like 100 second, but this is ugly.

**Comment by firnsan** [comment]
@july2993 
not very good workaround: When procuder find acked msg's offset is not sequential, just exit program and restart  to scan kafka to find out what have missed, and continue to produce from it .
1,2,4 (exit, start, scan), 3, 4, 5...
> Ofcouse, consumer must ignore the first '4', and wait producer recover

**Comment by july2993** [comment]
> When producer find acked msg's offset is not sequential

i think the Offset of msg can still be sequential if some msg send to Input() fail to push to kafka, but we can detect if some msg lost from Error() of check if msgs return from Successes() in the sequence as you sent to Input()

> Of course, consumer must ignore the first '4', and wait producer recover

this look like must done by application level(like assign a increase by one ID to msg Value)
