### ISSUE TITLE
Producer in the example got high memory usage and won't release(Even OOM)

### ISSUE THREAD

**Issue by TechieYork** [Shopify/sarama#840]
##### Versions

Sarama Version: Version 1.11.0 (2016-12-20)
Kafka Version: kafka_2.10-0.9.0.1
Go Version: go1.8 linux/amd64
Linux Version:3.10.0-327.el7.x86_64(CentOS7)

##### Configuration

Kafka setting:default setting only modify the max message size
Sarama setting:default

##### Logs

test2017/03/02 14:24:41.317706 Initializing new client
test2017/03/02 14:24:41.317775 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
test2017/03/02 14:24:41.317814 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
test2017/03/02 14:24:41.317822 client/metadata fetching metadata for all topics from broker localhost:9092
test2017/03/02 14:24:41.324790 Connected to broker at localhost:9092 (unregistered)
test2017/03/02 14:24:41.328543 client/brokers registered new broker #0 at localhost:9092
test2017/03/02 14:24:41.328597 Successfully initialized new client
test2017/03/02 14:24:41.331213 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
test2017/03/02 14:24:41.333672 Connected to broker at localhost:9092 (registered as #0)
test2017/03/02 14:24:41.335208 producer/broker/0 starting up
test2017/03/02 14:24:41.335242 producer/broker/0 state change to [open] on test_log/0
test2017/03/02 14:24:41.335257 producer/broker/0 state change to [open] on test_log/2
test2017/03/02 14:24:41.335261 producer/broker/0 state change to [open] on test_log/3
test2017/03/02 14:24:41.335263 producer/broker/0 state change to [open] on test_log/1
test2017/03/02 14:24:41.335265 producer/broker/0 state change to [open] on test_log/5
test2017/03/02 14:24:41.335268 producer/broker/0 state change to [open] on test_log/9
test2017/03/02 14:24:41.335270 producer/broker/0 state change to [open] on test_log/8
test2017/03/02 14:24:41.335272 producer/broker/0 state change to [open] on test_log/7
test2017/03/02 14:24:41.335274 producer/broker/0 state change to [open] on test_log/6
test2017/03/02 14:24:41.335278 producer/broker/0 state change to [open] on test_log/4
test2017/03/02 14:24:47.051174 producer/broker/0 maximum request accumulated, waiting for space
[1]    84713 killed     ./test_sarama

##### Problem Description

I used the AsyncProducer(select) example sarama provided, and the code as below:

`

	package main

	import (
		"log"
		"os"
		"os/signal"
		"github.com/Shopify/sarama"
	)
	
	func main() {
		logger := log.New(os.Stdout, "test", 5)
		sarama.Logger = logger
	
		producer, err := sarama.NewAsyncProducer([]string{"localhost:9092"}, nil)
		if err != nil {
			panic(err)
		}
	
		defer func() {
			if err := producer.Close(); err != nil {
				log.Fatalln(err)
			}
		}()
	
		// Trap SIGINT to trigger a shutdown.
		signals := make(chan os.Signal, 1)
		signal.Notify(signals, os.Interrupt)
	
		var enqueued, errors int
	
		var count int = 0
	
		ProducerLoop:
		for {
			select {
			case producer.Input() <- &sarama.ProducerMessage{Topic: "test_log", Key: nil, Value: sarama.StringEncoder("test log hahaha")}:
				enqueued++
			case err := <-producer.Errors():
				log.Println("Failed to produce message", err)
				errors++
			case <-signals:
				break ProducerLoop
			}
	
			count++
	
			if count > 10000000 {
				break
			}
		}
	
		log.Printf("Enqueued: %d; errors: %d\n", enqueued, errors)
	}
`
While running the memory kept increasing, util the 80%+ of the total memory then got killed(should killed by system)

##### Crash

I only meet crash once, these info may be useful

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x7023ec, 0x16)
	/root/install_package/golang/go/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc4991d0000, 0x8000000, 0x459600, 0x879a38)
	/root/install_package/golang/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x860de0, 0x8000000, 0x7fec2658fce0)
	/root/install_package/golang/go/src/runtime/malloc.go:428 +0x374
runtime.(*mheap).grow(0x860de0, 0x4000, 0x0)
	/root/install_package/golang/go/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x860de0, 0x4000, 0xc42002ed10)
	/root/install_package/golang/go/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0x860de0, 0x4000, 0x100000000, 0x0)
	/root/install_package/golang/go/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
	/root/install_package/golang/go/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0x7fec2658fdd8)
	/root/install_package/golang/go/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0x860de0, 0x4000, 0x10100000000, 0x0)
	/root/install_package/golang/go/src/runtime/mheap.go:628 +0xa0
runtime.largeAlloc(0x8000000, 0xc42003ef01, 0x2)
	/root/install_package/golang/go/src/runtime/malloc.go:795 +0x93
runtime.mallocgc.func1()
	/root/install_package/golang/go/src/runtime/malloc.go:690 +0x3e
runtime.systemstack(0xc420021300)
	/root/install_package/golang/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/root/install_package/golang/go/src/runtime/proc.go:1132

goroutine 11 [running]:
runtime.systemstack_switch()
	/root/install_package/golang/go/src/runtime/asm_amd64.s:281 fp=0xc42003ed30 sp=0xc42003ed28
runtime.mallocgc(0x8000000, 0x6a5200, 0x454d01, 0xc42003ef28)
	/root/install_package/golang/go/src/runtime/malloc.go:691 +0x930 fp=0xc42003edd0 sp=0xc42003ed30
runtime.makeslice(0x6a5200, 0x800000, 0x800000, 0xc42003ef88, 0x2, 0x2)
	/root/install_package/golang/go/src/runtime/slice.go:54 +0x7b fp=0xc42003ee20 sp=0xc42003edd0
github.com/DarkMetrix/log/test/vendor/github.com/eapache/queue.(*Queue).Add(0xc42003eee0, 0x6adaa0, 0xc47baa1f80)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/eapache/queue/queue.go:50 +0xf2 fp=0xc42003ee88 sp=0xc42003ee20
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).retryHandler(0xc4200af500)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:800 +0xff fp=0xc42003efa0 sp=0xc42003ee88
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).(github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.retryHandler)-fm()
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:100 +0x2a fp=0xc42003efb8 sp=0xc42003efa0
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.withRecover(0xc420011b00)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/utils.go:46 +0x43 fp=0xc42003efd8 sp=0xc42003efb8
runtime.goexit()
	/root/install_package/golang/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42003efe0 sp=0xc42003efd8
created by github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.NewAsyncProducerFromClient
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:100 +0x31f

goroutine 1 [select]:
main.main()
	/root/code/golang/src/github.com/DarkMetrix/log/test/test_sarama.go:36 +0x64d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/install_package/golang/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/root/install_package/golang/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/root/install_package/golang/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/root/install_package/golang/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 9 [select]:
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*client).backgroundMetadataUpdater(0xc4200dc000)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/client.go:563 +0x2c7
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*client).(github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.backgroundMetadataUpdater)-fm()
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/client.go:149 +0x2a
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.withRecover(0xc420011ac0)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.NewClient
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/client.go:149 +0x691

goroutine 7 [chan receive]:
github.com/DarkMetrix/log/test/vendor/github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x85c2e0)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/rcrowley/go-metrics/meter.go:221 +0x4c
created by github.com/DarkMetrix/log/test/vendor/github.com/rcrowley/go-metrics.NewMeter
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/rcrowley/go-metrics/meter.go:40 +0x127

goroutine 8 [chan receive]:
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*Broker).responseReceiver(0xc4200e2000)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/broker.go:473 +0xfa
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*Broker).(github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.responseReceiver)-fm()
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/broker.go:148 +0x2a
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.withRecover(0xc420011760)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*Broker).Open.func1
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/broker.go:148 +0x910

goroutine 10 [chan send]:
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).dispatcher(0xc4200af500)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:269 +0x3c1
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).(github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.dispatcher)-fm()
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:99 +0x2a
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.withRecover(0xc420011af0)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.NewAsyncProducerFromClient
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:99 +0x2c5

goroutine 12 [select, locked to thread]:
runtime.gopark(0x70e778, 0x0, 0x6fdb67, 0x6, 0x18, 0x2)
	/root/install_package/golang/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc42003df50, 0x0, 0x18)
	/root/install_package/golang/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc42003df50)
	/root/install_package/golang/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/root/install_package/golang/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
	/root/install_package/golang/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 21 [chan send]:
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*topicProducer).dispatch(0xc4200c4280)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:318 +0xf3
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*topicProducer).(github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.dispatch)-fm()
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:299 +0x2a
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.withRecover(0xc4200c6530)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).newTopicProducer
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:299 +0x224

goroutine 22 [chan send]:
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc4200ca5a0)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:450 +0x320
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*partitionProducer).(github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.dispatch)-fm()
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:398 +0x2a
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.withRecover(0xc4200c6540)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:398 +0x1f3

goroutine 24 [chan send]:
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).retryMessage(0xc4200af500, 0xc47baa2000, 0x83b3a0, 0xc42001e190)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:858 +0x9b
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).retryMessages(0xc4200af500, 0xc4885f4000, 0x270544, 0x2a6000, 0x83b3a0, 0xc42001e190)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:864 +0x62
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*brokerProducer).handleError.func3(0x6fe360, 0x8, 0xc400000000, 0xc4885f4000, 0x270544, 0x2a6000)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:771 +0x5d
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*produceSet).eachPartition(0xc42000c480, 0xc420128c20)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/produce_set.go:118 +0x13f
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*brokerProducer).handleError(0xc4200ca720, 0xc42000c220, 0x83b3a0, 0xc42001e190)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:772 +0x2ed
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*brokerProducer).handleResponse(0xc4200ca720, 0xc4200cc0a0)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:703 +0x57
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*brokerProducer).waitForSpace(0xc4200ca720, 0xc4911ad800, 0x1, 0xc42012c028)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:681 +0x191
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*brokerProducer).run(0xc4200ca720)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:620 +0x592
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*brokerProducer).(github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.run)-fm()
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:538 +0x2a
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.withRecover(0xc4200c6590)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).newBrokerProducer
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:538 +0x29b

goroutine 25 [chan receive]:
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).newBrokerProducer.func1()
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:542 +0x67
github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.withRecover(0xc4200cc660)
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/utils.go:46 +0x43
created by github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama.(*asyncProducer).newBrokerProducer
	/root/code/golang/src/github.com/DarkMetrix/log/test/vendor/github.com/Shopify/sarama/async_producer.go:554 +0x32a

**Comment by eapache** [comment]
There are limits to how quickly Sarama can produce. Your code is feeding it new messages as fast as that loop can run, which is *very* fast. Sarama will try and compensate by buffering messages, which takes memory, so the fact that it's using memory in this scenario is normal.

The default settings buffer fairly aggressively, but the amount of memory used depends somewhat on the size of the messages; it would not surprise me to see it use a GB or so before it finally gives up and refuses to accept any more messages.

**Comment by TechieYork** [comment]
Thanks a lot!
I understand this scenario.
Now I think I know where the problem is, my virtual machine which runs producer connecting kafka via wifi, the network bandwidth is small, so sarama have to buffer all the messages cause produce speed is faster than network send speed.

I tried again and waited for 10 min until the memory got recycled. A little bit long.

BTW, is there any method to control buffer size? config.ChannelBufferSize?

**Comment by eapache** [comment]
> I tried again and waited for 10 min until the memory got recycled. A little bit long.

Even once sarama is not using it anymore, Go will not necessarily release the memory back to the operating system right away. See https://stackoverflow.com/questions/24376817/go-1-3-garbage-collector-not-releasing-server-memory-back-to-system

> BTW, is there any method to control buffer size? config.ChannelBufferSize?

`config.ChannelBufferSize` will have an effect, but `Producer.Flush.MaxMessages` is probably more significant.

Limiting the global `sarama.MaxRequestSize` would also affect memory usage though it may have other side-effects.
