### ISSUE TITLE
Errors after restarting brokers.

### ISSUE THREAD

**Issue by agardiman** [Shopify/sarama#846]
## Problem Description
While producing messaging to a Kafka queue, I restart 2 or 3 kafka brokers. 
While the brokers are stopping, the sync producer doesn't have any problem because the messages are correctly sent to the last broker remained up. 
Unfortunately, the producer seems not being able to keep up with the new status of the cluster when the 2 brokers start again. In fact, it produces messages to the NOT restarted broker but returns endlessly the error 
> Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.

when sending messages to the brokers just restarted.

Restarting the producer does't solve the issue.

I have a local dockerized Kafka cluster made by 3 Kafka instances (Docker image: wurstmeister/kafka:0.10.1.1) and 1 Zookeeper instance (Docker image: mesoscloud/zookeeper:3.4.8-centos-7).

The source code is the following:

	logger := log.New(os.Stdout, "logger: ", log.Lshortfile)
	sarama.Logger = logger

	brokers := []string{"kafka-prova-0:9092", "kafka-prova-1:9092", "kafka-prova-2:9092"}
	producer, err := sarama.NewSyncProducer(brokers, producerConfiguration())
	if err != nil {
		panic(err)
	}
	defer producer.Close()

	for {
		msg := sarama.ProducerMessage{
			Topic: "topic-name",
			Value: sarama.ByteEncoder("something"),
		}
		_, _, err := producer.SendMessage(&msg)
		if err != nil {
			fmt.Printf("Error: %s\n", err)
		}
		time.Sleep(20 * time.Millisecond)
	}

What can be the cause of this issue?
Thank you!!

## Versions
Sarama Version: v1.11 and 3efb95dad8fbcd194d3c06f7b9c40eabeb719b36
Kafka Version: 0.10.1.1, 0.10.1.0
Go Version: 1.7

## Configuration
Sarama conf:
config := sarama.NewConfig()
config.Producer.Return.Successes = true
config.Producer.Return.Errors = true
config.Version = sarama.V0_10_1_0

### Error of producer.SendMessage(&msg): 
Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.

### Sarama.Logger: 
Error: kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.
logger: async_producer.go:459: producer/leader/topic-name/8 state change to [retrying-1]
logger: async_producer.go:469: producer/leader/topic-name/8 abandoning broker 0
logger: async_producer.go:613: producer/broker/0 state change to [closed] on topic-name/8
logger: client.go:586: client/metadata fetching metadata for [topic-name] from broker kafka-prova-2:9092
logger: async_producer.go:447: producer/leader/topic-name/8 selected broker 0
logger: async_producer.go:597: producer/broker/0 state change to [open] on topic-name/8
logger: async_producer.go:475: producer/leader/topic-name/8 state change to [flushing-1]
logger: async_producer.go:497: producer/leader/topic-name/8 state change to [normal]
logger: async_producer.go:745: producer/broker/0 state change to [retrying] on topic-name/8 because kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.
logger: async_producer.go:459: producer/leader/topic-name/8 state change to [retrying-2]
logger: async_producer.go:469: producer/leader/topic-name/8 abandoning broker 0
logger: async_producer.go:613: producer/broker/0 state change to [closed] on topic-name/8
logger: client.go:586: client/metadata fetching metadata for [topic-name] from broker kafka-prova-2:9092
logger: async_producer.go:447: producer/leader/topic-name/8 selected broker 0
logger: async_producer.go:597: producer/broker/0 state change to [open] on topic-name/8
logger: async_producer.go:475: producer/leader/topic-name/8 state change to [flushing-2]
logger: async_producer.go:497: producer/leader/topic-name/8 state change to [normal]
logger: async_producer.go:745: producer/broker/0 state change to [retrying] on topic-name/8 because kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.
logger: async_producer.go:459: producer/leader/topic-name/8 state change to [retrying-3]
logger: async_producer.go:469: producer/leader/topic-name/8 abandoning broker 0
logger: async_producer.go:613: producer/broker/0 state change to [closed] on topic-name/8
logger: client.go:586: client/metadata fetching metadata for [topic-name] from broker kafka-prova-2:9092
logger: async_producer.go:447: producer/leader/topic-name/8 selected broker 0
logger: async_producer.go:597: producer/broker/0 state change to [open] on topic-name/8
logger: async_producer.go:475: producer/leader/topic-name/8 state change to [flushing-3]
logger: async_producer.go:497: producer/leader/topic-name/8 state change to [normal]
logger: async_producer.go:745: producer/broker/0 state change to [retrying] on topic-name/8 because kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.

### Logs of the 2 restarted brokers: 
[2017-03-13 13:31:45,126] ERROR [ReplicaFetcherThread-0-2], Error for partition [topic-name,5] to broker 2:org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition. (kafka.server.ReplicaFetcherThread)

**Comment by eapache** [comment]
Per the logs, Sarama is asking the broker at `kafka-prova-2:9092` what the new leader is and that is still returning broker id 0 even though the leadership has moved. I do not know why `kafka-prova-2:9092` is returning wrong (stale?) information here.

**Comment by agardiman** [comment]
I tried with the default producer in Java (kafka-console-producer.sh) and that is able to produce without errors.

**Comment by agardiman** [comment]
I also tried consuming using the two libraries bsm/sarama-cluster and wvanbergen/kafka.

wvanbergen/kafka fails at startup with the following message: `Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.`

bsm/sarama-cluster continues to print the message: `Request was for a consumer group that is not coordinated by this broker.`

**Comment by agardiman** [comment]
@eapache You helped me looking in the right direction.

The three containers are using the same Docker network so they can see each other using their advertised hostnames.
In order to make the brokers visible from outside a container, I added the advertised hostnames in my /etc/hosts.
Unfortunately I didn't see that the broker0 and broker2's IPs were swapped, so the clients were trying to access to the right hostname but using the wrong IP.

Thanks a lot.

**Comment by eapache** [comment]
Glad I could help. Both wvanbergen/kafka and bsm/sarama-cluster are built on top of Sarama so it wouldn't surprise me they wouldn't work in this scenario. I am a bit surprised the java client worked though, I would have thought (based on your description) that it would have the exact same issue.

**Comment by agardiman** [comment]
Yeah, exactly that brought me to the wrong reasoning that I was using the go library in the wrong way. The fact is that I was running the default Java client from INSIDE a container, so in a correctly set environment, unlike my host.
