### ISSUE TITLE
does this work with Mapr Streams?

### ISSUE THREAD

**Issue by lakstap** [Shopify/sarama#847]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

**Comment by eapache** [comment]
> does this work with Mapr Streams?

I don't know. I've never tried it. MapR Streams claims to have a Kafka API (https://www.mapr.com/products/mapr-streams) so it seems plausible.
