### ISSUE TITLE
Buffer overwrite

### ISSUE THREAD

**Issue by juise** [Shopify/sarama#850]
##### Versions

Sarama Version: 280cdbd7fed6e93a0d682d2984c8e8e5dc08a2a8
Kafka Version: 0.10.1.0
Go Version: go1.7.3green+hgs

##### Configuration

```
type (
	Producer struct {
		Producer sarama.AsyncProducer
	}
)

func KafkaProducer(cfg config.Kafka) (*Producer, error) {
	cfgMeta := sarama.NewConfig()

	cfgMeta.Net.DialTimeout = 15 * time.Second
	cfgMeta.Net.MaxOpenRequests = 64

	cfgMeta.Net.KeepAlive = 60 * time.Second

	cfgMeta.Producer.RequiredAcks = sarama.WaitForAll // Wait for all in-sync replicas to ack the message
	cfgMeta.Producer.Retry.Max = 10                   // Retry up to 10 times to produce the message

	cfgMeta.Producer.Return.Errors = true
	cfgMeta.Producer.Return.Successes = false

	cfgMeta.ClientID = utils.Hostname

	producer, err := sarama.NewAsyncProducer(cfg.Brokers, cfgMeta)

	go func() {
		for _ = range producer.Errors() {
		}
	}()

      logger := l.New(os.Stderr, "", l.LstdFlags)
      sarama.Logger = logger

	return &Producer{Producer: producer}, err
}
```

##### Logs

```
мар 24 17:26:35 myapp.tty.in myapp[159781]: 2017/03/24 17:26:35 producer/broker/3 state change to [open] on conversion/0
мар 24 17:26:48 myapp.tty.in myapp[159781]: 2017/03/24 17:26:48 producer/broker/1 state change to [open] on conversion/11
мар 24 17:27:21 myapp.tty.in myapp[159781]: 2017/03/24 17:27:21 producer/broker/4 state change to [open] on redirection-urls/2
мар 24 17:27:22 myapp.tty.in myapp[159781]: 2017/03/24 17:27:22 producer/broker/2 state change to [open] on redirection-urls/0
мар 24 17:27:22 myapp.tty.in myapp[159781]: 2017/03/24 17:27:22 producer/broker/3 state change to [open] on redirection-urls/1
мар 24 17:27:22 myapp.tty.in myapp[159781]: 2017/03/24 17:27:22 producer/broker/1 state change to [open] on redirection-urls/11
мар 24 17:27:22 myapp.tty.in myapp[159781]: 2017/03/24 17:27:22 producer/broker/2 state change to [open] on redirection-urls/4
мар 24 17:27:22 myapp.tty.in myapp[159781]: 2017/03/24 17:27:22 producer/broker/1 state change to [open] on redirection-urls/3
мар 24 17:27:22 myapp.tty.in myapp[159781]: 2017/03/24 17:27:22 producer/broker/2 state change to [open] on redirection-urls/8
мар 24 17:27:22 myapp.tty.in myapp[159781]: 2017/03/24 17:27:22 producer/broker/3 state change to [open] on redirection-urls/9
мар 24 17:27:23 myapp.tty.in myapp[159781]: 2017/03/24 17:27:23 producer/broker/3 state change to [open] on redirection-urls/5
мар 24 17:27:23 myapp.tty.in myapp[159781]: 2017/03/24 17:27:23 producer/broker/4 state change to [open] on redirection-urls/6
мар 24 17:27:23 myapp.tty.in myapp[159781]: 2017/03/24 17:27:23 producer/broker/1 state change to [open] on redirection-urls/7
мар 24 17:27:26 myapp.tty.in myapp[159781]: 2017/03/24 17:27:26 producer/broker/4 state change to [open] on redirection-urls/10

```
##### Problem Description

My application accept json by http, and then push them into kafka via async producer. Right now I have 5 different topics. Into first 4 topics I'm write from one http-handler, and into the last topic (redirection-urls) from the other http_handler. 

Some times I've observe in topic redirection-urls the some parts of messages from other topics, which equal by length to my messages which I have push to redirection-urls topic.

I push message:
```
{"field_1":0, "field_2":"a", "field_3":false}
{"field_1":0, "field_2":"a", "field_3":false}
```
I got in redirection-urls:
```
{"uuid":"1873510061456966504","os_type":"mobi
{"uuid":"6919577987819299128","os_type":"desk
```

The part of my code:
```
import (
"myapp/kafka"
)

func Start(cfg config.Http, v model.Version, p *kafka.Producer) error {
...
        mux := func(ctx *fasthttp.RequestCtx) {
                path := string(ctx.Path())

                switch path {
                case "/api/v1/calculate":
                        httpCalculate(p, ctx)
                case "/api/v1/log":
                        httpLog(p, ctx)
                }
        }

       server := &fasthttp.Server{
                Handler:      mux,
                LogAllErrors: true,
        }

        return server.ListenAndServe(fmt.Sprintf("%s:%d", cfg.Host, cfg.Port)
}


func httpCalculate(p *kafka.Producer, ctx *fasthttp.RequestCtx) {
...
        go func() {
                kafka.Produce(p, event.EventType, buffer)
                }
        }()
...
}

func httpLog(p *kafka.Producer, ctx *fasthttp.RequestCtx) {
        body := ctx.PostBody()
        go func() {
                kafka.Produce(p, "redirection-urls", body)
        }()
}

kafka module (contains config from first section):

func Produce(p *Producer, topic string, msg []byte) {
        message := &sarama.ProducerMessage{
                Topic: topic,
                Value: sarama.ByteEncoder(msg),
        }

        p.Producer.Input() <- message
}
```

Looks like I'm doing something wrong, could someone help me please?

**Comment by eapache** [comment]
Your usage of Sarama looks safe enough. If there really is a buffer overwrite or race condition happening, Go's race detector (https://blog.golang.org/race-detector) might help track it down.

```
	go func() {
		for _ = range producer.Errors() {
		}
	}()
```

If you're not going to do anything with the errors you might as well just set `Producer.Return.Errors` to false. This probably has nothing to do with your problem though.

```
        go func() {
                kafka.Produce(p, "redirection-urls", body)
        }()
```

Launching a new goroutine for every kafka message produced is expensive and destroys any ordering guarantees you might have wanted.

I'll also note that the `fasthttp` readme has a big warning about race conditions, but I don't know enough about it to know if your code is safe or not.

**Comment by juise** [comment]
@eapache it's not good idea to close issue! The problem is still there!

I've add stupid log with fmt.Printf, and log ProducerMessage pusher into Input() from my code, and add some logs, inside sarama library:

My code:
```
func Produce(p *Producer, topic string, msg []byte) {
     message := &sarama.ProducerMessage{
          Topic: topic,
          Value: sarama.ByteEncoder(msg),
    }

    if topic == "redirection-urls" {
        fmt.Printf("a %v\n", msg)
        fmt.Printf("b %v\n", message)
    }

    p.Producer.Input() <- message

    if topic == "redirection-urls" {
        fmt.Printf("c %v\n", message)
    }
}
```

Samara:
```
sarama/async_producer.go:
229 func (p *asyncProducer) dispatcher() {
...
269         if msg.Topic == "redirection-urls" {
270             fmt.Printf("0 = %v\n", msg)
271         }
272
273        handler <- msg
274    }
```

I've emit only one message to redirection-urls topic, and what the log show me:
```
мар 25 18:14:02 myapp.tty.in myapp[134770]: a [123 34 102 105 101 108 100 95 49 34 58 48 44 32 34 102 105 101 108 100 95 50 34 58 34 97 34 44 32 34 102 105 101 108 100 95 51 34 58 116 114 117 101 125]
мар 25 18:14:02 myapp.tty.in myapp[134770]: b &{redirection-urls <nil> [123 34 102 105 101 108 100 95 49 34 58 48 44 32 34 102 105 101 108 100 95 50 34 58 34 97 34 44 32 34 102 105 101 108 100 95 51 34 58 116 114 117 101 125] <nil> 0 0 0001-01-01 00:00:00 +0000 UTC 0 0}
мар 25 18:14:02 myapptty.in myapp[134770]: c &{redirection-urls <nil> [123 34 102 105 101 108 100 95 49 34 58 48 44 32 34 102 105 101 108 100 95 50 34 58 34 97 34 44 32 34 102 105 101 108 100 95 51 34 58 116 114 117 101 125] <nil> 0 0 0001-01-01 00:00:00 +0000 UTC 0 0}

```
As you can see, the message is:
`123,34,102,105,101,108,100,95,49,34,58,48,44,32,34,102,105,101,108,100,95,50,34,58,34,97,34,44,32,34,102,105,101,108,100,95,51,34,58,116,114,117,101,125`

which equal to:
`{"field_1":0, "field_2":"a", "field_3":true}`

The a and b log is before push message into Input(), and c - after. The log below is more interesting:
`мар 25 18:14:02 myapp.rtty.in myapp[134770]: 0 = &{redirection-urls <nil> [123 34 117 117 105 100 34 58 34 53 54 57 55 48 49 49 49 53 56 52 52 54 49 52 56 49 56 48 34 44 34 111 115 95 116 121 112 101 34 58 34 109 111 98] <nil> 0 0 0001-01-01 00:00:00 +0000 UTC 0 0}`

This is log from sarama/async_producer.go, from func (p *asyncProducer) dispatcher() function. I wonder, how can it be?

**Comment by eapache** [comment]
The problem is not in Sarama. Per the documentation of fasthttp (https://godoc.org/github.com/valyala/fasthttp#RequestCtx.PostBody) the return value of the post body is only valid until the handler method (`httpLog` in this case) returns. Since you are launching a goroutine with a reference to it, the actual access to that data occurs later when it is invalid.

**Comment by juise** [comment]
Hmm, @eapache, but I do:
body := ctx.PostBody()

before the goroutine, so, the body variable is not bound to the current request and ctx.PostBody() function.

```
        body := ctx.PostBody()
        go func() {
                kafka.Produce(p, "redirection-urls", body)
        }()
```

**Comment by eapache** [comment]
`PostBody()` returns a `[]byte` which is still a reference; the goroutine grabs the reference instead of the underlying byte array. Make a new byte slice and `copy()` the result of `PostBody()` into that.

**Comment by juise** [comment]
Ouch, @eapache, thanks a lot, it's my fault, you are right, the problem was in assignment []byte as reference. Thanks!
