### ISSUE TITLE
Kafka message format v1

### ISSUE THREAD

**Issue by vgraveto** [Shopify/sarama#856]
##### Versions

Sarama Version: commit 3efb95d  
Kafka Version: 10.2.0
Go Version: go1.7.1 darwin/amd64

##### Problem Description

We are using kafka stream that imposes message format v1, but reading through sarama code and documentation I see that the format is supported. But when I send my messages (asyncProducer producer), kafka receives them ok, but kafka stream reports problems with the timestamp. As message format v0 has no such field, I think that we need to impose the producer to use v1. How should I impose that format?

Any example or help would be good

**Comment by eapache** [comment]
You have to set `Config.Version` to the version of kafka you are using. If that is greater than `V0_10_0_0` then it will generate the v1 message format automatically.
