### ISSUE TITLE
GetOffset by timestamp not working on at v1.11.0

### ISSUE THREAD

**Issue by liudanking** [Shopify/sarama#857]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: at v1.11.0
Kafka Version: 0.10.1.1
Go Version: 1.7

##### Configuration
```
func tsConsumer() {
	config := sarama.NewConfig()
	config.Version = sarama.V0_10_1_0
	client, err := sarama.NewClient(brockerList, config)
	if err != nil {
		log.Fatal(err)
	}
	t, err := time.Parse("2006/01/02 15:04:05", "2017/03/30 11:21:31")
	if err != nil {
		log.Fatal(err)
	}
	// t = t.Add(8 * time.Hour)
	log.Printf("time:%s", t.String())
	offset, err := client.GetOffset(TOPIC, 0, t.UnixNano())
	if err != nil {
		log.Printf("get offset failed:%v", err)
		return
	}

	log.Printf("offset:%d", offset)
}
```
##### Logs

[sarama] 2017/03/30 11:46:53 Initializing new client
[sarama] 2017/03/30 11:46:53 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2017/03/30 11:46:53 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2017/03/30 11:46:53 client/metadata fetching metadata for all topics from broker kafka-log-0:9092
[sarama] 2017/03/30 11:46:53 Connected to broker at kafka-log-0:9092 (unregistered)
[sarama] 2017/03/30 11:46:53 client/brokers registered new broker #0 at localhost:9092
[sarama] 2017/03/30 11:46:53 Successfully initialized new client
2017/03/30 11:46:53 time:2017-03-30 11:21:31 +0000 UTC
[sarama] 2017/03/30 11:46:53 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
[sarama] 2017/03/30 11:46:53 Connected to broker at localhost:9092 (registered as #0)
2017/03/30 11:46:53 offset:-1

##### Problem Description

try to get offset by timestamp always returns `-1`. I have checked my version and config, it seems ok, or is there anything I have missed?

**Comment by eapache** [comment]
You want to use `Unix()` not `UnixNano()`

**Comment by turtlemonvh** [comment]
Actually this is a `ms` resolution timestamp, so `UnixNano()/1e6` works well.
