### ISSUE TITLE
How to pass group id for consumer?

### ISSUE THREAD

**Issue by tarunjain07** [Shopify/sarama#863]
How to pass group id for consumer?
Pasting Python code -

> from kafka import KafkaConsumer
> consumer = KafkaConsumer('my_favorite_topic', **group_id='my_favorite_group'**)
> for msg in consumer:
>...     print (msg)

**Comment by tarunjain07** [comment]
appropriate subject line

**Comment by wvanbergen** [comment]
As per the [FAQ](https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions), sarama currently doesn't support higher level consumer groups.
