### ISSUE TITLE
Exactly once semantics with sarama producer

### ISSUE THREAD

**Issue by ajaybodhe** [Shopify/sarama#864]
##### Versions
Sarama Version: v1.10.0 / 9bb4a68d57ff6f623363aa172f0a8297aa289ba7
Kafka Version: 0.10.1
Go Version: 1.8

#### Kafka setup
* We are using 3 brokers for kafka
* We have kept the Replication factor as 3
* Topics are divided into 10 partitions
* Each message is read from the partition once

##### Problem Description
I am seeing some messages produced multiple times in the topics 
I am using following client configuration
```Go
conf := sarama.NewConfig()
conf.Producer.RequiredAcks = sarama.NoResponse
conf.Producer.Return.Successes = true
conf.Consumer.Return.Errors = true
conf.Producer.Return.Errors = true
conf.Producer.RequiredAcks = sarama.NoResponse
conf.Producer.Retry.Max=1
```
My requirement is at most once or exactly once if thats possible.
While searcing for this, I came across:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging

Is it supported in Sarama , or is there any plan to support that in near future?
If not how can this be solved?

**Comment by wvanbergen** [comment]
Sarama doesn't support `exactly once semantics`; You can either have at most once, or at least once semantics depending on your config.

This was due to limitations of the Kafka protocol itself. I see a KIP that aims to add this: https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging. Not sure if that already landed, but if so, sarama currently does not support it.

**Comment by ajaybodhe** [comment]
How do u support at max one
what are things I need to configure?

**Comment by wvanbergen** [comment]
By disabling all retries:

```
conf.Producer.Retry.Max=0
```

if I remember correctly

**Comment by ajaybodhe** [comment]
cool, Thanks,
Few things - 
1. how can I increase the timeout for which producer waits for ack from kafka broker?
So that I can decrease the possibility of resending the same message.

Sarama documentation claims that, this is the timeout field:
conf.Producer.TImeouts = 10s (default value)
But I am damn sure, even if I keep my producer and kafka far apart , the timeout of 10s will be hit.

2. Also I tried with different values of , conf.Producer.Retry.Max (1,2,3); my messages are getting duplicated 4 times consistently. How can I troubleshoot this?

3. Also If I set conf.Producer.RequiredAcks = sarama.NoResponse, what are the effects on delivery policy?

4, If you are aware of any production deployments of Sarama, can you please share Sarama and kafka configuration?

**Comment by wvanbergen** [comment]
4. This is what we use in production:

```
	kafkaConfig.Metadata.Retry.Max = 5
	kafkaConfig.Metadata.Retry.Backoff = 500 * time.Millisecond
	kafkaConfig.Producer.Return.Successes = true
	kafkaConfig.Producer.Return.Errors = true
	kafkaConfig.Producer.RequiredAcks = sarama.WaitForAll
	kafkaConfig.Producer.Timeout = 15 * time.Second
	kafkaConfig.Producer.Flush.Messages = 200
	kafkaConfig.Producer.Flush.Frequency = 400 * time.Millisecond
	kafkaConfig.Producer.Retry.Max = 12
	kafkaConfig.Producer.Retry.Backoff = 5 * time.Second
	kafkaConfig.Producer.Compression = sarama.CompressionSnappy
	kafkaConfig.Producer.MaxMessageBytes = DefaultMaxMessageSize
```

**Comment by ajaybodhe** [comment]
This is extremely helpful, I have been struggling with this since a week
now to talk about kafka
1. how many brokers in cluster?
2. How many topics?
3. How many partitions per topic?
4. Replication Factor for each partition

**Comment by ajaybodhe** [comment]
@wvanbergen 
Can u also share the consumer config u r using,

I am seeing this log again and again, 

Publishing logs {"env":"staging","host":"ip-10-0-1-152","level":"debug","msg":"[consumer/broker/1 abandoned subscription to scribe/0 because consuming was taking too long\n]","service":"scribe","time":"2017-04-10T12:11:24Z"}


And My consumer is getting stuck there.

**Comment by wvanbergen** [comment]
We have several Kafka clusters, most of them ranging between 5-20 brokers. We have hundreds of topics, with partitions ranging from 1 to 128. Replication factor is usually 3.

We usually don't consume using go/sarama, so I have no good consumer config to share. For your problem, you may have to set the consume timeout to make sure it is higher than what it takes for any message to be processed.

**Comment by ervitis** [comment]
Hi, sorry for re open this issue after 3 years, but I am interested if sarama has support for exactly once semantics in the producer. 

I have seen that the consumer has the isolation level and the producer the idempotence flag. So maybe that feature is supported now.

Regards
