### ISSUE TITLE
Timestamp only added in producer if compression is enabled

### ISSUE THREAD

**Issue by convolvatron** [Shopify/sarama#865]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.11.0
Kafka Version:0.10.2.0
Go Version:1.8

##### Problem Description
the problem is evident from looking at the conditionals in produce_set.go:buildRequest

the timestamp is only added in the case that Compression is not CompressionNone. it
seems like it should be orthogonal

**Comment by wvanbergen** [comment]
As I see it, the compression case in `buildRequest` simply sets the timestamp of the compressed set to the timestamp of the first message in the set. It also depends on the timestamp of the individual messages being set.

The timestamp is set when encoding individual messages here: https://github.com/Shopify/sarama/blob/e6df07fb9cf315a30d9a8d665185090d5bf84b22/message.go#L47-L49.  Are you setting `Version = 1` ?

**Comment by eapache** [comment]
The internal message version is also set for you if timestamps are used. The only config value that the user needs to worry about is setting `Config.Version` to be at least kafka 0.10.
