### ISSUE TITLE
How to consume topics using  wildcard character？

### ISSUE THREAD

**Issue by congleetea** [Shopify/sarama#868]
Hi, I want to consume multiple topics using a wildcard character.  For example, I have a consumer group: group1, which consumes all topics named test-topic-<N>, N can be any world.    and if a topic name test-topic-<N+1> added, it can be consumed automatically.   
 
Is there some methods to do it. 

thanks.

**Comment by wvanbergen** [comment]
There is not really anything special available for this. You can use the
Topics() API on Client, and find the topics you're interested in. Then,
start consuming those.

Willem

**Comment by congleetea** [comment]
thanks a lot. I will try it.

**Comment by wvanbergen** [comment]
There is nothing special about this API. You call `Topics()` and you get a list of topics back. There is no feature to notify you of newly created topics. Kafka 0.8, for which this client was written, does not have an API for that. 

I think newer versions of Kafka have APIs for this, but in the Kafka 0.8 world you need to set a Zookeeper watch to be notified of new topics. Kazoo is a library that you can use to interface with the Kafka metadata stored in Zookeeper and set watches: https://github.com/wvanbergen/kazoo-go
