### ISSUE TITLE
Callback for Async Producer Client

### ISSUE THREAD

**Issue by liangfan** [Shopify/sarama#869]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1.11.0
Kafka Version: 0.10.0.2
Go Version: 1.8

##### Problem Description

Do you have a plan to add callback for async producer client, or is there any elegant method to do the callback like [Java] `public Future<RecordMetadata> send(ProducerRecord<K, V> record, Callback callback)` in `KafkaProducer`.

**Comment by eapache** [comment]
Since the API uses asynchronous channels there isn't usually a need for callbacks, however they are still relatively straightforward to build if you need them, using the `SyncProducer`:
```go
go func() {
  partition, offset, err := producer.SendMessage(...)
  // do something with err
  myCallback()
}()
```
