### ISSUE TITLE
does sarama supports kafka Authentication using SASL/Kerberos 

### ISSUE THREAD

**Issue by yingqin678** [Shopify/sarama#870]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:v1.11
Kafka Version:0.9.0.0
Go Version:1.7

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

**Comment by wvanbergen** [comment]
No, sarama currently only supports SASL plain, not Kerberos.

**Comment by GlenRSmith** [comment]
@wvanbergen Any plans to add Kerberos support? Is it worth opening a new issue as a feature request?

**Comment by wvanbergen** [comment]
From our end, we're not planning to add support because we don't have a need for it ourselves. We'll happily accept PRs that add support for it though. 

I rather not keep issues open for feature requests, as it is possible these create unwarranted expectations for users and unnecessary pressure on maintainers.

**Comment by GlenRSmith** [comment]
Thanks, @wvanbergen. Appreciate that everyone has a preferred management and workflow. :-)
I would observe, though, that with the appropriate labeling, open feature requests can attract contributions.

**Comment by wvanbergen** [comment]
Yup, there's definitely pros and cons for this approach, but this is what we decided to go for a while back. I hope you understand.
