### ISSUE TITLE
Configure zookeeper chroot needed?

### ISSUE THREAD

**Issue by dahankzter** [Shopify/sarama#871]
##### Versions

Sarama Version: v1
Kafka Version: kafka_2.12-0.10.2.0
Go Version: 1.8.1

##### Problem Description

I have to for reasons configure my Zookeeper chroot path to "/projectX" but I am at a loss as to if and how I configure the path when I connect using Sarama.

zk.server:9092/projectX

does not seem to work.

How canI configure it to look for the data there?

**Comment by wvanbergen** [comment]
Sarama never talks to Zookeeper, just to the Kafka broker. You'll have to configure the zookeeper connection in the kafka broker configuration files; once that is set up properly sarama should work without any changes needed.

**Comment by dahankzter** [comment]
Ah you are right of course! I had the config pointing to Kafka but somehow mixed it up.
