### ISSUE TITLE
l4z invalid header checksum on consumer

### ISSUE THREAD

**Issue by ajorgensen** [Shopify/sarama#875]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: master @ 7f63d35b7921e19b021f39b8f4a344418747e251 
Kafka Version: 0.10.0.1
Go Version: go 1.8

##### Configuration

What configuration values are you using for Sarama and Kafka?
Standard configuration. Topics are written using lz4 compression. Java consume consumer works fine, [sarama console consumer](https://github.com/Shopify/sarama/blob/master/tools/kafka-console-consumer/kafka-console-consumer.go) failed to read the messages. I had to turn on verbose logging to see the failures.

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

```
2017/05/09 17:01:49 consumer/broker/41 disconnecting due to error processing FetchRequest: lz4.Read: invalid header checksum: got 26 expected 130
2017/05/09 17:01:49 Closed connection to broker kafka1001:9092
2017/05/09 17:01:49 kafka: error while consuming foo/88: lz4.Read: invalid header checksum: got 26 expected 130
2017/05/09 17:01:49 Done consuming topic foo
2017/05/09 17:01:49 Closing Client
```

##### Problem Description

The sarama consumer does not appear to be able to consume lz4 compressed payloads and complains about an invalid header checksum. This messages are produced and consumed without issue using the java client.

**Comment by eapache** [comment]
It sounds like you're getting bit by https://issues.apache.org/jira/browse/KAFKA-3160. This was theoretically fixed in Kafka 0.10, but if your producer is still running an older version it would produce the broken messages still.

**Comment by ajorgensen** [comment]
The producer is also running 0.10.0.1

**Comment by eapache** [comment]
Ya, they happened to add a new wire protocol version (KIP-31) in the same release, so they tied the encoding compatibility to that. I believe the broker will actually "unfix" correctly-encoded messages to maintain compatibility if your wire protocol version is prior to 0.10.

**Comment by ajorgensen** [comment]
Interesting that explains it then. Thanks for your help!

**Comment by eapache** [comment]
(FWIW, I believe Sarama's kafka version flag should in theory match the broker's configured protocol version, not the actual version of the broker. If that were the case Sarama would have warned you about this.)

**Comment by eapache** [comment]
You're welcome!

**Comment by arianitu** [comment]
Anyone running into this, you can fix it like so:

```
c := sarama.NewConfig()
...
c.Version = sarama.V0_10_0_0
```
