### ISSUE TITLE
How to retrieve a message which was sent using the AsyncProducer? 

### ISSUE THREAD

**Issue by CPS86** [Shopify/sarama#877]
##### Versions
Sarama Version: 1.12.0 
Kafka Version: 0.10.2.0
Go Version: 1.8

Hello

I would like to know how can I retrieve message which was successfully sent using the AsyncProducer?

So, I'm getting confirmation by reading from Success Channel. I am able to e.g. retrieve partition & offset information by:

case err := <- producer.Successes():
fmt.Println(strconv.Itoa(int(err.Parition)))
fmt.Println(strconv.Itoa(int(err.Offset)))

Apart from Partition & Offset, there is a Value field of Encode data type.
How can I convert that to string?

**Comment by wvanbergen** [comment]
If you have produced strings, the `Encoder` will be a `StringEncoder`, which is a type built on the built-in `string` type: https://godoc.org/github.com/Shopify/sarama#StringEncoder. You can simply cast it to `string`.

**Comment by CPS86** [comment]
Hello

Thanks for answer. I can't cast it to string

case msg := <- producer.Successes():
  fmt.Println(string(msg.Value))  // Getting cannot convert msg.Value (type sarama.Encoder) to type string
  fmt.Println(sarama.StringEncoder(err.Value)) // cannot convert msg.Value (type sarama.Encoder) to type sarama.StringEncoder: need type assertion 
  fmt.Println(sarama.StringEncoder(string(err.Value))) // Getting cannot convert msg.Value (type sarama.Encoder) to type string


Still don't know how can I do that.

**Comment by wvanbergen** [comment]
Try a type assertion: https://golang.org/ref/spec#Type_assertions
