### ISSUE TITLE
Is need connect zookeepers for a consumer? thank you.

### ISSUE THREAD

**Issue by lygn128** [Shopify/sarama#878]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

**Comment by wvanbergen** [comment]
Depends on what kind of consumer, and what version of Kafka you are using: https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#consuming
