### ISSUE TITLE
Lack of Consumer.Retry.Max option

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#881]
There is an asymmetry between the `Retry` options offered for the `Producer`, compared to the `Consumer`. Namely, there is no `Max` field under the `Retry` struct, to allow the `Consumer` to retry reading a partition up to a certain number of times.

I am fairly certain there is a good reason for this — I looked at the [Consumer configuration](https://kafka.apache.org/documentation/#consumerconfigs) on the Kafka website, and there is no `retries` option there either — but that reason eludes me.

Can you clarify the thinking behind this?

Thank you.

**Comment by wvanbergen** [comment]
For a producer, at some point you need to know that your message cannot be produced and act accordingly. So we have to cut short the attempts we made.

For consumers, there is no risk of data loss. It makes sense to just always keep trying and continue when things work again. As a developer, it should be relatively easy to:
- add a timeout so you can do something if you haven't processed any messages in a while.
- add alerting when your consumer is getting behind.

Neither require support from the consumer API.
