### ISSUE TITLE
Client does not return proper brokers

### ISSUE THREAD

**Issue by pceric** [Shopify/sarama#882]
##### Versions

Sarama Version: c01858abb625b73a3af51d0798e4ad42c8147093
Kafka Version: 0.10.1.0
Go Version: 1.8.1

##### Configuration

Default Kafka configuration.
Sarama with sarama.V0_10_1_0

##### Logs

See below for captured Sarama debug output.

##### Problem Description

I'm connecting to my Kafka cluster, currently just a single broker, with sarama.Client.  I'd like to access the brokers but Client.Brokers() does not appear to return working brokers. Simple examples follow:

```
config := sarama.NewConfig()
config.Version = sarama.V0_10_1_0
client, _ := sarama.NewClient(strings.Split("192.168.99.100:32768", ","), config)
topics, _ := client.Topics()
fmt.Printf("%v\n", topics)
```
> [Sarama] 2017/05/23 20:35:07 Initializing new client
> [Sarama] 2017/05/23 20:35:07 client/metadata fetching metadata for all topics from broker 192.168.99.100:32768
> [Sarama] 2017/05/23 20:35:07 Connected to broker at 192.168.99.100:32768 (unregistered)
> [Sarama] 2017/05/23 20:35:07 client/brokers registered new broker #0 at 3a9b133c56db:9092
> [Sarama] 2017/05/23 20:35:07 Successfully initialized new client
> [test __consumer_offsets]

We're good up to this point, I have a connected Client and it gave me the correct topics.  Now I ask the brokers for data:
```
for _, broker := range client.Brokers() {
    request := new(sarama.ListGroupsRequest)
    response, err := broker.ListGroups(request)
    if err != nil {
        log.Printf("Could not list groups: %s\n", err.Error())
    }
}
```
> 2017/05/23 20:53:24 Could not list groups: kafka: broker not connected
> [Sarama] 2017/05/23 20:53:24 Closing Client
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x8 pc=0x76f3e7]

I should have a connected broker, I just successfully got the topics.  Let's try connecting...
`broker.Open(client.Config())`
> [Sarama] 2017/05/23 20:35:10 Failed to connect to broker 3a9b133c56db:9092: dial tcp: lookup 3a9b133c56db: no such host
> 2017/05/23 20:35:10 Could not list groups: dial tcp: lookup 3a9b133c56db: no such host

At this point I don't have any working broker instances.

**Comment by wvanbergen** [comment]
- To connect to the cluster, we use a "seed broker". Once connected, we will ask the cluster for all the brokers in the cluster. This list is what gets returned if you call `Brokers()`. The seed broker(s) are usually not used after this bootstrapping step of the client.

- This means that the Kafka cluster is returning `3a9b133c56db:9092` as a broker address. This is probably an internal address that is not reachable from the location of the client. You'll have to update your brokers' configuration to return an address that is reachable from where your client is running. Look for the advertised host and port options in the broker docs.
