### ISSUE TITLE
AsyncProducer does not flush message to broker after called saram.Close()  when Flush.Messages configured

### ISSUE THREAD

**Issue by fikgol** [Shopify/sarama#884]
##### Versions
Sarama Version: sarama.v1
Kafka Version: kafka_2.11-0.10.2.1
Go Version: go1.8.1 darwin/amd64

##### Problem Description
Configured kafkaConfig.Producer.Flush.Messages = 100

If sent messages less than 100, after close the async producer, the messages would not be sent.

After changing  kafkaConfig.Producer.Flush.Messages = 1 or input messages more than 100, it works fine.

How could I flush the message to brokers when the input messages less than Flush.Messages ?

**Comment by eapache** [comment]
When you set `Flush.Messages` you also almost always want to set `Flush.Frequency` so that if the required number of messages don't accumulate in a given time you don't add too much latency to your producer.
