### ISSUE TITLE
Testing PartitionConsumer.Close() errors

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#886]
I am trying to write a unit test for the case when calling `Close` on the `PartitionConsumer` returns an error: https://github.com/Shopify/sarama/blob/master/consumer.go#L410...L428

What would be the easiest/most straightforward way of forcing such an error?

**Comment by eapache** [comment]
Use the mocked version of the consumer stack: https://github.com/Shopify/sarama/tree/master/mocks

It has a number of useful functions for forcing various states.
