### ISSUE TITLE
CPU utilization  grow up to a high level and never reduce

### ISSUE THREAD

**Issue by wenpos** [Shopify/sarama#888]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.12.0
Kafka Version:  kafka_2.11-0.9.0.0
Go Version: 1.8

##### Configuration
 config := cluster.NewConfig()
	config.Version = sarama.V0_9_0_0
	config.Consumer.Retry.Backoff = 5 * time.Second
	config.Consumer.MaxProcessingTime = 200 * time.Millisecond
	config.Consumer.MaxWaitTime = 1000 * time.Millisecond
	config.Consumer.Offsets.CommitInterval = 3 * time.Second

##### Logs
No Error logs

##### Problem Description
My app to consume message  has been running in docker. At the beginning, the CPU utilization was quite low (between 0%~10%)， while some time later (not exactly), the CPU utilization was going to a high level (about 40%), even if no new message in topic to be consumed. Once it happened, the CPU utilization never reduce. This problem has troubled me long time. 
Thank you very much.

**Comment by eapache** [comment]
I have not seen CPU usage like this, so without more information it will be impossible to tell where the problem is. Go has very good profiling tools you can try to get a better idea: https://blog.golang.org/profiling-go-programs

**Comment by wenpos** [comment]
Thanks for your reply. Here is the profile information:
![pprof-top-cum](https://user-images.githubusercontent.com/20151865/26859071-c4c2c7ce-4b67-11e7-8105-1598bc5f0cad.png)
[pprof001.zip](https://github.com/Shopify/sarama/files/1057013/pprof001.zip)

**Comment by eapache** [comment]
How many partitions are you consuming with this consumer?

**Comment by wenpos** [comment]
Only one partition

**Comment by eapache** [comment]
The profile indicates that most of your CPU time is being spent in the underlying read/write network calls, which would only make sense if you were processing a large quantity of messages or a large number of partitions, since your `MaxWaitTime` is set to 1000 milliseconds. Are you sure there are no new messages being consumed?

**Comment by wenpos** [comment]
- Yes,I am sure the quantity of message in our current is not large enough. When new message comes, we could consume new message. The CPU never reduces when no new message sent to topic.

- When I run my program in virtual machine, the CPU  usage was normal. But ,when I run it in docker it almost occurs. Is there any difference？

**Comment by eapache** [comment]
> When I run my program in virtual machine, the CPU usage was normal. But ,when I run it in docker it almost occurs. Is there any difference?

There are plenty of differences between full VMs and docker, but if this issue is only happening in docker then it is almost certainly a docker bug (or perhaps a golang-on-docker bug) and not specific to Sarama.
