### ISSUE TITLE
Mock Consumer ignoring config

### ISSUE THREAD

**Issue by kchristidis** [Shopify/sarama#890]
As thing stand today, the mock `Consumer` object ignores the `Config` object passed to it via the `NewConsumer` constructor. This is expected behavior as documented [here](https://github.com/Shopify/sarama/blob/61ca52d100f625ec7d4762c8ea0dda195cd035f1/mocks/consumer.go#L21).

I am wondering whether:

1. There is a specific reason for this decision.
2. You would be interested in a patch that treats the `conf` argument the same way `NewClient` does.

**Comment by eapache** [comment]
IIRC we just couldn't think of any config values that would influence the way the mock consumer actually behaved in practice when we wrote it. It's quite possible we've added some since then. Which ones in particular are you thinking of?

**Comment by kchristidis** [comment]
I'm writing a unit test where it would be extremely helpful for me to set `ChannelBufferSize` to `0` to make it the `pc.messages` channel unbuffered.

**Comment by eapache** [comment]
That is already respected: https://github.com/Shopify/sarama/blob/61ca52d100f625ec7d4762c8ea0dda195cd035f1/mocks/consumer.go#L99 I think the documentation might just be out of date.

**Comment by kchristidis** [comment]
But this is reading the config object that is created internally [here](https://github.com/Shopify/sarama/blob/61ca52d100f625ec7d4762c8ea0dda195cd035f1/mocks/consumer.go#L24) right? So I don't have a means to edit it. Am I missing something?

**Comment by eapache** [comment]
That's only created if the config you pass in as an argument is nil. If you pass in a valid config it will use that instead.

**Comment by kchristidis** [comment]
Ugh, I am obviously blind. Thanks for this — and the quick response.

**Comment by kchristidis** [comment]
(Will update the documentation with a patch.)

**Comment by kchristidis** [comment]
See: https://github.com/Shopify/sarama/pull/891
