### ISSUE TITLE
Is there a way to set linger.ms for kafka version 0.10.x in producer?

### ISSUE THREAD

**Issue by isethi** [Shopify/sarama#893]
##### Versions

Kafka Version: 0.10.1
Go Version: 1.8.3

##### Problem Description

Is there a way to set linger.ms for producer in the configs?

**Comment by eapache** [comment]
The config value `Producer.Flush.Frequency` is close enough, though not exactly the same.

**Comment by isethi** [comment]
Here it says  // The best-effort frequency of flushes. Equivalent to
            // `queue.buffering.max.ms` setting of JVM producer.
            Frequency time.Duration

but queue.buffering.max.ms doesnt exist in 0.10.0 . how is it different from linger.ms?

**Comment by eapache** [comment]
How is `queue.buffering.max.ms` different from `linger.ms`? I don't know exactly, you'd have ask upstream what they changed.
