### ISSUE TITLE
Needed kafka consumer code with ssl support

### ISSUE THREAD

**Issue by binups** [Shopify/sarama#894]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:
Kafka Version:
Go Version:

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
                       I 
                                      I need proper kafka consumer go  code with ssl support , i not able to find any proper kafka consumer code with ssl support

**Comment by eapache** [comment]
The consumer (https://godoc.org/github.com/Shopify/sarama#Consumer) takes a configuration value (https://godoc.org/github.com/Shopify/sarama#Config). `Config.Net.TLS` can be used to set up SSL/TLS connections.
