### ISSUE TITLE
Reading gRPC stream data in Kafka Producer

### ISSUE THREAD

**Issue by mohigup** [Shopify/sarama#896]
##### Versions

Sarama Version: 1.12.0 
Kafka Version: 0.10.2.1
Go Version: 1.8

##### Problem Description

I want to use Shopify sarama for Kafka implementation and integrate gRPC with it.
My query is that it is possible to open a gRPC server channel and read streams of data passed from a gRPC client in the Kafka Producer. 
Please help

**Comment by wvanbergen** [comment]
Kafka allows any kind of byte array to be used as messages. So it should be possible to build any data format on top of it, as long as you can think of it as a stream of messages.

I am not too aware of the specifics of gRPC, and it's out of scope for this project to support it.
