### ISSUE TITLE
Multiple Consumer Groups with Failure Recovery

### ISSUE THREAD

**Issue by mohigup** [Shopify/sarama#898]
Question

Versions

Sarama Version: 1.12.0
Kafka Version: 0.10.2.1
Go Version: 1.8

Problem Description

I am looking to use Sarama Library for Kafka and wanted to know if the current version supports consuming the same data in different multiple consumer groups with [failure recovery](https://svds.com/kafka-simple-consumer-failure-recovery/).
 Each consumer group receives a copy of data.

**Comment by eapache** [comment]
https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#how-can-i-use-sarama-to-join-a-consumer-group
