### ISSUE TITLE
Companies using Kafka

### ISSUE THREAD

**Issue by mohigup** [Shopify/sarama#899]
Question

Versions

Sarama Version: 1.12.0
Kafka Version: 0.10.2.1
Go Version: 1.8

Problem Description

I want to use Kafka for a project and about to pitch for Shopify Sarama use. It will be helpful if the list of companies using sarama could be provided.

**Comment by erikdubbelboer** [comment]
We at https://www.atomx.com/ are using Sarama on multiple servers to push thousands of messages to Kafka and to consume them at the other end. We use multiple topics with multiple partitions.

**Comment by mohigup** [comment]
@erikdubbelboer Thanks for the Info. I was hoping if the repo contributor had more information.

**Comment by eapache** [comment]
We still use Sarama quite heavily within Shopify. Other than that, I know a couple of companies which I suspect are using Sarama, but I don't have explicit confirmation from any of them.

**Comment by tcrayford** [comment]
Heroku uses sarama for its production systems in multiple places

**Comment by mohigup** [comment]
Thanks @tcrayford. @eapache If you comfortable in sharing the information, it would be great and help in gathering more votes. Thanks again for responding back.

**Comment by eapache** [comment]
VividCortex said they used Sarama, at least back in 2015: https://www.vividcortex.com/blog/2015/02/11/compressed-messages-using-kafka/

Also, I know that employees of IBM, HP, and Cisco have all contributed pull requests at one time or another: that's not proof that Sarama is being used by those companies, but it's a clue at least.

**Comment by potocnyj** [comment]
> VividCortex said they used Sarama, at least back in 2015: 

Can confirm, we use kafka fairly extensively in our backend and Sarama is the driver we use for all of our applications 👍

**Comment by mohigup** [comment]
Thanks everyone. I did find another article where **Movio** talks about usage of Sarama
https://movio.co/en/blog/Kasper-process-library/

**Comment by kchristidis** [comment]
Can confirm that IBM is using Sarama as well.

**Comment by mohigup** [comment]
thanks @kchristidis

**Comment by eapache** [comment]
@erikdubbelboer @tcrayford @potocnyj @kchristidis with your permission I will add your companies to https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#is-sarama-used-in-production-anywhere

**Comment by tcrayford** [comment]
@eapache fine by me

**Comment by potocnyj** [comment]
@eapache no objections here 👍

**Comment by jurriaan** [comment]
We at Blendle use Sarama quite extensively too (mostly stream processing).

**Comment by erikdubbelboer** [comment]
@eapache 👍

**Comment by rsrsps** [comment]
we use it here at skyport systems, fwiw.

**Comment by kchristidis** [comment]
@eapache: Sure thing.

**Comment by eapache** [comment]
Thanks all :)
