### ISSUE TITLE
Example for offset management using sarama

### ISSUE THREAD

**Issue by gauravsb** [Shopify/sarama#902]
##### Versions

Sarama Version: Latest
Kafka Version: 0.9.0.1 
Go Version: go1.8.3

##### Problem Description

Sorry, this might not be the place to post this. I am new to golang and sarama. I am able to consume properly from sarama, however it seems that I have to manage offset manually in sarama. 

I couldn't find any good example of offset management with sarama. Would be helpful if someone could share example with offset management in sarama. I want to start reading after my last processed offset every time the application starts

I know that https://github.com/bsm/sarama-cluster does that. But I would like to know how to do it sarama using _OffsetManager_ or sth else

Thanks

**Comment by eapache** [comment]
Sarama's built-in offset management is pretty basic, because sarama-cluster does such a better job that it's never been worth it to build an alternative. Your options are basically to use sarama-cluster, or to do it entirely manually.

**Comment by gauravsb** [comment]
okay. sarama-cluster is working fine for me as of now. It would be great if you can add similar support in this repo so that it becomes a one stop solution for kafka with golang
