### ISSUE TITLE
Default Value for offsets.retention.minutes

### ISSUE THREAD

**Issue by mohigup** [Shopify/sarama#904]
**Question**

**Versions**

Sarama Version: 1.12.0
Kafka Version: 0.10.2.1
Go Version: 1.8

**Problem Description**

As per the go sarama documentation, `offsets.retention.minutes` is configured as follows:

> If zero, disabled (in which case the offsets.retention.minutes option on the
> broker will be used). Kafka only supports precision up to milliseconds; nanoseconds will be truncated. Requires Kafka broker version 0.9.0 or later.
> (default is 0: disabled).

Now the Kafka documentation says that log retention window in minutes for offsets topic is set to 1440.
Does it means that if the default value is 0 in Sarama, then it will be 1440 minutes as defined by Kafka broker?

There was a comment in of the issues on [sarama-cluster](https://github.com/bsm/sarama-cluster/issues/87) which looks contradictory to the values stated in sarama documentation.

> So I am not 100% sure the above is correct, but that's something you need to bring up with the Sarama maintainers. According to Kafka's documentation, you need to set the setting to -1 to disable it (= persist indefinitely), while 0 is a valid setting (= expire immediately).

Please clarify.

**Comment by eapache** [comment]
I honestly don't remember, but I suspect I was referring to the code in Sarama's offset manager which locally checks for the value to be 0 or not (in method `constructRequest`). Sarama-cluster doesn't use this code AFAICT so it's probably totally irrelevant.

> Does it means that if the default value is 0 in Sarama, then it will be 1440 minutes as defined by Kafka broker?

If you're using sarama's `OffsetManager` then I think so. If you're using sarama-cluster then it really depends what that library does with the value.

**Comment by mohigup** [comment]
@eapache I see that sarama-cluster Config extends sarama.Config.

[github](https://github.com/bsm/sarama-cluster/blob/master/config.go#L13)
```
// Config extends sarama.Config with Group specific namespace
type Config struct {
```
@dim please confirm

**Comment by dim** [comment]
By default, the retention time on the [OffsetCommitRequest](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetCommitRequest) is `-1` unless configured otherwise, see [here](https://github.com/bsm/sarama-cluster/blob/55a2be7071a78ba5700a94d8452e4d2aa6860e20/consumer.go#L149) and [here](https://github.com/bsm/sarama-cluster/blob/55a2be7071a78ba5700a94d8452e4d2aa6860e20/consumer.go#L152)

**Comment by mohigup** [comment]
Thanks @dim.
So, if I set retention time using following code, it will reflect changes in offset retention time and override the default retention time?

```
config := cluster.NewConfig()
config.Consumer.Offsets.Retention.Minutes=5
// message consumed
consumer.MarkOffset(msg, "")
```

**Comment by dim** [comment]
It's `config.Consumer.Offsets.Retention = 5*time.Minute`, but yes: https://github.com/Shopify/sarama/blob/master/config.go#L222

**Comment by mohigup** [comment]
Thanks @dim 🎉
