### ISSUE TITLE
Does sarama going to support the Admin client supported by kafka ?

### ISSUE THREAD

**Issue by chandradeepak** [Shopify/sarama#908]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:Version 1.11.0
Kafka Version: 0.10.1
Go Version: 1.8

##### Configuration
Default

What configuration values are you using for Sarama and Kafka?
Default
##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

Does sarama going to support the Admin client supported by kafka ?

it has all the operation to do create and delete topics which is the way to go forward.

[Admin client](https://cwiki.apache.org/confluence/display/KAFKA/KIP-117%3A+Add+a+public+AdminClient+API+for+Kafka+admin+operations
)

**Comment by eapache** [comment]
It seems like something that might be worth building as a separate project on top of sarama, similar to how sarama-cluster adds consumer group balancing? I'm not necessarily opposed to adding it to sarama either, but I don't have time to work on it myself.

**Comment by chandradeepak** [comment]
it says some thing about the [KPI 4 wire protocols](https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations)  is sarama also built like that ?

we have to implement a similar api for admin as well . can you point me to some references or documentation where i can get started for this feature .

**Comment by eapache** [comment]
KIP-4 wire protocols are similar to the normal protocol but include some additions (nullability, booleans). Sarama does not currently support them, but it would probably be easier to extend it than to build them from scratch.

The pending PR does look related.
