### ISSUE TITLE
partition consumer shutdown because the requested offset is out of range

### ISSUE THREAD

**Issue by simon-xia** [Shopify/sarama#910]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: Version 1.12.0
Kafka Version: 2.11-0.10.0.0
Go Version: 1.8

##### Configuration

What configuration values are you using for Sarama and Kafka?
default config

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

[Sarama] 2017/07/06 16:03:16 kafka: error while consuming userlog/13: kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
[Sarama] 2017/07/06 16:03:16 consumer/userlog/13 shutting down because kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.

##### Problem Description

some partition consumer shut down, while running

**Comment by eapache** [comment]
The offset can fall out of range for a number of different reasons. The fact that Sarama shuts down in this case is intentional, as it is now up to the caller to decide whether to restart consuming at a different offset or to alert a human.

**Comment by simon-xia** [comment]
so is there a [`auto.offset.reset`](http://kafka.apache.org/documentation.html#consumerconfigs) config in consumer?  @eapache

**Comment by eapache** [comment]
No. Any of those behaviours can be created by simply restarting the PartitionConsumer in the desired state when it closes due to an offset error.
