### ISSUE TITLE
Assistance in Consumer Group/Lag Reporting

### ISSUE THREAD

**Issue by jbkc85** [Shopify/sarama#914]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1.12.0 (2017-05-08)
Kafka Version: 0.10.2.0
Go Version: 1.8.3 (darwin)

##### Configuration

config.Version = sarama.V0_10_2_0

##### Logs

N/A

##### Problem Description

Wondering if anyone has a live example, and or a link describing the necessary steps to monitor a consumer/consumer group (old and new) offsets and lag.  I have been unable to get Meta from consumer groups or consumers connected in my Kafka cluster that has similar output to the ```./kafka-consumer-groups.sh --bootstrap-server localhost:9092 --describe --group``` command.  Since I am fairly new to Kafka et al, was wondering if anyone could assist me in pointing me in the right direction!

Thanks in advance.

**Comment by eapache** [comment]
Monitoring is slightly different from joining, but the answer from https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#how-can-i-use-sarama-to-join-a-consumer-group still applies.
