### ISSUE TITLE
Example of how to access consumer and producer metrics?

### ISSUE THREAD

**Issue by joelpresence** [Shopify/sarama#915]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 2fd980e23bdcbb8edeb78fc704de0c39a6567ffc
Kafka Version: 0.10.2.1
Go Version: 1.8.3

##### Configuration

What configuration values are you using for Sarama and Kafka?

Heroku kafka

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

How do I access and log the consumer and producer metrics mentioned near the top of https://godoc.org/github.com/Shopify/sarama ?  I can see the list of metric names but no examples of how to actually grab them off of some Sarama code.  I see the metric registry on the consumer, but how to use it and how to access producer metrics from it?

A short code example would be super helpful.

Could somebody please help?  I'd be happy to add it to the README later if that would help.

Thanks!

**Comment by eapache** [comment]
We use https://github.com/rcrowley/go-metrics so all of the documentation for dealing with the registry is there. There is a very basic example at https://godoc.org/github.com/Shopify/sarama#example-Config--Metrics.

**Comment by joelpresence** [comment]
Hi @eapache , thanks for responding!  I had already seen those config examples, but to be honest, they didn't help me.  I'm not looking for example gauges like `m1` but rather the actual Kafka metrics.  I don't see how to access values like the following:
```
metricName := "record-send-rate"
metricValue := ... // How do I get this
fmt.Printf("%v=%v\n", metricName, metricValue)
```
For all of the metric names in the table at https://godoc.org/github.com/Shopify/sarama, how would I actually log and view and print the values?
```
// Access these values how?
+----------------------------------------------+------------+---------------------------------------------------------------+
| Name                                         | Type       | Description                                                   |
+----------------------------------------------+------------+---------------------------------------------------------------+
| incoming-byte-rate                           | meter      | Bytes/second read off all brokers                             |
| incoming-byte-rate-for-broker-<broker-id>    | meter      | Bytes/second read off a given broker                          |
| outgoing-byte-rate                           | meter      | Bytes/second written off all brokers                          |
| outgoing-byte-rate-for-broker-<broker-id>    | meter      | Bytes/second written off a given broker                       |
| request-rate                                 | meter      | Requests/second sent to all brokers                           |
| request-rate-for-broker-<broker-id>          | meter      | Requests/second sent to a given broker                        |
| request-size                                 | histogram  | Distribution of the request size in bytes for all brokers     |
| request-size-for-broker-<broker-id>          | histogram  | Distribution of the request size in bytes for a given broker  |
| request-latency-in-ms                        | histogram  | Distribution of the request latency in ms for all brokers     |
| request-latency-in-ms-for-broker-<broker-id> | histogram  | Distribution of the request latency in ms for a given broker  |
| response-rate                                | meter      | Responses/second received from all brokers                    |
| response-rate-for-broker-<broker-id>         | meter      | Responses/second received from a given broker                 |
| response-size                                | histogram  | Distribution of the response size in bytes for all brokers    |
| response-size-for-broker-<broker-id>         | histogram  | Distribution of the response size in bytes for a given broker |
+----------------------------------------------+------------+---------------------------------------------------------------+
```

Sorry, I realize this might come across as snarky or whiny and that is totally not my intent.  I'm very grateful for you releasing this awesome library.  I'm just frustrated.  :-)  I'm not looking for config, just a tip on how to access the value of the metric `record-send-rate` and the metric `request-latency-in-ms` and print them using `Printf`.  Could you provide that example please?

Or is it something as simple as:
```
metricValue := config.MetricRegistry.Get("record-send-rate")
```
I'd be happy to submit a PR adding this example if I can get it to work and there's interest.

Thanks again and take care!

**Comment by joelpresence** [comment]
OK, I got it working but I'll submit a PR with some added godoc to enhance your example to make it easier for others.  Would that be OK?

**Comment by eapache** [comment]
Doc improvements are always welcome!

Although I believe it's the go-metrics API you'd use for accessing the metrics, so it's probably there that the docs should live?

**Comment by joelpresence** [comment]
Thanks @eapache .  Well, the issue for me was that I didn't know about nor did I care about go-metrics or its API.  I'm here just to use Sarama and Kafka.  So as a Sarama user I don't care how or where it collects its metrics, only that it does collect metrics and that I can easily access them.  Given that Saram already documents the metrics registry usage vs its own config, I'd like to add it to that example.  If my PR doesn't feel right, that's OK.  :-)

I'll try to update this later today with a PR.  Thanks again!

**Comment by pradeepkusingh** [comment]
@joelpresence  I am also looking for same details. Can you please post here?

**Comment by Smriti-OSS** [comment]
@joelpresence @pradeepkusingh Were you able to document the examples for the metrics? I am looking for the same details.

**Comment by raxit65535** [comment]
@joelpresence @pradeepkusingh  @Smriti-OSS  if you were able to document the examples of how to view metrics can you share some updates.

**Comment by sayan1886** [comment]
Periodically log every metric in human-readable form to standard error:

`go metrics.Log(metrics.DefaultRegistry, 5 * time.Second, log.New(os.Stderr, "metrics: ", log.Lmicroseconds))`

Periodically log every metric in slightly-more-parseable form to syslog:

```
w, _ := syslog.Dial("unixgram", "/dev/log", syslog.LOG_INFO, "metrics")
go metrics.Syslog(metrics.DefaultRegistry, 60e9, w)
```

you have to use the local registry where Sarama pushes the metrics, i.e `saramaConfig.MetricRegistry`

get all metrics in a `map` 

`allMetrices := registry.GetAll()`
