### ISSUE TITLE
Could the usage of compress package be optimized?

### ISSUE THREAD

**Issue by kof02guy** [Shopify/sarama#916]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: Version 1.12.0
Kafka Version: 0.10.2.1
Go Version: 1.7.5

##### Configuration

What configuration values are you using for Sarama and Kafka?
I use GZIPCompression as the compression type

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
I noticed that in the encode() method, each time a new var bytes.Buffer is initialized, which does contribute a lot of performance overload in my test. Is it possible to use a unique bytes.Buffer for each goroutine and just Reset() the buffer before each invocation of encode() when the compression is enabled?

**Comment by eapache** [comment]
There is potentially room to optimize this, but it wouldn't be simple because of the two-pass nature of the encoding and the use of `compressedCache`.

**Comment by kof02guy** [comment]
I encountered this in another project of mine and I've optimized this, which will bring about 40% performance increase.
I advice to optimize this, because this lies absolutely in the critical path of the overall processing of kafka read and write.

**Comment by eapache** [comment]
If you have an optimized version already then I would be happy to accept a pull request.

**Comment by kof02guy** [comment]
No I mean that I've encountered this problem in another project not using sarama and I use Reset() instead of initialize a new bytes.Buffer each time and the performance increases. When I profiled the project using sarama I found this issue
