### ISSUE TITLE
Questions about consumer group offset

### ISSUE THREAD

**Issue by se0wtf** [Shopify/sarama#918]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1
Kafka Version: 0.10.1.1
Go Version: 1.8

##### Configuration

What configuration values are you using for Sarama and Kafka?
default

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

Q1:
When i request the offset from a consumer group (see following code), the request takes about **20s**. Its seems really long, do you know if it's normal ?
```golang
request := sarama.OffsetFetchRequest{ConsumerGroup: groupName, Version: 1}
r, err := b.FetchOffset(&request)
```

Q2:
I'm trying to use the API  GetAvailableOffset but the response is always empty. In my comprehension, i should get back a list of all groups and topics/offset associated. Is it normal ?
```golang
request := sarama.OffsetRequest{Version:1}
for _, b := range Brokers {
	r, err := b.GetAvailableOffsets(&request)
	if err != nil {
		glog.Fatal("Unable to retreive offset ",err)
	}
	glog.Info("Offsets: ", r)
}
```
The response is `I0725 11:08:27.410419    9649 kafka.go:108] Offsets: &{0 map[]}`

Thanks guys !

**Comment by eapache** [comment]
> When i request the offset from a consumer group (see following code), the request takes about 20s.

That is not normal. One thing I notice is that in your example code you are not calling `AddPartition` on the request, so it is not actually requesting any specific topic or partition? If kafka is returning *all* partitions in this case that could take some time which might explain the slowness.

> I'm trying to use the API GetAvailableOffset but the response is always empty. In my comprehension, i should get back a list of all groups and topics/offset associated. Is it normal ?

Again, because you're not adding any partitions to the request I don't think you'll get anything back?
