### ISSUE TITLE
Consumer question

### ISSUE THREAD

**Issue by DoraDreams** [Shopify/sarama#919]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: V1
Kafka Version: 0.10.1.1
Go Version: 1.8

##### Configuration

What configuration values are you using for Sarama and Kafka?
default

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

I only want to consumer messages from special topic, and close that consumer, which means that it should not receive message continuously. So how can i to achieve that

**Comment by eapache** [comment]
> I only want to consumer messages from special topic

Consuming from a specific topic is a core part of the API, please see the documentation at https://godoc.org/github.com/Shopify/sarama#Consumer.

> close that consumer, which means that it should not receive message continuously

https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#how-do-i-consume-until-the-end-of-a-partition

**Comment by DoraDreams** [comment]
Thanks for your answer, I have another question. Is there any way for us to make value as a struct value?

**Comment by eapache** [comment]
Sarama only provides message values as bytes, but whatever logic you use in your encoder to convert it to bytes when producing can presumably be inverted to regenerate the struct in your consumer. That logic is up to you.
