### ISSUE TITLE
Question on partitionConsumer Close() draining messages

### ISSUE THREAD

**Issue by sp1ff** [Shopify/sarama#920]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.12
Kafka Version: *
Go Version: 1.8

##### Configuration

What configuration values are you using for Sarama and Kafka? Defaults

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

N/A

##### Problem Description

Really more of a question-- here is the beginning of partitionConsumer's Close() method:

    func (child *partitionConsumer) Close() error {
        child.AsyncClose()

        go withRecover(func() {
            for range child.messages {
                // drain
            }
        }) <=========

AsyncClose will begin the process of shutting down the partitionConsumer, but as the name implies, it does so asynchronously.  I guess the most common usage idiom for the user of partitionConsumer would be something like this:

    for msg := range pc.Messages() {
       // Do stuff...
    }
    // Wind up here when pc.Close() eventually closes the channel

So when Close() is at the line I've marked "<======", we have two goroutines reading the same (buffered) channel. The anonymous function is, in effect, stealing my messages from me. If, at the moment that anonymous function is spawned, the channel buffer contains three Kafka messages {M0, M1, M2}, it's possible that my client will get & process M0 & M2, while the anonymous function will drain M1.

Does my description of the issue make sense?  Check me: maybe I'm missing something, here, but it seems to me that if my partition consumer is keeping track of the offsets it's processed, it now has to be very careful to keep track of any "skips" in the message stream.

**Comment by eapache** [comment]
`AsyncClose()` is a public method, so you can just call it yourself instead of `Close()`.

**Comment by sp1ff** [comment]
Ahhhhhhhhh... is the intent that one calls AsyncClose() if one is still reading the Messages() channel, and Close() if one is done? That makes sense, but was not at all clear to me from the docs.

**Comment by eapache** [comment]
Ya, `AsyncClose` is really the more useful/common method for most cases, `Close` just wraps it to provide a synchronous version (which can be helpful in some circumstances) and implement https://golang.org/pkg/io/#Closer.

**Comment by eapache** [comment]
Any suggestions on how to improve the docs?

**Comment by sp1ff** [comment]
Sure-- let me put together a proposed change to the docstrings' verbiage & open a pull request.

**Comment by sp1ff** [comment]
PR [here](https://github.com/Shopify/sarama/pull/927)-- let me know what you think.
