### ISSUE TITLE
Is there any chance that one written message triggers more than one succeeded

### ISSUE THREAD

**Issue by kof02guy** [Shopify/sarama#922]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 0.10
Kafka Version: 0.10.2.1
Go Version: 1.75

##### Configuration

What configuration values are you using for Sarama and Kafka?
Sarama using gzip compression
kafka with 4 brokers and 2 replicas

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
**This is the method used to append record to kafka, which will be invoked by multiple goroutines.** 

```
func (st *msgStatus) IncAppended() {
    atomic.AddInt32(&st.appendedMsg, 1)
}
func (p *KafkaProducer) AppendRecord(msg *sarama.ProducerMessage) {
    if nil != msg {
        p.producer.Input() <- msg
        key, err := msg.Key.Encode()
        if nil != err {
            LogError(FAIL_MAJOR, KAFKA, "Get id from producer message failed:%v", err)
            return
        }
        id := HashUserID(key) % p.hashSize
        p.msgStatus[id].IncAppended()
        //LogDebug("Msg Appended Key:%s HashId:%d AppendedNum:%d", string(key), id, p.msgStatus[id].GetAppended())
    }
}

```
**And this is the goroutine looping to process the responses**
```
func (p *KafkaProducer) Start() {
    go func() {
        defer RecoverFunc()
        LogInfo("Enter Kafka producer Start. Topic:%s", p.topic)
        defer LogInfo("End Kafka producer Start. Topic:%s", p.topic)
        for {
            select {
            case err := <-p.producer.Errors():
                UpdateMonitor(KAFKA_WRITE_FAIL_COUNT, 1)
                key, err1 := err.Msg.Key.Encode()
                if nil != err1 {
                    LogError(FAIL_MAJOR, KAFKA, "Get id from producer message failed:%v", err1)
                    continue
                }
                id := HashUserID(key) % p.hashSize
                p.msgStatus[id].IncFailed()
                p.msgMutex.Lock()
                p.errorMsgs[id] = append(p.errorMsgs[id], err.Msg)
                p.msgMutex.Unlock()
                LogError(FAIL_MAJOR, KAFKA, "Failed to write record to Kafka. topic:%s, msg:%v, err:%v", p.topic, err.Msg, err.Err)
                if nil != err {
                    UpdateMonitor(KAFKA_WRITE_FAIL_COUNT, 1)
                }
            case msg := <-p.producer.Successes():
                key, err := msg.Key.Encode()
                if nil != err {
                    LogError(FAIL_MAJOR, KAFKA, "Get id from producer message failed:%v", err)
                    continue
                }
                id := HashUserID(key) % p.hashSize
                p.msgStatus[id].IncSucceeded()
                //LogDebug("Msg Succeeded Key:%s HashId:%d SucceededNum:%d Topic:%s Partition:%d Offset:%d", string(key), id, p.msgStatus[id].GetSucceeded(), p.topic, msg.Partition, msg.Offset)
                UpdateMonitor(KAFKA_WRITE, GetKafkaProducerMessageLen(msg))
            case <-p.exitCh:
                p.exitChRes <- true
                return
            }
        }
    }()
}
```

**After 10000 appended records, I'll CheckCompleted to make sure that the records all succeeded of failed.**

```
func (p *KafkaProducer) CheckCompleted(id uint32) bool {
    appended := p.msgStatus[id].GetAppended()
    if id < p.hashSize &&
        appended > 0 &&
        appended = p.msgStatus[id].GetSucceeded()+p.msgStatus[id].GetFailed() ||
        0 == appended {
        return true
    }
    //LogDebug("ID:%d Appended:%d Succeeded:%d Failed:%d", id, p.msgStatus[id].GetAppended(), p.msgStatus[id].GetSucceeded(), p.msgStatus[id].GetFailed())
    return false
}
```

But Sometimes CheckComplete() returns false because **append < succeeded + failed, where failed == 0.** So I wonder if there's any chance or any situation which will cause this issue.

**Comment by eapache** [comment]
For one thing, on the line `appended = p.msgStatus[id].GetSucceeded()+p.msgStatus[id].GetFailed()` I'm assuming that should be a `==`.

I'm also assuming (since they're not shown) that `IncSucceeded`, `IncFailed`, `GetSucceeded`, and `GetFailed` use the appropriate atomic int methods.

> append < succeeded + failed, where failed == 0

One possible explanation is that `AppendRecord` is sending the message but not calling `IncAppended`, which I see can happen if the message does not have an encodable key?

Or perhaps the key encoding function is not pure, and so it's ending up in a different bucket sometimes when it is returned from sarama?

> So I wonder if there's any chance or any situation which will cause this issue.

No situation in Sarama should cause this; if it is really happening then it's a bug.

**Comment by eapache** [comment]
Closing as stale. Please reopen if you have more information showing this is an actual bug.
