### ISSUE TITLE
committed offset turn to -1 after receiving "The requested offset is outside the range of offsets maintained by the server for the given topic/partition"

### ISSUE THREAD

**Issue by kof02guy** [Shopify/sarama#925]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.12.0
Kafka Version: 0.10.1.2
Go Version: 1.7.5

##### Configuration

What configuration values are you using for Sarama and Kafka?
kafka client config:
```
config := cluster.NewConfig()
    //each asynchronous message sent by producer will have a
    //feedback response
    config.Producer.Return.Successes = true
    config.Producer.Return.Errors = true
    //all replicas must be written successfully before a message
    //is assumed succeeded
    config.Producer.RequiredAcks = sarama.WaitForAll
    //The retry times before a write is reported as failed
    config.Producer.Retry.Max = KAFKA_MAX_WRITE_RETRY
    config.Producer.Partitioner = sarama.NewHashPartitioner
    config.Producer.Compression = sarama.CompressionGZIP
    config.Consumer.Return.Errors = true
    //The initial offset should be set to the oldest
    //because if we set it to OffsetNewest and
    //there's no offset commit for a partition
    //there may be kafka messages consumed but not ingested because
    //of possible failures during ingestion
    config.Consumer.Offsets.Initial = sarama.OffsetOldest
    //config.Consumer.Offsets.Retention = 100 * 24 * 3600 * 1000 //keep the committed offset 100 days of topic __consume_offsets
    config.Group.Return.Notifications = true
    config.ClientID = KAFKA_CLIENT_ID
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.
**Error occurs when consuming message:kafka: error while consuming fw_audience_csv/14: kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.**

##### Problem Description
after receiving this error:
`Error occurs when consuming message:kafka: error while consuming fw_audience_csv/14: kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.`

The committed offset got from kafka is -1:
        Partition:0 Offset:-1
        Partition:1 Offset:8086507970
        Partition:2 Offset:-1
        Partition:3 Offset:8079132564
        Partition:4 Offset:8069433372
        Partition:5 Offset:-1
        Partition:6 Offset:-1
        Partition:7 Offset:-1
        Partition:8 Offset:8056641911
        Partition:9 Offset:8054427975
        Partition:10 Offset:-1
        Partition:11 Offset:8088913458
        Partition:12 Offset:8085295440
        Partition:13 Offset:8061676231
        Partition:14 Offset:-1
        Partition:15 Offset:8051648270

The -1 committed offsets' related partitions all raised the error log.
But in our kafka manager, the offset it not -1

Do you have any suggestions? I'm quite confused about this.

**Comment by eapache** [comment]
Are you using `sarama-cluster`? This looks like it might be an issue with that library? Have you talked to them?

**Comment by kof02guy** [comment]
OK I'll consult them. Thanks a  lot
