### ISSUE TITLE
client.InSyncReplicas returns ErrReplicaNotAvailable with nil data when only few brokers are down

### ISSUE THREAD

**Issue by ruoshan** [Shopify/sarama#929]
##### Versions
Sarama Version: 2fd980e23bdcbb8edeb78fc704de0c39a6567ffc

##### Problem Description
client.InSyncReplicas returns ErrReplicaNotAvailable with nil data when only few brokers are down, but there are actually some ISR to be returned. We could still make use of the ISR of alive brokers.

Can client.InSyncReplicas return partial ISR info with ErrReplicaNotAvailable together?

**Comment by eapache** [comment]
This seems reasonable to me. @funkygao you added that check originally, did you have a specific reason for it?

**Comment by ruoshan** [comment]
any updates? @funkygao
