### ISSUE TITLE
support Authentication using SASL/Kerberos

### ISSUE THREAD

**Issue by thao6626** [Shopify/sarama#934]
Hi, i find sarama supports SASL/PLAINTEXT authentication, but i do not find SASL/keberos authentication introduced in Apache kafka document.

`// SASL based authentication with broker. While there are multiple SASL authentication methods
// the current implementation is limited to plaintext (SASL/PLAIN) authentication
`
Will the keberos authentication be supported in the future??

thanks !!!

**Comment by eapache** [comment]
We have no immediate plans to add Kerberos support as we do not need it ourselves. We would be happy to accept a pull request though (we had one previous one - #729 - but it had some unresolved issues).
