### ISSUE TITLE
sarama data race using byte slice after sync_producer.SendMessage

### ISSUE THREAD

**Issue by Kane-Sendgrid** [Shopify/sarama#935]
##### Versions
Sarama Version: Version 1.11.0 (2016-12-20)
Kafka Version: 0.10.2
Go Version: 1.8.3

##### Problem Description
We have a problem with data race when using byte slice passed to sync_producer.SendMessage after SendMessage returned
```
Previous read at 0x00c4205ee000 by goroutine 98:
--
  runtime.slicecopy()
      /usr/local/go/src/runtime/slice.go:160 +0x0
  github.com/vendor/github.com/Shopify/sarama.(*realEncoder).putBytes()
      /opt/go/src/github.com/vendor/github.com/Shopify/sarama/real_encoder.go:57 +0x284
  github.com/vendor/github.com/Shopify/sarama.(*Message).encode()
      /opt/go/src/github.com/vendor/github.com/Shopify/sarama/message.go:99 +0x2b7
  github.com/vendor/github.com/Shopify/sarama.(*MessageBlock).encode()
      /opt/go/src/github.com/vendor/github.com/Shopify/sarama/message_set.go:20 +0xf8
  github.com/vendor/github.com/Shopify/sarama.(*MessageSet).encode()
      /opt/go/src/github.com/vendor/github.com/Shopify/sarama/message_set.go:55 +0xdb
  github.com/vendor/github.com/Shopify/sarama.encode()
      /opt/go/src/github.com/vendor/github.com/Shopify/sarama/encoder_decoder.go:35 +0x3e0
  github.com/vendor/github.com/Shopify/sarama.(*produceSet).buildRequest()
```

It seems that sarama might return an early error, while still trying to send message to kafka. That might create data race if byte slice is reused after .SendMessage returned.

**Comment by eapache** [comment]
> It seems that sarama might return an early error, while still trying to send message to kafka.

I don't see an obvious way for this to happen. We always `return` or `continue` or whatever immediately after feeding a message back out on the error channel. I suppose it's possible this is a really subtle bug I can't see, but I'm wondering also if this is a false positive in the race detector.

**Comment by Kane-Sendgrid** [comment]
```
	msg.Metadata = expectation
	sp.producer.Input() <- msg

	if err := <-expectation; err != nil {
		return -1, -1, err.Err
	}
```

I have problems tracking all places where message it sent to expectation channel.
I don't think it's possible to have false positive in race detector, also this data race happened only once during couple of months. Does sarama have internal breaker timeouts? We've experienced data races before when some other timer/timeout hits before network timeouts, leaving goroutine running while error is already pushed back.

**Comment by eapache** [comment]
> I have problems tracking all places where error is sent to expectation channel.

The expectation channel is only written to in `handleSuccesses` and `handleErrors` on the sync producer, which is only when the underlying async producer returns the message.

> Does sarama have internal breaker timeouts? We've experienced data races before when some other timer/timeout hits before network timeouts, leaving goroutine running while error is already pushed back.

Sarama does use internal circuit-breakers, but never to interrupt an in-flight request, only to prevent requests from starting in the first place. The only timeout we set on the network operation is the network-layer timeout, and if that fires then there should never be any response because the socket will close.

Do you have any logs from Sarama around the time of the issue?

**Comment by Kane-Sendgrid** [comment]
Unfortunately sarama logs were not enabled. It seems it could be related to retries somehow. How retries are handled inside sarama?

>

**Comment by eapache** [comment]
Retries are complicated because Sarama must preserve message order. The process is described fairly thoroughly at https://github.com/Shopify/sarama/wiki/Producer-implementation.

**Comment by eapache** [comment]
Have you been able to reproduce this at all or was it a one-time thing?

**Comment by Kane-Sendgrid** [comment]
It never happened again (it happened only once in a couple of months so far). If there is some bug then it is cause by very rare condition. We are planning to create a test environment for our app to try to reproduce it, it gonna take some time though.

**Comment by eapache** [comment]
Please re-open if you ever see this again or have any ideas how to reproduce.
