### ISSUE TITLE
Message.decode should not use ioutil.ReadAll

### ISSUE THREAD

**Issue by hasnickl** [Shopify/sarama#936]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.8.0 (4ba9bba6adb6697bcec3841e1ecdfecf5227c3b9)
Kafka Version: 0.10.1.0
Go Version: 1.6

##### Problem Description

Certain configurations hit a codepath in message decoding that uses `ioutil.ReadAll()` ([Message#L172](https://github.com/Shopify/sarama/blob/master/message.go#L172)) ([Message#L193](https://github.com/Shopify/sarama/blob/master/message.go#L193)). This is problematic in high performance situations with large enough messages, because internally `ioutil.ReadAll()` reads data out into a buffer that it grows as needed. 

In the internal `bytes.Buffer`, growing is done via calls to `bytes.makeSlice`. See the attached screenshot for my memory profiling. Allocating new slices takes up about 65% of my memory footprint, and I think this code path has room for optimization.

My first thought is to create a right-sized buffer to read into instead of using `ioutil.ReadAll`

![screen shot 2017-08-22 at 11 00 52 am](https://user-images.githubusercontent.com/11505152/29575499-4f85fe28-872a-11e7-84d9-f8550c9f57f4.png)

**Comment by eapache** [comment]
> My first thought is to create a right-sized buffer to read into instead of using ioutil.ReadAll

As far as I know there is no way to determine what the right size is in advance, as it is not exposed in the Kafka wire protocol or in the gzip format.

For the LZ4 case it seems like it might be possible, but handling concatenate streams correctly sounds complicated (https://godoc.org/github.com/pierrec/lz4#Reader.Read).

**Comment by hasnickl** [comment]
Maybe a configuration value can be exposed to set a starting buffer capacity?

**Comment by eapache** [comment]
Yes, that sounds possible by initializing a `bytes.Buffer` and using its `ReadFrom` method.

Although looking at your graph above, the majority of the memory usage from this path is already happening due to the largest slice size, so cutting out the smaller slices will not save you a great deal.

**Comment by erikdubbelboer** [comment]
Would it not be possible to keep the `[]byte` for `m.Value` in a `sync.Pool`? If `Message` would get a `Free()` method that releases `m.Value` to this pool it could be reused. If people don't call `m.Free()` it will just always allocate like it does now.

Other libraries do this as well such as: https://godoc.org/github.com/go-mangos/mangos#Message.Free

**Comment by hasnickl** [comment]
I really like that idea @erikdubbelboer, my only concern is the existing direct access to `m.Value`. If users pass that byte slice around and aren't careful about using `Free()` they could read bad data out of it.

Maybe this is okay with sufficient documentation on the function?

**Comment by eapache** [comment]
The other complication with a pool is that the `Consumer` type does not return `Message` objects directly, so there would need to be some way of proxying the `Free` call from the consumer back to the underlying `Message`.

That said, it wouldn't be impossible.

**Comment by erikdubbelboer** [comment]
You mean `ConsumerMessage`? It could just share the same `[]byte` pool as `Message` and .

At the other side the `Encoder` interface could be extended with a `Free()` method that sarama will call when the value isn't needed anymore. This way people can implement their own `Encoder` types that reuse buffers as well.

**Comment by hasnickl** [comment]
@eapache to address your earlier point, yes the memory footprint is mostly used by the larger slices. However, some of my highest CPU usage is in `runtime.mallocgc` and `runtime.heapBitsSweepScan`. 

Reducing allocation/GC pressure should improve throughput even if the memory impact is minimal.

**Comment by eapache** [comment]
I'm not against any of these enhancements, but I'm not going to be tackling any of them myself in the near future. If somebody wants to PR them with appropriate benchmark results backing them up, I'd be happy to take a look.

**Comment by erikdubbelboer** [comment]
I looked into adding the `Free()` method but there are so many separate places where the `[]byte` for the value can be created that I couldn't really find a nice way to implement this.
