### ISSUE TITLE
Notification of successful subscription?

### ISSUE THREAD

**Issue by sanchezl** [Shopify/sarama#943]
##### Versions

Sarama Version: v1.12.0
Kafka Version: 0.10.1.0
Go Version: 1.8

##### Configuration

Consumer.Return.Errors = true

##### Logs

N/A

##### Problem Description

I need to be able to detect that my partition consumer has not been able to connect to it's broker leader after a certain amount of time.

For example in the diagram below, `my_client` talks to `my_server_1` which in turn talks to the Kafka cluster over `net_1`. I need to be able to detect when `my_server_1` (a kafka consumer) cannot reach the kafka cluster (most likely because of a problem with `net_1`).  If I can detect that the kafka consumer on `my_server_1` has been unable to reach the Kafka cluster after some "timeout", then I can let `my_client` know that maybe it should try to talk to `my_server_2`.

```
   +---------------+         +---------------+
   |   my_client   |-------->|  my_server_1  |---------net_1-----------+
   +---------------+         +---------------+                         v
                                                             +-------------------+
                             +---------------+               |                   |
                             |  my_server_2  |---net_2------>|   kafka_cluster   |
                             +---------------+               |                   |
                                                             +-------------------+
```

I can listen to `PartitionConsumer.Errors()` to know that errors are occurring, but I have no reliable way to detect that the consumer has successfully reconnected to the partition leader. I've currently implemented a solution where are start some timers and do my best to guess that the leader has been found (actually receiving a message from the kafka cluster is a good indication, but sometimes the message flow slows dow to a trickle).

Is there some way to get a notice that the partition consumer has successfully subscribed to a partition on the leader broker?

**Comment by eapache** [comment]
> Is there some way to get a notice that the partition consumer has successfully subscribed to a partition on the leader broker?

There currently is not, I had never thought of this use case before.

As an immediate workaround you could capture log messages (`sarama.Logger` is just an interface so you can implement your own that proxies to a normal logger) and look for messages that look like: `consumer/broker/%d added subscription to %s/%d`.

I'll think about a better long-term way to accomplish this though.
