### ISSUE TITLE
Support for creating topics?

### ISSUE THREAD

**Issue by briansorahan** [Shopify/sarama#944]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: https://github.com/Shopify/sarama/tree/15174039fd207656a0f97f52bc78ec7793deeada
Kafka Version: 0.9.1
Go Version: 1.8.1

##### Configuration

What configuration values are you using for Sarama and Kafka?

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

This is more of a question than a problem. Is it possible to [create topics](https://kafka.apache.org/protocol#The_Messages_CreateTopics) with sarama?

**Comment by eapache** [comment]
No, that operation has not been implemented yet. It probably falls in the bucket of #901.
