### ISSUE TITLE
ProducerMessage confusion

### ISSUE THREAD

**Issue by lsyin** [Shopify/sarama#945]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:0.8
Kafka Version:2.10
Go Version:1.8.3

##### Configuration

What configuration values are you using for Sarama and Kafka?
In kafka part of my server.properties:
```      
      broker.id=0 
      num.partitions=10
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description
In the type ProducerMessage, after I set the Partition field and the Offset field, I send a message to kafka,but when I consume the message,Partition field and the Offset field not take any effect,I don't know why?  I make sure the message was successfully delivered.But the two field haven't taken any effect.Could you tell me why and what purpose do you set these fields. Looking forward to hearing from you!

# my produce code:

``` 
 msg := &sarama.ProducerMessage{}
 msg.Topic = "hello"
 msg.Partition = 10
 msg.Key = sarama.StringEncoder("key")
 msg.Value = sarama.ByteEncoder("hello,world")
 msg.Offset= 6

```
# after I run the produce code ,the log show below:

[srama]2017/09/07 16:05:05 producer/broker/0 starting up
[srama]2017/09/07 16:05:05 producer/broker/0 state change to [open] on hello/7
[srama]2017/09/07 16:05:05 Connected to broker at SHA1000048829:9092 (registered as #0)
[srama]2017/09/07 16:05:05 partition=7, offset=2
[srama]2017/09/07 16:05:05 Producer shutting down.
[srama]2017/09/07 16:05:05 Closing Client

I set the Partition=10, Offset=6, but actually is partition=7, offset=2,they seem not to  take any effect.

**Comment by eapache** [comment]
You cannot set a specific offset; the offset is always assigned by the broker when produced.

You can set a specific partition, but to do so you need to configure your producer with `Config.Producer.Partitioner = NewManualPartitioner`.

**Comment by lsyin** [comment]
Yeah, I think I got it. The Partition and Offset fields are set because message requires them ,and producer can initial them. Only after I set  `config.Producer.Partitioner = sarama.NewManualPartitioner`  the field Partition is work, but the field Offset couldn't change wherever  I set it or not.
Thanks a lot for you replying.
