### ISSUE TITLE
some data not compressed using CompressionGZIP

### ISSUE THREAD

**Issue by imroc** [Shopify/sarama#947]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: master latest
Kafka Version: 0.10.0.1
Go Version: go1.9

##### Configuration

What configuration values are you using for Sarama and Kafka?
producer config:
``` go
	config.Producer.RequiredAcks = sarama.NoResponse
	config.Producer.Partitioner = sarama.NewHashPartitioner
	config.Producer.Return.Errors = true
	config.Producer.Compression = sarama.CompressionGZIP
	config.Version = sarama.V0_10_0_1
	config.Producer.Flush.Bytes = 1024 * 1024 // 1MB
	config.Net.DialTimeout = 2 * time.Second
```
consumer config:
``` go
	config := consumergroup.NewConfig()
	config.Offsets.Initial = conf.Kafka.Offset
	config.Consumer.MaxProcessingTime = 2 * time.Minute
	config.Consumer.Return.Errors = true
	config.Version = sarama.V0_10_0_1
	config.Producer.Compression = sarama.CompressionGZIP
```
when I tcpdump, I can see a lot of plain txt, they are not compressed. and I debug the `sarama.Message.encode` and `sarama.Message.decode`, some are not compression, some are gzip compressed, why ?
##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

**Comment by eapache** [comment]
Are they not encoded on produce, or on consume? Or both?

**Comment by imroc** [comment]
@eapache  just consume, I can see plain text in the tcpdump:
![image](https://user-images.githubusercontent.com/7448852/30359257-0ceed6b2-987c-11e7-9a64-92f9628c3fb5.png)

**Comment by imroc** [comment]
@eahdawn  oh sorry, my bad, another producer is written by ruby, and it is not using compression yet
