### ISSUE TITLE
Help with sarama.MockBroker and sarama-cluster

### ISSUE THREAD

**Issue by jvrmaia** [Shopify/sarama#948]
Hi,

Sarama Version: c01858abb625b73a3af51d0798e4ad42c8147093
Kafka Version:  0.10.2.0
Go Version: 1.8.3

I opened this [issue](https://github.com/bsm/sarama-cluster/issues/166) at sarama-cluster and wanna know with someone here can help with too.

Tks

**Comment by eapache** [comment]
I'll answer on that ticket.
