### ISSUE TITLE
AsyncProducer: i/o timeout error when closing (lots of them)

### ISSUE THREAD

**Issue by chandradeepak** [Shopify/sarama#949]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version:v1.12  , 55b3f6a77f08038b1e82c3db3c1ce619e46de9b6
Kafka Version:0.10.0.1
Go Version:1.8.3

##### Configuration
config.Producer.RequiredAcks = sarama.WaitForAll
config.Producer.Compression = sarama.CompressionSnappy   // Compress messages
config.Producer.Flush.Frequency = 250 * time.Millisecond // Flush batches every 250ms
config.Producer.Retry.Max = 5                            // Retry maximum 5 times
config.Producer.Flush.MaxMessages = 10000
config.Producer.Flush.Bytes = 1024

config.Producer.Return.Successes = true
config.Producer.Return.Errors = true
config.Consumer.Fetch.Min = minMessageSize
config.Consumer.Fetch.Default = defaultMessageSize
config.Consumer.Fetch.Max = maxMessageSize
config.Consumer.Return.Errors = true
config.Consumer.Offsets.Initial = sarama.OffsetOldest 

What configuration values are you using for Sarama and Kafka?

##### Logs

producer/broker/1004 state change to [closing] because EOF\n

"Error while closing connection to broker localhost:9092: write tcp localhost:33268-\u003elocalhost:9092: i/o timeout\n"
Error closing broker -1 : write tcp localhost:33268-\u003elocalhost:9092: i/o timeout\n"

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

##### Problem Description

we see lot of these errors in our sarama logs . Is this due to some messages are missed in publishing or is it because of the configuration parameters we are using are not correct. 

There was some reference to this https://github.com/Shopify/sarama/issues/834 do we need to set any specific config from that  .

please advise  or suggest is this some thing to worry about ?

**Comment by eapache** [comment]
> producer/broker/1004 state change to [closing] because EOF

This means the broker closed the connection unexpectedly; there will usually be logs *on the broker* when this happens explaining what went wrong.

> "Error while closing connection to broker localhost:9092: write tcp localhost:33268-\u003elocalhost:9092: i/o timeout\n"

"i/o timeout" means exactly what it sounds like. Either your broker is being very slow to respond, or the connection is flaky (which seems unlikely if the address is on localhost) or you're trying to transfer an enormous amount of data, or...

> Is this due to some messages are missed in publishing 

I wouldn't think so. Any message that isn't delivered from the producer should be returned on `Errors`.

> is it because of the configuration parameters we are using are not correct.

The configuration you included looks correct to me. You can try increasing `config.Net.ReadTimeout` and `config.Net.WriteTimeout` and see if that helps, but I'm not really sure.

**Comment by pirlck** [comment]
mark
