### ISSUE TITLE
How to use ResetOffset function?

### ISSUE THREAD

**Issue by LaughingVzr** [Shopify/sarama#953]
How to use ResetOffset function?

**Comment by eapache** [comment]
The function is used to reset the consumer offset to an earlier point in time. You can see the documentation for more details: https://godoc.org/github.com/Shopify/sarama#PartitionOffsetManager

**Comment by LaughingVzr** [comment]
Thank u,but i didn't understand the parama named metadata.
by the time,after invoke reset offset,i can use this client consumer start the reset-offset,is it?
other condition,the message is expired (expired log.retention.time),use reset function is useful?
