### ISSUE TITLE
Topics whitelist sarama vs. sarama-cluster

### ISSUE THREAD

**Issue by agforte** [Shopify/sarama#955]
Hi all,

unless I have missed something, it appears that sarama-cluster allows the setting of both Topics.Whitelist and Topics.Blacklist in the Config of a consumer group. However, these appear not to be supported by Sarama. The confusing part is that sarama-cluster passes the configuration with both Whitelist and Blacklist to Sarama (from `sarama-cluster/client.go`):

```
client, err := sarama.NewClient(addrs, &config.Config)
```

How come this does not give any error? Am I wrong and Sarama does support Whitelist/Blacklist of topics?

Thanks.

**Comment by eapache** [comment]
Sarama does not support whitelist/blacklist; the config that sarama-cluster uses wraps the sarama config struct and so the only part that gets passed into `NewClient` is the common part without the whitelist/blacklist https://github.com/bsm/sarama-cluster/blob/3a8591c00548b67617971bb9df75f7745057a7c4/config.go#L13-L14
