### ISSUE TITLE
Consumer incremental subscription to topics?

### ISSUE THREAD

**Issue by agforte** [Shopify/sarama#956]
Hi all, I was wondering if there are plans to support a way for a consumer to subscribe to new topics as new subscribe requests come in. That is, adding new topics to current ones. Currently, there seems to be no way to subscribe to multiple topics for one consumer, let alone incrementally.

**Comment by eapache** [comment]
You can call `Consumer.ConsumePartition` with different topics at any time. The consumer does support consuming from multiple topics, and adjusting the set of topics/partitions on the fly.
