### ISSUE TITLE
Drain Messages during Consumer Shutdown

### ISSUE THREAD

**Issue by hasnickl** [Shopify/sarama#963]
#### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 1.13.0

#### Problem Description
Consumer shutdown process breaks message ordering guarantee. 

I've been debugging an issue with consumption when I trigger a graceful shutdown in my application. Kafka consumer is the head of my pipeline, so shutdown is as simple as close the kafka consumer and rest of the pipeline shuts itself down.

The problem is this line in the `Close()` method:
https://github.com/Shopify/sarama/blob/master/consumer.go#L421
```
go withRecover(func() {
		for range child.messages {
			// drain
		}
	})
```
So the message queue is being drained while shutting down. The problem here is consumers are still reading from this channel, and only stopping when it closes. This leads to a scenario where:

1. Downstream consumer reads message with offset 10 from channel
2. `Close()` method pops message with offset 11 from channel
3. Downstream consumer reads message with offset 12 from channel

This leads to my application wanting to mark offset 12 as processed, but we never got offset 11 at a point my implementation expects serialized offset progression.

#### Proposal
This go routine should be removed completely from the `Close()` method. When consumer closes, whatever feeds the `child.messages` channel should be stopped, then the channel should be closed. This will allow downstream consumers to drain the channel then correctly handle its closure.

This is how it should be from what I can see, let me know if I'm being ignorant of something here

**Comment by eapache** [comment]
I think `AsyncClose` is what you're looking for? `Close` is explicitly designed for the case where you *don't* want to drain the remaining messages yourself.

**Comment by hasnickl** [comment]
@eapache thanks, now i feel foolish :)
