### ISSUE TITLE
Migrating offsets from zookeeper to kakfa

### ISSUE THREAD

**Issue by sagard** [Shopify/sarama#966]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: v1.12.0
Kafka Version: 0.10.2.1
Go Version: 1.9

##### Problem Description
I have to upgrade sarama clients from 0.8 to latest version and started using sarama-cluster instead of wvanbergen/kafka. I see that offset will be committed to kafka now.

On Apache Kafka page it says that for doing migration from zk based storage to kafka you need to do following:
Set offsets.storage=kafka and dual.commit.enabled=true in your consumer config.

But wvanbergen/kafka doesn't support these properties and they don't indent to support it.
How can we migrate offsets from zk to kafka? Is default value of dual.commit.enabled true?

**Comment by eapache** [comment]
sarama-cluster might support both formats? You'd have to ask that project. Otherwise I believe your only option would be to manually copy the offsets from zookeeper to Kafka.
