### ISSUE TITLE
Sarama consumer group Owner

### ISSUE THREAD

**Issue by liaojianqi** [Shopify/sarama#979]
##### Version
Sarama Version: 1.13.0 (2017-10-04)
Kafka Version: kafka_2.11-0.10.1.0
Go Version: 1.9.2 darwin/amd64

##### Problem Description

how to set consumer group's owner name?
when I exec:
`./kafka-consumer-groups.sh --zookeeper localhost:2181 --describe --group g1`
then output:
`GROUP    TOPIC   PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG   OWNER`
` g1         integration      0                 319587936       352119221       32531285        none`
OWNER is 'none'.

I want to know hot to set consumer group's OWNER in sarama please?

**Comment by eapache** [comment]
https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#how-can-i-use-sarama-to-monitor-or-join-a-consumer-group
