### ISSUE TITLE
add Kafka 1.0 to Travis + KafkaVersion constant

### ISSUE THREAD

**Issue by buyology** [Shopify/sarama#983]
now that Kafka 1.0 is out — can we add it to Travis?

the release also contains new request/response pair(s) (in particular `CreatePartitions` for which I'm onto a PR) so also need a new KafkaVersion constant

**Comment by eapache** [comment]
Ya, absolutely it's on my todo list. Happy to take a PR for this too if somebody beats me to the punch.
