### ISSUE TITLE
How to realize timestamp in producer?

### ISSUE THREAD

**Issue by jinleileiking** [Shopify/sarama#987]
I want to produce messages to kafka to use with mysql.

ksql show these:

```
has invalid (negative) timestamp. Possibly because a pre-0.10 producer client was used to write this record to Kafka without embedding a timestamp, or because the input topic was created before upgrading the Kafka cluster to 0.10+. Use a different TimestampExtractor to process this data.

```

Then I found.

https://docs.confluent.io/current/streams/developer-guide/config-streams.html#streams-developer-guide-timestamp-extractor

But how to realize in golang???

**Comment by eapache** [comment]
Sarama will add timestamps if it is producing to at a broker of at least Kafka 0.10 as determined by `config.Version`. Just set that value correctly and new messages should be produced with timestamps.

**Comment by jinleileiking** [comment]
@eapache where to set `config.Version` Thanks.

**Comment by eapache** [comment]
When you call `NewAsyncProducer` or `NewSyncProducer` the last parameter is the config object. Set it on that.

**Comment by jinleileiking** [comment]
Thanks.
