### ISSUE TITLE
Sarama errors connection when Kafka broker replies come out of order

### ISSUE THREAD

**Issue by rthille** [Shopify/sarama#992]
##### Versions
Master branch appears to have this error:
https://github.com/Shopify/sarama/blob/6a8d89d71d22bbdc14b6cb52778889a710be19a7/broker.go#L518
You can see there that if any reply other than the expected one is returned , the broker will return an error and the consumer will disconnect (https://github.com/Shopify/sarama/blob/6a8d89d71d22bbdc14b6cb52778889a710be19a7/consumer.go#L694)
This would be OK if brokers only ever had one outstanding request in flight, but the default for `Net.MaxOpenRequests` is 5.

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*
Sarama Version: 6a8d89d71d22bbdc14b6cb52778889a710be19a7
Kafka Version: 0.9.0.1
Go Version: go version go1.8.3 linux/amd64

##### Configuration

What configuration values are you using for Sarama and Kafka?
Defaults?

##### Logs
"msg":"Sarama: consumer/broker/0 disconnecting due to error processing FetchRequest: kafka: error decoding packet: correlation ID didn't match, wanted 31864, got 31865\n"
"msg":"Sarama: Closed connection to broker 172.16.1.13:9092\n",

##### Problem Description

Kafka brokers can sometimes return request responses out of order. Sarama can't deal with that, so shouldn't have multiple requests in-flight at the same time.

**Comment by eapache** [comment]
> Kafka brokers can sometimes return request responses out of order.

Since when? The [protocol documentation](https://kafka.apache.org/protocol.html#protocol_network) says explicitly:
> The server guarantees that on a single TCP connection, requests will be processed in the order they are sent and responses will return in that order as well. The broker's request processing allows only a single in-flight request per connection in order to guarantee this ordering.

**Comment by rthille** [comment]
Huh.  Can you explain the log messages we are seeing from Sarama then?  Can Sarama somehow lose the ordering, or drop a response internally and then see the correlation ID mismatch?

**Comment by eapache** [comment]
I cannot explain those log messages. If you're seeing this consistently, you may be able to use Wireshark to inspect the traffic and determine if the broker is really sending packets out of order (a broker bug) or if Sarama is messing up the decode somehow.

**Comment by eapache** [comment]
Please feel free to reopen if you have more information (e.g. a wireshark trace or test case) showing this is a Sarama issue.
